### ISSUE TITLE
 Can riscv architecture be supported ？

### ISSUE THREAD

**Issue by xswfantasy** [camunda/zeebe#10005]
**Under the riscv architecture, after compiling zeebe with maven and making it into a docker image, an error is reported when running, 
Ask Daniel to help analyze，thanks**

**dockerfile**
````
ARG APP_ENV=prod

# Building builder image
FROM riscv64/ubuntu:20.04 as builder
ARG DISTBALL

ENV TMP_ARCHIVE=/tmp/zeebe.tar.gz \
    TMP_DIR=/tmp/zeebe \
    TINI_VERSION=v0.19.0

COPY ${DISTBALL} ${TMP_ARCHIVE}

RUN mkdir -p ${TMP_DIR} && \
    tar xfvz ${TMP_ARCHIVE} --strip 1 -C ${TMP_DIR} && \
    # already create volume dir to later have correct rights
    mkdir ${TMP_DIR}/data


RUN apt-get update && \
    apt-get install tini && \
    cp /usr/bin/tini ${TMP_DIR}/bin/tini

#ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini ${TMP_DIR}/bin/tini
COPY docker/utils/startup.sh ${TMP_DIR}/bin/startup.sh
RUN chmod +x -R ${TMP_DIR}/bin/
RUN chmod 0775 ${TMP_DIR} ${TMP_DIR}/data
#RUN apt-get update && \
#    apt-get install tini && \
#    cp /usr/bin/tini ${TMP_DIR}/bin/tini

# Building prod image
FROM riscv64/openjdk:17 as prod

# Building dev image
FROM riscv64/openjdk:17 as dev

RUN echo "running DEV pre-install commands"
RUN apt-get update
RUN apt install curl -y
#RUN curl -sSL https://github.com/jvm-profiling-tools/async-profiler/releases/download/v1.7.1/async-profiler-1.7.1-linux-x64.tar.gz | tar xzv

# Building application image
FROM ${APP_ENV} as app

ENV ZB_HOME=/usr/local/zeebe \
    ZEEBE_BROKER_GATEWAY_NETWORK_HOST=0.0.0.0 \
    ZEEBE_STANDALONE_GATEWAY=false
ENV PATH "${ZB_HOME}/bin:${PATH}"

WORKDIR ${ZB_HOME}
EXPOSE 26500 26501 26502
VOLUME ${ZB_HOME}/data

RUN groupadd -g 1000 zeebe && \
    adduser -u 1000 zeebe --system --ingroup zeebe && \
    chmod g=u /etc/passwd && \
    chown 1000:0 ${ZB_HOME} && \
    chmod 0775 ${ZB_HOME}

COPY --from=builder --chown=1000:0 /tmp/zeebe/bin/startup.sh /usr/local/bin/startup.sh
COPY --from=builder --chown=1000:0 /tmp/zeebe ${ZB_HOME}

ENTRYPOINT ["tini", "--", "/usr/local/bin/startup.sh"]
```
`
### the error is as follows:

`Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-08-05 06:26:39.008 [] [main] ERROR
      org.springframework.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:770) [spring-boot-2.6.1.jar:2.6.1]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:751) [spring-boot-2.6.1.jar:2.6.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:309) [spring-boot-2.6.1.jar:2.6.1]
	at io.camunda.zeebe.broker.StandaloneBroker.main(StandaloneBroker.java:79) [camunda-cloud-zeebe-1.3.5.jar:1.3.5]
Caused by: io.camunda.zeebe.util.exception.UncheckedExecutionException: Failed to start broker
	at io.camunda.zeebe.broker.Broker.internalStart(Broker.java:110) ~[zeebe-broker-1.3.5.jar:1.3.5]
	at io.camunda.zeebe.util.LogUtil.doWithMDC(LogUtil.java:23) ~[zeebe-util-1.3.5.jar:1.3.5]
	at io.camunda.zeebe.broker.Broker.start(Broker.java:83) ~[zeebe-broker-1.3.5.jar:1.3.5]
	at io.camunda.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:93) ~[camunda-cloud-zeebe-1.3.5.jar:1.3.5]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:767) ~[spring-boot-2.6.1.jar:2.6.1]
	... 3 more
Caused by: java.util.concurrent.ExecutionException: Startup failed in the following steps: [Partition Manager]. See suppressed exceptions for details.
	at io.camunda.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:141) ~[zeebe-util-1.3.5.jar:1.3.5]
	at io.camunda.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:108) ~[zeebe-util-1.3.5.jar:1.3.5]
	at io.camunda.zeebe.util.sched.FutureUtil.join(FutureUtil.java:21) ~[zeebe-util-1.3.5.jar:1.3.5]
	at io.camunda.zeebe.util.sched.future.CompletableActorFuture.join(CompletableActorFuture.java:196) ~[zeebe-util-1.3.5.jar:1.3.5]
	at io.camunda.zeebe.broker.Broker.internalStart(Broker.java:101) ~[zeebe-broker-1.3.5.jar:1.3.5]
	at io.camunda.zeebe.util.LogUtil.doWithMDC(LogUtil.java:23) ~[zeebe-util-1.3.5.jar:1.3.5]
	at io.camunda.zeebe.broker.Broker.start(Broker.java:83) ~[zeebe-broker-1.3.5.jar:1.3.5]
	at io.camunda.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:93) ~[camunda-cloud-zeebe-1.3.5.jar:1.3.5]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:767) ~[spring-boot-2.6.1.jar:2.6.1]
	... 3 more
Caused by: io.camunda.zeebe.util.startup.StartupProcessException: Startup failed in the following steps: [Partition Manager]. See suppressed exceptions for details.
	at io.camunda.zeebe.util.startup.StartupProcess.aggregateExceptionsSynchronized(StartupProcess.java:282) ~[zeebe-util-1.3.5.jar:1.3.5]
	at io.camunda.zeebe.util.startup.StartupProcess.completeStartupFutureExceptionallySynchronized(StartupProcess.java:183) ~[zeebe-util-1.3.5.jar:1.3.5]
	at io.camunda.zeebe.util.startup.StartupProcess.lambda$proceedWithStartupSynchronized$3(StartupProcess.java:167) ~[zeebe-util-1.3.5.jar:1.3.5]
	at io.camunda.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:33) ~[zeebe-util-1.3.5.jar:1.3.5]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:82) ~[zeebe-util-1.3.5.jar:1.3.5]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:44) ~[zeebe-util-1.3.5.jar:1.3.5]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) ~[zeebe-util-1.3.5.jar:1.3.5]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97) ~[zeebe-util-1.3.5.jar:1.3.5]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80) ~[zeebe-util-1.3.5.jar:1.3.5]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189) ~[zeebe-util-1.3.5.jar:1.3.5]
	Suppressed: io.camunda.zeebe.util.startup.StartupProcessStepException: Bootstrap step Partition Manager failed
		at io.camunda.zeebe.util.startup.StartupProcess.completeStartupFutureExceptionallySynchronized(StartupProcess.java:185) ~[zeebe-util-1.3.5.jar:1.3.5]
		at io.camunda.zeebe.util.startup.StartupProcess.lambda$proceedWithStartupSynchronized$3(StartupProcess.java:167) ~[zeebe-util-1.3.5.jar:1.3.5]
		at io.camunda.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:33) ~[zeebe-util-1.3.5.jar:1.3.5]
		at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:82) ~[zeebe-util-1.3.5.jar:1.3.5]
		at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:44) ~[zeebe-util-1.3.5.jar:1.3.5]
		at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) ~[zeebe-util-1.3.5.jar:1.3.5]
		at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97) ~[zeebe-util-1.3.5.jar:1.3.5]
		at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80) ~[zeebe-util-1.3.5.jar:1.3.5]
		at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189) ~[zeebe-util-1.3.5.jar:1.3.5]
	Caused by: java.util.concurrent.CompletionException: java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni12637028452020772129.so: /tmp/librocksdbjni12637028452020772129.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64 .so on a RISC-V platform)
		at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
		at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
		at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?]
		at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
		at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
		at io.atomix.utils.concurrent.AtomixFuture.lambda$wrap$0(AtomixFuture.java:50) ~[zeebe-atomix-utils-1.3.5.jar:1.3.5]
		at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
		at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
		at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
		at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
		at io.atomix.utils.concurrent.AtomixFuture.lambda$wrap$0(AtomixFuture.java:50) ~[zeebe-atomix-utils-1.3.5.jar:1.3.5]
		at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
		at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
		at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
		at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
		at io.atomix.utils.concurrent.AtomixFuture.lambda$wrap$0(AtomixFuture.java:50) ~[zeebe-atomix-utils-1.3.5.jar:1.3.5]
		at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
		at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
		at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
		at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
		at io.atomix.utils.concurrent.AtomixFuture.lambda$wrap$0(AtomixFuture.java:50) ~[zeebe-atomix-utils-1.3.5.jar:1.3.5]
		at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
		at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
		at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
		at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
		at io.atomix.raft.impl.DefaultRaftServer.lambda$start$5(DefaultRaftServer.java:211) ~[zeebe-atomix-cluster-1.3.5.jar:1.3.5]
		at io.atomix.raft.impl.RaftContext.awaitState(RaftContext.java:338) ~[zeebe-atomix-cluster-1.3.5.jar:1.3.5]
		at io.atomix.raft.impl.DefaultRaftServer.lambda$start$6(DefaultRaftServer.java:207) ~[zeebe-atomix-cluster-1.3.5.jar:1.3.5]
		at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
		at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
		at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
		at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
		at io.atomix.raft.cluster.impl.RaftClusterContext.completeBootstrapFuture(RaftClusterContext.java:275) ~[zeebe-atomix-cluster-1.3.5.jar:1.3.5]
		at io.atomix.raft.cluster.impl.RaftClusterContext.lambda$bootstrap$0(RaftClusterContext.java:135) ~[zeebe-atomix-cluster-1.3.5.jar:1.3.5]
		at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:171) ~[zeebe-atomix-utils-1.3.5.jar:1.3.5]
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
		at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
		at java.lang.Thread.run(Thread.java:833) ~[?:?]
`

**Comment by npepinpe** [comment]
We rely on RocksDB as our embedded key value store. RISCV support in RocksDB seems pretty new, but it seems the RocksDB folks don't bundle it as part of the Java artifact, so it's inaccessible for now.

This is unfortunately a hard blocker for Zeebe on the RISC-V architecture. We haven't heard much demand for it in the past, could you elaborate on your use case? That would help us prioritize support for this platform.

**Comment by xswfantasy** [comment]
> We rely on RocksDB as our embedded key value store. RISCV support in RocksDB seems pretty new, but it seems the RocksDB folks don't bundle it as part of the Java artifact, so it's inaccessible for now.
> 
> This is unfortunately a hard blocker for Zeebe on the RISC-V architecture. We haven't heard much demand for it in the past, could you elaborate on your use case? That would help us prioritize support for this platform.

Thank you, we want to use the zeebe software on our edge, the device architecture of the edge is riscv architecture, do you have any plans to support riscv in the future?

**Comment by menski** [comment]
@felix-mueller any input from your side? From engineering perspective we don't see the RISCV platform as a target architecture.

**Comment by felix-mueller** [comment]
@menski I don't see RISCV platform as a target architecture currently. We want to add ARM support soon, but thats it right now.

**Comment by menski** [comment]
Thanks for confirmation @felix-mueller

@xswfantasy right now we don't see RISCV as a target platform for our platform, therefore we will close this issue for now.
