### ISSUE TITLE
NullPointerException upon writing error response

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/zeebe#10014]
**Describe the bug**

The `ErrorResponseWriter` tried to write an error response, but the `errorCode` was null.

**To Reproduce**

I don't know

**Expected behavior**

No NPE is thrown.

**Log/Stacktrace**

https://console.cloud.google.com/errors/detail/CNr_jurZ9ZLCzAE;service=zeebe;time=P7D?project=camunda-cloud-240911

<details><summary>Full Stacktrace</summary>
 <p>

```
 java.lang.NullPointerException: error code
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:?]
	at io.camunda.zeebe.util.EnsureUtil.ensureNotNull(EnsureUtil.java:20) ~[zeebe-util-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.broker.transport.ErrorResponseWriter.tryWriteResponse(ErrorResponseWriter.java:161) ~[zeebe-broker-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.broker.transport.AsyncApiRequestHandler.lambda$handleRequest$1(AsyncApiRequestHandler.java:114) ~[zeebe-broker-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT] 
```

</p>
</details>

**Environment:**
- Zeebe Version: latest SNAPSHOT

**Comment by remcowesterhoud** [comment]
@oleschoenburg I'm a bit swarmed currently so I didn't do a very deep dive into this NPE. What I quickly saw is that it originates from the `AsyncApiRequestHandler`. It seems like you've created this a few days ago. Maybe you can have a quick look if you already see something wrong.

**Comment by oleschoenburg** [comment]
`AsyncApiRequestHandler` is mostly a rename, it existed before as `ApiRequestHandler`.

Looks like the command api handler returned the error writer but didn't set a error code, which should not be possible :grimacing:

**Comment by oleschoenburg** [comment]
Yikes, looks like I made a mess out of `AsyncApiRequestHandler` :facepalm: 

We are re-using the readers and writers which is not safe since handlers are async.

**Comment by pihme** [comment]
Appears in benchmark that was created after the fix was merged
