### ISSUE TITLE
Test `StreamProcessorReplayModeTest.shouldReplayMoreAfterResumed` is broken

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#10027]
**Describe the bug**

This test is broken, indicating a bug. It's appears to be not flaky or nondeterministic.

**To Reproduce**

Run `StreamProcessorReplayModeTest.shouldReplayMoreAfterResumed`, the test will fail

**Expected behavior**

Test succeeds. 

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.RuntimeException: java.lang.IllegalStateException: Expected to find a process deployed with key '-1' but not found.
	at io.camunda.zeebe.streamprocessor.ReplayStateMachine.lambda$replayNextEvent$4(ReplayStateMachine.java:169) ~[classes/:?]
	at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:33) ~[classes/:?]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) ~[classes/:?]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[classes/:?]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[classes/:?]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[classes/:?]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[classes/:?]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[classes/:?]
Caused by: java.lang.IllegalStateException: Expected to find a process deployed with key '-1' but not found.
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.getFlowElement(DbProcessState.java:291) ~[classes/:?]
	at io.camunda.zeebe.engine.state.appliers.ProcessInstanceElementActivatingApplier.createEventScope(ProcessInstanceElementActivatingApplier.java:239) ~[classes/:?]
	at io.camunda.zeebe.engine.state.appliers.ProcessInstanceElementActivatingApplier.applyState(ProcessInstanceElementActivatingApplier.java:49) ~[classes/:?]
	at io.camunda.zeebe.engine.state.appliers.ProcessInstanceElementActivatingApplier.applyState(ProcessInstanceElementActivatingApplier.java:30) ~[classes/:?]
	at io.camunda.zeebe.engine.state.appliers.EventAppliers.applyState(EventAppliers.java:250) ~[classes/:?]
	at io.camunda.zeebe.engine.Engine.replay(Engine.java:90) ~[classes/:?]
	at io.camunda.zeebe.streamprocessor.ReplayStateMachine.replayEvent(ReplayStateMachine.java:229) ~[classes/:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at io.camunda.zeebe.streamprocessor.ReplayStateMachine.lambda$tryToReplayBatch$5(ReplayStateMachine.java:210) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[classes/:?]
	at io.camunda.zeebe.streamprocessor.ReplayStateMachine.tryToReplayBatch(ReplayStateMachine.java:208) ~[classes/:?]
	at io.camunda.zeebe.streamprocessor.ReplayStateMachine.lambda$replayNextEvent$3(ReplayStateMachine.java:165) ~[classes/:?]
	at io.camunda.zeebe.scheduler.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:36) ~[classes/:?]
	at io.camunda.zeebe.scheduler.retry.RecoverableRetryStrategy.run(RecoverableRetryStrategy.java:48) ~[classes/:?]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[classes/:?]
	... 5 more
```

</p>
</details>

**Comment by Zelldon** [comment]
I reverted the last PR merge, and will check tomorrow the tests again. It seems to be related to mock's which are no longer set, since the Engine doesn't allow this anymore.

**Comment by Zelldon** [comment]
I think this is no longer the case.

We introduce new StreamPlatformExtension to write new tests https://github.com/camunda/zeebe/pull/10036 and the Eventappliers are already created outside after we fixed the test issues.
