### ISSUE TITLE
Delete existing PENDING_DEPLOYMENT causes ZeebeDbInconsistentException

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#10064]
**Describe the bug**

The deployment partition (i.e. partition 1) on benchmark cluster `medic-cw-32-be18e23b78-benchmark` is `DEAD`, due to a ZeebeDbInconsistentException.

This cluster was already facing other problems, but these appear unrelated
- https://github.com/camunda/zeebe/issues/10059

The ZeebeDbInconsistentException is thrown when a partition tries to make a state change that is unexpected and would otherwise lead to inconsistent state.  The partition is then marked as `DEAD` to preserve the consistent state. 

See
- https://github.com/camunda/zeebe/issues/8787

Looking at the stacktrace (below), it's pretty clear that an attempt was made to delete a non-existing pending deployment from the state. This attempt was made as a direct result of writing a `DeploymentDistribution:Completed` event. 

We [check whether a pending deployment exists](https://github.com/camunda/zeebe/blob/be18e23b78/engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/distribute/CompleteDeploymentDistributionProcessor.java#L44-L50) before writing the COMPLETED event, but [not for the specific partition id](https://github.com/camunda/zeebe/blob/be18e23b7844bae2f070434dd75234496e183ffa/engine/src/main/java/io/camunda/zeebe/engine/state/deployment/DbDeploymentState.java#L88-L98).

**To Reproduce**

May be hard to reproduce, but is potentially caused by a retried deployment distribution.

**Expected behavior**

We should reject the `DeploymentDistribution:Complete` command when the specific pending deployment (for the deployment key and the partition id) doesn't exist, instead of writing the `DeploymentDistribution:Completed` event.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
 io.camunda.zeebe.db.ZeebeDbInconsistentException: Key DbCompositeKey{first=DbLong{2251800016784062}, second=DbInt{2}} in ColumnFamily PENDING_DEPLOYMENT does not exist
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.assertKeyExists(TransactionalColumnFamily.java:289) ~[zeebe-db-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$deleteExisting$12(TransactionalColumnFamily.java:199) ~[zeebe-db-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$ensureInOpenTransaction$17(TransactionalColumnFamily.java:301) ~[zeebe-db-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.DefaultTransactionContext.runInTransaction(DefaultTransactionContext.java:33) ~[zeebe-db-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.ensureInOpenTransaction(TransactionalColumnFamily.java:300) ~[zeebe-db-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.deleteExisting(TransactionalColumnFamily.java:196) ~[zeebe-db-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.engine.state.deployment.DbDeploymentState.removePendingDeploymentDistribution(DbDeploymentState.java:70) ~[zeebe-workflow-engine-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.engine.state.appliers.DeploymentDistributionCompletedApplier.applyState(DeploymentDistributionCompletedApplier.java:27) ~[zeebe-workflow-engine-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.engine.state.appliers.DeploymentDistributionCompletedApplier.applyState(DeploymentDistributionCompletedApplier.java:15) ~[zeebe-workflow-engine-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.engine.state.appliers.EventAppliers.applyState(EventAppliers.java:250) ~[zeebe-workflow-engine-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.streamprocessor.writers.ResultBuilderBackedEventApplyingStateWriter.appendFollowUpEvent(ResultBuilderBackedEventApplyingStateWriter.java:41) ~[zeebe-workflow-engine-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.deployment.distribute.CompleteDeploymentDistributionProcessor.processRecord(CompleteDeploymentDistributionProcessor.java:52) ~[zeebe-workflow-engine-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.streamprocessor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:24) ~[zeebe-workflow-engine-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:115) ~[zeebe-workflow-engine-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.lambda$processCommand$2(ProcessingStateMachine.java:264) ~[zeebe-workflow-engine-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:260) ~[zeebe-workflow-engine-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:215) ~[zeebe-workflow-engine-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:191) ~[zeebe-workflow-engine-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT] 
```

</p>
</details>

**Environment:**
- Zeebe Version: be18e23b7844bae2f070434dd75234496e183ffa

**Reported errors**
- [ZeebeDbInconsistentException: Key DbCompositeKey{first=DbLong{2251800016784062}, second=DbInt{2}} in ColumnFamily PENDING_DEPLOYMENT does not exist](https://console.cloud.google.com/errors/detail/CLmJrZGJ1rWTdw;service=zeebe;version=medic-cw-32-be18e23b78-benchmark;time=P7D?project=zeebe-io
)
- [Broker-1-StreamProcessor-1 failed, marking it as dead](https://console.cloud.google.com/errors/detail/CLWTn7vY7pS04QE;service=zeebe;version=medic-cw-32-be18e23b78-benchmark;time=P7D?project=zeebe-io)
- [Partition-1 failed, marking it as dead](https://console.cloud.google.com/errors/detail/CJen7e_I-5vgQw;service=zeebe;version=medic-cw-32-be18e23b78-benchmark;time=P7D?project=zeebe-io)

**Comment by korthout** [comment]
I've marked this as critical as it marks the deployment partition as DEAD, and we should resolve it ASAP.
