### ISSUE TITLE
JobMetricsTest.shouldCountTimedOut  is flaky

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#10160]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? once (saw it on main) https://github.com/camunda/zeebe/runs/7987166782?check_suite_focus=true

- Does it block your work? Not yet
- Do we suspect that it is a real failure? Maybe

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
io.camunda.zeebe.test.util.stream.StreamWrapperException: No event found matching the criteria
	at io.camunda.zeebe.test.util.stream.StreamWrapper.await(StreamWrapper.java:72)
	at io.camunda.zeebe.engine.metrics.JobMetricsTest.shouldCountTimedOut(JobMetricsTest.java:102)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:[413](https://github.com/camunda/zeebe/runs/7987166782?check_suite_focus=true#step:7:414))
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:55)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:223)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:175)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:139)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

[Test results for Slow Unit Tests.zip](https://github.com/camunda/zeebe/files/9414579/Test.results.for.Slow.Unit.Tests.zip)

**Comment by remcowesterhoud** [comment]
**Hypotheses**
This test activates a job with a timeout of 10 minutes. After activating the engine time is increased by 10 minutes. The test will now verify that the job has ran into a timeout.
The assertion we do has a maximum waiting time of 5 seconds. The `JobTimeoutTrigger` is scheduled once every 30 seconds. This results in a relatively high margin of error. The expectation would be that the test fails 1 in 6 times.
This is not the case. Most of the times the test succeeds. My assumption is that the increase in engine time will cause the `JobTimeoutTrigger` to be executed as the increase > 30 seconds. This would mean the test is flaky because of a race condition. If the `JobTimeoutTrigger` executed before the `TIMEOUT` command has been written the test will fail.

**Comment by npepinpe** [comment]
Happened again: https://github.com/camunda/zeebe/commit/8b1c7aba1ec41cf4cd929c8af869887c9bf820c6

**Comment by korthout** [comment]
@npepinpe Is this something you're willing to pick up?

**Comment by korthout** [comment]
@npepinpe During the triage someone mentioned that this was a timing issue related to pushed jobs. But, that is not the case now that I look more closely at the test failure logs. There is clearly a Job Batch Activated. Sorry about the confusion.

```
07:40:32.628 [] INFO  io.camunda.zeebe.test - Compact log representation:
--------
        ['C'ommand/'E'event/'R'ejection] [valueType] [intent] - #[position]->#[source record position] K[key] - [summary of value]
        P9K999 - key; #999 - record position; "ID" element/process id; @"elementid"/[P9K999] - element with ID and key
        Keys are decomposed into partition id and per partition key (e.g. 2251799813685253 -> P1K005). If single partition, the partition is omitted.
        Long IDs are shortened (e.g. 'startEvent_5d56488e-0570-416c-ba2d-36d2a3acea78' -> 'star..acea78'
--------
C CREA      CREATE         - #56-> -1  -1 - new <process "process"> (default start)  with variables: {jobType=job}
E VAR       CREATED        - #57->#56 K22 - jobType->"job" in <process [K21]>
C PI        ACTIVATE       - #58->#56 K21 - PROCESS "process" in <process "process"[K21]>
E CREA      CREATED        - #59->#56 K23 - new <process "process"> (default start)  with variables: {jobType=job}
E PI        ACTIVATING     - #60->#56 K21 - PROCESS "process" in <process "process"[K21]>
E PI        ACTIVATED      - #61->#56 K21 - PROCESS "process" in <process "process"[K21]>
C PI        ACTIVATE       - #62->#56  -1 - START_EVENT "startEv..3c3ae59" in <process "process"[K21]>
E PI        ACTIVATING     - #63->#56 K24 - START_EVENT "startEv..3c3ae59" in <process "process"[K21]>
E PI        ACTIVATED      - #64->#56 K24 - START_EVENT "startEv..3c3ae59" in <process "process"[K21]>
C PI        COMPLETE       - #65->#56 K24 - START_EVENT "startEv..3c3ae59" in <process "process"[K21]>
E PI        COMPLETING     - #66->#56 K24 - START_EVENT "startEv..3c3ae59" in <process "process"[K21]>
E PI        COMPLETED      - #67->#56 K24 - START_EVENT "startEv..3c3ae59" in <process "process"[K21]>
E PI        SEQ_FLOW_TAKEN - #68->#56 K25 - SEQUENCE_FLOW "sequenc..b144f03" in <process "process"[K21]>
C PI        ACTIVATE       - #69->#56 K26 - SERVICE_TASK "task" in <process "process"[K21]>
E PI        ACTIVATING     - #70->#56 K26 - SERVICE_TASK "task" in <process "process"[K21]>
E JOB       CREATED        - #71->#56 K27 - K27 "job" @"task"[K26] 3 retries, in <process "process"[K21]> (no vars)
E PI        ACTIVATED      - #72->#56 K26 - SERVICE_TASK "task" in <process "process"[K21]>
C JOB_BATCH ACTIVATE       - #73-> -1  -1 - "job" max: 10
E JOB_BATCH ACTIVATED      - #74->#73 K28 - "job" 1/10
                K27 "job" @"task"[K26] 3 retries, in <process "process"[K21]> with variables: {jobType=job}

-------------- Deployed Processes ----------------------

--------------- Decomposed keys (for debugging) -----------------
 -1 <-> -1
K21 <-> 2251799813685269
K22 <-> 2251799813685270
K23 <-> 2251799813685271
K24 <-> 2251799813685272
K25 <-> 2251799813685273
K26 <-> 2251799813685274
K27 <-> 2251799813685275
K28 <-> 2251799813685276
```

The test failed because the job did not time out. There was not even a `Job:TIMEOUT` command written to the log (yet).

>Error:  Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 22.00 s <<< FAILURE! -- in io.camunda.zeebe.engine.metrics.JobMetricsTest
Error:  io.camunda.zeebe.engine.metrics.JobMetricsTest.shouldCountTimedOut -- Time elapsed: 5.244 s <<< ERROR!
io.camunda.zeebe.test.util.stream.StreamWrapperException: No event found matching the criteria
	at io.camunda.zeebe.test.util.stream.StreamWrapper.await(StreamWrapper.java:86)
	at io.camunda.zeebe.engine.metrics.JobMetricsTest.shouldCountTimedOut(JobMetricsTest.java:117)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)

https://github.com/camunda/zeebe/blob/87fc5648a261cf41ae3c7acba06b4b1e277384ee/engine/src/test/java/io/camunda/zeebe/engine/metrics/JobMetricsTest.java#L115-L117

**Comment by Zelldon** [comment]
Failed again on merge https://github.com/camunda/zeebe/actions/runs/6276049311/job/17044876047

**Comment by koevskinikola** [comment]
The ZPA team (@koevskinikola, @remcowesterhoud, @tmetzke, @ana-vinogradova-camunda, @nicpuppa) tried to root-cause the flakiness of this test in a mob programming sessions on 02.11.2023.

* We couldn't reproduce the failure. 
   * We attempted to trigger the failure by repetitively running the single test, and the whole test class until failure for >3000 runs.
* From the logs we could see [here](https://github.com/camunda/zeebe/issues/10160#issuecomment-1708708324), we had the hypothesis that the `JobTimeoutTrigger` wasn't executed on time to write the `JobIntent.TIME_OUT` command, so the `await` for the `JobIntent.TIMED_OUT` event expires before it can be written on the log.
   * We tried to simulate this scenario by debugging and setting breakpoints [when the job creation event is appended](https://github.com/camunda/zeebe/blob/294fd35f62dbc4e2a774c014f7fd3abc5b5b97ab/engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/behavior/BpmnJobBehavior.java#L215), and [the `JobTimeoutTrigger` is triggered](https://github.com/camunda/zeebe/blob/3c6e27506e8665900edc404c2ce59eeb46fe9226/engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobTimeoutTrigger.java#L78), but were unsuccessful.

**Comment by remcowesterhoud** [comment]
To add to this, [when we increase the engine time the `JobTimeoutTrigger` should be triggered.](https://camunda.slack.com/archives/C05DH1F5TAR/p1698932833415869)

**Comment by korthout** [comment]
@npepinpe Could it be that this is related to the race condition you described here?
- https://github.com/camunda/zeebe/issues/13870#issuecomment-1795453935

**Comment by npepinpe** [comment]
Probably not, the `JobTimeoutTrigger` doesn't use the `DueDateChecker` =/
