### ISSUE TITLE
Can't run StandaloneGatewaySecurityTest.shouldStartWithTlsEnabled locally

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#10488]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? All the time locally
- Does it block your work? Not sure.
- Do we suspect that it is a real failure? Not sure.

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
[ERROR] Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 5.739 s <<< FAILURE! - in io.camunda.zeebe.gateway.StandaloneGatewaySecurityTest
[ERROR] io.camunda.zeebe.gateway.StandaloneGatewaySecurityTest.shouldStartWithTlsEnabled  Time elapsed: 4.519 s  <<< ERROR!
java.lang.UnsatisfiedLinkError: failed to load the required native library
	at io.netty.handler.ssl.OpenSsl.ensureAvailability(OpenSsl.java:601)
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:215)
	at io.netty.handler.ssl.ReferenceCountedOpenSslServerContext.<init>(ReferenceCountedOpenSslServerContext.java:74)
	at io.netty.handler.ssl.ReferenceCountedOpenSslServerContext.<init>(ReferenceCountedOpenSslServerContext.java:62)
	at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:480)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:606)
	at io.atomix.cluster.messaging.impl.NettyMessagingService.loadServerSslContext(NettyMessagingService.java:438)
	at io.atomix.cluster.messaging.impl.NettyMessagingService.start(NettyMessagingService.java:333)
	at io.atomix.cluster.AtomixCluster.startServices(AtomixCluster.java:246)
	at io.atomix.cluster.AtomixCluster.start(AtomixCluster.java:224)
	at io.camunda.zeebe.gateway.StandaloneGateway.run(StandaloneGateway.java:108)
	at io.camunda.zeebe.gateway.StandaloneGatewaySecurityTest.shouldStartWithTlsEnabled(StandaloneGatewaySecurityTest.java:49)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:55)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:223)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:175)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:139)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
Caused by: java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_linux_x86_64_arch, netty_tcnative_linux_x86_64, netty_tcnative_linux_x86_64_fedora, netty_tcnative_x86_64, netty_tcnative]
	at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:114)
	at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:710)
	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:149)
	... 82 more
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative_linux_x86_64_arch
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:239)
		at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:105)
		... 84 more
	Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative_linux_x86_64_arch.so
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:186)
		... 85 more
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_x86_64_arch in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
			at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
			at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
			at java.base/java.lang.System.loadLibrary(System.java:1989)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:391)
			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:161)
			... 85 more
			Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_x86_64_arch in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
				at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
				at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
				at java.base/java.lang.System.loadLibrary(System.java:1989)
				at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
				at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.base/java.lang.reflect.Method.invoke(Method.java:568)
				at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:425)
				at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
				at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:417)
				at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:383)
				... 86 more
	Suppressed: java.lang.UnsatisfiedLinkError: /tmp/libnetty_tcnative_linux_x86_645619419862621489504.so: libcrypt.so.1: cannot open shared object file: No such file or directory
		at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
		at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
		at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
		at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
		at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
		at java.base/java.lang.Runtime.load0(Runtime.java:755)
		at java.base/java.lang.System.load(System.java:1953)
		at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)
		at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:391)
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:218)
		at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:105)
		... 84 more
		Suppressed: java.lang.UnsatisfiedLinkError: /tmp/libnetty_tcnative_linux_x86_645619419862621489504.so: libcrypt.so.1: cannot open shared object file: No such file or directory
			at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
			at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
			at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
			at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
			at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
			at java.base/java.lang.Runtime.load0(Runtime.java:755)
			at java.base/java.lang.System.load(System.java:1953)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)
			at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
			at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
			at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
			at java.base/java.lang.reflect.Method.invoke(Method.java:568)
			at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:425)
			at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
			at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:417)
			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:383)
			... 86 more
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_x86_64 in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
			at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
			at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
			at java.base/java.lang.System.loadLibrary(System.java:1989)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:391)
			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:161)
			... 85 more
			Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_x86_64 in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
				at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
				at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
				at java.base/java.lang.System.loadLibrary(System.java:1989)
				at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
				at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.base/java.lang.reflect.Method.invoke(Method.java:568)
				at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:425)
				at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
				at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:417)
				at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:383)
				... 86 more
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative_linux_x86_64_fedora
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:239)
		at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:105)
		... 84 more
	Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative_linux_x86_64_fedora.so
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:186)
		... 85 more
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_x86_64_fedora in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
			at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
			at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
			at java.base/java.lang.System.loadLibrary(System.java:1989)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:391)
			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:161)
			... 85 more
			Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_x86_64_fedora in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
				at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
				at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
				at java.base/java.lang.System.loadLibrary(System.java:1989)
				at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
				at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.base/java.lang.reflect.Method.invoke(Method.java:568)
				at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:425)
				at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
				at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:417)
				at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:383)
				... 86 more
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative_x86_64
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:239)
		at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:105)
		... 84 more
	Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative_x86_64.so
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:186)
		... 85 more
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_x86_64 in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
			at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
			at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
			at java.base/java.lang.System.loadLibrary(System.java:1989)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:391)
			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:161)
			... 85 more
			Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_x86_64 in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
				at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
				at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
				at java.base/java.lang.System.loadLibrary(System.java:1989)
				at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
				at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.base/java.lang.reflect.Method.invoke(Method.java:568)
				at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:425)
				at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
				at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:417)
				at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:383)
				... 86 more
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:239)
		at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:105)
		... 84 more
	Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative.so
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:186)
		... 85 more
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
			at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
			at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
			at java.base/java.lang.System.loadLibrary(System.java:1989)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:391)
			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:161)
			... 85 more
			Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
				at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
				at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
				at java.base/java.lang.System.loadLibrary(System.java:1989)
				at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
				at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.base/java.lang.reflect.Method.invoke(Method.java:568)
				at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:425)
				at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
				at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:417)
				at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:383)
				... 86 more
</pre>
</details>

**Hypotheses**

Not sure. I thought it can't resolve the dependency, so I added it as test dependency to the `dist` module.

```xml

    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-tcnative-boringssl-static</artifactId>
      <scope>test</scope>
    </dependency>
```

Didn't helped. 

@oleschoenburg suggested to remove the local dependcy from my maven cache so I deleted ` rm -r ~/.m2/repository/io/netty/netty-tcnative-boringssl-static/`. Also didn't helped :cry:

**Comment by npepinpe** [comment]
Is it because it failed to load `libcrypt`?

> libcrypt.so.1: cannot open shared object file: No such file or directory

It was one of the suppressed errors when trying to load the packaged dependency. Perhaps in one of the updates they changed something and now it implicitly depends on `libcrypt`? See this semi-relevant issue: https://github.com/GoogleContainerTools/distroless/issues/942

**Comment by Zelldon** [comment]
Not sure whether I can follow :sweat_smile: I run it locally, does this matter?

**Comment by npepinpe** [comment]
There's an implicit dependency from tcnative to libcrypt, so you need it installed on whatever system its going to run on - Docker image or locally.

**Comment by npepinpe** [comment]
If you're on arch (IIRC), you can install `libxcrypt-compat` to solve this issue.

**Comment by Zelldon** [comment]
Thanks @npepinpe so this means everyone who wants to run our tests, has to do that right?

**Comment by npepinpe** [comment]
See the even more relevant Arch issue: https://issuehint.com/issue/netty/netty-tcnative/703

**Comment by npepinpe** [comment]
On most Linux distros, libcrypt is already installed :) Apparently arch removed it from their glibc recently: https://bbs.archlinux.org/viewtopic.php?id=274160

**Comment by npepinpe** [comment]
More sources:

- https://github.com/netty/netty/wiki/Forked-Tomcat-Native#prerequisites-for-statically-linked-netty-tcnative--static
- https://github.com/grpc/grpc-java/commit/2b7269b68c610f2dbabed149ce5f866a3935a647#diff-f1a97ccd40c28e5c0945852559d3903cR349

So we could add it as well to our docs :+1:

**Comment by Zelldon** [comment]
Thanks @npepinpe for the links :+1: 

```
$ sudo pacman -Ss libxcrypt
core/libxcrypt 4.4.28-2 [installed]
    Modern library for one-way hashing of passwords
core/libxcrypt-compat 4.4.28-2
    Modern library for one-way hashing of passwords - legacy API functions

$ sudo pacman -S libxcrypt-compat
resolving dependencies...
looking for conflicting packages...

Packages (1) libxcrypt-compat-4.4.28-2

Total Download Size:   0.07 MiB
Total Installed Size:  0.17 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 libxcrypt-compat...    67.8 KiB   929 KiB/s 00:00 [#######] 100%
(1/1) checking keys in keyring                     [#######] 100%
(1/1) checking package integrity                   [#######] 100%
(1/1) loading package files                        [#######] 100%
(1/1) checking for file conflicts                  [#######] 100%
(1/1) checking available disk space                [#######] 100%
:: Processing package changes...
(1/1) installing libxcrypt-compat                  [#######] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
```

Fixed it. :white_check_mark: Yes I think would be good to add this to the contribution guide or docs.
