### ISSUE TITLE
Caused by: java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-95 [ACTIVE]

### ISSUE THREAD

**Issue by bugbugmaker** [camunda/zeebe#10510]
```
2022-09-27 16:03:55.314 [Broker-0-Exporter-7] [Broker-0-zb-fs-workers-8] WARN
      io.camunda.zeebe.broker.exporter.elasticsearch - Error on exporting record with key 15762598695797046
io.camunda.zeebe.exporter.ElasticsearchExporterException: Failed to put component template
        at io.camunda.zeebe.exporter.ElasticsearchClient.putComponentTemplate(ElasticsearchClient.java:263) ~[zeebe-elasticsearch-exporter-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.exporter.ElasticsearchClient.putComponentTemplate(ElasticsearchClient.java:217) ~[zeebe-elasticsearch-exporter-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.exporter.ElasticsearchExporter.createComponentTemplate(ElasticsearchExporter.java:183) ~[zeebe-elasticsearch-exporter-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.exporter.ElasticsearchExporter.createIndexTemplates(ElasticsearchExporter.java:133) ~[zeebe-elasticsearch-exporter-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.exporter.ElasticsearchExporter.export(ElasticsearchExporter.java:80) ~[zeebe-elasticsearch-exporter-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.export(ExporterContainer.java:151) ~[zeebe-broker-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.exportRecord(ExporterContainer.java:138) ~[zeebe-broker-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.broker.exporter.stream.ExporterDirector$RecordExporter.export(ExporterDirector.java:425) ~[zeebe-broker-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.util.retry.BackOffRetryStrategy.run(BackOffRetryStrategy.java:51) ~[zeebe-util-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.0.0.jar:1.0.0]
Caused by: java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-95 [ACTIVE]
        at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:865) ~[elasticsearch-rest-client-7.12.1.jar:7.12.1]
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:283) ~[elasticsearch-rest-client-7.12.1.jar:7.12.1]
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270) ~[elasticsearch-rest-client-7.12.1.jar:7.12.1]
        at io.camunda.zeebe.exporter.ElasticsearchClient.putComponentTemplate(ElasticsearchClient.java:258) ~[zeebe-elasticsearch-exporter-1.0.0.jar:1.0.0]
        ... 14 more
Caused by: java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-95 [ACTIVE]
        at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.timeout(HttpAsyncRequestExecutor.java:387) ~[httpcore-nio-4.4.14.jar:4.4.14]
        at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:92) ~[httpasyncclient-4.1.4.jar:4.1.4]
        at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:39) ~[httpasyncclient-4.1.4.jar:4.1.4]
        at org.apache.http.impl.nio.reactor.AbstractIODispatch.timeout(AbstractIODispatch.java:175) ~[httpcore-nio-4.4.14.jar:4.4.14]
        at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionTimedOut(BaseIOReactor.java:261) ~[httpcore-nio-4.4.14.jar:4.4.14]
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.timeoutCheck(AbstractIOReactor.java:502) ~[httpcore-nio-4.4.14.jar:4.4.14]
        at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:211) ~[httpcore-nio-4.4.14.jar:4.4.14]
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280) ~[httpcore-nio-4.4.14.jar:4.4.14]
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[httpcore-nio-4.4.14.jar:4.4.14]
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) ~[httpcore-nio-4.4.14.jar:4.4.14]
        at java.lang.Thread.run(Thread.java:834) ~[?:?]
```

**Comment by npepinpe** [comment]
The reason this is a warning and not an error is because time outs may happen if Elastic is simply unreachable, or overloaded, or many other things (as we don't control Elastic). You should double check your environment, and this is only worth looking into if Elastic was happily running and serving other requests.

Please advise/confirm, otherwise we will close this issue in a week.

**Comment by npepinpe** [comment]
Closing as per my comment.
