### ISSUE TITLE
NPE during process instance modification

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#10606]
**Describe the bug**

```
Expected to process record 'TypedRecordImpl{metadata=RecordMetadata{recordType=COMMAND, intentValue=255, intent=MODIFY, requestStreamId=1, requestId=37707, protocolVersion=3, valueType=PROCESS_INSTANCE_MODIFICATION, rejectionType=NULL_VAL, rejectionReason=, brokerVersion=8.1.0}, value={"processInstanceKey":2251799813688377,"terminateInstructions":[{"elementInstanceKey":2251799813688383}],"activateInstructions":[{"elementId":"end","ancestorScopeKey":-1,"variableInstructions":[]}]}}' without errors, but exception occurred with message 'Cannot invoke "io.camunda.zeebe.engine.state.instance.ElementInstance.getKey()" because "elementInstance" is null'.
```

**To Reproduce**

Unclear, data (ie. models) is not accessible anymore.

**Expected behavior**

No NPE, if this is expected then we should throw a meaningful exception.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
 java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.engine.state.instance.ElementInstance.getKey()" because "elementInstance" is null
	at io.camunda.zeebe.engine.processing.processinstance.ProcessInstanceModificationProcessor.terminateElement(ProcessInstanceModificationProcessor.java:535) ~[zeebe-workflow-engine-8.1.0-rc2.jar:8.1.0-rc2]
	at io.camunda.zeebe.engine.processing.processinstance.ProcessInstanceModificationProcessor.terminateElement(ProcessInstanceModificationProcessor.java:558) ~[zeebe-workflow-engine-8.1.0-rc2.jar:8.1.0-rc2]
	at io.camunda.zeebe.engine.processing.processinstance.ProcessInstanceModificationProcessor.lambda$processRecord$3(ProcessInstanceModificationProcessor.java:203) ~[zeebe-workflow-engine-8.1.0-rc2.jar:8.1.0-rc2]
	at java.lang.Iterable.forEach(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.processinstance.ProcessInstanceModificationProcessor.processRecord(ProcessInstanceModificationProcessor.java:197) ~[zeebe-workflow-engine-8.1.0-rc2.jar:8.1.0-rc2]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[zeebe-workflow-engine-8.1.0-rc2.jar:8.1.0-rc2]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.lambda$processCommand$3(ProcessingStateMachine.java:261) ~[zeebe-workflow-engine-8.1.0-rc2.jar:8.1.0-rc2]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-8.1.0-rc2.jar:8.1.0-rc2]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:257) ~[zeebe-workflow-engine-8.1.0-rc2.jar:8.1.0-rc2]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:206) ~[zeebe-workflow-engine-8.1.0-rc2.jar:8.1.0-rc2]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:182) ~[zeebe-workflow-engine-8.1.0-rc2.jar:8.1.0-rc2]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.1.0-rc2.jar:8.1.0-rc2]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.1.0-rc2.jar:8.1.0-rc2]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.1.0-rc2.jar:8.1.0-rc2]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.1.0-rc2.jar:8.1.0-rc2]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.1.0-rc2.jar:8.1.0-rc2]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.1.0-rc2.jar:8.1.0-rc2] 
```

</p>
</details>

Error group: https://console.cloud.google.com/errors/detail/CNSa-5ifjeT1Og?project=camunda-cloud-240911

**Environment:**
- Zeebe Version: 8.1.0-rc2

**Comment by remcowesterhoud** [comment]
This bug has occurred in he medic process now. In my case is was caused by a Call Activity which had an incident whilst mapping the outputs. I've written a test to reproduce it.

```java
  @Test
  public void verifyCallActivityWithIncidentCanBeModified() {
    final var child = Bpmn.createExecutableProcess("child").startEvent().endEvent().done();
    final var parent =
        Bpmn.createExecutableProcess("parent")
            .startEvent()
            .callActivity("callActivity", c -> c.zeebeProcessId("child"))
            .zeebeOutputExpression("x", "y")
            .manualTask("task")
            .endEvent()
            .done();

    ENGINE.deployment().withXmlResource(child).withXmlResource(parent).deploy();

    final var processInstanceKey = ENGINE.processInstance().ofBpmnProcessId("parent").create();

    final var callActivityElement =
        RecordingExporter.processInstanceRecords(ProcessInstanceIntent.ELEMENT_ACTIVATED)
            .withProcessInstanceKey(processInstanceKey)
            .withElementId("callActivity")
            .withElementType(BpmnElementType.CALL_ACTIVITY)
            .getFirst();

    Assertions.assertThat(
            RecordingExporter.incidentRecords(IncidentIntent.CREATED)
                .withProcessInstanceKey(processInstanceKey)
                .getFirst())
        .extracting(r -> r.getValue().getElementId())
        .isEqualTo("callActivity");

    ENGINE
        .processInstance()
        .withInstanceKey(processInstanceKey)
        .modification()
        .activateElement("task")
        .terminateElement(callActivityElement.getKey())
        .modify();

    verifyThatRootElementIsActivated(processInstanceKey, "task", BpmnElementType.MANUAL_TASK);
    verifyThatProcessInstanceIsCompleted(processInstanceKey);
  }
```

I feel like this could be a common scenario in which modification is used and we should aim to fix this in the next patch release. WDYT @saig0?

**Comment by remcowesterhoud** [comment]
As it's as small fix I'll go ahead and do it.
