### ISSUE TITLE
SecureClusteredMessagingIT:shouldFormAClusterWithTls is flaky

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#10655]
**Summary**

- How often does the test fail? multiple times
- Does it block your work?
- Do we suspect that it is a real failure? NO

**Failures**
<details><summary>Example assertion failure</summary>
<pre>
Expecting code not to raise a throwable but caught
  "java.util.concurrent.CompletionException: java.lang.IllegalStateException: Channel to remote peer localhost/<unresolved>:49267 was unexpectedly closed before any certificates were extracted
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118)
	at io.camunda.zeebe.test.util.netty.NettySslClient.getRemoteCertificateChain(NettySslClient.java:93)
	at io.camunda.zeebe.test.util.asserts.SslAssert.lambda$isSecuredBy$0(SslAssert.java:72)
	at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:63)
	at org.assertj.core.api.AssertionsForClassTypes.catchThrowable(AssertionsForClassTypes.java:892)
	at org.assertj.core.api.AssertionsForClassTypes.assertThatCode(AssertionsForClassTypes.java:863)
	at org.assertj.core.api.Assertions.assertThatCode(Assertions.java:1287)
	at io.camunda.zeebe.test.util.asserts.SslAssert.isSecuredBy(SslAssert.java:72)
	at io.camunda.zeebe.it.network.SecureClusteredMessagingIT.assertAddressIsSecured(SecureClusteredMessagingIT.java:113)
	at io.camunda.zeebe.it.network.SecureClusteredMessagingIT.lambda$shouldFormAClusterWithTls$4(SecureClusteredMessagingIT.java:87)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at java.base/java.util.Collections$UnmodifiableMap.forEach(Collections.java:1553)
	at io.camunda.zeebe.it.network.SecureClusteredMessagingIT.shouldFormAClusterWithTls(SecureClusteredMessagingIT.java:87)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
</pre>
</details>

**Logs**

https://github.com/camunda/zeebe/actions/runs/3219269983/jobs/5264437335
[Test results for Integration Tests.zip](https://github.com/camunda/zeebe/files/9746651/Test.results.for.Integration.Tests.1.zip)

**Comment by Zelldon** [comment]
Is failing on main https://github.com/camunda/zeebe/actions/runs/3224756524/jobs/5276240737 feels like it is no longer flaky but more just failing.

Maybe related to an expired certificate?

**Comment by deepthidevaki** [comment]
I'm running it locally with out any failures :shrug:

**Comment by Zelldon** [comment]
Which docker image are you using?

**Comment by deepthidevaki** [comment]
image built from latest main.

**Comment by korthout** [comment]
@npepinpe Do you already have an idea why this fails/flakes?

I have to retry most CI runs now because of this test 😕

**Comment by npepinpe** [comment]
Yes, I should have a fix tomorrow, don't think today will be possible
