### ISSUE TITLE
NPE on ProcessingScheduleService.runDelayed(java.time.Duration, java.lang.Runnable)

### ISSUE THREAD

**Issue by saig0** [camunda/zeebe#10784]
**Describe the bug**

The broker was started. During the bootstrapping of the partitions, the broker was interrupted. As a result, it interrupted the transition of the partitions from `INACTIVE` to `LEADER`. 

After pausing the partitions, the following error was written. 

```
java.lang.NullPointerException: 
  Cannot invoke "io.camunda.zeebe.engine.api.ProcessingScheduleService.runDelayed(java.time.Duration, java.lang.Runnable) 
  because "this.scheduleService" is null
at io.camunda.zeebe.engine.processing.message.PendingProcessMessageSubscriptionChecker.rescheduleTimer(PendingProcessMessageSubscriptionChecker.java:70) 
```

The shutdown continued without other errors. The log state statement can be considered _noise_.

**To Reproduce**

Interrupt the bootstrapping of the partition from `INACTIVE` to `LEADER`.

The partition was paused just before the error was printed.

**Expected behavior**

No error is printed.

The bootstrapping of the partition is interrupted without causing an NPE.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.engine.api.ProcessingScheduleService.runDelayed(java.time.Duration, java.lang.Runnable)" because "this.scheduleService" is null
	at io.camunda.zeebe.engine.processing.message.PendingProcessMessageSubscriptionChecker.rescheduleTimer(PendingProcessMessageSubscriptionChecker.java:70) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.engine.processing.message.PendingProcessMessageSubscriptionChecker.onResumed(PendingProcessMessageSubscriptionChecker.java:65) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at io.camunda.zeebe.streamprocessor.StreamProcessor.lambda$resumeProcessing$14(StreamProcessor.java:525) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.scheduler.ActorControl.lambda$call$0(ActorControl.java:123) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:86) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
```

</p>
</details>

**Environment:**
- OS: Camunda 8 SaaS
- Zeebe Version: `8.1.2`
- Configuration:

**Comment by menski** [comment]
We see this as low prio and more noice, doesn't block the shutdown.

**Comment by korthout** [comment]
[Reported](https://console.cloud.google.com/errors/detail/CN7v37mm2r6ppgE;service=zeebe;time=P7D?project=camunda-cloud-240911) in production on `8.2.0-alpha2`. Once fixed, we should resolve this reported error.

**Comment by Zelldon** [comment]
The switch to the AsyncScheduleService (with working on #11788 ) we have change moved this issue to the AsyncSchedule service,


[Right now I think it is the same cause, partition restarts/stops and service is set to null, which causes issues.](https://console.cloud.google.com/logs/query;query=%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.pod_name%3D%22zeebe-0%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.namespace_name%3D%2212cec096-206e-4a38-a869-a5921442c819-zeebe%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22europe-west1-d%22;timeRange=2023-03-07T00:42:08.981Z%2F2023-03-07T01:42:08.981Z;pinnedLogId=2023-03-07T01:11:38.981929639Z%2Fqiguubm20wwrdieb;cursorTimestamp=2023-03-07T01:11:38.981929639Z?project=camunda-cloud-240911)



```java
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.scheduler.ActorControl.submit(java.lang.Runnable)" because "this.actorControl" is null

at io.camunda.zeebe.stream.impl.ProcessingScheduleServiceImpl.lambda$toRunnable$5 ( [io/camunda.zeebe.stream.impl/ProcessingScheduleServiceImpl.java:131](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.stream.impl%2FProcessingScheduleServiceImpl.java&line=131&project=camunda-cloud-240911) )
at io.camunda.zeebe.scheduler.ActorJob.invoke ( [io/camunda.zeebe.scheduler/ActorJob.java:92](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.scheduler%2FActorJob.java&line=92&project=camunda-cloud-240911) )
at io.camunda.zeebe.scheduler.ActorJob.execute ( [io/camunda.zeebe.scheduler/ActorJob.java:45](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.scheduler%2FActorJob.java&line=45&project=camunda-cloud-240911) )
at io.camunda.zeebe.scheduler.ActorTask.execute ( [io/camunda.zeebe.scheduler/ActorTask.java:119](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.scheduler%2FActorTask.java&line=119&project=camunda-cloud-240911) )
at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask ( [io/camunda.zeebe.scheduler/ActorThread.java:106](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.scheduler%2FActorThread.java&line=106&project=camunda-cloud-240911) )
at io.camunda.zeebe.scheduler.ActorThread.doWork ( [io/camunda.zeebe.scheduler/ActorThread.java:87](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.scheduler%2FActorThread.java&line=87&project=camunda-cloud-240911) )
at io.camunda.zeebe.scheduler.ActorThread.run ( [io/camunda.zeebe.scheduler/ActorThread.java:198](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.scheduler%2FActorThread.java&line=198&project=camunda-cloud-240911) )

```

Error group:

 https://console.cloud.google.com/errors/detail/CPmUkIL--MrwNg;service=zeebe;time=P7D?project=camunda-cloud-240911

Additional improvement: Add partition id and node id to actor name, and context.


\cc @oleschoenburg

**Comment by Zelldon** [comment]
Same occurred for our medic benchmarks

https://console.cloud.google.com/errors/detail/CPmUkIL--MrwNg;service=zeebe;time=P7D?project=zeebe-io

**Comment by npepinpe** [comment]
Has not happened in a long time, closing for now. Hard to tell if it's still relevant; do reopen with a link to the error.
