### ISSUE TITLE
`SnapshotWithExportersTest.shouldTakeSnapshotWhenExporterPositionIsMinusOne` fails with NPE

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#10796]
```
java.lang.NullPointerException: Cannot invoke "String.split(String)" because "name" is null
	at io.camunda.zeebe.snapshots.impl.FileBasedSnapshotId.ofFileName(FileBasedSnapshotId.java:45)
	at io.camunda.zeebe.it.clustering.SnapshotWithExportersTest.lambda$shouldTakeSnapshotWhenExporterPositionIsMinusOne$5(SnapshotWithExportersTest.java:103)
	at org.awaitility.core.AbstractHamcrestCondition.lambda$new$0(AbstractHamcrestCondition.java:48)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by oleschoenburg** [comment]
Fixed by https://github.com/camunda/zeebe/pull/10812
