### ISSUE TITLE
StreamProcessorTest#shouldBeAbleToWriteRejectionOnErrorHandling

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#10913]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail?
  - at least once
- Does it block your work?
  - no
- Do we suspect that it is a real failure?
  - no

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Error:  Tests run: 26, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 26.364 s <<< FAILURE! - in io.camunda.zeebe.streamprocessor.StreamProcessorTest
Error:  io.camunda.zeebe.streamprocessor.StreamProcessorTest.shouldBeAbleToWriteRejectionOnErrorHandling  Time elapsed: 8.768 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 

Expecting value to be true but was false
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at io.camunda.zeebe.streamprocessor.StreamProcessorTest.shouldBeAbleToWriteRejectionOnErrorHandling(StreamProcessorTest.java:637)
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

https://github.com/camunda/zeebe/actions/runs/3391040744/jobs/5635816543

See the build link for logs.

**Comment by Zelldon** [comment]
https://github.com/camunda/zeebe/pull/10903

**Comment by npepinpe** [comment]
Happened again: https://github.com/camunda/zeebe/actions/runs/3416186595/jobs/5686079676

I see the PR isn't merged though, so hopefully it'll be fixed soon :crossed_fingers:
