### ISSUE TITLE
BpmnModelException: Collection expected to have <1> entry but has <0> 

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#10962]
**Describe the bug**

When transforming a message element, if there are any extension elements, we look up a message subscription and expect one to be present. It seems possible that there are other extensions and yet not subscription.

**To Reproduce**

Since the error occurs during the deployment (and prevents it), I couldn't get the original model. I did come up with one equivalent, though I realize it doesn't represent a real user model. I'm still very curious how a user ran into this!

Deploy the following model:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:zeebe="http://camunda.org/schema/zeebe/1.0" xmlns:modeler="http://camunda.org/schema/modeler/1.0" id="Definitions_17ciwxv" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Camunda Modeler" exporterVersion="5.0.0" modeler:executionPlatform="Camunda Cloud" modeler:executionPlatformVersion="8.0.0">
  <bpmn:process id="Process_1e1db37" isExecutable="true">
    <bpmn:startEvent id="StartEvent_1">
      <bpmn:outgoing>Flow_1ihpu77</bpmn:outgoing>
      <bpmn:messageEventDefinition id="MessageEventDefinition_1i4l5ll" messageRef="Message_3us25ap" />
    </bpmn:startEvent>
    <bpmn:sequenceFlow id="Flow_1ihpu77" sourceRef="StartEvent_1" targetRef="Event_1t5fhii" />
    <bpmn:endEvent id="Event_1t5fhii">
      <bpmn:incoming>Flow_1ihpu77</bpmn:incoming>
    </bpmn:endEvent>
  </bpmn:process>
  <bpmn:message id="Message_3us25ap" name="Message_3us25ap">
    <bpmn:extensionElements>
      <zeebe:loopCharacteristics inputCollection="=inputs" inputElement="input" outputCollection="outputs" outputElement="=output" />
    </bpmn:extensionElements>
  </bpmn:message>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_1e1db37">
      <bpmndi:BPMNEdge id="Flow_1ihpu77_di" bpmnElement="Flow_1ihpu77">
        <di:waypoint x="215" y="97" />
        <di:waypoint x="432" y="97" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="Event_0n9czjp_di" bpmnElement="StartEvent_1">
        <dc:Bounds x="179" y="79" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_1t5fhii_di" bpmnElement="Event_1t5fhii">
        <dc:Bounds x="432" y="79" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_1kncmh3_di" bpmnElement="Event_1legy83">
        <dc:Bounds x="272" y="272" width="36" height="36" />
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>
```

Notice that instead of a `zeebe:subscription` extension element in the message, I put a `zeebe:loopCharacteristics`. It doesn't really matter, the real issue is that:

1. It is a message start event
2. The message has some extension element
3. There is no subscription extension element

**Expected behavior**

I get a clear rejection message saying I need a subscription. Right now, I just get an error in the logs and no rejection, and I am a sad user.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
io.camunda.zeebe.model.bpmn.BpmnModelException: Collection expected to have <1> entry but has <0>
	at io.camunda.zeebe.model.bpmn.impl.QueryImpl.singleResult(QueryImpl.java:79) ~[zeebe-bpmn-model-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.MessageTransformer.transform(MessageTransformer.java:39) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.MessageTransformer.transform(MessageTransformer.java:21) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.TransformationVisitor.visit(TransformationVisitor.java:42) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.model.bpmn.traversal.TypeHierarchyVisitor.visit(TypeHierarchyVisitor.java:39) ~[zeebe-bpmn-model-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.model.bpmn.traversal.ModelWalker.walk(ModelWalker.java:66) ~[zeebe-bpmn-model-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.BpmnTransformer.transformDefinitions(BpmnTransformer.java:110) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.transformResource(BpmnResourceTransformer.java:69) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transformResource(DeploymentTransformer.java:120) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transform(DeploymentTransformer.java:97) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.processRecord(DeploymentCreateProcessor.java:98) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.lambda$processCommand$3(ProcessingStateMachine.java:261) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:257) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:206) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:182) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
```

</p>
</details>

**Environment:**
- OS: SaaS
- Zeebe Version: 8.1.2
- Configuration: SaaS

**Comment by npepinpe** [comment]
Some more context:

- It seems in the `MessageValidator`, for message start events, we only verify the name and nothing else. I assume we also want to verify the subscription?
- The `MessageTransformer` checks that if there is some extension elements, then there must be  a subscription. I don't think that's correct, but you would know better.

Tentatively I would say this is mid severity, as it's clearly a bad request, but since there is no good error reporting it's hard for the user to know what they're doing wrong.
