### ISSUE TITLE
`ReplayStateMachine.replayNextEvent` tries to complete  `recoveryFuture` twice

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#11060]
**Describe the bug**

During rapid transitions to leader and back to follower of a partition, the replay state machine tries to complete the `recoveryFuture` twice which is not allowed.

**To Reproduce**

Not clear yet, see https://console.cloud.google.com/errors/detail/CPyvvqu217v0sAE;service=zeebe;time=P7D?project=camunda-cloud-240911

Logs here: https://drive.google.com/file/d/1dWJEhqsoBKw1Ppd4tPlvHYEBDi2ppYJC/view?usp=share_link

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalStateException: Cannot complete future, the future is already completed  with value [lastProcessedPosition: 5474841, lastWrittenPosition: 5474842]
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.completeExceptionally(CompletableActorFuture.java:186) ~[zeebe-scheduler-8.1.0-alpha5.jar:8.1.0-alpha5]
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.completeExceptionally(CompletableActorFuture.java:193) ~[zeebe-scheduler-8.1.0-alpha5.jar:8.1.0-alpha5]
	at io.camunda.zeebe.streamprocessor.ReplayStateMachine.replayNextEvent(ReplayStateMachine.java:191) ~[zeebe-workflow-engine-8.1.0-alpha5.jar:8.1.0-alpha5]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.1.0-alpha5.jar:8.1.0-alpha5]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.1.0-alpha5.jar:8.1.0-alpha5]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.1.0-alpha5.jar:8.1.0-alpha5]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.1.0-alpha5.jar:8.1.0-alpha5]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.1.0-alpha5.jar:8.1.0-alpha5]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.1.0-alpha5.jar:8.1.0-alpha5]
Caused by: java.lang.RuntimeException: Failed to replay records. [snapshot-position: 5474841, last-read-record-position: 5474842, last-replayed-event-position: -1]
	... 7 more
Caused by: java.lang.IllegalStateException: Cannot complete future, the future is already completed  with value [lastProcessedPosition: 5474841, lastWrittenPosition: 5474842]
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.complete(CompletableActorFuture.java:166) ~[zeebe-scheduler-8.1.0-alpha5.jar:8.1.0-alpha5]
	at io.camunda.zeebe.streamprocessor.ReplayStateMachine.onRecordsReplayed(ReplayStateMachine.java:254) ~[zeebe-workflow-engine-8.1.0-alpha5.jar:8.1.0-alpha5]
	at io.camunda.zeebe.streamprocessor.ReplayStateMachine.replayNextEvent(ReplayStateMachine.java:180) ~[zeebe-workflow-engine-8.1.0-alpha5.jar:8.1.0-alpha5]
	... 6 more
```

</p>
</details>

**Environment:**
- Zeebe Version: 8.1.0-alpha5

**Comment by oleschoenburg** [comment]
Appears to be a duplicate of https://github.com/camunda/zeebe/issues/10240 because https://github.com/camunda/zeebe/commit/10ddfb1c1b2f0e11ceed9015e024bdc36b32ad06 is not in 8.1.0-alpha5

Thanks to @npepinpe for spotting it!
