### ISSUE TITLE
`ProcessExecutionRandomizedPropertyTest.shouldExecuteProcessToEnd` fails reproducibly

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#11288]
**Describe the bug**

The test fails reproducibly with fixed seeds. I found this by accident and haven't looked into whether this is a flaky test or a bug.

**To Reproduce**
Run `ProcessExecutionRandomizedPropertyTest.shouldExecuteProcessToEnd` with `processSeed=3273775557986795449L, executionPathSeed=7501916199212078022L`

**Expected behavior**

Test doesn't fail.

**Log**

<details><summary>Test logs</summary>
 <p>

```

13:55:58.171 [] INFO  io.camunda.zeebe.test - Test failed, following records were exported:
13:55:58.281 [] INFO  io.camunda.zeebe.test - Compact log representation:
--------
	['C'ommand/'E'event/'R'ejection] [valueType] [intent] - #[position]->#[source record position] K[key] - [summary of value]
	P9K999 - key; #999 - record position; "ID" element/process id; @"elementid"/[P9K999] - element with ID and key
	Keys are decomposed into partition id and per partition key (e.g. 2251799813685253 -> P1K005). If single partition, the partition is omitted.
	Long IDs are shortened (e.g. 'startEvent_5d56488e-0570-416c-ba2d-36d2a3acea78' -> 'star..acea78'
--------
C DPLY       CREATE            - #001->  -1   -1 - 
E PROC       CREATED           - #002->#001 K001 - process.xml -> "process_id_58" (version:1)
E PROC       CREATED           - #003->#001 K002 - process.xml -> "process..d_id_44" (version:1)
E DPLY       CREATED           - #004->#001 K003 - process.xml, process.xml
E DPLY       FULLY_DISTRIBUTED - #005->#001 K003 - 
C CREA       CREATE            - #006->  -1   -1 - new <process "process_id_58"> (default start)  (no vars)
C PI         ACTIVATE          - #007->#006 K004 - PROCESS "process_id_58" in <process "process_id_58"[K004]>
E CREA       CREATED           - #008->#006 K005 - new <process "process_id_58"> (default start)  (no vars)
E PI         ACTIVATING        - #009->#007 K004 - PROCESS "process_id_58" in <process "process_id_58"[K004]>
E PI         ACTIVATED         - #010->#007 K004 - PROCESS "process_id_58" in <process "process_id_58"[K004]>
C PI         ACTIVATE          - #011->#007   -1 - START_EVENT "id_59" in <process "process_id_58"[K004]>
E PI         ACTIVATING        - #012->#011 K006 - START_EVENT "id_59" in <process "process_id_58"[K004]>
E PI         ACTIVATED         - #013->#011 K006 - START_EVENT "id_59" in <process "process_id_58"[K004]>
C PI         COMPLETE          - #014->#011 K006 - START_EVENT "id_59" in <process "process_id_58"[K004]>
E PI         COMPLETING        - #015->#014 K006 - START_EVENT "id_59" in <process "process_id_58"[K004]>
E PI         COMPLETED         - #016->#014 K006 - START_EVENT "id_59" in <process "process_id_58"[K004]>
E PI         SEQ_FLOW_TAKEN    - #017->#014 K007 - SEQUENCE_FLOW "sequenc..c9413e1" in <process "process_id_58"[K004]>
C PI         ACTIVATE          - #018->#014 K008 - PARALLEL_GATEWAY "fork_id_1" in <process "process_id_58"[K004]>
E PI         ACTIVATING        - #019->#018 K008 - PARALLEL_GATEWAY "fork_id_1" in <process "process_id_58"[K004]>
E PI         ACTIVATED         - #020->#018 K008 - PARALLEL_GATEWAY "fork_id_1" in <process "process_id_58"[K004]>
E PI         COMPLETING        - #021->#018 K008 - PARALLEL_GATEWAY "fork_id_1" in <process "process_id_58"[K004]>
E PI         COMPLETED         - #022->#018 K008 - PARALLEL_GATEWAY "fork_id_1" in <process "process_id_58"[K004]>
E PI         SEQ_FLOW_TAKEN    - #023->#018 K009 - SEQUENCE_FLOW "id_37" in <process "process_id_58"[K004]>
C PI         ACTIVATE          - #024->#018 K010 - SERVICE_TASK "id_39" in <process "process_id_58"[K004]>
E PI         SEQ_FLOW_TAKEN    - #025->#018 K011 - SEQUENCE_FLOW "sequenc..403f5fb" in <process "process_id_58"[K004]>
C PI         ACTIVATE          - #026->#018 K012 - PARALLEL_GATEWAY "fork_id_5" in <process "process_id_58"[K004]>
E PI         ACTIVATING        - #027->#024 K010 - SERVICE_TASK "id_39" in <process "process_id_58"[K004]>
E JOB        CREATED           - #028->#024 K013 - K013 "job_id_39" @"id_39"[K010] 3 retries, in <process "process_id_58"[K004]> (no vars)
E PI         ACTIVATED         - #029->#024 K010 - SERVICE_TASK "id_39" in <process "process_id_58"[K004]>
C JOB_BATCH  ACTIVATE          - #030->  -1   -1 - "job_id_39" max: 10
E PI         ACTIVATING        - #031->#026 K012 - PARALLEL_GATEWAY "fork_id_5" in <process "process_id_58"[K004]>
E PI         ACTIVATED         - #032->#026 K012 - PARALLEL_GATEWAY "fork_id_5" in <process "process_id_58"[K004]>
E PI         COMPLETING        - #033->#026 K012 - PARALLEL_GATEWAY "fork_id_5" in <process "process_id_58"[K004]>
E PI         COMPLETED         - #034->#026 K012 - PARALLEL_GATEWAY "fork_id_5" in <process "process_id_58"[K004]>
E PI         SEQ_FLOW_TAKEN    - #035->#026 K014 - SEQUENCE_FLOW "id_12" in <process "process_id_58"[K004]>
C PI         ACTIVATE          - #036->#026 K015 - SEND_TASK "id_14" in <process "process_id_58"[K004]>
E PI         SEQ_FLOW_TAKEN    - #037->#026 K016 - SEQUENCE_FLOW "sequenc..5611794" in <process "process_id_58"[K004]>
C PI         ACTIVATE          - #038->#026 K017 - SCRIPT_TASK "id_9" in <process "process_id_58"[K004]>
E JOB_BATCH  ACTIVATED         - #039->#030 K018 - "job_id_39" 1/10
                 K013 "job_id_39" @"id_39"[K010] 3 retries, in <process "process_id_58"[K004]> (no vars)
C JOB        COMPLETE          - #040->  -1 K013 - K013 -1 retries, in <process ?[?]> (no vars)
E PI         ACTIVATING        - #041->#036 K015 - SEND_TASK "id_14" in <process "process_id_58"[K004]>
E JOB        CREATED           - #042->#036 K019 - K019 "job_id_14" @"id_14"[K015] 3 retries, in <process "process_id_58"[K004]> (no vars)
E PI         ACTIVATED         - #043->#036 K015 - SEND_TASK "id_14" in <process "process_id_58"[K004]>
E PI         ACTIVATING        - #044->#038 K017 - SCRIPT_TASK "id_9" in <process "process_id_58"[K004]>
E JOB        CREATED           - #045->#038 K020 - K020 "job_id_9" @"id_9"[K017] 3 retries, in <process "process_id_58"[K004]> (no vars)
E PI         ACTIVATED         - #046->#038 K017 - SCRIPT_TASK "id_9" in <process "process_id_58"[K004]>
E JOB        COMPLETED         - #047->#040 K013 - K013 "job_id_39" @"id_39"[K010] 3 retries, in <process "process_id_58"[K004]> (no vars)
E PROC_EVNT  TRIGGERING        - #048->#040 K021 -  @"id_39"[K010] in <process K001[K004]> (no vars)
C PI         COMPLETE          - #049->#040 K010 - SERVICE_TASK "id_39" in <process "process_id_58"[K004]>
C JOB_BATCH  ACTIVATE          - #050->  -1   -1 - "job_id_9" max: 10
E PI         COMPLETING        - #051->#049 K010 - SERVICE_TASK "id_39" in <process "process_id_58"[K004]>
E PI         COMPLETED         - #052->#049 K010 - SERVICE_TASK "id_39" in <process "process_id_58"[K004]>
E PI         SEQ_FLOW_TAKEN    - #053->#049 K022 - SEQUENCE_FLOW "sequenc..65ad8e0" in <process "process_id_58"[K004]>
C PI         ACTIVATE          - #054->#049 K023 - SUB_PROCESS "id_40" in <process "process_id_58"[K004]>
E JOB_BATCH  ACTIVATED         - #055->#050 K024 - "job_id_9" 1/10
                 K020 "job_id_9" @"id_9"[K017] 3 retries, in <process "process_id_58"[K004]> (no vars)
C JOB        FAIL              - #056->  -1 K020 - K020 3 retries, in <process ?[?]> (no vars)
E PI         ACTIVATING        - #057->#054 K023 - SUB_PROCESS "id_40" in <process "process_id_58"[K004]>
E PI         ACTIVATED         - #058->#054 K023 - SUB_PROCESS "id_40" in <process "process_id_58"[K004]>
C PI         ACTIVATE          - #059->#054   -1 - START_EVENT "id_41" in <process "process_id_58"[K004]>
E JOB        FAILED            - #060->#056 K020 - K020 "job_id_9" @"id_9"[K017] 3 retries, in <process "process_id_58"[K004]> (no vars)
C JOB_BATCH  ACTIVATE          - #061->  -1   -1 - "job_id_9" max: 10
E PI         ACTIVATING        - #062->#059 K025 - START_EVENT "id_41" in <process "process_id_58"[K004]>
E PI         ACTIVATED         - #063->#059 K025 - START_EVENT "id_41" in <process "process_id_58"[K004]>
C PI         COMPLETE          - #064->#059 K025 - START_EVENT "id_41" in <process "process_id_58"[K004]>
E JOB_BATCH  ACTIVATED         - #065->#061 K026 - "job_id_9" 1/10
                 K020 "job_id_9" @"id_9"[K017] 3 retries, in <process "process_id_58"[K004]> (no vars)
C JOB        THROW_ERROR       - #066->  -1 K020 - K020 -1 retries, error_id_9: in <process ?[?]> (no vars)
E PI         COMPLETING        - #067->#064 K025 - START_EVENT "id_41" in <process "process_id_58"[K004]>
E PI         COMPLETED         - #068->#064 K025 - START_EVENT "id_41" in <process "process_id_58"[K004]>
E PI         SEQ_FLOW_TAKEN    - #069->#064 K027 - SEQUENCE_FLOW "sequenc..48ae304" in <process "process_id_58"[K004]>
C PI         ACTIVATE          - #070->#064 K028 - CALL_ACTIVITY "id_44" in <process "process_id_58"[K004]>
E JOB        ERROR_THROWN      - #071->#066 K020 - K020 "job_id_9" @"id_9"[K017] 3 retries, error_id_9: in <process "process_id_58"[K004]> (no vars)
E PROC_EVNT  TRIGGERING        - #072->#066 K029 -  @"boundar..or_id_9"[K017] in <process K001[K004]> (no vars)
C PI         TERMINATE         - #073->#066 K017 - SCRIPT_TASK "id_9" in <process "process_id_58"[K004]>
E PI         ACTIVATING        - #074->#070 K028 - CALL_ACTIVITY "id_44" in <process "process_id_58"[K004]>
E PI         ACTIVATED         - #075->#070 K028 - CALL_ACTIVITY "id_44" in <process "process_id_58"[K004]>
C PI         ACTIVATE          - #076->#070 K030 - PROCESS "process..d_id_44" in <process "process..d_id_44"[K030]>
E PI         TERMINATING       - #077->#073 K017 - SCRIPT_TASK "id_9" in <process "process_id_58"[K004]>
E PI         TERMINATED        - #078->#073 K017 - SCRIPT_TASK "id_9" in <process "process_id_58"[K004]>
E PROC_EVNT  TRIGGERED         - #079->#073 K029 -  @"boundar..or_id_9"[K017] in <process K001[K004]> (no vars)
E PI         ACTIVATING        - #080->#073 K031 - BOUNDARY_EVENT "boundar..or_id_9" in <process "process_id_58"[K004]>
E PI         ACTIVATED         - #081->#073 K031 - BOUNDARY_EVENT "boundar..or_id_9" in <process "process_id_58"[K004]>
C PI         COMPLETE          - #082->#073 K031 - BOUNDARY_EVENT "boundar..or_id_9" in <process "process_id_58"[K004]>
E PI         ACTIVATING        - #083->#076 K030 - PROCESS "process..d_id_44" in <process "process..d_id_44"[K030]>
E PI         ACTIVATED         - #084->#076 K030 - PROCESS "process..d_id_44" in <process "process..d_id_44"[K030]>
C PI         ACTIVATE          - #085->#076   -1 - START_EVENT "escalat..t_id_44" in <process "process..d_id_44"[K030]>
E PI         COMPLETING        - #086->#082 K031 - BOUNDARY_EVENT "boundar..or_id_9" in <process "process_id_58"[K004]>
E PI         COMPLETED         - #087->#082 K031 - BOUNDARY_EVENT "boundar..or_id_9" in <process "process_id_58"[K004]>
E PI         SEQ_FLOW_TAKEN    - #088->#082 K032 - SEQUENCE_FLOW "sequenc..5733fc6" in <process "process_id_58"[K004]>
C PI         ACTIVATE          - #089->#082 K033 - END_EVENT "endEven..65398ba" in <process "process_id_58"[K004]>
E PI         ACTIVATING        - #090->#085 K034 - START_EVENT "escalat..t_id_44" in <process "process..d_id_44"[K030]>
E PI         ACTIVATED         - #091->#085 K034 - START_EVENT "escalat..t_id_44" in <process "process..d_id_44"[K030]>
C PI         COMPLETE          - #092->#085 K034 - START_EVENT "escalat..t_id_44" in <process "process..d_id_44"[K030]>
E PI         ACTIVATING        - #093->#089 K033 - END_EVENT "endEven..65398ba" in <process "process_id_58"[K004]>
E PI         ACTIVATED         - #094->#089 K033 - END_EVENT "endEven..65398ba" in <process "process_id_58"[K004]>
E PI         COMPLETING        - #095->#089 K033 - END_EVENT "endEven..65398ba" in <process "process_id_58"[K004]>
E PI         COMPLETED         - #096->#089 K033 - END_EVENT "endEven..65398ba" in <process "process_id_58"[K004]>
C PI         TERMINATE         - #097->#089 K015 - SEND_TASK "id_14" in <process "process_id_58"[K004]>
C PI         TERMINATE         - #098->#089 K023 - SUB_PROCESS "id_40" in <process "process_id_58"[K004]>
E PI         COMPLETING        - #099->#092 K034 - START_EVENT "escalat..t_id_44" in <process "process..d_id_44"[K030]>
E PI         COMPLETED         - #100->#092 K034 - START_EVENT "escalat..t_id_44" in <process "process..d_id_44"[K030]>
E PI         SEQ_FLOW_TAKEN    - #101->#092 K035 - SEQUENCE_FLOW "sequenc..29eff26" in <process "process..d_id_44"[K030]>
C PI         ACTIVATE          - #102->#092 K036 - END_EVENT "escalat..t_id_44" in <process "process..d_id_44"[K030]>
E PI         TERMINATING       - #103->#097 K015 - SEND_TASK "id_14" in <process "process_id_58"[K004]>
E JOB        CANCELED          - #104->#097 K019 - K019 "job_id_14" @"id_14"[K015] 3 retries, in <process "process_id_58"[K004]> (no vars)
E PI         TERMINATED        - #105->#097 K015 - SEND_TASK "id_14" in <process "process_id_58"[K004]>
E PI         TERMINATING       - #106->#098 K023 - SUB_PROCESS "id_40" in <process "process_id_58"[K004]>
C PI         TERMINATE         - #107->#098 K028 - CALL_ACTIVITY "id_44" in <process "process_id_58"[K004]>
E PI         ACTIVATING        - #108->#102 K036 - END_EVENT "escalat..t_id_44" in <process "process..d_id_44"[K030]>
E PI         ACTIVATED         - #109->#102 K036 - END_EVENT "escalat..t_id_44" in <process "process..d_id_44"[K030]>
E PROC_EVNT  TRIGGERING        - #110->#102 K038 -  @"boundar..t_id_44"[K028] in <process K001[K004]> (no vars)
E PROC_EVNT  TRIGGERED         - #111->#102 K038 -  @"boundar..t_id_44"[K028] in <process K001[K004]> (no vars)
E PI         ACTIVATING        - #112->#102 K039 - BOUNDARY_EVENT "boundar..t_id_44" in <process "process_id_58"[K004]>
E PI         ACTIVATED         - #113->#102 K039 - BOUNDARY_EVENT "boundar..t_id_44" in <process "process_id_58"[K004]>
C PI         COMPLETE          - #114->#102 K039 - BOUNDARY_EVENT "boundar..t_id_44" in <process "process_id_58"[K004]>
E ESCALATION ESCALATED         - #115->#102 K037 - EscalationRecord {"processInstanceKey":2251799813685278,"escalationCode":"escalation_code_id_44","throwElementId":"escalation_throw_end_event_id_44","catchElementId":"boundary_escalation_catch_event_id_44"}
C PI         COMPLETE          - #116->#102 K036 - END_EVENT "escalat..t_id_44" in <process "process..d_id_44"[K030]>
E PI         TERMINATING       - #117->#107 K028 - CALL_ACTIVITY "id_44" in <process "process_id_58"[K004]>
C PI         TERMINATE         - #118->#107 K030 - PROCESS "process..d_id_44" in <process "process..d_id_44"[K030]>
R PI         COMPLETE          - #119->#114 K039 - BOUNDARY_EVENT "boundar..t_id_44" in <process "process_id_58"[K004]> !INVALID_STATE (Expected flow scope instance to be in state 'ELEMENT_ACTIVATED' but was 'ELEMENT_TERMINATING'.)
E PI         COMPLETING        - #120->#116 K036 - END_EVENT "escalat..t_id_44" in <process "process..d_id_44"[K030]>
E PI         COMPLETED         - #121->#116 K036 - END_EVENT "escalat..t_id_44" in <process "process..d_id_44"[K030]>
C PI         COMPLETE          - #122->#116 K030 - PROCESS "process..d_id_44" in <process "process..d_id_44"[K030]>
E PI         TERMINATING       - #123->#118 K030 - PROCESS "process..d_id_44" in <process "process..d_id_44"[K030]>
E PI         TERMINATED        - #124->#118 K030 - PROCESS "process..d_id_44" in <process "process..d_id_44"[K030]>
E PI         TERMINATED        - #125->#118 K028 - CALL_ACTIVITY "id_44" in <process "process_id_58"[K004]>
R PI         COMPLETE          - #126->#122 K030 - PROCESS "process..d_id_44" in <process "process..d_id_44"[K030]> !INVALID_STATE (Expected element instance with key '2251799813685278' to be present in state but not found.)
```

</p>
</details>

**Environment:**
- Zeebe Version: 6609fe1a3ea4edbfd9abb661fdd5ce512e6dadb8

**Comment by oleschoenburg** [comment]
More seeds from a [failed CI run](https://github.com/camunda/zeebe/runs/10197974608), not sure if related or not: 
`processSeed=6512603751039175291, executionPathSeed=-2998090558913936035`
`processSeed=6512603751039175291, executionPathSeed=-5362689173149861340`
`processSeed=6512603751039175291, executionPathSeed=580039509098294618`

**Comment by korthout** [comment]
We should look into this sooner rather than later, as this can block CI runs.

**Comment by remcowesterhoud** [comment]
This is another case of boundary events conflicting with a termination. We've seen this before and fixed it partially in https://github.com/camunda/zeebe/pull/11216. Unfortunately this case can still occur.

In this case we have this process, which is called by a call activity:
<img width="692" alt="image" src="https://user-images.githubusercontent.com/5787702/212692301-b73596fe-af3c-468d-be9b-9621098a36a2.png">

The problem occurs when we terminate this process, and if the timing is right the commands and events are written to the log in this order:

1. TERMINATE Process
3. ACTIVATE End event (in this case it's an escalation end event)
4. TERMINATING Process
5. TERMINATE Sub Process
6. ACTIVATING End event
7. ACTIVATED End event

Here we can see that the ACTIVATE of the end event is processed before the TERMINATE of the sub process, but after the TERMINATE of the process. The ACTIVATE of the end event will synchronously activate the boundary event. Since we already processed the TERMINATE of the Process this boundary event will not get terminated. However, once the sub process gets terminated the process still has the boundary event as an active element instance. Because of this the termination is not considered to be complete and the process gets stuck.

I don't see a straightforward fix for this currently. There is an [issue to be able to react on internal command rejections](https://github.com/camunda/zeebe/issues/6964). We should discuss this and see if we can come up with a solution for this problem

**Comment by oleschoenburg** [comment]
https://github.com/camunda/zeebe/commit/824010c56ed8028ee6ba8f47797f58b2351636a6 with new seeds: `processSeed=2258459481247071349, executionPathSeed=-5992484530338886134`

from this run: https://github.com/camunda/zeebe/actions/runs/3952200621

**Comment by berkaycanbc** [comment]
This test failed again during a main build and retrying the build solved it.

**Comment by remcowesterhoud** [comment]
@berkaycanbc Could you please add the seeds, otherwise we can't reproduce it.

**Comment by berkaycanbc** [comment]
> @berkaycanbc Could you please add the seeds, otherwise we can't reproduce it.

@remcowesterhoud here they are: `processSeed=7533641039158471957, executionPathSeed=-9047391171208753859`

**Comment by deepthidevaki** [comment]
Failed again 
```
 io.camunda.zeebe.engine.processing.randomized.ProcessExecutionRandomizedPropertyTest.shouldExecuteProcessToEnd[TestDataRecord{processSeed=6247886289663005460, executionPathSeed=-4398664877632549981}] -- Time elapsed: 5.305 s <<< ERROR!
io.camunda.zeebe.test.util.stream.StreamWrapperException: No event found matching the criteria
	at io.camunda.zeebe.test.util.stream.StreamWrapper.await(StreamWrapper.java:87)
	at io.camunda.zeebe.engine.util.ProcessExecutor.triggerTimerStartEvent(ProcessExecutor.java:267)
	at io.camunda.zeebe.engine.util.ProcessExecutor.applyStep(ProcessExecutor.java:76)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at io.camunda.zeebe.engine.processing.randomized.ProcessExecutionRandomizedPropertyTest.shouldExecuteProcessToEnd(ProcessExecutionRandomizedPropertyTest.java:75)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
```
[Test results for Property Tests.zip](https://github.com/camunda/zeebe/files/15095593/Test.results.for.Property.Tests.zip)

**Comment by berkaycanbc** [comment]
ZPA Triage:

This issue might indicate a bug. We think, someone should soon investigate to determine its severity.
