### ISSUE TITLE
Zeebe doesn't recover after out of disk

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#11348]
**Describe the bug**

The medic 52 week benchmark failed with out of disk space. The problem was that elastic disc went full (curator wasn't configured properly, due to reduced disk sizes).

![elastic](https://user-images.githubusercontent.com/2758593/209781816-aa828b30-e6d7-4509-a85e-9676f01119dc.png)
![exporting](https://user-images.githubusercontent.com/2758593/209781820-91bceec5-3c8e-49d1-8809-a1447f235c81.png)

After deleting the PVC's and elastic pods, elastic recovered but zeebe not. [Exporting failed with:](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22medic-cw-52-cce4510-benchmark%22%0Alabels.k8s-pod%2Fapp%3D%22camunda-platform%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fcomponent%3D%22zeebe-broker%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22medic-cw-52-cce4510-benchmark%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fmanaged-by%3D%22Helm%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22zeebe%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fpart-of%3D%22camunda-platform%22;pinnedLogId=2022-12-28T08:12:36.844567422Z%2F9w4d7t9fouw5pkat;cursorTimestamp=2022-12-28T08:12:36.844567422Z?project=zeebe-io)

```
io.camunda.zeebe.exporter.ElasticsearchExporterException: Failed to flush bulk request: [Failed to flush 49 item(s) of bulk request [type: mapper_parsing_exception, reason: failed to parse], Failed to flush 33 item(s) of bulk request [type: illegal_argument_exception, reason: Limit of total fields [1000] has been exceeded]]
```

**To Reproduce**
Make elastic read only (either by small disk or set it to read only), wait until Zeebe goes OOD. Make elastic writeable again. 

**Expected behavior**
After elastic is available again, zeebe should be able to recover.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```

io.camunda.zeebe.exporter.ElasticsearchExporterException: Failed to flush bulk request: [Failed to flush 49 item(s) of bulk request [type: mapper_parsing_exception, reason: failed to parse], Failed to flush 33 item(s) of bulk request [type: illegal_argument_exception, reason: Limit of total fields [1000] has been exceeded]]
	at io.camunda.zeebe.exporter.ElasticsearchClient.throwCollectedBulkError(ElasticsearchClient.java:177) ~[zeebe-elasticsearch-exporter-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.exporter.ElasticsearchClient.exportBulk(ElasticsearchClient.java:160) ~[zeebe-elasticsearch-exporter-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.exporter.ElasticsearchClient.flush(ElasticsearchClient.java:101) ~[zeebe-elasticsearch-exporter-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.exporter.ElasticsearchExporter.flush(ElasticsearchExporter.java:166) ~[zeebe-elasticsearch-exporter-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.exporter.ElasticsearchExporter.export(ElasticsearchExporter.java:103) ~[zeebe-elasticsearch-exporter-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.lambda$export$5(ExporterContainer.java:181) ~[zeebe-broker-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.jar.ThreadContextUtil.runCheckedWithClassLoader(ThreadContextUtil.java:58) ~[zeebe-util-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.jar.ThreadContextUtil.runWithClassLoader(ThreadContextUtil.java:34) ~[zeebe-util-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.export(ExporterContainer.java:180) ~[zeebe-broker-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.exportRecord(ExporterContainer.java:167) ~[zeebe-broker-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.broker.exporter.stream.ExporterDirector$RecordExporter.export(ExporterDirector.java:525) ~[zeebe-broker-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.retry.BackOffRetryStrategy.run(BackOffRetryStrategy.java:51) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: 8.2.0-snpahsot
- Configuration: benchmark

**Comment by Zelldon** [comment]
```
$ k delete pod -l app.kubernetes.io/component=zeebe-broker
pod "medic-cw-52-cce4510-benchmark-zeebe-0" deleted
pod "medic-cw-52-cce4510-benchmark-zeebe-1" deleted
pod "medic-cw-52-cce4510-benchmark-zeebe-2" deleted
```
Fixed it.

![elastic-export](https://user-images.githubusercontent.com/2758593/209783045-7044751a-65da-433d-ba19-0b5dd4bfc911.png)

**Comment by Zelldon** [comment]
I think the problem is that the batch is to large to write to elastic, which caused the above exception.

**Comment by korthout** [comment]
This may or may not be related, but another cluster did not recover fully after an OOD and started reporting the following error: [JournalException$OutOfDiskSpace: Not enough space to allocate a new journal segment](https://console.cloud.google.com/errors/detail/CIeksZeH5JWWhAE;service=zeebe;time=P7D?project=zeebe-io). See [medic cw8](https://docs.google.com/document/d/1SzgBwOCXrzQ5jvZD_4pxhi9gFYTXNL6m6DUnPQGRNbg/edit#heading=h.9epfjratzuet).
