### ISSUE TITLE
ReplayStateMachine detects inconistent log

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#11347]
**Describe the bug**

[It looks like that our daily chaos experiments have caused an inconsistent log on 8.1.6. ](https://console.cloud.google.com/errors/detail/CMurko6c3rDudQ;service=zeebe;time=P7D?project=camunda-cloud-240911)

The chaos experiments seem to succeed, so this was not detected via failure. But we had an error in our error reporting tool. 

Almost a second before the snapshotting failed with:

```
io.camunda.zeebe.db.ZeebeDbException: Failed to take snapshot in path /usr/local/zeebe/data/raft-partition/partitions/1/pending/904-7-1410-1420.
...
Caused by: org.rocksdb.RocksDBException: While open a file for appending: /usr/local/zeebe/data/raft-partition/partitions/1/runtime/000016.log: No such file or directory
	...
```

Might be related to concurrent access of the PVC as @deepthidevaki observed [last week](https://camunda.slack.com/archives/C037RS2JHB8/p1671541168366179).

**To Reproduce**

Not sure yet, was caused via chaos experiment automation. https://bru-3.operate.ultrawombat.com/7b2cd3f5-cfcc-4a65-ab22-0ccaa071e68e/processes/4503599762282256

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
ava.lang.RuntimeException: java.lang.IllegalStateException: Expected that position '1421' of current event is higher then position '1421' of last event, but was not. Inconsistent log detected!
	at io.camunda.zeebe.streamprocessor.ReplayStateMachine.lambda$replayNextEvent$4(ReplayStateMachine.java:166) ~[zeebe-workflow-engine-8.1.6-SNAPSHOT.jar:8.1.6-SNAPSHOT]
	at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:33) ~[zeebe-scheduler-8.1.6-SNAPSHOT.jar:8.1.6-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) ~[zeebe-scheduler-8.1.6-SNAPSHOT.jar:8.1.6-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.1.6-SNAPSHOT.jar:8.1.6-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.1.6-SNAPSHOT.jar:8.1.6-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.1.6-SNAPSHOT.jar:8.1.6-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.1.6-SNAPSHOT.jar:8.1.6-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.1.6-SNAPSHOT.jar:8.1.6-SNAPSHOT]
Caused by: java.lang.IllegalStateException: Expected that position '1421' of current event is higher then position '1421' of last event, but was not. Inconsistent log detected!
	at io.camunda.zeebe.streamprocessor.ReplayStateMachine.onRecordReplayed(ReplayStateMachine.java:272) ~[zeebe-workflow-engine-8.1.6-SNAPSHOT.jar:8.1.6-SNAPSHOT]
	at io.camunda.zeebe.streamprocessor.ReplayStateMachine.replayEvent(ReplayStateMachine.java:232) ~[zeebe-workflow-engine-8.1.6-SNAPSHOT.jar:8.1.6-SNAPSHOT]
	at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:?]
	at io.camunda.zeebe.streamprocessor.ReplayStateMachine.lambda$tryToReplayBatch$5(ReplayStateMachine.java:205) ~[zeebe-workflow-engine-8.1.6-SNAPSHOT.jar:8.1.6-SNAPSHOT]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-8.1.6-SNAPSHOT.jar:8.1.6-SNAPSHOT]
	at io.camunda.zeebe.streamprocessor.ReplayStateMachine.tryToReplayBatch(ReplayStateMachine.java:203) ~[zeebe-workflow-engine-8.1.6-SNAPSHOT.jar:8.1.6-SNAPSHOT]
	at io.camunda.zeebe.streamprocessor.ReplayStateMachine.lambda$replayNextEvent$3(ReplayStateMachine.java:162) ~[zeebe-workflow-engine-8.1.6-SNAPSHOT.jar:8.1.6-SNAPSHOT]
	at io.camunda.zeebe.scheduler.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:28) ~[zeebe-scheduler-8.1.6-SNAPSHOT.jar:8.1.6-SNAPSHOT]
	at io.camunda.zeebe.scheduler.retry.RecoverableRetryStrategy.run(RecoverableRetryStrategy.java:48) ~[zeebe-scheduler-8.1.6-SNAPSHOT.jar:8.1.6-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.1.6-SNAPSHOT.jar:8.1.6-SNAPSHOT]
	... 5 more
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: 8.1.6-snapshot 
- Configuration:

**Comment by Zelldon** [comment]
Investigation Zeebe-1:

_Hypothesis: Multiple pods are again running at the same time._

* [Transition ot Leader in Term 6 completed](https://console.cloud.google.com/logs/query;query=%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.pod_name%3D%22zeebe-1%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.namespace_name%3D%22f12f6f1d-281b-4972-828f-389ce7e269c3-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0AjsonPayload.context.partitionId%3D%221%22;timeRange=2022-12-28T01:16:45.876Z%2F2022-12-28T02:16:45.876Z;pinnedLogId=2022-12-28T01:44:27.144511386Z%2Fyvz95ent9jweiz9o;summaryFields=resource%252Flabels%252Fpod_name,jsonPayload%252Fcontext%252F%2522actor-name%2522:false:32:beginning;cursorTimestamp=2022-12-28T01:44:27.145622738Z?project=camunda-cloud-240911)
* [Transition to Follower](https://console.cloud.google.com/logs/query;query=%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.pod_name%3D%22zeebe-1%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.namespace_name%3D%22f12f6f1d-281b-4972-828f-389ce7e269c3-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0AjsonPayload.context.partitionId%3D%221%22;timeRange=2022-12-28T01:16:45.876Z%2F2022-12-28T02:16:45.876Z;pinnedLogId=2022-12-28T01:45:05.714091681Z%2Fuy7u74rdzl24l4ry;summaryFields=resource%252Flabels%252Fpod_name,jsonPayload%252Fcontext%252F%2522actor-name%2522:false:32:beginning;cursorTimestamp=2022-12-28T01:45:10.047503773Z?project=camunda-cloud-240911)
* [Directly after - server join completed (looks like restart of a pod happened)](https://console.cloud.google.com/logs/query;query=%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.pod_name%3D%22zeebe-1%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.namespace_name%3D%22f12f6f1d-281b-4972-828f-389ce7e269c3-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0AjsonPayload.context.partitionId%3D%221%22;timeRange=2022-12-28T01:16:45.876Z%2F2022-12-28T02:16:45.876Z;pinnedLogId=2022-12-28T01:45:05.715019792Z%2Fducqw96g7ajhvhsb;summaryFields=resource%252Flabels%252Fpod_name,jsonPayload%252Fcontext%252F%2522actor-name%2522:false:32:beginning;cursorTimestamp=2022-12-28T01:45:05.715019792Z?project=camunda-cloud-240911)

**Comment by Zelldon** [comment]
https://camunda.slack.com/archives/CT702EPFH/p1672210735847999

**Comment by megglos** [comment]
@Zelldon as discussed let's create an issue for zbchaos and close hits

 #11334 would handle this situation by letting one broker crash

**Comment by Zelldon** [comment]
I might be wrong, but we haven't seen this again so I will close this. Might be related to our chaos experiments, but we haven;t adjusted them and it didn't appeared again so might be likely more an infrastructure issue.
