### ISSUE TITLE
ClassCastException: class ModelElementInstanceImpl cannot be cast to class FlowNode

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#11343]
**Describe the bug**
A workflow was deployed multiple times on prod, and caused this exception

**To Reproduce**
https://drive.google.com/drive/folders/1rvRI9_l9fRZnmdU_vy-mfTcptvYGrKge?usp=share_link

**Expected behavior**
No error.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.ClassCastException: class org.camunda.bpm.model.xml.impl.instance.ModelElementInstanceImpl cannot be cast to class io.camunda.zeebe.model.bpmn.instance.FlowNode (org.camunda.bpm.model.xml.impl.instance.ModelElementInstanceImpl and io.camunda.zeebe.model.bpmn.instance.FlowNode are in unnamed module of loader 'app')
	at io.camunda.zeebe.model.bpmn.impl.instance.SequenceFlowImpl.getSource(SequenceFlowImpl.java:101) ~[zeebe-bpmn-model-8.2.0-alpha2.jar:8.2.0-alpha2]
	at io.camunda.zeebe.model.bpmn.validation.zeebe.SequenceFlowValidator.validate(SequenceFlowValidator.java:36) ~[zeebe-bpmn-model-8.2.0-alpha2.jar:8.2.0-alpha2]
	at io.camunda.zeebe.model.bpmn.validation.zeebe.SequenceFlowValidator.validate(SequenceFlowValidator.java:25) ~[zeebe-bpmn-model-8.2.0-alpha2.jar:8.2.0-alpha2]
	at io.camunda.zeebe.model.bpmn.validation.ValidationVisitor.lambda$visit$0(ValidationVisitor.java:51) ~[zeebe-bpmn-model-8.2.0-alpha2.jar:8.2.0-alpha2]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at io.camunda.zeebe.model.bpmn.validation.ValidationVisitor.visit(ValidationVisitor.java:51) ~[zeebe-bpmn-model-8.2.0-alpha2.jar:8.2.0-alpha2]
	at io.camunda.zeebe.model.bpmn.traversal.TypeHierarchyVisitor.visit(TypeHierarchyVisitor.java:39) ~[zeebe-bpmn-model-8.2.0-alpha2.jar:8.2.0-alpha2]
	at io.camunda.zeebe.model.bpmn.traversal.ModelWalker.walk(ModelWalker.java:66) ~[zeebe-bpmn-model-8.2.0-alpha2.jar:8.2.0-alpha2]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnValidator.validate(BpmnValidator.java:40) ~[zeebe-workflow-engine-8.2.0-alpha2.jar:8.2.0-alpha2]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.transformResource(BpmnResourceTransformer.java:65) ~[zeebe-workflow-engine-8.2.0-alpha2.jar:8.2.0-alpha2]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transformResource(DeploymentTransformer.java:120) ~[zeebe-workflow-engine-8.2.0-alpha2.jar:8.2.0-alpha2]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transform(DeploymentTransformer.java:97) ~[zeebe-workflow-engine-8.2.0-alpha2.jar:8.2.0-alpha2]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.processRecord(DeploymentCreateProcessor.java:98) ~[zeebe-workflow-engine-8.2.0-alpha2.jar:8.2.0-alpha2]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:128) ~[zeebe-workflow-engine-8.2.0-alpha2.jar:8.2.0-alpha2]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$3(ProcessingStateMachine.java:264) ~[zeebe-stream-platform-8.2.0-alpha2.jar:8.2.0-alpha2]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-8.2.0-alpha2.jar:8.2.0-alpha2]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:260) ~[zeebe-stream-platform-8.2.0-alpha2.jar:8.2.0-alpha2]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:209) ~[zeebe-stream-platform-8.2.0-alpha2.jar:8.2.0-alpha2]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:185) ~[zeebe-stream-platform-8.2.0-alpha2.jar:8.2.0-alpha2]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.2.0-alpha2.jar:8.2.0-alpha2]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.2.0-alpha2.jar:8.2.0-alpha2]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.2.0-alpha2.jar:8.2.0-alpha2]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.2.0-alpha2.jar:8.2.0-alpha2]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.2.0-alpha2.jar:8.2.0-alpha2]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.2.0-alpha2.jar:8.2.0-alpha2] 
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: 8.2.0-alpha2
- Configuration: Trial with Low Hardware

**Comment by Zelldon** [comment]
Resources https://drive.google.com/drive/folders/1rvRI9_l9fRZnmdU_vy-mfTcptvYGrKge?usp=share_link

**Comment by skayliu** [comment]
> Resources https://drive.google.com/drive/folders/1rvRI9_l9fRZnmdU_vy-mfTcptvYGrKge?usp=share_link

Hi, @Zelldon, Can you upload the bpmn file here?

**Comment by Zelldon** [comment]
Hey @skayliu sorry I can't since this is user data, which we shouldn't share publicly. Pretty sure the @camunda/zeebe-process-automation team will investigate this soon and can share a simplified/anonymized version as soon as they determine what the issue is.

**Comment by remcowesterhoud** [comment]
Here is a small repro. It has to do with an ad-hoc subprocess. I have no clue yet what this is 😄 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:modeler="http://camunda.org/schema/modeler/1.0" id="Definitions_1birbky" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Camunda Modeler" exporterVersion="5.7.0" modeler:executionPlatform="Camunda Cloud" modeler:executionPlatformVersion="8.1.0">
  <bpmn:process id="Process_053jrwn" isExecutable="true">
    <bpmn:startEvent id="StartEvent_1">
      <bpmn:outgoing>Flow_1hqnq4r</bpmn:outgoing>
    </bpmn:startEvent>
    <bpmn:sequenceFlow id="Flow_1hqnq4r" sourceRef="StartEvent_1" targetRef="Activity_109qddu" />
    <bpmn:adHocSubProcess id="Activity_109qddu">
      <bpmn:incoming>Flow_1hqnq4r</bpmn:incoming>
      <bpmn:outgoing>Flow_1kvf2rt</bpmn:outgoing>
      <bpmn:startEvent id="Event_1sswcon">
        <bpmn:outgoing>Flow_1sby4q1</bpmn:outgoing>
      </bpmn:startEvent>
      <bpmn:endEvent id="Event_0pwdkpt">
        <bpmn:incoming>Flow_1sby4q1</bpmn:incoming>
      </bpmn:endEvent>
      <bpmn:sequenceFlow id="Flow_1sby4q1" sourceRef="Event_1sswcon" targetRef="Event_0pwdkpt" />
    </bpmn:adHocSubProcess>
    <bpmn:endEvent id="Event_1m5imql">
      <bpmn:incoming>Flow_1kvf2rt</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:sequenceFlow id="Flow_1kvf2rt" sourceRef="Activity_109qddu" targetRef="Event_1m5imql" />
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_053jrwn">
      <bpmndi:BPMNShape id="_BPMNShape_StartEvent_2" bpmnElement="StartEvent_1">
        <dc:Bounds x="179" y="159" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_1m5imql_di" bpmnElement="Event_1m5imql">
        <dc:Bounds x="492" y="159" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1kxqe7h_di" bpmnElement="Activity_109qddu" isExpanded="true">
        <dc:Bounds x="240" y="77" width="220" height="200" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_1sswcon_di" bpmnElement="Event_1sswcon">
        <dc:Bounds x="280.33333333333337" y="159" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_0pwdkpt_di" bpmnElement="Event_0pwdkpt">
        <dc:Bounds x="372" y="159" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Flow_1sby4q1_di" bpmnElement="Flow_1sby4q1">
        <di:waypoint x="316" y="177" />
        <di:waypoint x="372" y="177" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1hqnq4r_di" bpmnElement="Flow_1hqnq4r">
        <di:waypoint x="215" y="177" />
        <di:waypoint x="240" y="177" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1kvf2rt_di" bpmnElement="Flow_1kvf2rt">
        <di:waypoint x="460" y="177" />
        <di:waypoint x="492" y="177" />
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>

```

**Comment by remcowesterhoud** [comment]
We need to add a validation to reject deployments containing an adhoc subprocess
