### ISSUE TITLE
NPE during transformation of BPMN model

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/zeebe#11392]
**Describe the bug**

The transformation of a BPMN model failed int he `SequenceFlowTransformer` with a `NullPointerException`. The transformer could not find the current process.
The problem has only occurred once so far on a trial cluster. It seems the user was following the tutorials. I have tried to deploy all models from the tutorials and they all worked without issues.

**To Reproduce**

I was unable to come up with a way to reproduce this. When digging into the code it seems to me that this could only occur when the `SequenceFlowTransformer` is executed before the `ContextProcessTransformer`. As far as I can see this can only occur when a sequence flow element exists outside of the process element. However, trying to deploy a process like this results in a rejection, not this exception.

**Expected behavior**

No NPE is thrown. If the process is invalid it should get rejected by the validations.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
 java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.engine.processing.deployment.model.element.ExecutableProcess.getElementById(String, java.lang.Class)" because "process" is null
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.SequenceFlowTransformer.transform(SequenceFlowTransformer.java:30) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.SequenceFlowTransformer.transform(SequenceFlowTransformer.java:20) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.TransformationVisitor.visit(TransformationVisitor.java:42) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.model.bpmn.traversal.TypeHierarchyVisitor.visit(TypeHierarchyVisitor.java:39) ~[zeebe-bpmn-model-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.model.bpmn.traversal.ModelWalker.walk(ModelWalker.java:73) ~[zeebe-bpmn-model-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.BpmnTransformer.transformDefinitions(BpmnTransformer.java:118) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.lambda$transformResource$1(BpmnResourceTransformer.java:72) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.util.Either$Right.flatMap(Either.java:366) ~[zeebe-util-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.transformResource(BpmnResourceTransformer.java:65) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transformResource(DeploymentTransformer.java:120) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transform(DeploymentTransformer.java:97) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.processRecord(DeploymentCreateProcessor.java:96) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$3(ProcessingStateMachine.java:264) ~[zeebe-stream-platform-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:260) ~[zeebe-stream-platform-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:209) ~[zeebe-stream-platform-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:185) ~[zeebe-stream-platform-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.2.0-alpha3.jar:8.2.0-alpha3] 
```

</p>
</details>

**Environment:**
- OS: SAAS
- Zeebe Version: 8.2.0-alpha3

**Comment by remcowesterhoud** [comment]
Same thing has occurred in the `FlowNodeTransformer`

```
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.engine.processing.deployment.model.element.ExecutableProcess.getElementById(String, java.lang.Class)" because "process" is null
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.FlowNodeTransformer.transform(FlowNodeTransformer.java:35) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.FlowNodeTransformer.transform(FlowNodeTransformer.java:21) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.TransformationVisitor.visit(TransformationVisitor.java:42) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.model.bpmn.traversal.TypeHierarchyVisitor.visit(TypeHierarchyVisitor.java:39) ~[zeebe-bpmn-model-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.model.bpmn.traversal.ModelWalker.walk(ModelWalker.java:73) ~[zeebe-bpmn-model-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.BpmnTransformer.transformDefinitions(BpmnTransformer.java:118) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.lambda$transformResource$1(BpmnResourceTransformer.java:72) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.util.Either$Right.flatMap(Either.java:366) ~[zeebe-util-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.transformResource(BpmnResourceTransformer.java:65) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transformResource(DeploymentTransformer.java:120) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transform(DeploymentTransformer.java:97) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.processRecord(DeploymentCreateProcessor.java:96) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$3(ProcessingStateMachine.java:264) ~[zeebe-stream-platform-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:260) ~[zeebe-stream-platform-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:209) ~[zeebe-stream-platform-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:185) ~[zeebe-stream-platform-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.2.0-alpha3.jar:8.2.0-alpha3] 
```

Both these cases were on trial clusters. Since these clusters get deleted after 16 hours I cannot access these anymore to try and pull the BPMN files from them.

**Comment by remcowesterhoud** [comment]
Another case, this time in the `IntermediateThrowEventTransformer` . Again no luck with getting the bpmn files since the log was already compacted.

```
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.engine.processing.deployment.model.element.ExecutableProcess.getElementById(String, java.lang.Class)" because "process" is null
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.IntermediateThrowEventTransformer.transform(IntermediateThrowEventTransformer.java:35) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.IntermediateThrowEventTransformer.transform(IntermediateThrowEventTransformer.java:20) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.TransformationVisitor.visit(TransformationVisitor.java:42) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.model.bpmn.traversal.TypeHierarchyVisitor.visit(TypeHierarchyVisitor.java:39) ~[zeebe-bpmn-model-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.model.bpmn.traversal.ModelWalker.walk(ModelWalker.java:73) ~[zeebe-bpmn-model-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.BpmnTransformer.transformDefinitions(BpmnTransformer.java:124) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.lambda$transformResource$1(BpmnResourceTransformer.java:72) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.util.Either$Right.flatMap(Either.java:366) ~[zeebe-util-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.transformResource(BpmnResourceTransformer.java:65) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transformResource(DeploymentTransformer.java:120) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transform(DeploymentTransformer.java:97) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.processRecord(DeploymentCreateProcessor.java:96) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$3(ProcessingStateMachine.java:264) ~[zeebe-stream-platform-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:260) ~[zeebe-stream-platform-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:209) ~[zeebe-stream-platform-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:185) ~[zeebe-stream-platform-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.2.0-alpha3.jar:8.2.0-alpha3] 
```

**Comment by remcowesterhoud** [comment]
Accidentally encountered when analysing a different issue. Here is a minimal repro process:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:modeler="http://camunda.org/schema/modeler/1.0" id="Definitions_1uynw6x" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Camunda Modeler" exporterVersion="5.5.0" modeler:executionPlatform="Camunda Cloud" modeler:executionPlatformVersion="8.1.0">
  <bpmn:collaboration id="Collaboration_1f6ocs4">
    <bpmn:participant id="Participant_06e56kn" name="Process 1" processRef="Process_09o31ff" />
    <bpmn:participant id="Participant_0sqceyc" name="Process 2" processRef="process2" />
  </bpmn:collaboration>
  <bpmn:process id="Process_09o31ff" isExecutable="true">
    <bpmn:startEvent id="StartEvent_1">
      <bpmn:outgoing>Flow_1c52xue</bpmn:outgoing>
    </bpmn:startEvent>
    <bpmn:endEvent id="Event_1c478sz">
      <bpmn:incoming>Flow_1c52xue</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:sequenceFlow id="Flow_1c52xue" sourceRef="StartEvent_1" targetRef="Event_1c478sz" />
  </bpmn:process>
  <bpmn:process id="process2" name="process2" isExecutable="false">
    <bpmn:startEvent id="Event_0r4103l">
      <bpmn:outgoing>Flow_1h6k1xb</bpmn:outgoing>
    </bpmn:startEvent>
    <bpmn:sequenceFlow id="Flow_1h6k1xb" sourceRef="Event_0r4103l" targetRef="collapsedSP" />
    <bpmn:endEvent id="Event_06wbtrl">
      <bpmn:incoming>Flow_18crda1</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:sequenceFlow id="Flow_18crda1" sourceRef="collapsedSP" targetRef="Event_06wbtrl" />
    <bpmn:subProcess id="collapsedSP" name="Collapsed SP">
      <bpmn:incoming>Flow_1h6k1xb</bpmn:incoming>
      <bpmn:outgoing>Flow_18crda1</bpmn:outgoing>
    </bpmn:subProcess>
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Collaboration_1f6ocs4">
      <bpmndi:BPMNShape id="Participant_06e56kn_di" bpmnElement="Participant_06e56kn" isHorizontal="true">
        <dc:Bounds x="129" y="60" width="600" height="250" />
        <bpmndi:BPMNLabel />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="_BPMNShape_StartEvent_2" bpmnElement="StartEvent_1">
        <dc:Bounds x="179" y="159" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_1c478sz_di" bpmnElement="Event_1c478sz">
        <dc:Bounds x="272" y="159" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Flow_1c52xue_di" bpmnElement="Flow_1c52xue">
        <di:waypoint x="215" y="177" />
        <di:waypoint x="272" y="177" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="Participant_0sqceyc_di" bpmnElement="Participant_0sqceyc" isHorizontal="true">
        <dc:Bounds x="129" y="360" width="600" height="250" />
        <bpmndi:BPMNLabel />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_0r4103l_di" bpmnElement="Event_0r4103l">
        <dc:Bounds x="192" y="462" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_06wbtrl_di" bpmnElement="Event_06wbtrl">
        <dc:Bounds x="432" y="462" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1b9zm7p_di" bpmnElement="collapsedSP">
        <dc:Bounds x="280" y="440" width="100" height="80" />
        <bpmndi:BPMNLabel />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Flow_1h6k1xb_di" bpmnElement="Flow_1h6k1xb">
        <di:waypoint x="228" y="480" />
        <di:waypoint x="280" y="480" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_18crda1_di" bpmnElement="Flow_18crda1">
        <di:waypoint x="380" y="480" />
        <di:waypoint x="432" y="480" />
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1npwjd3">
    <bpmndi:BPMNPlane id="BPMNPlane_00ui56r" bpmnElement="collapsedSP" />
  </bpmndi:BPMNDiagram>
</bpmn:definitions>

```

**Comment by korthout** [comment]
Impact is that command is rejected, so impact is not large. It also doesn't occur often (sometimes though). We should improve this at some point but its not urgent.

**Comment by skayliu** [comment]
> It seems to have something to do with having multiple pools, one of which is non-executable.

I did a little search, the NPE is throw from the `Executable Process`, `context.getCurrentProcess()` is null.

**Comment by saig0** [comment]
And, it happened again. On a trial cluster. But I don't see the actual process that caused the issue.

```
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.engine.processing.deployment.model.element.ExecutableProcess.getElementById(String, java.lang.Class)" because "process" is null
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.ExclusiveGatewayTransformer.transform(ExclusiveGatewayTransformer.java:30) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.ExclusiveGatewayTransformer.transform(ExclusiveGatewayTransformer.java:18) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.TransformationVisitor.visit(TransformationVisitor.java:42) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.model.bpmn.traversal.TypeHierarchyVisitor.visit(TypeHierarchyVisitor.java:39) ~[zeebe-bpmn-model-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.model.bpmn.traversal.ModelWalker.walk(ModelWalker.java:73) ~[zeebe-bpmn-model-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.BpmnTransformer.transformDefinitions(BpmnTransformer.java:121) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.lambda$transformResource$1(BpmnResourceTransformer.java:72) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.util.Either$Right.flatMap(Either.java:366) ~[zeebe-util-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.transformResource(BpmnResourceTransformer.java:65) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transformResource(DeploymentTransformer.java:120) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transform(DeploymentTransformer.java:97) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.processRecord(DeploymentCreateProcessor.java:96) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$3(ProcessingStateMachine.java:264) ~[zeebe-stream-platform-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:260) ~[zeebe-stream-platform-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:209) ~[zeebe-stream-platform-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:185) ~[zeebe-stream-platform-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.2.0-alpha3.jar:8.2.0-alpha3]
```

We should think about giving it a higher priority since it could impact the onboarding experience (i.e. happened often for trial users). And it is probably easy to fix.

**Comment by remcowesterhoud** [comment]
Another occurrence on the `IntermediateCatchEventTransformer`

```
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.engine.processing.deployment.model.element.ExecutableProcess.getElementById(String, java.lang.Class)" because "process" is null
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.IntermediateCatchEventTransformer.transform(IntermediateCatchEventTransformer.java:30) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.IntermediateCatchEventTransformer.transform(IntermediateCatchEventTransformer.java:18) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.TransformationVisitor.visit(TransformationVisitor.java:42) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.model.bpmn.traversal.TypeHierarchyVisitor.visit(TypeHierarchyVisitor.java:39) ~[zeebe-bpmn-model-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.model.bpmn.traversal.ModelWalker.walk(ModelWalker.java:73) ~[zeebe-bpmn-model-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.BpmnTransformer.transformDefinitions(BpmnTransformer.java:121) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.lambda$transformResource$1(BpmnResourceTransformer.java:72) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.util.Either$Right.flatMap(Either.java:366) ~[zeebe-util-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.transformResource(BpmnResourceTransformer.java:65) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transformResource(DeploymentTransformer.java:120) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transform(DeploymentTransformer.java:97) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.processRecord(DeploymentCreateProcessor.java:96) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[zeebe-workflow-engine-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$3(ProcessingStateMachine.java:264) ~[zeebe-stream-platform-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:260) ~[zeebe-stream-platform-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:209) ~[zeebe-stream-platform-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:185) ~[zeebe-stream-platform-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.2.0-alpha3.jar:8.2.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.2.0-alpha3.jar:8.2.0-alpha3] 
```

**Comment by remcowesterhoud** [comment]
I will move this to the ready column so we can root-cause this and see what the impact is of this issue. If it's not an easy fix we can move it back and discuss the priority during the planning.

**Comment by koevskinikola** [comment]
Issue is with the `return` statement [here](https://github.com/camunda/zeebe/blob/11b2aa2a4edef69687be1a847dcadb4e9ffc67a9/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/traversal/ModelWalker.java#L70). It prevents the `ModelWalker` from continuing the search of executable processes, once a non-executable one is encountered.

Changing `return` to `continue` should fix the issue.

**Comment by saig0** [comment]
> Changing return to continue should fix the issue.

:see_no_evil: Good catch. :rofl:
