### ISSUE TITLE
NPE when handling follow-up events of process instance modification

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#11413]
**Describe the bug**

```
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.engine.state.instance.ElementInstance.getValue()" because "processInstance" is null
```

**To Reproduce**

Unclear

**Expected behavior**

No NPE

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
 java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.engine.state.instance.ElementInstance.getValue()" because "processInstance" is null
	at io.camunda.zeebe.engine.state.appliers.ProcessInstanceModifiedEventApplier.incrementNumberOfTakenSequenceFlows(ProcessInstanceModifiedEventApplier.java:61) ~[zeebe-workflow-engine-8.1.5.jar:8.1.5]
	at io.camunda.zeebe.engine.state.appliers.ProcessInstanceModifiedEventApplier.applyState(ProcessInstanceModifiedEventApplier.java:39) ~[zeebe-workflow-engine-8.1.5.jar:8.1.5]
	at io.camunda.zeebe.engine.state.appliers.ProcessInstanceModifiedEventApplier.applyState(ProcessInstanceModifiedEventApplier.java:21) ~[zeebe-workflow-engine-8.1.5.jar:8.1.5]
	at io.camunda.zeebe.engine.state.appliers.EventAppliers.applyState(EventAppliers.java:259) ~[zeebe-workflow-engine-8.1.5.jar:8.1.5]
	at io.camunda.zeebe.engine.processing.streamprocessor.writers.ResultBuilderBackedEventApplyingStateWriter.appendFollowUpEvent(ResultBuilderBackedEventApplyingStateWriter.java:41) ~[zeebe-workflow-engine-8.1.5.jar:8.1.5]
	at io.camunda.zeebe.engine.processing.processinstance.ProcessInstanceModificationProcessor.processRecord(ProcessInstanceModificationProcessor.java:223) ~[zeebe-workflow-engine-8.1.5.jar:8.1.5]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[zeebe-workflow-engine-8.1.5.jar:8.1.5]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.lambda$processCommand$3(ProcessingStateMachine.java:261) ~[zeebe-workflow-engine-8.1.5.jar:8.1.5]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-8.1.5.jar:8.1.5]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:257) ~[zeebe-workflow-engine-8.1.5.jar:8.1.5]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:206) ~[zeebe-workflow-engine-8.1.5.jar:8.1.5]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:182) ~[zeebe-workflow-engine-8.1.5.jar:8.1.5]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.1.5.jar:8.1.5]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.1.5.jar:8.1.5]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.1.5.jar:8.1.5]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.1.5.jar:8.1.5]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.1.5.jar:8.1.5]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.1.5.jar:8.1.5] 
```

</p>
</details>

**Environment:**
- SaaS
- Zeebe Version: 8.1.5, 8.2.0-alpha3

[Error group](https://console.cloud.google.com/errors/detail/COzEm_6Kp6S_OQ;service=zeebe;time=P7D?project=camunda-cloud-240911)
Somewhat similar issue: #10606

**Comment by korthout** [comment]
We need to understand the impact of this before we can prioritize it. Let's investigate whether this leads to a blacklisted instance.

**Comment by remcowesterhoud** [comment]
I have not root-caused it yet, but I can already confirm that a NPE during a modification will result in a blacklisted instance as we've seen in previous issues.

**Comment by remcowesterhoud** [comment]
This NPE occurs when a user passes the process instance key as terminate instruction, whilst also trying to activate any element within the process. It's a strange combination and I would consider this a user mistake that we don't handle as we should.

I see 3 possible solutions here:

1. A terminate instruction is not allowed to contain the process instance key. Reject the command if this is the case.
2. We should terminate the process instance without throwing the NPE. We don't care about the activate instruction getting rejected.
3. We should not terminate the process instance and activate the element in the activate instruction.

My preference is option 1 as this way we don't make any assumption about the user's intentions. I will discuss it internally with the team before creating the fix.
