### ISSUE TITLE
When there is a big chunk of expired messages, then Zeebe fails to write the batch of corresponding commands

### ISSUE THREAD

**Issue by romansmirnov** [camunda/zeebe#11480]
**Describe the bug**

The `MessageTimeToLiveChecker` fails to submit a batch of commands to expire a big chunk of expired message:
```
2023-01-25 20:21:34.338 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] WARN
      io.camunda.zeebe.broker.logstreams - Writing of scheduled TaskResult failed!
java.lang.IllegalArgumentException: Expected to claim segment of size 9544, but can't claim more than 8192 bytes.
        at io.camunda.zeebe.dispatcher.Dispatcher.offer(Dispatcher.java:207) ~[zeebe-dispatcher-8.1.2.jar:8.1.2]
        at io.camunda.zeebe.dispatcher.Dispatcher.claimFragmentBatch(Dispatcher.java:164) ~[zeebe-dispatcher-8.1.2.jar:8.1.2]
        at io.camunda.zeebe.logstreams.impl.log.LogStreamBatchWriterImpl.claimBatchForEvents(LogStreamBatchWriterImpl.java:235) ~[zeebe-logstreams-8.1.2.jar:8.1.2]
        at io.camunda.zeebe.logstreams.impl.log.LogStreamBatchWriterImpl.tryWrite(LogStreamBatchWriterImpl.java:212) ~[zeebe-logstreams-8.1.2.jar:8.1.2]
        at io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceImpl.lambda$toRunnable$5(ProcessingScheduleServiceImpl.java:165) ~[zeebe-workflow-engine-8.1.2.jar:8.1.2]
        at io.camunda.zeebe.scheduler.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:28) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
        at io.camunda.zeebe.scheduler.retry.AbortableRetryStrategy.run(AbortableRetryStrategy.java:45) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
        at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
        at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
        at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
        at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
        at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
        at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
```
**To Reproduce**
1. Configure `maxMessageSize` to 8KB
2. Publish > 10k messages to Zeebe with a TTL 5 minutes
3. Stop Zeebe
4. Wait > 5 minutes
5. Start Zeebe again
6. Wait until the `MessageTimeToLiveChecker` starts working

**Expected behavior**
* Writing the batch of commands succeeds

**Hints**
* `LogStreamBatchWriterImpl#canWriteAdditionalEvent(int, int)` does not respect the header length for each (log) entry
https://github.com/camunda/zeebe/blob/0844bf55cb63d18a0ca92399034cb04f5c708049/logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/LogStreamBatchWriterImpl.java#L105-L107
* It should call `#computeBatchLength()` to calculate the correct `batchSize`:
```
public boolean canWriteAdditionalEvent(final int eventCount, final int batchSize) {
  final var batchLength = computeBatchLength(eventCount, batchSize);
  return logWriteBuffer.canClaimFragmentBatch(eventCount, batchLength);
}
```
* The 8KB `maxMessageSize` setting was just made to get it quickly reproducible.

**Environment:**
- Zeebe Version: 8.1.2

**Affected versions:**
`stable/8.0` seems not affected, there is just one implementation of `canWriteAdditionalEvent ` which makes use of computeBatchLength as suggested by @romansmirnov, [see](https://github.com/camunda/zeebe/blob/stable/8.0/logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/LogStreamBatchWriterImpl.java#L100).

`8.2.0/main` is not affected as well - manually verified this with the steps to reproduce.

---

related to [SUPPORT-15740](https://jira.camunda.com/browse/SUPPORT-15740)

**Comment by lzgabel** [comment]
Environment:
* Self-Managed Zeebe Version: 8.1.4

```
2023-01-19 16:06:43.379 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] WARN
      io.camunda.zeebe.broker.logstreams - Writing of scheduled TaskResult failed!
java.lang.IllegalArgumentException: Expected to claim segment of size 4643888, but can't claim more than 4194304 bytes.
.....

2023-01-19 16:06:43.379 [Broker-0-InterPartitionCommandReceiverActor-4] [Broker-0-zb-actors-0] WARN
io.camunda.zeebe.broker.transport - Failed to write command MESSAGE_SUBSCRIPTION DELETE from 0 to logstream
2023-01-19 16:06:43.379 [Broker-0-InterPartitionCommandReceiverActor-4] [Broker-0-zb-actors-0] WARN
io.camunda.zeebe.broker.transport - Failed to write command MESSAGE_SUBSCRIPTION DELETE from 0 to logstream
```

Hi @romansmirnov, @korthout. We've run into the same issue several times recently in our production environment. As a result, partition data leads to uneven distribution. (as shown in the figure below, the key is partitionId).

![image](https://user-images.githubusercontent.com/24605947/214752628-c1b6e537-f631-45e4-84b2-e7b2e8a9ee4a.png)


When an instance is routed to a partition with more data (as shown in the above figure partition-5), the processing performance of the process instance drops sharply, and eventually the historical data has to be cleaned up to rebuild the partition.

---
The following figure shows the status of each partition queried by the `zdb` tool:

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/24605947/214753351-7475c09c-9677-4990-8b92-be3591e902cd.png">

**Comment by megglos** [comment]
@oleschoenburg @Zelldon it seems to me that on `main` the corresponding [`canWriteEvents`](https://github.com/camunda/zeebe/blob/main/logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/Sequencer.java#L57) method in the new `Sequencer` class is not affected and behaving as expected, right?
So we only need to fix this for 8.1 then.

**Comment by Zelldon** [comment]
Hm I think the alignment is wrong @megglos Actually it should call `org.agrona.BitUtil.align` like we do here https://github.com/camunda/zeebe/blob/main/logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/serializer/DataFrameDescriptor.java#L32

**Comment by megglos** [comment]
- for `main` we should evaluate whether the alignment is actually still needed 
@oleschoenburg let's sync
