### ISSUE TITLE
snapshot not created

### ISSUE THREAD

**Issue by wuchuanron** [camunda/zeebe#11503]
The service stopped a few days ago for some unknown reason. Today, the service restarted and found that the snapshot could not continue to be created. It was frozen at 4030387-40-4659997-4659998. It has been used normally before. It can be determined that the program is OK. The zeebe version number is 1.2.11.

**Comment by lzgabel** [comment]
👋  Hi @wuchuanron. Thanks for raising this. Can you please share the log files from the Zeebe Broker?

**Comment by wuchuanron** [comment]
Excuse me, let me confirm. Is it raft-partition-partition-1-1.log? @lzgabel

**Comment by lzgabel** [comment]
@wuchuanron. No, the log files are located in the `logs` folder.

<img width="525" alt="image" src="https://user-images.githubusercontent.com/24605947/215656497-2ce2f7d4-c98c-47a2-be22-1af0bdfdd2e6.png">

**Comment by wuchuanron** [comment]
I found some error logs.

-------------------------------------------------

11:38:31.041 [Broker-0-zb-actors-0] ERROR i.c.zeebe.logstreams - [onFailure,325] - Actor Broker-0-StreamProcessor-1 failed in phase STARTED.
java.lang.IllegalStateException: Expected to find event with the snapshot position 4659997 in log stream, but nothing was found. Failed to recover 'Broker-0-StreamProcessor-1'.
	at io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor.recoverFromSnapshot(StreamProcessor.java:287)
	at io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor.onActorStarted(StreamProcessor.java:124)
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:79)
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:44)
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122)
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97)
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80)
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189)
11:38:31.044 [Broker-0-zb-actors-0] ERROR i.c.zeebe.logstreams - [onFailure,325] - Actor Broker-0-StreamProcessor-1 failed in phase FAILED.
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.engine.processing.streamprocessor.ReplayStateMachine.close()" because "this.replayStateMachine" is null
	at io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor.tearDown(StreamProcessor.java:221)
	at io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor.onActorFailed(StreamProcessor.java:211)
	at io.camunda.zeebe.util.sched.ActorTask.fail(ActorTask.java:537)
	at io.camunda.zeebe.util.sched.ActorControl.fail(ActorControl.java:419)
	at io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor.onFailure(StreamProcessor.java:326)
	at io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor.onActorStarted(StreamProcessor.java:169)
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:79)
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:44)
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122)
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97)
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80)
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189)
11:38:31.044 [Broker-0-zb-actors-0] ERROR i.c.zeebe.util.actor - [executeCurrentTask,100] - Unexpected error occurred in task Broker-0-StreamProcessor-1 ACTIVE phase: FAILED
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.engine.processing.streamprocessor.ReplayStateMachine.close()" because "this.replayStateMachine" is null
	at io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor.tearDown(StreamProcessor.java:221)
	at io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor.onActorFailed(StreamProcessor.java:211)
	at io.camunda.zeebe.util.sched.ActorTask.fail(ActorTask.java:537)
	at io.camunda.zeebe.util.sched.ActorControl.fail(ActorControl.java:419)
	at io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor.onFailure(StreamProcessor.java:326)
	at io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor.handleFailure(StreamProcessor.java:202)
	at io.camunda.zeebe.util.sched.ActorTask.onFailure(ActorTask.java:304)
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:53)
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122)
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97)
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80)
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189)

**Comment by wuchuanron** [comment]
The previous log has been cleared. At present, only the startup log is available.
