### ISSUE TITLE
Improper handling of ExceededBatchRecordSizeException

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#11681]
**Describe the bug**

An `ExceededBatchRecordSizeException` is thrown while processing a command. This is caught in the transaction context. The transaction context doesn't handle `ExceededBatchRecordSizeException` explicitly, so it wraps it in a `RuntimeException`, resulting in a `RuntimeException(ExceededBatchRecordSizeException)`. When the `ProcessingStateMachine` receives it, it treats it as a generic exception instead of a `ExceededBatchRecordSizeException`.

See: https://console.cloud.google.com/errors/detail/CLP9hd7Xvp7OogE;service=zeebe;time=P7D?project=camunda-cloud-240911

**To Reproduce**

For example, when correlating message subscriptions:

1. The processor is already in a transaction. This one handles the error properly because it starts a transaction, then obtains the current one via the context, receiving a `ZeebeTransaction`. `ZeebeTransaction` only handles `RocksDBException`, and rethrows everything as is. So far so good.
2. While processing and correlating messages, we call `DbMessageSubscriptionState#visitSubscriptions`, which in turn ends up calling `TransactionalColumnFamily#ensureInOpenTransaction`. This will execute the actual visitor lambda from within `DefaultTransactionContext#runInTransaction`. Since we're already in a transaction, the visitor code is run as is, within the try catch there.
3. `DefaultTransactionContext` catches all `Exception`, which includes `ExceededBatchRecordSizeException`, and wraps them in `RuntimeException`.
4. This bubbles up to the `ProcessingStateMachine`, which then handles it as an unexpected error, not as its usual `ExceededBatchRecordSizeException`.

**Expected behavior**

We handled `ExceededBatchRecordSizeException` in the same way every time, i.e. trying to at least process/commit as much as we can.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
 java.lang.RuntimeException: Unexpected error occurred during zeebe db transaction operation.
	at io.camunda.zeebe.db.impl.rocksdb.transaction.DefaultTransactionContext.runInTransaction(DefaultTransactionContext.java:47) ~[zeebe-db-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.ensureInOpenTransaction(TransactionalColumnFamily.java:300) ~[zeebe-db-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.whileEqualPrefix(TransactionalColumnFamily.java:191) ~[zeebe-db-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.engine.state.message.DbMessageSubscriptionState.visitSubscriptions(DbMessageSubscriptionState.java:102) ~[zeebe-workflow-engine-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.engine.processing.message.MessagePublishProcessor.correlateToSubscriptions(MessagePublishProcessor.java:124) ~[zeebe-workflow-engine-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.engine.processing.message.MessagePublishProcessor.handleNewMessage(MessagePublishProcessor.java:112) ~[zeebe-workflow-engine-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.engine.processing.message.MessagePublishProcessor.processRecord(MessagePublishProcessor.java:97) ~[zeebe-workflow-engine-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[zeebe-workflow-engine-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.lambda$processCommand$3(ProcessingStateMachine.java:261) ~[zeebe-workflow-engine-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:257) ~[zeebe-workflow-engine-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:206) ~[zeebe-workflow-engine-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:182) ~[zeebe-workflow-engine-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.1.4.jar:8.1.4]
Caused by: io.camunda.zeebe.engine.api.records.RecordBatch$ExceededBatchRecordSizeException: Can't append entry: '*** with size: 2903348 this would exceed the maximum batch size. [ currentBatchEntryCount: 1, currentBatchSize: 2903291]
	at io.camunda.zeebe.engine.api.records.RecordBatch.appendRecord(RecordBatch.java:62) ~[zeebe-workflow-engine-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.streamprocessor.BufferedProcessingResultBuilder.appendRecordReturnEither(BufferedProcessingResultBuilder.java:64) ~[zeebe-workflow-engine-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.engine.api.ProcessingResultBuilder.appendRecord(ProcessingResultBuilder.java:37) ~[zeebe-workflow-engine-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.engine.processing.streamprocessor.writers.ResultBuilderBackedEventApplyingStateWriter.appendFollowUpEvent(ResultBuilderBackedEventApplyingStateWriter.java:40) ~[zeebe-workflow-engine-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.engine.processing.message.MessagePublishProcessor.lambda$correlateToSubscriptions$0(MessagePublishProcessor.java:140) ~[zeebe-workflow-engine-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.engine.state.message.DbMessageSubscriptionState.visitMessageSubscription(DbMessageSubscriptionState.java:212) ~[zeebe-workflow-engine-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.engine.state.message.DbMessageSubscriptionState.lambda$visitSubscriptions$1(DbMessageSubscriptionState.java:105) ~[zeebe-workflow-engine-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.visit(TransactionalColumnFamily.java:368) ~[zeebe-db-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$forEachInPrefix$18(TransactionalColumnFamily.java:347) ~[zeebe-db-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ColumnFamilyContext.withPrefixKey(ColumnFamilyContext.java:111) ~[zeebe-db-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.forEachInPrefix(TransactionalColumnFamily.java:327) ~[zeebe-db-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$whileEqualPrefix$11(TransactionalColumnFamily.java:191) ~[zeebe-db-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$ensureInOpenTransaction$17(TransactionalColumnFamily.java:301) ~[zeebe-db-8.1.4.jar:8.1.4]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.DefaultTransactionContext.runInTransaction(DefaultTransactionContext.java:33) ~[zeebe-db-8.1.4.jar:8.1.4]
	... 18 more 
```

</p>
</details>

**Environment:**
- Zeebe Version: 8.2.0-alpha4
- Configuration: SaaS

**Comment by npepinpe** [comment]
Note that in the error above, there was only 1 command ever processed, so in this case it didn't matter. But I think the case could happen with multiple commands anyway.

**Comment by oleschoenburg** [comment]
@npepinpe Great breakdown of the root cause here :+1: 
The issue description says `8.2.0-alpha4`, but the linked error group mentions `8.1.4`.
The issue is not new but it does have an impact on batch processing since the `ProcessingStateMachine` must see the `ExceededBatchRecordSizeException` to properly rollback and retry processing.

**Comment by npepinpe** [comment]
Ah, my bad, I opened another issue, I must have confused the both of them :s
