### ISSUE TITLE
`StreamProcessorTest#shouldRunAsyncSchedulingEvenIfProcessingIsBlocked` is unstable

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#11847]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? Not sure, possible quite often.
- Does it block your work? Sort of.
- Do we suspect that it is a real failure? Probably not.

**Failures**

Test does not finish and hangs indefinitely: https://github.com/camunda/zeebe/actions/runs/4290924604/jobs/7475475454

**Hypotheses**

Not sure. At the very least the test should not block forever and it should time out instead.

**Details**

<details><summary>Thread dump</summary>
<pre>
"-zb-actors-10" #242 daemon prio=5 os_prio=0 cpu=4.75ms elapsed=1467.52s tid=0x00007f0d8c183f50 nid=0x4bcd waiting on condition  [0x00007f0d839f7000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.6/Native Method)
	- parking to wait for  <0x0000000511882c88> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.6/LockSupport.java:211)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@17.0.6/AbstractQueuedSynchronizer.java:715)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(java.base@17.0.6/AbstractQueuedSynchronizer.java:1047)
	at java.util.concurrent.CountDownLatch.await(java.base@17.0.6/CountDownLatch.java:230)
	at io.camunda.zeebe.stream.impl.StreamProcessorTest.lambda$shouldRunAsyncSchedulingEvenIfProcessingIsBlocked$13(StreamProcessorTest.java:500)
	at io.camunda.zeebe.stream.impl.StreamProcessorTest$$Lambda$783/0x00000008010cef50.answer(Unknown Source)
	at org.mockito.internal.stubbing.StubbedInvocationMatcher.answer(StubbedInvocationMatcher.java:42)
	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:103)
	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:34)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:56)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptAbstract(MockMethodInterceptor.java:161)
	at io.camunda.zeebe.stream.api.RecordProcessor$MockitoMock$srUaQ1Mo.process(Unknown Source)
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:340)
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$2(ProcessingStateMachine.java:263)
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine$$Lambda$697/0x00000008010ab998.run(Unknown Source)
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84)
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:263)
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:222)
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:198)
	at io.camunda.zeebe.stream.impl.StreamProcessor$$Lambda$695/0x00000008010a39c8.run(Unknown Source)
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92)
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45)
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119)
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106)
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87)
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198)

"ForkJoinPool-2-worker-1" #22 daemon prio=5 os_prio=0 cpu=2114.69ms elapsed=1471.56s tid=0x00007f0e6129bc70 nid=0x4012 waiting on condition  [0x00007f0e10df8000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.6/Native Method)
	- parking to wait for  <0x0000000511890988> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@17.0.6/LockSupport.java:252)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@17.0.6/AbstractQueuedSynchronizer.java:1672)
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.get(CompletableActorFuture.java:134)
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.get(CompletableActorFuture.java:109)
	at io.camunda.zeebe.scheduler.FutureUtil.join(FutureUtil.java:21)
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.join(CompletableActorFuture.java:198)
	at io.camunda.zeebe.stream.impl.StreamPlatform$ProcessorContext.close(StreamPlatform.java:364)
	at org.agrona.CloseHelper.quietCloseAll(CloseHelper.java:64)
	at io.camunda.zeebe.stream.impl.StreamPlatformExtension$StreamProcessorTestContext.close(StreamPlatformExtension.java:122)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore$$Lambda$731/0x0000000800ed4448.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore.lambda$closeAllStoredCloseableValues$3(ExtensionValuesStore.java:68)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore$$Lambda$454/0x000000080100e108.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(java.base@17.0.6/ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$3$1.accept(java.base@17.0.6/ReferencePipeline.java:197)
	at java.util.stream.SortedOps$RefSortingSink$$Lambda$455/0x0000000800e4d400.accept(java.base@17.0.6/Unknown Source)
	at java.util.ArrayList.forEach(java.base@17.0.6/ArrayList.java:1511)
	at java.util.stream.SortedOps$RefSortingSink.end(java.base@17.0.6/SortedOps.java:395)
	at java.util.stream.Sink$ChainedReference.end(java.base@17.0.6/Sink.java:258)
	at java.util.stream.AbstractPipeline.copyInto(java.base@17.0.6/AbstractPipeline.java:510)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(java.base@17.0.6/AbstractPipeline.java:499)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(java.base@17.0.6/ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(java.base@17.0.6/ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(java.base@17.0.6/AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(java.base@17.0.6/ReferencePipeline.java:596)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore.closeAllStoredCloseableValues(ExtensionValuesStore.java:68)
	at org.junit.jupiter.engine.descriptor.AbstractExtensionContext.close(AbstractExtensionContext.java:80)
	at org.junit.jupiter.engine.execution.JupiterEngineExecutionContext.close(JupiterEngineExecutionContext.java:53)
	at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.cleanUp(JupiterTestDescriptor.java:222)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$cleanUp$1(TestMethodTestDescriptor.java:155)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor$$Lambda$730/0x0000000800ed4220.execute(Unknown Source)
</pre>
</details>

**Comment by Zelldon** [comment]
There were two issues with the test:

 1. We release the latch for the processor at the end, but if an assertion failed we don't. This causes on clean up to wait for ever on the stream processor closing and us not seeing the failure.
 2. The scheduled task was not executed because of https://github.com/camunda/zeebe/issues/11849
