### ISSUE TITLE
Gateway Reports Stream Write Error During Load Tests Leading To Low Throughput.

### ISSUE THREAD

**Issue by shahamit** [camunda/zeebe#11864]
We are executing benchmarking tests using camunda-8-benchmark tool on zeebe 8.1.6. We have seen warnings logged on the gateway stating `io.netty.handler.codec.http2.Http2Exception$StreamException: Stream closed before write could take place`. There is an info message too logged on the client which is the benchmarking tool in this case. The info statement is `io.grpc.internal.AbstractClientStream : Received data on closed stream`

These logs appear for certain cluster configurations as detailed below and also when the system is under load. Once these logs are reported the throughput of zeebe engine starts dropping. 

This issue was discussed on [this forum thread](https://forum.camunda.io/t/gateway-fails-with-stream-write-error/42282/2).

**To Reproduce**

We executed multiple tests with different cluster configurations and on different aws hardware. Note the "Stream Error On Gateway" column.

1. Tests executed with both brokers and gateway on c6a.xlarge instances (compute optimised - 4vcpu, 8GB RAM).

<google-sheets-html-origin>

CPU Limit | Gateways | Brokers | Partitions | Replication Factor | Zero BackPressure Throughput | Steady BackPressure Throughput | Stream Error On Gateway | Comments
-- | -- | -- | -- | -- | -- | -- | -- | --
3.5 | 2 | 5 | 5 | 1 | 25 | 53 | No |  
3.5 | 2 | 5 | 5 | 2 | 112 | 182 | Yes | Run 1
3.5 | 2 | 5 | 5 | 2 | 154 | 182 | Yes | Run 2
3.5 | 2 | 5 | 5 | 2 | 139 | 173 | Yes | Run 3
  |   |   |   |   |   |   |   |  
3.5 | 2 | 4 | 4 | 2 | 91 | 140 | No |  
3.5 | 2 | 3 | 3 | 2 | 51 | 100 | No |  
3.5 | 2 | 2 | 2 | 2 | 25 | 50 | No |  
  |   |   |   |   |   |   |   |  
3.5 | 2 | 6 | 6 | 2 | 200 |   | Yes (after 40 mins) | steady test
  |   |   |   |   |   |   |   |  
3.5 | 2 | 7 | 7 | 2 | 190 |   | Yes | nolimit test
3.5 | 2 | 7 | 7 | 2 | 200 | 200 | No | steady test. slight backpressure
  |   |   |   |   |   |   |   |  
3.5 | 2 | 8 | 8 | 2 | 200 |   | No | steady test. Run 1
3.5 | 2 | 8 | 8 | 2 | 200 |   | No | steady test. Run 2 (3 hrs)
3.5 | 2 | 8 | 8 | 2 | 222 | 190 | Yes | nolimit
  |   |   |   |   |   |   |   |  
3.5 | 2 | 9 | 9 | 2 |   |   | Yes | steady test - goal 250
3.5 | 2 | 9 | 9 | 2 | 230 | 230 | No | steady test - goal 230

2. Tests executed with brokers on m4.2xlarge (general purpose - 8 vcpu, 16GB RAM) ec2 instances and gateway on c6a.xlarge instances. 

 <google-sheets-html-origin>

Gateways | Brokers | Partitions | Replication Factor | Zero BackPressure | Steady BackPressure | Stream Error On Gateway | Comments
-- | -- | -- | -- | -- | -- | -- | --
2 | 3 | 3 | 3 | 35 | 73 | No |  
2 | 3 | 3 | 1 | 38 | 77 | No |  
2 | 3 | 9 | 1 | 66 | 67 | Yes |  
2 | 3 | 7 | 1 | 41 | 50 | No |  
2 | 3 | 4 | 1 | 30 | 33 | No |  
  |   |   |   |   |   |   |  
1 | 4 | 4 | 3 | 66 | 96 | No |  
1 | 4 | 10 | 1 | 54 | 58 | Yes |  
1 | 4 | 9 | 1 | 53 | 63 | Yes |  
1 | 4 | 8 | 1 | 46 | 57 | Yes |  
  |   |   |   |   |   |   |  
2 | 5 | 5 | 2 | 90 | 116 | No |  
2 | 5 | 7 | 2 | 135 | 125 | Yes |  
  |   |   |   |   |   |   |  
2 | 6 | 6 | 2 | 113 | 130 | No |  
  |   |   |   |   |   |   |  
2 | 8 | 8 | 2 | 148 | 130 | Yes |  
  |   |   |   |   |   |   |  
2 | 12 | 12 | 2 | 195 | 180 | Yes | cpu thread pool = 6
2 | 12 | 12 | 2 | 180 | 80 | Yes | cpu thread pool = 4
  |   |   |   |   |   |   |  
2 | 14 | 14 | 2 | 200 |   | No | Benchmarking tool steady at 200 PI/s

The mention about "steady test" in the above comments column indicate a tweak in the benchmarking tool done to not start any new process instances after a configured value is reached.

**Expected behavior**

No drop in the throughput and no warnings logged in the gateway

**Log/Stacktrace**

`Exception: io.netty.handler.codec.http2.Http2Exception$StreamException: Stream closed before write could take place`

Stacktrace

<details>
<summary>Stacktrace</summary>
```
io.netty.handler.codec.http2.Http2Exception$StreamException: Stream closed before write could take place
	at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:172) ~[netty-codec-http2-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$FlowState.cancel(DefaultHttp2RemoteFlowController.java:481) [netty-codec-http2-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$1.onStreamClosed(DefaultHttp2RemoteFlowController.java:105) [netty-codec-http2-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.handler.codec.http2.DefaultHttp2Connection.notifyClosed(DefaultHttp2Connection.java:357) [netty-codec-http2-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.removeFromActiveStreams(DefaultHttp2Connection.java:1007) [netty-codec-http2-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.deactivate(DefaultHttp2Connection.java:963) [netty-codec-http2-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultStream.close(DefaultHttp2Connection.java:515) [netty-codec-http2-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultStream.close(DefaultHttp2Connection.java:521) [netty-codec-http2-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.handler.codec.http2.Http2ConnectionHandler.closeStream(Http2ConnectionHandler.java:613) [netty-codec-http2-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onRstStreamRead(DefaultHttp2ConnectionDecoder.java:444) [netty-codec-http2-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onRstStreamRead(Http2InboundFrameLogger.java:80) [netty-codec-http2-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readRstStreamFrame(DefaultHttp2FrameReader.java:509) [netty-codec-http2-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:259) [netty-codec-http2-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:159) [netty-codec-http2-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41) [netty-codec-http2-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:173) [netty-codec-http2-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378) [netty-codec-http2-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438) [netty-codec-http2-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) [netty-codec-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) [netty-codec-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) [netty-codec-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) [netty-transport-classes-epoll-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) [netty-transport-classes-epoll-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [netty-transport-classes-epoll-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.73.Final.jar:4.1.73.Final]
	at java.lang.Thread.run(Unknown Source) [?:?]
```
</details>

**Environment:**
- OS: Linux
- Zeebe Version: 8.1.6
- Configuration: no exporters

**Comment by shahamit** [comment]
In another test that I executed with 7 brokers and 7 partitions but changing the `taskCompletionDelay` to 10 secs instead of the default 200 ms I observed that the completion rate dropped to 1 without any backpressure.

![image](https://user-images.githubusercontent.com/1281926/222411396-17b6f4a7-7605-4272-b242-394379670764.png)

**Comment by korthout** [comment]
@megglos Is there anything you expect of ZPA on this issue?

**Comment by shahamit** [comment]
While executing a chaos experiment - [disconnect gateway](https://github.com/zeebe-io/zeebe-chaos/issues/331#issuecomment-1477909841) we saw the stream getting closed info statement in the zeebe client logs `io.grpc.internal.AbstractClientStream : Received data on closed stream`.

**Comment by megglos** [comment]
> @megglos Is there anything you expect of ZPA on this issue?

I put it into the boards of both teams given it's a shared component + it may also relate to the client.

**Comment by korthout** [comment]
@megglos It seems that your team already has this on their Ready column. We don't think it's useful that both teams look into this issue simultaneously. We'll await your findings.

**Comment by npepinpe** [comment]
@deepthidevaki will take a look as it seems related to some things she observed this week as medic, but if it's not, then the assumption is that @megglos meant to put this in backlog, but in case not, we'll wait for him to be back to discuss this again.

**Comment by deepthidevaki** [comment]
Observed something similar in one of the benchmark.

Observed repeated logs where gateway cannot send jobs to the workers 
```
ERROR 2023-08-28T15:52:07.556173647Z [resource.labels.podName: release-8-2-x-zeebe-gateway-7685f56869-c9dxh] Aug 28, 2023 3:52:07 PM io.grpc.netty.NettyServerHandler onStreamError
ERROR 2023-08-28T15:52:07.556225286Z [resource.labels.podName: release-8-2-x-zeebe-gateway-7685f56869-c9dxh] WARNING: Stream Error
ERROR 2023-08-28T15:52:07.556232885Z [resource.labels.podName: release-8-2-x-zeebe-gateway-7685f56869-c9dxh] io.netty.handler.codec.http2.Http2Exception$StreamException: Stream closed before write could take place at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:173) at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$FlowState.cancel(DefaultHttp2RemoteFlowController.java:481) at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$1.onStreamClosed(DefaultHttp2RemoteFlowController.java:105) at ERROR 2023-08-28T15:52:07.556421909Z [resource.labels.podName: release-8-2-x-zeebe-gateway-7685f56869-c9dxh] {}
DEBUG 2023-08-28T15:52:07.965226800Z [resource.labels.podName: release-8-2-x-zeebe-gateway-7685f56869-c9dxh] Failed to send 40 activated jobs for type benchmark-task (with job keys: [6755402314842260, 6755402314842270, 6755402314842280, 6755402314842290, 6755402314842300, 6755402314842310, 6755402314842320, 6755402314842330, 6755402314842340, 6755402314842350, 6755402314842360, 6755402314842370, 6755402314842380, 6755402314842390, 6755402314842400, 6755402314842410, 6755402314842420, 6755402314842430, 6755402314842440, 6755402314842450, 6755402314842460, 6755402314842470, 6755402314842480, 6755402314842490, 6755402314842500, 6755402314842510, 6755402314842520, 6755402314842530, 6755402314842540, 6755402314842550, 6755402314842560, 6755402314842570, 6755402314842580, 6755402314842590, 6755402314842600, 6755402314842610, 6755402314842620, 6755402314842630, 6755402314842640, 6755402314842650]) to client, because: Failed to send activated jobs to client
```

[On the workers (client)](https://console.cloud.google.com/logs/query;cursorTimestamp=2023-08-28T14:55:20.556643980Z;endTime=2023-08-29T10:02:18.000Z;pinnedLogId=2023-08-28T14:55:20.556643980Z%2Fx1fl22y4kyp4psnc;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22release-8-2-x%22%0Alabels.k8s-pod%2Fapp%3D%22worker%22%0Atimestamp%3D%222023-08-28T14:55:20.556643980Z%22%0AinsertId%3D%22x1fl22y4kyp4psnc%22;startTime=2023-08-28T09:01:48.000Z?project=zeebe-io) : 
```
ERROR 2023-08-28T15:39:27.599669386Z Aug 28, 2023 3:39:27 PM io.grpc.internal.AbstractClientStream$TransportState inboundDataReceived
ERROR 2023-08-28T15:39:27.599677522Z INFO: Received data on closed stream
INFO 2023-08-28T14:55:20.556836743Z java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason at java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[?:?] at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:?] at io.camunda.zeebe.ResponseChecker.run(ResponseChecker.java:41) [classes/:?] Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason at io.grpc.Status.asRuntimeException(Status.java:539) ~[grpc-api-1.54.2.jar:1.54.2] at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(Clien
```

This persisted for several hours.
It was resolved when the workers were restarted.

**Comment by Zelldon** [comment]
Triage:

Lets timebox it (~1 hour) to reproduce it, if we are not able to reproduce and get no further input lets close it.

**Comment by npepinpe** [comment]
We will look at it as part of job activation stabilization after the client flow control epic.

**Comment by npepinpe** [comment]
Is this still an issue with [job streaming](https://docs.camunda.io/docs/apis-tools/java-client/job-worker/#job-streaming) turned on?

**Comment by tmetzke** [comment]
@npepinpe, this support case looks related: https://jira.camunda.com/browse/SUPPORT-22444
There are multiple warnings in the job workers like the following:
```
io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
	at io.grpc.Status.asRuntimeException(Status.java:539)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:576)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:757)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:736)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
I will have a look into the gateway logs next Monday to see if they correlate with the messages @deepthidevaki [observed as mentioned above](https://github.com/camunda/camunda/issues/11864#issuecomment-1700977301).

Just wanted to leave this here already in case this helps.
