### ISSUE TITLE
Update JavaDoc and gRPC docs regarding values of "timeout"

### ISSUE THREAD

**Issue by stephanpelikan** [camunda/zeebe#11903]
I created this subscription for usertasks:

```java
        workers.add(
                client
                        .newWorker()
                        .jobType("io.camunda.zeebe:userTask")
                        .handler(userTaskHandler)
                        .timeout(Long.MAX_VALUE) // don't fetched user-tasks more than once
                        .name(workerId));
```

As you can see, I set `timeout` to a very high value to ensure this task is not reassigned by Zeebe in case of not completing in time.

Doing so I got the error

io.grpc.StatusRuntimeException: INTERNAL: Command 'ACTIVATE' rejected with code 'PROCESSING_ERROR': Expected to process record 'TypedRecordImpl{metadata=RecordMetadata{recordType=COMMAND, intentValue=255, intent=ACTIVATE, requestStreamId=1, requestId=1647, protocolVersion=3, valueType=JOB_BATCH, rejectionType=NULL_VAL, rejectionReason=, brokerVersion=8.1.5}, value={"type":"io.camunda.zeebe:userTask","worker":"dev1","timeout":9223372036854775807,"maxJobsToActivate":32,"jobKeys":[2251799813815872],"jobs":[{"deadline":-9223370359103830381,"worker":"dev1","retries":1,"retryBackoff":0,"recurringTime":-1,"type":"io.camunda.zeebe:userTask","customHeaders":[packed value (length=38)],"variables":"3wAAAAKiaWShMqdzdWNjZXNzwg==","errorMessage":"","errorCode":"","bpmnProcessId":"DemoWorkflow","processDefinitionVersion":4,"processDefinitionKey":2251799813805900,"processInstanceKey":2251799813815865,"elementId":"Activity_1ruuvs6","elementInstanceKey":2251799813815871}],"variables":[],"truncated":false}}' without errors, but exception occurred with message '**deadline must be greater than 0**'.

This seems to be kind of an overflow. I was wondering because the timeout-parameter is of type long but this is not accepted. In the [gRPC-API-docs](https://docs.camunda.io/docs/apis-clients/grpc/) I found this:
```
// when the job can be activated again, sent as a UNIX epoch timestamp
int64 deadline = 12;
```
Which means also "long". So I tried `Integer.MAX_VALUE` (which is Dienstag, **19. Januar 2038** 04:14:07 GMT+01:00 if I assume the unit is seconds) which is good enough for now. But actually I do not know if the units are seconds or milliseconds.

So, I miss in documentation:
- The unit of `timeout` (seconds or milliseconds?)
- The maximum value of `timeout` accepted without getting the error shown above and what timestamp this maximum value is equivalent to
- Maybe add a constant to any Java API class/interface to provide this maximum value as a constant

**Comment by korthout** [comment]
Thanks for reporting @stephanpelikan ❤️ 

The Zeebe Process Automation team discussed this issue. This is an overflow bug.

**About documentation**
Please note the difference between the timeout and the deadline:
- `timeout` (part of [ActivateJobsRequest](https://docs.camunda.io/docs/apis-clients/grpc/#input-activatejobsrequest))
>// a job returned after this call will not be activated by another call until the
>// timeout (in ms) has been reached

- `deadline` (part of [ActivateJobsResponse](https://docs.camunda.io/docs/apis-clients/grpc/#output-activatejobsresponse))
>// when the job can be activated again, sent as a UNIX epoch timestamp

Also note that the units are defined for both RPCs (and in JavaDoc on the zeebe-java-client: [timeout](https://github.com/camunda/zeebe/blob/main/clients/java/src/main/java/io/camunda/zeebe/client/api/worker/JobWorkerBuilderStep1.java#L64-L76), [deadline](https://github.com/camunda/zeebe/blob/main/clients/java/src/main/java/io/camunda/zeebe/client/api/response/ActivatedJob.java#L77-L82)).

I hope this clarifies it. Please let us know if there's anything that we can do to improve the documentation on this.

**About the overflow bug**
So the `timeout` is a duration, and the `deadline` is a moment in time. The timeout can be any long (int64), which is added to the moment the job is activated for the worker to form the deadline. Forming this deadline is what overflows.

The internal error produced by that overflow should **not** end up at the client. Instead, we need an error message that is helpful, explaining what happened and what can be done against it.

Note that the bug has no further impact. The job activation is rolled back safely.

**Comment by stephanpelikan** [comment]
I recently retested this using Camunda 8.5.5 and sprint-boot-starter-camunda 8.5.4 still experiencing this issue:

```
2024-12-12T09:22:05.331Z  WARN 1 --- [coman] [t-executor-2322] io.camunda.zeebe.client.job.poller       : Failed to activate jobs for worker coman-service-6464cc898b-phdcq and job type io.camunda.zeebe:userTaskio.grpc.StatusRuntimeException: INTERNAL: Command 'ACTIVATE' rejected with code 'PROCESSING_ERROR': Expected to process record 'TypedRecordImpl{metadata=RecordMetadata{recordType=COMMAND, valueType=JOB_BATCH, intent=ACTIVATE, authorization=JWT.eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJpc3MiOiJ6ZWViZS1nYXRld2F5IiwiYXVkIjoiemVlYmUtYnJva2VyIiwic3ViIjoiemVlYmUtY2xpZW50IiwiYXV0aG9yaXplZF90ZW5hbnRzIjpbImNhbXVuZGEtcGxheWdyb3VuZCIsImRwZmkiLCJjb2JyIiwiaXJpcyJdfQ.}, value={"type":"io.camunda.zeebe:userTask","worker":"coman-service-6464cc898b-phdcq","timeout":9223372036854775807,"maxJobsToActivate":32,"jobKeys":[2251799834518923],"jobs":[{"deadline":-9223370302859450492,"timeout":-1,"worker":"coman-service-6464cc898b-phdcq","retries":1,"retryBackoff":0,"recurringTime":-1,"type":"io.camunda.zeebe:userTask","customHeaders":[packed value (length=63)],"variables":"3wAAABKmY......mVybGluXQ==","errorMessage":"","errorCode":"","bpmnProcessId":"Cobr","processDef...}' without errors, but exception occurred with message 'deadline must be greater than 0'.    at io.grpc.Status.asRuntimeException(Status.java:533) ~[grpc-api-1.62.2.jar!/:1.62.2]    at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:481) ~[grpc-stub-1.62.2.jar!/:1.62.2]    at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574) ~[grpc-core-1.62.2.jar!/:1.62.2]    at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72) ~[grpc-core-1.62.2.jar!/:1.62.2]    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742) ~[grpc-core-1.62.2.jar!/:1.62.2]    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723) ~[grpc-core-1.62.2.jar!/:1.62.2]    at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.62.2.jar!/:1.62.2]    at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[grpc-core-1.62.2.jar!/:1.62.2]    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]    at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

Currently, I use a timeout of `100L * 365 * 24 * 3600 * 1000` (100 years) what is fine. The maximum timeout would be `max UNIX epoch` minus now in milliseconds.
