### ISSUE TITLE
Recent changes cause issues on rolling updates

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#11989]
**Describe the bug**

I know that we not officially support rolling updates, mostly because of https://github.com/camunda/zeebe/issues/7449

But there were also recent some changes it seems, which causes issues with the `ExporterStateDecoder`. Right now the issues have been detected on Clusters which uses the SNAPSHOT version. I understand that is not supported and might have issues due to incompatibilities, but I'm wondering whether this is not also an issue on the next version.

If we release the version, and a user does a normal update (e.g. helm update) as of now I feel they might run into this, since on k8 you normally do a rolling update.

**Error groups:**

* https://console.cloud.google.com/errors/detail/CNzmrcPlmbiEPQ;service=zeebe;version=SNAPSHOT;time=P7D?project=camunda-cloud-240911
* https://console.cloud.google.com/errors/detail/CNP86-m_5vn5Ew;service=zeebe;version=SNAPSHOT;time=P7D?project=camunda-cloud-240911

_My current assumption would be that it can be resolved by restarting all PODS._ Or is this an issue on the state?

**To Reproduce**

Starting with an old version, run with some load, upgrade to current SNAPSHOT.

**Expected behavior**
No issues during the upgrade.

**Log/Stacktrace**

[LOG](https://console.cloud.google.com/logs/query;query=error_group%2528%22CNzmrcPlmbiEPQ%22%2529%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.pod_name%3D%22zeebe-2%22%0Aresource.labels.cluster_name%3D%22integration-worker-1%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.namespace_name%3D%22a6c25d58-8fad-4479-bd96-f1ec44f865ec-zeebe%22%0Aresource.labels.location%3D%22europe-west1%22;timeRange=2023-03-10T07:16:58.477Z%2F2023-03-10T08:16:58.477Z;cursorTimestamp=2023-03-10T07:44:38.303108654Z?project=camunda-cloud-240911)

<details><summary>
LOG
</summary>
 <p>

```
java.lang.IndexOutOfBoundsException: index=78 capacity=78
	at org.agrona.concurrent.UnsafeBuffer.boundsCheck(UnsafeBuffer.java:2212) ~[agrona-1.17.1.jar:1.17.1]
	at org.agrona.concurrent.UnsafeBuffer.getByte(UnsafeBuffer.java:947) ~[agrona-1.17.1.jar:1.17.1]
	at io.camunda.zeebe.broker.protocol.ExporterStateDecoder$StateDecoder.wrap(ExporterStateDecoder.java:179) ~[zeebe-broker-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.broker.protocol.ExporterStateDecoder.state(ExporterStateDecoder.java:148) ~[zeebe-broker-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.broker.exporter.stream.ExporterStateDistributeMessage.wrap(ExporterStateDistributeMessage.java:84) ~[zeebe-broker-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.broker.exporter.stream.ExporterStateDistributionService.storeExporterState(ExporterStateDistributionService.java:46) ~[zeebe-broker-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService$InternalMessageConsumer.accept(DefaultClusterCommunicationService.java:286) ~[zeebe-atomix-cluster-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService$InternalMessageConsumer.accept(DefaultClusterCommunicationService.java:275) ~[zeebe-atomix-cluster-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$registerHandler$6(NettyMessagingService.java:268) ~[zeebe-atomix-cluster-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
```

</p>
</details>

[Similar issue here](https://console.cloud.google.com/logs/query;query=error_group%2528%22CNP86-m_5vn5Ew%22%2529%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.cluster_name%3D%22integration-worker-1%22%0Aresource.labels.pod_name%3D%22zeebe-2%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.namespace_name%3D%22569ed5b9-9321-4fc8-94d3-06f0bed6d6d6-zeebe%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22;timeRange=2023-03-09T10:36:03.535Z%2F2023-03-09T11:36:03.535Z;cursorTimestamp=2023-03-09T11:05:33.535591043Z?project=camunda-cloud-240911)

[This also caused issues on dev, ](https://camunda.slack.com/archives/C04CABJF6FP/p1678363913819779)

**Environment:**
- OS: 
- Zeebe Version: SNAPSHOT

**Comment by oleschoenburg** [comment]
Seems to be related to ed3265f78915ab2029df2e46d8fec1aa94e4acac. The commit mentions that this does not break and on first glance I'd have to agree that it looks like it shouldn't. A new `varDataEncoding` field was added and marked so that SBE should know that it only exists in version 3 of the message.

**Comment by Zelldon** [comment]
@npepinpe mentions that it is potentially https://github.com/camunda/zeebe/pull/11944 he will revert it
