### ISSUE TITLE
Not possible to use 1 node in a zeebe cluster

### ISSUE THREAD

**Issue by Hanor** [camunda/zeebe#12046]
**Describe the bug**

Hello,

I'm trying to use zeebe on GKE and when I configure the cluster size and other properties to allow me use the zeebe with only one node I'm receiving the below error:

CompletionException: java.lang.IllegalStateException: Expected that persisted cluster size '3' is equal to given one '1', but was different.

**To Reproduce**

Add the helm repository of Camunda

`helm repo add camunda https://helm.camunda.io`

Update

 `helm repo update`

Install the charts with a custom configuration

`helm install development-camunda camunda/camunda-platform -f zeebe-core-gke.yml`

Example: **zeebe-core-gke.yml**

````
zeebe:
    enabled: true
    clusterSize: 1
    partitionCount: 1
    replicationFactor: 1
````

**Expected behavior**

I expected to configure zeebe to work with a single node.
Apparently it's mandatory to use at least 3 nodes.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Expected that persisted cluster size '3' is equal to given one '1', but was different. Persisted configuration 'Configuration{index=0, time=2023-03-07 03:23:21,394, members=[DefaultRaftMember{id=0, type=ACTIVE, updated=2023-03-07T15:23:21.394Z}, DefaultRaftMember{id=1, type=ACTIVE, updated=2023-03-07T15:23:21.394Z}, DefaultRaftMember{id=2, type=ACTIVE, updated=2023-03-07T15:23:21.394Z}]}' is different then given one, new given member id's are: '[0]'. Changing the configuration is not supported. Please restart with the same configuration or recreate a new cluster after deleting persisted data.
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.IllegalStateException: Expected that persisted cluster size '3' is equal to given one '1', but was different. Persisted configuration 'Configuration{index=0, time=2023-03-07 03:23:21,394, members=[DefaultRaftMember{id=0, type=ACTIVE, updated=2023-03-07T15:23:21.394Z}, DefaultRaftMember{id=1, type=ACTIVE, updated=2023-03-07T15:23:21.394Z}, DefaultRaftMember{id=2, type=ACTIVE, updated=2023-03-07T15:23:21.394Z}]}' is different then given one, new given member id's are: '[0]'. Changing the configuration is not supported. Please restart with the same configuration or recreate a new cluster after deleting persisted data
```

</p>
</details>

**Environment:**
- OS: Linux
- Cloud: GCP

**Comment by Hanor** [comment]
I removed the Cluter in GCP and I recreated the cluster and this worked. 
But I need to ask, how can I be able to increase or decrease the cluster size without lose the data?

**Comment by Zelldon** [comment]
Hey @Hanor 

thanks for trying Zeebe and reaching out. Right now 
autoscaling is not supported, see #4391

I will close this as duplicate.

Greets 
Chris
