### ISSUE TITLE
NPE when closing StreamProcessor

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#12200]
**Describe the bug**

An error popped up during the RC1 benchmark, where there is no `asyncActor` to close when closing the stream processor. This may happen if the processor failed in starting phase, where no `asyncActor` has been created yet.

In this particular instance, it failed to recover from snapshot, tried to close, and as part of closing tried to close a null asyncActor.

**Expected behavior**

No NPE occurs.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.stream.impl.StreamProcessor$AsyncProcessingScheduleServiceActor.closeAsync()" because "this.asyncActor" is null
	at io.camunda.zeebe.stream.impl.StreamProcessor.onFailure(StreamProcessor.java:415) ~[zeebe-stream-platform-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.stream.impl.StreamProcessor.onActorStarted(StreamProcessor.java:221) ~[zeebe-stream-platform-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT] 
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: 8.2.0-rc1
- Configuration:

**Comment by megglos** [comment]
ZDP Triage:
- it's noise, no real impact besides the log
- should be an easy fix though
- testing is is the challenge here - manual test may be enough

**Comment by jack5505** [comment]
Can I work in this issue
