### ISSUE TITLE
NPE when creating a SegmentedJournalReader

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#12202]
**Describe the bug**

A follower got into a weird state where it failed to create a `SegmentedJournalReader`. To give more context, it was currently out of disk in general (with 3 partitions), and on one partition, had just received a snapshot from the leader. The snapshot failed to be written (since there was not enough disk space) and was rolled back, but the log was already cleared. When clearing the journal, it first deleted any segments then cleared its in-memory map. Normally, it would then create a new segment, but as it was out of disk space, no segments were created, which resulted in a partition with no snapshot and no journal.

This is the root cause for #12201 (which caused then #12200).

See https://console.cloud.google.com/errors/detail/CKaytc_Ms-yy7gE;service=zeebe;version=release-8-2-0-rc1?project=zeebe-io

Consequences here are that the follower cannot do anything, meaning no snapshot is taken, meaning it can only recover the next time the leader sends a snapshot, iff it has enough disk space.

**Expected behavior**

No NPE occurs, and we properly handle when there is no disk space such that the journal may simply be empty.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.journal.file.Segment.createReader()" because "this.currentSegment" is null
	at io.camunda.zeebe.journal.file.SegmentedJournalReader.initialize(SegmentedJournalReader.java:39) ~[zeebe-journal-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.journal.file.SegmentedJournalReader.<init>(SegmentedJournalReader.java:33) ~[zeebe-journal-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.journal.file.SegmentedJournal.openReader(SegmentedJournal.java:172) ~[zeebe-journal-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.atomix.raft.storage.log.RaftLog.openCommittedReader(RaftLog.java:72) ~[zeebe-atomix-cluster-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.atomix.raft.partition.impl.RaftPartitionServer.openReader(RaftPartitionServer.java:205) ~[zeebe-atomix-cluster-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.broker.logstreams.AtomixLogStorage.newReader(AtomixLogStorage.java:43) ~[zeebe-broker-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.broker.logstreams.AtomixLogStorage.newReader(AtomixLogStorage.java:24) ~[zeebe-broker-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.createLogStreamReader(LogStreamImpl.java:209) ~[zeebe-logstreams-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:86) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT] 
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: 8.2.0-rc1
- Configuration:

**Comment by megglos** [comment]
ZDP Triage:
relates to https://github.com/camunda/zeebe/issues/12374
whatever the fix is may also resolve this issue
