### ISSUE TITLE
Process Instance not blacklisted on StackOverflowError

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/zeebe#12240]
**Describe the bug**

Causing a `StackOverflowError` will crash the broker. The process instance that caused this is not getting blacklisted.

**To Reproduce**

[recursive.bpmn.zip](https://github.com/camunda/zeebe/files/11148644/recursive.bpmn.zip)

```
zbctl --insecure deploy resource recursive.bpmn
zbctl --insecure create instance recursive --variables="{\"index\": 1}"
-- wait until Zeebe finished processing
zbctl --insecure publish message msg --correlationKey=1
```

**Expected behavior**

Zeebe can handle the `StackOverflowError`, and the instance that caused this gets blacklisted to prevent it from crash-looping the broker.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.StackOverflowError: null
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.delete(ZeebeTransaction.java:64) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$deleteExisting$13(TransactionalColumnFamily.java:207) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$ensureInOpenTransaction$18(TransactionalColumnFamily.java:308) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.DefaultTransactionContext.runInTransaction(DefaultTransactionContext.java:31) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.ensureInOpenTransaction(TransactionalColumnFamily.java:307) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.deleteExisting(TransactionalColumnFamily.java:203) ~[classes/:?]
	at io.camunda.zeebe.engine.state.variable.DbVariableState.lambda$removeAllVariables$1(DbVariableState.java:135) ~[classes/:?]
	at io.camunda.zeebe.engine.state.variable.DbVariableState.lambda$visitVariablesLocal$11(DbVariableState.java:341) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.visit(TransactionalColumnFamily.java:390) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$forEachInPrefix$19(TransactionalColumnFamily.java:369) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ColumnFamilyContext.withPrefixKey(ColumnFamilyContext.java:112) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.forEachInPrefix(TransactionalColumnFamily.java:353) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.forEachInPrefix(TransactionalColumnFamily.java:325) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$whileEqualPrefix$12(TransactionalColumnFamily.java:198) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$ensureInOpenTransaction$18(TransactionalColumnFamily.java:308) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.DefaultTransactionContext.runInTransaction(DefaultTransactionContext.java:31) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.ensureInOpenTransaction(TransactionalColumnFamily.java:307) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.whileEqualPrefix(TransactionalColumnFamily.java:198) ~[classes/:?]
	at io.camunda.zeebe.engine.state.variable.DbVariableState.visitVariablesLocal(DbVariableState.java:335) ~[classes/:?]
	at io.camunda.zeebe.engine.state.variable.DbVariableState.removeAllVariables(DbVariableState.java:132) ~[classes/:?]
	at io.camunda.zeebe.engine.state.variable.DbVariableState.removeScope(DbVariableState.java:123) ~[classes/:?]
	at io.camunda.zeebe.engine.state.instance.DbElementInstanceState.removeInstance(DbElementInstanceState.java:150) ~[classes/:?]
	at io.camunda.zeebe.engine.state.appliers.ProcessInstanceElementTerminatedApplier.applyState(ProcessInstanceElementTerminatedApplier.java:41) ~[classes/:?]
	at io.camunda.zeebe.engine.state.appliers.ProcessInstanceElementTerminatedApplier.applyState(ProcessInstanceElementTerminatedApplier.java:19) ~[classes/:?]
	at io.camunda.zeebe.engine.state.appliers.EventAppliers.applyState(EventAppliers.java:302) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.streamprocessor.writers.ResultBuilderBackedEventApplyingStateWriter.appendFollowUpEvent(ResultBuilderBackedEventApplyingStateWriter.java:41) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.transitionTo(BpmnStateTransitionBehavior.java:218) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.transitionToTerminated(BpmnStateTransitionBehavior.java:208) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.lambda$onChildTerminated$7(ProcessProcessor.java:170) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.transitionTo(ProcessProcessor.java:181) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.onChildTerminated(ProcessProcessor.java:167) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.onChildTerminated(ProcessProcessor.java:27) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.lambda$onElementTerminated$7(BpmnStateTransitionBehavior.java:404) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.invokeElementContainerIfPresent(BpmnStateTransitionBehavior.java:443) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.onElementTerminated(BpmnStateTransitionBehavior.java:400) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.bpmn.container.CallActivityProcessor.lambda$transitionToTerminated$10(CallActivityProcessor.java:157) ~[classes/:?]
	at java.util.Optional.ifPresentOrElse(Optional.java:198) ~[?:?]
	at io.camunda.zeebe.engine.processing.bpmn.container.CallActivityProcessor.transitionToTerminated(CallActivityProcessor.java:146) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.bpmn.container.CallActivityProcessor.onChildTerminated(CallActivityProcessor.java:135) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.bpmn.container.CallActivityProcessor.onChildTerminated(CallActivityProcessor.java:29) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.onCalledProcessTerminated(BpmnStateTransitionBehavior.java:379) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.lambda$getPostTransitionAction$9(ProcessProcessor.java:200) ~[classes/:?]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:381) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.transitionTo(ProcessProcessor.java:182) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.onChildTerminated(ProcessProcessor.java:167) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.onChildTerminated(ProcessProcessor.java:27) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.lambda$onElementTerminated$7(BpmnStateTransitionBehavior.java:404) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.invokeElementContainerIfPresent(BpmnStateTransitionBehavior.java:443) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.onElementTerminated(BpmnStateTransitionBehavior.java:400) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.bpmn.container.CallActivityProcessor.lambda$transitionToTerminated$10(CallActivityProcessor.java:157) ~[classes/:?]
...
14:48:16.499 [] [hz.ShutdownThread] INFO  com.hazelcast.instance.impl.Node - [192.168.178.34]:5701 [dev] [5.1.2] Running shutdown hook... Current state: ACTIVE
14:48:16.500 [] [hz.ShutdownThread] INFO  com.hazelcast.core.LifecycleService - [192.168.178.34]:5701 [dev] [5.1.2] [192.168.178.34]:5701 is SHUTTING_DOWN
14:48:16.502 [Broker-0-Startup] [Broker-0-zb-actors-1] DEBUG io.camunda.zeebe.broker.system - Shutdown was called with context: io.camunda.zeebe.broker.bootstrap.BrokerStartupContextImpl@4a91fe00
14:48:16.502 [Broker-0-Startup] [Broker-0-zb-actors-1] INFO  io.camunda.zeebe.broker.system - Shutdown Admin API
14:48:16.502 [] [hz.ShutdownThread] WARN  com.hazelcast.instance.impl.Node - [192.168.178.34]:5701 [dev] [5.1.2] Terminating forcefully...
```

</p>
</details>

**Environment:**
- Zeebe Version: latest main branch

**Comment by remcowesterhoud** [comment]
@Zelldon Here you go 😄

**Comment by Zelldon** [comment]
Thanks @remcowesterhoud :+1:

**Comment by megglos** [comment]
@remcowesterhoud do we not what process caused this? Was it a Call-Activity calling itself?

**Comment by koevskinikola** [comment]
The issue occurred again in a trial cluster resulting in the broker crash looping.

**Comment by marcosgvieira** [comment]
🔄 **Status updated automatically (Core Features)**

**From:** Ready  
**To:** Backlog  

**Reason:** The issue does not have an assignee.

**Comment by ajanoni-camunda** [comment]
### New production occurrence — regex-induced `StackOverflowError` (build 8.10.0-alpha4)

Observed again on a SaaS prod broker during a medic shift. Same failure mode as this issue: a `StackOverflowError` raised during stream processing is treated as an unrecoverable `VirtualMachineError`, so `VirtualMachineErrorHandler` halts the broker (exit code 156) instead of banning the offending process instance. The instance is not banned, so it is a poison-pill on replay.

**What's new vs. the original reproducer:** the original report is a recursive BPMN causing deep recursion in the engine (variable removal). This occurrence's `StackOverflowError` originates entirely inside `java.util.regex.Pattern` — i.e. catastrophic regex backtracking / a deeply nested pattern during processing (most likely a FEEL string function such as `matches`/`replace`/`split` over a pathological pattern/input). So the ban-on-`StackOverflowError` handling needs to cover regex-triggered SOEs too, not just recursive call structures.

**Symptoms / timeline (sanitized):**
- Broker became LEADER of a partition and started its StreamProcessor, then threw the SOE on the engine actor thread (`zb-actors-1`) ~2s later.
- Broker halted ~83s after startup; Raft term churned rapidly (13 → 14 → 15) as leadership flapped — consistent with brokers crash-looping on the same record.

**Environment:**
- SaaS (observed); the defect is in engine/stream-processing code, so Self-Managed is affected too.
- Version: 8.10.0-alpha4 (build `4a76f06`).

**Truncated stack trace (all captured frames are pure regex recursion; the application call site is below the truncation point):**

```
ERROR io.camunda.zeebe.util.actor [zb-actors-1]
  Shutting down because we can't recover from JVM errors. Consider restarting this broker if it is a temporary issue.
java.lang.StackOverflowError
	at java.base/java.util.regex.Pattern$Loop.match(Unknown Source)
	at java.base/java.util.regex.Pattern$GroupTail.match(Unknown Source)
	at java.base/java.util.regex.Pattern$BranchConn.match(Unknown Source)
	at java.base/java.util.regex.Pattern$CharProperty.match(Unknown Source)
	at java.base/java.util.regex.Pattern$Branch.match(Unknown Source)
	at java.base/java.util.regex.Pattern$GroupHead.match(Unknown Source)
	... (repeating for 237 captured frames)
```

Note: `VirtualMachineErrorHandler` already special-cases DMN-scala `StackOverflowError` as a graceful, deterministic poison-pill failure; the FEEL/regex processing path is not similarly guarded and instead halts the broker.

[Downloaded logs](https://drive.google.com/file/d/193L0iUunvrIhwmoRdP9HSaH9uMUMqLwE/view?usp=share_link)
[GCP Logs](https://cloudlogging.app.goo.gl/tBiaj9etuWuM4uG18)
