### ISSUE TITLE
Failed to append block with last event position and the partition can not work

### ISSUE THREAD

**Issue by jerry123888** [camunda/zeebe#12456]
![image](https://user-images.githubusercontent.com/92800459/232664267-9203a7a6-2fbd-4429-91f9-311b5c5db0e1.png)

the partition-25 can not work  because of the errors:
[2023-04-17 13:42:57.362]||raft-server-16-raft-partition-partition-25|ERROR|io.camunda.zeebe.logstreams|Failed to append block with last event position 3342255987.
java.lang.IllegalStateException: Unexpected position 3342255986 was encountered after position 3342255984 when appending positions <3342255986, 3342255987>.
	at io.atomix.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:564) ~[zeebe-atomix-cluster-1.2.4.jar:1.2.4]
	at io.atomix.raft.roles.LeaderRole.lambda$appendEntry$8(LeaderRole.java:544) ~[zeebe-atomix-cluster-1.2.4.jar:1.2.4]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:174) [zeebe-atomix-utils-1.2.4.jar:1.2.4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
[2023-04-17 13:42:57.379]|Broker-16-LogAppender-25|Broker-16-zb-actors-2|ERROR|io.camunda.zeebe.logstreams|Actor Broker-16-LogAppender-25 failed in phase STARTED.
java.lang.IllegalStateException: Unexpected position 3342255986 was encountered after position 3342255984 when appending positions <3342255986, 3342255987>.
	at io.atomix.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:564) ~[zeebe-atomix-cluster-1.2.4.jar:1.2.4]
	at io.atomix.raft.roles.LeaderRole.lambda$appendEntry$8(LeaderRole.java:544) ~[zeebe-atomix-cluster-1.2.4.jar:1.2.4]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:174) ~[zeebe-atomix-utils-1.2.4.jar:1.2.4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
[2023-04-17 13:42:57.381]|Broker-16-LogStream-25|Broker-16-zb-actors-5|INFO|io.camunda.zeebe.logstreams|Close appender for log stream logstream-raft-partition-partition-25
[2023-04-17 13:42:57.381]|Broker-16-ZeebePartition-25|Broker-16-zb-actors-4|WARN|io.camunda.zeebe.broker.system|logstream-raft-partition-partition-25 failed, marking it as unhealthy
[2023-04-17 13:42:57.382]|Broker-16-LogStream-25|Broker-16-zb-actors-5|INFO|io.camunda.zeebe.logstreams|On closing logstream logstream-raft-partition-partition-25 close 2 readers
[2023-04-17 13:42:57.384]|Broker-16-Exporter-25|Broker-16-zb-fs-workers-3|INFO|org.apache.kafka.clients.producer.KafkaProducer|[Producer clientId=zeebe-f33780f2-3b1b-42ba-aa48-b852498a5484, transactionalId=f33780f2-3b1b-42ba-aa48-b852498a5484] Closing the Kafka producer with timeoutMillis = 5000 ms.
[2023-04-17 13:42:57.387]|Broker-16-Exporter-25|Broker-16-zb-fs-workers-3|INFO|org.apache.kafka.common.metrics.Metrics|Metrics scheduler closed
[2023-04-17 13:42:57.387]|Broker-16-Exporter-25|Broker-16-zb-fs-workers-3|INFO|org.apache.kafka.common.metrics.Metrics|Closing reporter org.apache.kafka.common.metrics.JmxReporter
[2023-04-17 13:42:57.387]|Broker-16-Exporter-25|Broker-16-zb-fs-workers-3|INFO|org.apache.kafka.common.metrics.Metrics|Metrics reporters closed
[2023-04-17 13:42:57.387]|Broker-16-Exporter-25|Broker-16-zb-fs-workers-3|INFO|org.apache.kafka.common.utils.AppInfoParser|App info kafka.producer for zeebe-f33780f2-3b1b-42ba-aa48-b852498a5484 unregistered
[2023-04-17 13:42:57.387]|Broker-16-Exporter-25|Broker-16-zb-fs-workers-3|INFO|io.camunda.zeebe.broker.exporter.kafka|Closed Kafka exporter
[2023-04-17 13:42:57.574]|Broker-16-ZeebePartition-25|Broker-16-zb-actors-3|INFO|org.camunda.feel.FeelEngine|Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@3746b267)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@627ab468, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@632fc30b, configuration: Configuration(false)]
[2023-04-17 13:42:57.623]|Broker-16-StreamProcessor-25|Broker-16-zb-actors-3|INFO|org.camunda.feel.FeelEngine|Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@4f189687)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@73cced1b, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@9bd5b17, configuration: Configuration(false)]
[2023-04-17 13:42:57.624]|Broker-16-StreamProcessor-25|Broker-16-zb-actors-3|INFO|io.camunda.zeebe.logstreams|Recovered state of partition 25 from snapshot at position 3342251375
[2023-04-17 13:42:57.624]|Broker-16-StreamProcessor-25|Broker-16-zb-actors-3|INFO|org.camunda.feel.FeelEngine|Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@3b1c5c21)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@30bb596b, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@240bce52, configuration: Configuration(false)]
[2023-04-17 13:42:57.625]|Broker-16-StreamProcessor-25|Broker-16-zb-actors-3|INFO|org.camunda.feel.FeelEngine|Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@478d4c27)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@1ea9fda3, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@74338f1c, configuration: Configuration(false)]
[2023-04-17 13:42:57.626]|Broker-16-StreamProcessor-25|Broker-16-zb-actors-3|INFO|org.camunda.feel.FeelEngine|Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@e30b696)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@23713f03, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@72649a2b, configuration: Configuration(false)]
[2023-04-17 13:42:57.627]|Broker-16-StreamProcessor-25|Broker-16-zb-actors-3|INFO|io.camunda.zeebe.processor|Processor starts replay of events. [snapshot-position: 3342251375, replay-mode: REPLAY]
[2023-04-17 13:42:57.630]|Broker-16-Exporter-25|Broker-16-zb-fs-workers-1|INFO|io.camunda.zeebe.broker.exporter.kafka|Configured Kafka exporter

**Comment by megglos** [comment]
Hey @jerry123888 ,

we are checking if there are any existing issues for this bug to confirm whether it's known and already fixed in a later release.
As 1.2 is out of support already, is it feasible for you to update to a still supported version like 8.0+ anytime soon?

**Comment by megglos** [comment]
Hey @jerry123888,

I couldn't find any identical issue for the error you encountered, which is there is a gap between the last written position and the new one to write. However in the course of the more recent releases there were a couple of fixes on similar issues, I would thus suggest you to update your setup to a recently supported version.

> can i restart the broker to recover ?
A restart would definitely be worth trying 

I hope you understand that as of now I can't do much more on this issue as it affects a version that is already out of support as per [release lifecyle](https://github.com/camunda/zeebe#release-lifecycle).

I would thus close this issue for now, but feel free to reach out once more if you have further questions.
