### ISSUE TITLE
Double process variable data with a zero after the comma is instantiated as an Integer

### ISSUE THREAD

**Issue by goenkale** [camunda/zeebe#12473]
I'm testing a Zeebe client where I get some process variables. The process instance starts with some data from the Desktop modeler with this payload:
```
{
  "reference": "C8_1234544",
  "amount": 100.00,
  "cardNumber": "7894567891235456",
  "cardExpiry": "10/2027",
  "cardCVC": "111"
}
```
Check that the "amount" is a double. Once I check the instance process variables from Operate I discover the value as an int 100. From my Zeebe client I get the input process variables and I cast them properly:

```
public class CreditCardServiceHandler implements JobHandler{
	
	CreditCardService creditCardService = new CreditCardService();
	
	@Override
	public void handle(JobClient client, ActivatedJob job) throws Exception{
		 final Map<String, Object> inputVariables = job.getVariablesAsMap();
                 final String reference = (String) inputVariables.get("reference");
                 final Double amount = (Double) inputVariables.get("amount");
                 final String cardNumber = (String) inputVariables.get("cardNumber");
                 final String cardExpiry = (String) inputVariables.get("cardExpiry");
                 final String cardCVC =  (String) inputVariables.get("cardCVC");
        
                 final String confirmation = creditCardService.chargeCreditCard(reference, amount, cardNumber, cardExpiry, cardCVC);
        
                 final Map<String, Object> outputVariables = new HashMap<String, Object>();
                 outputVariables.put("confirmation", confirmation);
        
                 client.newCompleteCommand(job.getKey()).variables(outputVariables).send().join();
	}

}
```
The engine throws and exception trying to cast an Integer to a Double:
```
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Double (java.lang.Integer and java.lang.Double are in module java.base of loader 'bootstrap')
	at com.camunda.academy.handler.CreditCardServiceHandler.handle(CreditCardServiceHandler.java:22)
	at io.camunda.zeebe.client.impl.worker.JobRunnableFactory.executeJob(JobRunnableFactory.java:44)
	at io.camunda.zeebe.client.impl.worker.JobRunnableFactory.lambda$create$0(JobRunnableFactory.java:39)
	at java.base/j...
```
In a second test, I tried with an amount of 100.5 and it's working fine. It seems that the process variable is instantiated as an Integer instead of a Double, and that's the issue. Something that could be new in C8.2 since I'm following the C8 training from the Academy and it's the first time someone finds this issue.

You can reproduce it by following this course: https://employee-academy.camunda.com/path/c8-lp-getting-started/c8-getting-started-human-workflow

Or importing the java project in you IDE and the bpmn process to your Desktop Modeler, deploy it, etc.

**Environment:**
- OS: Windows
- Zeebe Version: 8.2.2

**Comment by goenkale** [comment]
[paymentProcess.zip](https://github.com/camunda/zeebe/files/11262202/paymentProcess.zip)
[c8-getting-started-microservice-orchestration-lab2.zip](https://github.com/camunda/zeebe/files/11262225/c8-getting-started-microservice-orchestration-lab2.zip)

**Comment by remcowesterhoud** [comment]
Thanks for raising this @goenkale! I can reproduce the behaviour and am investigating where this is coming from. At the moment I don't think this a bug in Zeebe, as it is working fine when I start a process instance with the Java client or `zbctl` directly.

I've asked for more information from the Modeler team and hope to hear back from them soon.

**Comment by nikku** [comment]
A safe way to consume these properties is the following:

```java
Number foo = (Number) inputVariables.get("amount");
double fooAsDouble = foo.doubleValue();
```

Another safe way of pulling the variables via [`ActivatedJob#getVariablesAsType`](https://javadoc.io/static/io.camunda/zeebe-client-java/8.2.2/io/camunda/zeebe/client/api/response/ActivatedJob.html#getVariablesAsType(java.lang.Class)) through a dedicated object object mapper.

We could verify how to better preserve types, as we start a process via JSON in the Modeler. This builds on shaky grounds though, as technically variables are passed as JSON, and JSON only knows a number type, not the Java specifics.

**Comment by remcowesterhoud** [comment]
I've [created a PR](https://github.com/camunda-academy/c8-getting-started-microservice-orchestration-lab/pull/2) to fix the example lab to also cast to `Number`. As this isn't a bug in Zeebe I will close this issue now.
