### ISSUE TITLE
All BackupMultiPartitionTest cases failed in run

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#12732]
**Summary**

A CI run on `main` failed because all three test cases of the `BackupMultiPartitionTest` failed with errors. They were not detected by the flaky-test-extractor, but failed reliably in [this particular CI run](https://github.com/camunda/zeebe/actions/runs/4927371766/jobs/8804261399). However, the commit had passed the CI run before when it was merged by Bors.

The assertion message does not help me to figure out what really happened.

> Try to answer the following as best as possible

- How often does the test fail? I've seen it once
- Does it block your work? No, but tests shouldn't fail on main
- Do we suspect that it is a real failure? I'm not sure what happens, because the assertion message is not helpful.

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Error:  io.camunda.zeebe.it.backup.BackupMultiPartitionTest.shouldTriggerBackupViaInterPartitionMessageDeploymentDistribute  Time elapsed: 16.647 s  <<< ERROR!
org.awaitility.core.ConditionTimeoutException: 
Assertion condition defined as a io.camunda.zeebe.it.backup.BackupMultiPartitionTest 
Expecting actual:
  BrokerResponse{isResponse=true, response=io.camunda.zeebe.protocol.impl.encoding.BackupStatusResponse@23bb825f, partitionId=1, key=-1}
to match given predicate.
</pre>
</details>

<details><summary>Assertion improvement suggestion</summary>
<p>
A suggestion to improve the assertion is offered by the test runner.
</p>
<pre>
You can use 'matches(Predicate p, String description)' to have a better error message
For example:
  assertThat(player).matches(p -> p.isRookie(), "is rookie");
will give an error message looking like:

Expecting actual:
  player
to match 'is rookie' predicate within 10 seconds.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
	at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:769)
	at 
</pre>
</details> 

**Hypotheses**

> List any hypotheses if you have one; can be omitted

I have no clue why this test failed or what really happened. The assertion message is not helpful.

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
Error:  Tests run: 5, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 126.53 s <<< FAILURE! - in io.camunda.zeebe.it.backup.BackupMultiPartitionTest
Error:  io.camunda.zeebe.it.backup.BackupMultiPartitionTest.shouldTriggerBackupViaInterPartitionMessageCorrelationCommands  Time elapsed: 17.455 s  <<< ERROR!
org.awaitility.core.ConditionTimeoutException: 
Assertion condition defined as a io.camunda.zeebe.it.backup.BackupMultiPartitionTest 
Expecting actual:
  BrokerResponse{isResponse=true, response=io.camunda.zeebe.protocol.impl.encoding.BackupStatusResponse@ba96871, partitionId=2, key=-1}
to match given predicate.

You can use 'matches(Predicate p, String description)' to have a better error message
For example:
  assertThat(player).matches(p -> p.isRookie(), "is rookie");
will give an error message looking like:

Expecting actual:
  player
to match 'is rookie' predicate within 10 seconds.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
	at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:769)
	at io.camunda.zeebe.it.backup.BackupMultiPartitionTest.waitUntilBackupCompletedOnPartition(BackupMultiPartitionTest.java:332)
	at io.camunda.zeebe.it.backup.BackupMultiPartitionTest.takeBackupOnPartition(BackupMultiPartitionTest.java:322)
	at io.camunda.zeebe.it.backup.BackupMultiPartitionTest.shouldTriggerBackupViaInterPartitionMessageCorrelationCommands(BackupMultiPartitionTest.java:182)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.SameThreadTimeoutInvocation.proceed(SameThreadTimeoutInvocation.java:45)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:[217](https://github.com/camunda/zeebe/actions/runs/4927371766/jobs/8804261399#step:10:218))
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:202)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:146)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:202)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.awaitility.core.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:101)
	at org.awaitility.core.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:81)
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:103)
	... 67 more
</pre>
</details>

**Comment by oleschoenburg** [comment]
The logs for the mentioned CI run are deleted by now. I believe that around that time we were experiencing various stability issues with test containers. `BackupMultiPartitionTest` uses a shared `MinioContainer` - if that fails to start, all test cases would fail.

I'll close this as we don't have logs to investigate and it seems likely that this was just a temporary stability problem.
