### ISSUE TITLE
When activating jobs, the Zeebe Gateway fails to stream out activated jobs by not respecting the `maxMessageSize`

### ISSUE THREAD

**Issue by romansmirnov** [camunda/zeebe#12778]
**Describe the bug**

By default, the `maxMessageSize` is set to 4MB, meaning, any incoming message cannot be greater than 4MB but also any outgoing message won't be greater than 4MB. This setting applies to the Broker and also to the Gateway.

Eventually, the `maxMessageSize` is used to collect jobs to activate in the Broker. So while collecting jobs, the broker checks the following conditions:
1. If the number of jobs already collected is greater than or equal to the passed `maxJobsToActivate`, then stop collecting further.
2. If the size (in bytes) of jobs - including their variables  - already collected + the size (in bytes) of the next job is greater than `maxMessageSize`, then stop collecting further.

https://github.com/camunda/zeebe/blob/f1a8adc26245dd132397d8a82c3e4ffb1486ca5f/engine/src/main/java/io/camunda/zeebe/engine/processing/job/JobBatchCollector.java#L94-L95

Assuming there are 100 jobs and each job has, in addition, variables of 1MB, that means - and when keeping it simple - it will collect the first jobs up to `maxMessageSize` of 4MB, and return these 4 jobs back to the Gateway.

Before streaming out the activated jobs, the Gateway will convert the Broker Response (MessagePack) to a Client Response (gRPC):

https://github.com/camunda/zeebe/blob/f1a8adc26245dd132397d8a82c3e4ffb1486ca5f/gateway/src/main/java/io/camunda/zeebe/gateway/ResponseMapper.java#L245-L276

Thereby, it converts the variables from a byte array to a JSON as String representation:

https://github.com/camunda/zeebe/blob/f1a8adc26245dd132397d8a82c3e4ffb1486ca5f/gateway/src/main/java/io/camunda/zeebe/gateway/ResponseMapper.java#L269

In terms of memory usage, the JSON as String is bigger than the byte array representation. That means, while the broker response is `<= 4MB` the actual Client response might result in a size `> 4MB`. So Zeebe Java Client rejects the response containing the activated jobs, and the Client cancels the channel/stream/connection as well. Also, the Gateway logs out a `Stream Error` indicating that streaming out the activated jobs to the client failed:

```
io.grpc.netty.NettyServerHandler onStreamError
WARNING: Stream Error
io.netty.handler.codec.http2.Http2Exception$StreamException: Stream closed before write could take place
        at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:173)
        at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$FlowState.cancel(DefaultHttp2RemoteFlowController.java:481)
        at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$1.onStreamClosed(DefaultHttp2RemoteFlowController.java:105)
        at io.netty.handler.codec.http2.DefaultHttp2Connection.notifyClosed(DefaultHttp2Connection.java:357)
        at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.removeFromActiveStreams(DefaultHttp2Connection.java:1007)
        at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.deactivate(DefaultHttp2Connection.java:963)
        at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultStream.close(DefaultHttp2Connection.java:515)
        at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultStream.close(DefaultHttp2Connection.java:521)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.closeStream(Http2ConnectionHandler.java:628)
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onRstStreamRead(DefaultHttp2ConnectionDecoder.java:444)
        at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onRstStreamRead(Http2InboundFrameLogger.java:80)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readRstStreamFrame(DefaultHttp2FrameReader.java:509)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:259)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:159)
        at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:173)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:393)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:453)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

Consequently, the activated jobs remain locked in the Broker (and they only are re-activatable after a configured timeout) because the exception above happens out of the control flow when sending back the activated jobs to the client. Additionally, the Gateway continues collecting further jobs for the same `ActivateJobs` request but fails to send them back to the Client as the stream already got canceled (but this time it happens in the control flow of the Gateway).

Why does the Zeebe Java Client reject the response?
By default, the max message inbound size is limited to 4MB.

**To Reproduce**
1. Start Zeebe 8.2.x with default values
2. Execute the following code with a Zeebe Java Client version 8.2.x:
```
public class DeployAndStartInstance {

  private static final Logger LOG = LogManager.getLogger(DeployAndStartInstance.class);

  public static void main(String[] args) {
    try (ZeebeClient client = ZeebeClientFactory.getZeebeClient()) {
      final var modelInstance = Bpmn.createExecutableProcess("foo")
          .startEvent()
          .serviceTask()
            .zeebeJobType("foo")
          .endEvent()
          .done();

      client.newDeployResourceCommand()
          .addProcessModel(modelInstance, "foo.bpmn")
          .send()
          .join();

      final var byteArray = new byte[1024*1024*1];
      new Random().nextBytes(byteArray);
      final var message = new String(byteArray, Charset.forName("UTF-8")); 

      for (int i = 0; i < 70; i++) {
        final ProcessInstanceEvent event = client.newCreateInstanceCommand()
            .bpmnProcessId("foo")
            .latestVersion()
            .variables(Map.of("message_content", message))
            .send()
            .join();
        
        LOG.info(
            "Started instance for processDefinitionKey='{}', bpmnProcessId='{}', version='{}' with processInstanceKey='{}'",
            event.getProcessDefinitionKey(), event.getBpmnProcessId(), event.getVersion(),
            event.getProcessInstanceKey());
      }

      client.newWorker().jobType("foo").handler((jobClient, job) -> {
        jobClient.newCompleteCommand(job.getKey()).send()
          // join(); <-- This would block for the result. While this is easier-to-read code, it has limitations for parallel work.
          // Hence, the following code leverages reactive programming. This is discssed in https://blog.bernd-ruecker.com/writing-good-workers-for-camunda-cloud-61d322cad862.
          .whenComplete((result, exception) -> {
            if (exception == null) {
              LOG.info("Completed job successful with result:" + result);
            } else {
              LOG.error("Failed to complete job", exception);
            }
          });
      }).open();

      // run until System.in receives exit command
      waitUntilSystemInput("exit");
    }
  }

  private static void waitUntilSystemInput(final String exitCode) {
    try (final Scanner scanner = new Scanner(System.in)) {
      while (scanner.hasNextLine()) {
        final String nextLine = scanner.nextLine();
        if (nextLine.contains(exitCode)) {
          return;
        }
      }
    }
  }
}
```

**Observed behavior**
* The Gateway logs a `WARNING: Stream Error` exception.
* The activated jobs remain locked for a given timeout.
* The Client logs out the following:
```
Mai 16, 2023 4:06:04 PM io.grpc.internal.AbstractClientStream$TransportState inboundDataReceived
INFO: Received data on closed stream
Mai 16, 2023 4:06:04 PM io.grpc.internal.AbstractClientStream$TransportState inboundDataReceived
INFO: Received data on closed stream
Mai 16, 2023 4:06:04 PM io.grpc.internal.AbstractClientStream$TransportState inboundDataReceived
INFO: Received data on closed stream
Mai 16, 2023 4:06:04 PM io.grpc.internal.AbstractClientStream$TransportState inboundDataReceived
INFO: Received data on closed stream
Mai 16, 2023 4:06:04 PM io.grpc.internal.AbstractClientStream$TransportState inboundDataReceived
INFO: Received data on closed stream
```

**Expected behavior**
* The Gateway respects the `maxMessageSize` when sending back the activated jobs to the Client.

**Some Solution Ideas**
* When mapping the broker response to the client response, do bookkeeping on the response size to ensure the `maxMessageSize`.
* Another idea would be to double the max inbound message size in the Zeebe Java Client by default.
* Nice to have: Bring the `WARNING: Stream Error` exception into the control flow of the Gateway so that the Gateway can react to it and potentially make the jobs re-activatable again.

**Environment:**
- Zeebe Version: 8.2.3
- Configuration: Default Configuration

**Comment by korthout** [comment]
ZPA triage:
- @koevskinikola and @berkaycanbc will look into this as part of understanding what is needed for the job push topic in the gateway
- it's not likely that they will fix it, but just better understand it
- we can prioritize it once we better understand it

**Comment by megglos** [comment]
@koevskinikola @berkaycanbc once you get into the investigation, please don't hesitate to reach out to @romansmirnov if there is anything unclear

**Comment by abbasadel** [comment]
ZPA Planning:
- Putting back to the backlog until we find some time to work on it.

**Comment by megglos** [comment]
pushing back into the Inbox as this seemed to have affected another user here https://github.com/camunda/zeebe/issues/15190#issuecomment-1833766192

**Comment by shahamit** [comment]
I am facing issue #15190 in our set up but since it was marked as a duplicate of this issue I am continuing the discussion here. 
@megglos @npepinpe - 
1. is there a way to identify the payload size (through monitoring/debugging etc?) during a workflow execution so as to confirm that we are facing this issue in our setup?
2. The java test shared in the issue description above executes the workflow with 1 MB payloads. So if workflows have variable values above 1 MB, we would see errors stating `Stream closed before write could take place` in the zeebe gateway. Is my understanding correct?

**Comment by abbasadel** [comment]
@berkaycanbc, we think you are the right person to work on this. Have a look and let us know

**Comment by berkaycanbc** [comment]
@korthout Cannot backport this to 8.1 because `ZEEBE_GATEWAY_NETWORK_MAXMESSAGESIZE` setting doesn't exist there. Therefore, this issues not valid for `stable/8.1`.

**Comment by korthout** [comment]
@berkaycanbc While it was not configurable, it was set to 4MiB (see e030092aacd008ce0c3b8c7d2e0c3f7976bee401).

You could consider changing the PR slightly to use that hardcoded instead. This way we can resolve the issue on 8.1 too.

**Comment by berkaycanbc** [comment]
> @berkaycanbc While it was not configurable, it was set to 4MiB (see [e030092](https://github.com/camunda/zeebe/commit/e030092aacd008ce0c3b8c7d2e0c3f7976bee401)).
> 
> You could consider changing the PR slightly to use that hardcoded instead. This way we can resolve the issue on 8.1 too.

Ahh, alright, makes sense. I will create a PR for it as well. 👍
