### ISSUE TITLE
Failing to write to logstream during stepdown is logged as error

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#12780]
**Describe the bug**

```
ERROR 2023-05-16T00:30:04.104402170Z [resource.labels.containerName: zeebe] Unexpected error on writing CREATE command Failed to write request to logstream
```

The error is from CommandAPIHandler when it tries to write a user request to the leader's logstream. This happened while the leader is transition to follower, and the logstream has already closed. Before this error we see that Sequencer rejects the record because it is closed. 

This is a new error message introduced in https://github.com/camunda/zeebe/pull/12676. Previously this error was ignored. So we never got the error message.

[logs](https://console.cloud.google.com/errors/detail/CNy21ZD_7pnW3AE;service=zeebe;time=P7D?project=zeebe-io)

**Expected behavior**

- Reduce the log level to warn/debug
- logstream#tryWrite should return specific error code instead of -1, and use that to log more meaningful message. 
- If we can recognize that this is during the leader transition we can chose to not log the error. Instead return a PARTITION_LEADER_MISMATCH code back to the gateway so that it can retry the command with the new leader before sending an error to the client.

**Comment by megglos** [comment]
ZDP-Triage:
- mostly noise
- it's expected and shouldn't be logged as error in the particular scenario

**Comment by megglos** [comment]
ZDP-Planning:
- we will look into it before the next release
- also affects 8.2,8.1,8.0 due to a backporrt

**Comment by Zelldon** [comment]
I feel this is not 100% resolved. [We see a lot of errors messages also in the gateway](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22medic-y-2023-cw-20-d2345cc-benchmark%22%0Alabels.k8s-pod%2Fapp%3D%22camunda-platform%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fcomponent%3D%22zeebe-gateway%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22medic-y-2023-cw-20-d2345cc-benchmark%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fmanaged-by%3D%22Helm%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22zeebe-gateway%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fpart-of%3D%22camunda-platform%22;cursorTimestamp=2023-06-07T10:45:04.209515605Z?project=zeebe-io):

Example of a current medic benchmark
```
io.camunda.zeebe.gateway.cmd.BrokerErrorException: Received error from broker (INTERNAL_ERROR): Failed writing request: Failed to write request to logstream
	at io.camunda.zeebe.gateway.impl.broker.BrokerRequestManager.handleResponse(BrokerRequestManager.java:194) ~[zeebe-gateway-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequestInternal$2(BrokerRequestManager.java:143) ~[zeebe-gateway-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) [zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) [zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) [zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) [zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
"
```

[Where at this time a role change happens](https://grafana.dev.zeebe.io/d/NzsO1mUnk/zeebe-overview?orgId=1&var-DS_PROMETHEUS=Prometheus&var-cluster=All&var-namespace=medic-y-2023-cw-20-d2345cc-benchmark&var-pod=All&var-partition=All&from=1686132065352&to=1686136683285)
![role](https://github.com/camunda/zeebe/assets/2758593/66f672f3-3af8-44f0-8cb3-7d3cb5029dd5)

**Comment by deepthidevaki** [comment]
@Zelldon That is an old benchmark before the bug fix.
