### ISSUE TITLE
ERROR in Operate importer

### ISSUE THREAD

**Issue by dostalradim** [camunda/zeebe#12803]
**Describe the bug**

We have some instances of operate and zeebe clusters and everything works well. But in this single instance we have following problem with operate, it's showing some old processes in broken state but our data from these processes looks processed right. We have no idea how this could happen. Do you know what could be the origin of this error?

**Log/Stacktrace**

* logs from zeebe operate importer, errors are still repeated to log

```
---[TRUNCATED]---
2023-05-18 05:23:34.483  INFO 7 --- [           main] i.c.o.s.SchemaStartup                    : SchemaStartup finished.
2023-05-18 05:23:34.495  INFO 7 --- [           main] i.c.o.ImportModuleConfiguration          : Starting module: importer
2023-05-18 05:23:34.496  INFO 7 --- [           main] i.c.o.ArchiverModuleConfiguration        : Starting module: archiver
2023-05-18 05:23:35.238  WARN 7 --- [           main] i.c.o.e.ElasticsearchConnector           : Username and/or password for are empty. Basic authentication for elasticsearch is not used.
2023-05-18 05:23:35.269  INFO 7 --- [           main] i.c.o.w.StartupBean                      : INIT: Create users in elasticsearch if not exists ...
2023-05-18 05:23:35.333  INFO 7 --- [           main] i.c.o.w.StartupBean                      : INIT: Start operation executor...
2023-05-18 05:23:35.333  INFO 7 --- [           main] i.c.o.w.StartupBean                      : INIT: DONE
2023-05-18 05:23:35.486  INFO 7 --- [           main] i.c.o.z.ImportPositionHolder             : INIT: Start import position updater...
2023-05-18 05:23:35.492  INFO 7 --- [           main] i.c.o.z.ZeebeImporter                    : INIT: Start importing data...
2023-05-18 05:23:36.088  INFO 7 --- [           main] i.c.o.z.RecordsReaderHolder              : Starting import for partitions: [1, 2, 3]
2023-05-18 05:23:36.108  INFO 7 --- [           main] i.c.o.z.ZeebePostImporter                : INIT: Init post importers...
2023-05-18 05:23:36.118  INFO 7 --- [           main] i.c.o.a.Archiver                         : INIT: Start archiving data...
2023-05-18 05:23:36.118  INFO 7 --- [           main] i.c.o.a.Archiver                         : Starting archiver for partitions: [1, 2, 3]
2023-05-18 05:23:36.665 ERROR 7 --- [       import_1] i.c.o.z.RecordsReader                    : Exception occurred when importing data: Warning! Import batch became smaller after reread. Should not happen. Will be retried. Expected last sequence 4503599627370607, actual last sequence 4503599627370585.

io.camunda.operate.exceptions.OperateRuntimeException: Warning! Import batch became smaller after reread. Should not happen. Will be retried. Expected last sequence 4503599627370607, actual last sequence 4503599627370585.
	at io.camunda.operate.zeebeimport.ImportJob.processPossibleIndexChange(ImportJob.java:116) ~[operate-importer-8.2.5.jar!/:?]
	at io.camunda.operate.zeebeimport.ImportJob.call(ImportJob.java:78) ~[operate-importer-8.2.5.jar!/:?]
	at io.camunda.operate.zeebeimport.RecordsReader.lambda$executeJob$4(RecordsReader.java:409) ~[operate-importer-8.2.5.jar!/:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]

2023-05-18 05:23:36.668 ERROR 7 --- [       import_2] i.c.o.z.RecordsReader                    : Exception occurred when importing data: Warning! Import batch became smaller after reread. Should not happen. Will be retried. Expected last sequence 4503599627370586, actual last sequence 4503599627370564.

io.camunda.operate.exceptions.OperateRuntimeException: Warning! Import batch became smaller after reread. Should not happen. Will be retried. Expected last sequence 4503599627370586, actual last sequence 4503599627370564.
	at io.camunda.operate.zeebeimport.ImportJob.processPossibleIndexChange(ImportJob.java:116) ~[operate-importer-8.2.5.jar!/:?]
	at io.camunda.operate.zeebeimport.ImportJob.call(ImportJob.java:78) ~[operate-importer-8.2.5.jar!/:?]
	at io.camunda.operate.zeebeimport.RecordsReader.lambda$executeJob$4(RecordsReader.java:409) ~[operate-importer-8.2.5.jar!/:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]

2023-05-18 05:23:36.794 ERROR 7 --- [       import_3] i.c.o.z.RecordsReader                    : Exception occurred when importing data: Warning! Import batch became smaller after reread. Should not happen. Will be retried. Expected last sequence 6755399441055900, actual last sequence 6755399441055878.

io.camunda.operate.exceptions.OperateRuntimeException: Warning! Import batch became smaller after reread. Should not happen. Will be retried. Expected last sequence 6755399441055900, actual last sequence 6755399441055878.
	at io.camunda.operate.zeebeimport.ImportJob.processPossibleIndexChange(ImportJob.java:116) ~[operate-importer-8.2.5.jar!/:?]
	at io.camunda.operate.zeebeimport.ImportJob.call(ImportJob.java:78) ~[operate-importer-8.2.5.jar!/:?]
	at io.camunda.operate.zeebeimport.RecordsReader.lambda$executeJob$4(RecordsReader.java:409) ~[operate-importer-8.2.5.jar!/:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

</p>
</details>

**Environment:**
- K8S
- Zeebe Version: 8.2.5

**Comment by mihail-ca** [comment]
FYI @romansmirnov @sdorokhova the error message mentioned here in the logs was introduced by changes for this issue: https://github.com/camunda/operate/issues/4411 Do you have any clue what may be wrong ? Thank you.

**Comment by mihail-ca** [comment]
@dostalradim I was not able to reproduce the error, we would need more information regarding steps to reproduce, thank you.

**Comment by dostalradim** [comment]
We had 8.2.0-alpha version, which was first version installed in one of our project because we need some feature from it and the project was not too important so we risk it :). And when we upgrade to version 8.2.0 this problem appear. So we removed the indices with alpha in name through Kibana and then the operate started.

**Comment by johanwelgemoed** [comment]
To quickly weight in. I think that might be the issue. At moment, alphas are not considered upgradable. ie. cannot upgrade from an alpha to a minor. This might change in future but is not the case at moment unfortunately. I will mention this scenario to product management so that they have an additional data point when considering priority for alpha upgradability in future.

**Comment by dostalradim** [comment]
Well, thank you very much, then the issue is solved and we can close it.

**Comment by johanwelgemoed** [comment]
Closing since updating from alphas not supported. There is a larger epic in product hub to in future support this functionality
