### ISSUE TITLE
Zeebe has been running for a period of time with high CPU usage. What is the reason for this

### ISSUE THREAD

**Issue by bugbugmaker** [camunda/zeebe#13083]
"http-nio-0.0.0.0-9600-Acceptor" #41 daemon prio=5 os_prio=0 cpu=0.37ms elapsed=600903.75s tid=0x00007f379573d000 nid=0x48 runnable  [0x00007f36edbf6000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.Net.accept(java.base@17.0.4.1/Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.implAccept(java.base@17.0.4.1/Unknown Source)
	at sun.nio.ch.ServerSocketChannelImpl.accept(java.base@17.0.4.1/Unknown Source)
	at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:546)
	at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:79)
	at org.apache.tomcat.util.net.Acceptor.run(Acceptor.java:129)
	at java.lang.Thread.run(java.base@17.0.4.1/Unknown Source)

"Broker-0-zb-actors-0" #42 prio=5 os_prio=0 cpu=109476836.45ms elapsed=600903.65s tid=0x00007f37957a7510 nid=0x49 runnable  [0x00007f36edaf4000]
   java.lang.Thread.State: RUNNABLE
	at io.camunda.zeebe.logstreams.impl.log.LogStorageAppender.appendBlock(LogStorageAppender.java:143)
	at io.camunda.zeebe.logstreams.impl.log.LogStorageAppender.onWriteBufferAvailable(LogStorageAppender.java:196)
	at io.camunda.zeebe.logstreams.impl.log.LogStorageAppender$$Lambda$1574/0x000000080142c470.run(Unknown Source)
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:74)
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:42)
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:125)
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97)
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80)
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189)

"Broker-0-zb-actors-1" #43 prio=5 os_prio=0 cpu=111834708.38ms elapsed=600903.65s tid=0x00007f37957a8080 nid=0x4a runnable  [0x00007f36ed9f3000]
   java.lang.Thread.State: RUNNABLE
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:165)
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97)
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80)
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189)

"Broker-0-zb-fs-workers-0" #44 prio=5 os_prio=0 cpu=7800079.53ms elapsed=600903.65s tid=0x00007f37957aa360 nid=0x4b runnable  [0x00007f36ed8f3000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.4.1/Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@17.0.4.1/Unknown Source)
	at org.agrona.concurrent.BackoffIdleStrategy.idle(BackoffIdleStrategy.java:214)
	at io.camunda.zeebe.util.sched.ActorThread$ActorTaskRunnerIdleStrategy.onIdle(ActorThread.java:267)
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:85)
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189)

"Broker-0-zb-fs-workers-1" #45 prio=5 os_prio=0 cpu=7754551.86ms elapsed=600903.65s tid=0x00007f37957aaf30 nid=0x4c runnable  [0x00007f36ed7f2000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.4.1/Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@17.0.4.1/Unknown Source)
	at org.agrona.concurrent.BackoffIdleStrategy.idle(BackoffIdleStrategy.java:214)
	at io.camunda.zeebe.util.sched.ActorThread$ActorTaskRunnerIdleStrategy.onIdle(ActorThread.java:267)
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:85)
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189)

**Comment by megglos** [comment]
seems to be a duplicate of https://github.com/camunda/zeebe/issues/13160 , closing as we have a conversation there
