### ISSUE TITLE
May I ask what is the reason for this? The CPU occupied by Zeebe has been consistently high, and the stack information as follows

### ISSUE THREAD

**Issue by bugbugmaker** [camunda/zeebe#13160]
"http-nio-0.0.0.0-9600-Poller" #40 daemon prio=5 os_prio=0 cpu=3834.69ms elapsed=52292.66s tid=0x00007fe7a535a480 nid=0x4e runnable  [0x00007fe7152f5000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPoll.wait(java.base@17.0.4.1/Native Method)
	at sun.nio.ch.EPollSelectorImpl.doSelect(java.base@17.0.4.1/Unknown Source)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(java.base@17.0.4.1/Unknown Source)
	- locked <0x00000007013e1c58> (a sun.nio.ch.Util$2)
	- locked <0x00000007013e1c08> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(java.base@17.0.4.1/Unknown Source)
	at org.apache.tomcat.util.net.NioEndpoint$Poller.run(NioEndpoint.java:807)
	at java.lang.Thread.run(java.base@17.0.4.1/Unknown Source)

"http-nio-0.0.0.0-9600-Acceptor" #41 daemon prio=5 os_prio=0 cpu=0.42ms elapsed=52292.65s tid=0x00007fe7a535b9a0 nid=0x4f runnable  [0x00007fe7151f4000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.Net.accept(java.base@17.0.4.1/Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.implAccept(java.base@17.0.4.1/Unknown Source)
	at sun.nio.ch.ServerSocketChannelImpl.accept(java.base@17.0.4.1/Unknown Source)
	at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:546)
	at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:79)
	at org.apache.tomcat.util.net.Acceptor.run(Acceptor.java:129)
	at java.lang.Thread.run(java.base@17.0.4.1/Unknown Source)

"Broker-0-zb-actors-0" #42 prio=5 os_prio=0 cpu=43198018.36ms elapsed=52292.44s tid=0x00007fe7a531ed10 nid=0x50 runnable  [0x00007fe7150f2000]
   java.lang.Thread.State: RUNNABLE
	at io.camunda.zeebe.logstreams.impl.log.LogStorageAppender.appendBlock(LogStorageAppender.java:121)
	at io.camunda.zeebe.logstreams.impl.log.LogStorageAppender.onWriteBufferAvailable(LogStorageAppender.java:196)
	at io.camunda.zeebe.logstreams.impl.log.LogStorageAppender$$Lambda$1556/0x00000008014253e8.run(Unknown Source)
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:74)
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:42)
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:125)
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97)
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80)
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189)

"Broker-0-zb-actors-1" #43 prio=5 os_prio=0 cpu=36769234.13ms elapsed=52292.44s tid=0x00007fe7a531f880 nid=0x51 waiting on condition  [0x00007fe714ff2000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.4.1/Native Method)
	- parking to wait for  <0x00000007364b8400> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.4.1/Unknown Source)
	at java.util.concurrent.CompletableFuture$Signaller.block(java.base@17.0.4.1/Unknown Source)
	at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@17.0.4.1/Unknown Source)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@17.0.4.1/Unknown Source)
	at java.util.concurrent.CompletableFuture.waitingGet(java.base@17.0.4.1/Unknown Source)
	at java.util.concurrent.CompletableFuture.join(java.base@17.0.4.1/Unknown Source)
	at io.camunda.zeebe.broker.logstreams.LogDeletionService.delegateDeletion(LogDeletionService.java:67)
	at io.camunda.zeebe.broker.logstreams.LogDeletionService.lambda$onNewSnapshot$2(LogDeletionService.java:59)
	at io.camunda.zeebe.broker.logstreams.LogDeletionService$$Lambda$2091/0x00000008016b5758.run(Unknown Source)
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:72)
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:42)
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:125)
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97)
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80)
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189)

"Broker-0-zb-fs-workers-0" #44 prio=5 os_prio=0 cpu=700565.30ms elapsed=52292.44s tid=0x00007fe7a5321de0 nid=0x52 runnable  [0x00007fe714ef1000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.4.1/Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@17.0.4.1/Unknown Source)
	at org.agrona.concurrent.BackoffIdleStrategy.idle(BackoffIdleStrategy.java:214)
	at io.camunda.zeebe.util.sched.ActorThread$ActorTaskRunnerIdleStrategy.onIdle(ActorThread.java:267)
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:85)
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189)

"Broker-0-zb-fs-workers-1" #45 prio=5 os_prio=0 cpu=700968.45ms elapsed=52292.44s tid=0x00007fe7a53229b0 nid=0x53 runnable  [0x00007fe714df0000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.4.1/Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@17.0.4.1/Unknown Source)
	at org.agrona.concurrent.BackoffIdleStrategy.idle(BackoffIdleStrategy.java:214)
	at io.camunda.zeebe.util.sched.ActorThread$ActorTaskRunnerIdleStrategy.onIdle(ActorThread.java:267)
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:85)
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189)

"atomix-cluster-0" #46 prio=5 os_prio=0 cpu=35.80ms elapsed=52290.69s tid=0x00007fe6980ad740 nid=0x59 waiting on condition  [0x00007fe7756d8000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.4.1/Native Method)
	- parking to wait for  <0x00000007013a20f0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.4.1/Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(java.base@17.0.4.1/Unknown Source)
	at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@17.0.4.1/Unknown Source)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@17.0.4.1/Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@17.0.4.1/Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@17.0.4.1/Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@17.0.4.1/Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@17.0.4.1/Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.4.1/Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.4.1/Unknown Source)
	at java.lang.Thread.run(java.base@17.0.4.1/Unknown Source)

"netty-messaging-event-epoll-server-0" #47 prio=5 os_prio=0 cpu=8.88ms elapsed=52290.19s tid=0x00007fe698509750 nid=0x5a runnable  [0x00007fe7758da000]
   java.lang.Thread.State: RUNNABLE
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.Native.epollWait(Native.java:209)
	at io.netty.channel.epoll.Native.epollWait(Native.java:202)
	at io.netty.channel.epoll.EpollEventLoop.epollWaitNoTimerChange(EpollEventLoop.java:294)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:351)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(java.base@17.0.4.1/Unknown Source)

**Comment by bugbugmaker** [comment]
@nikku @npepinpe @falko Could you please give me some help

**Comment by bugbugmaker** [comment]
@Zelldon

**Comment by npepinpe** [comment]
The thread dump you pasted indicates all your threads are simply waiting or idling. Nothing really stands out there, to be honest. If this happens again, a thread dump would be useful if you could also check (say, via `ps` or `htop` or `top`) which thread specifically is using the CPU.

**Comment by bugbugmaker** [comment]
John
***@***.***



&nbsp;
Which threads occupy the highest CPU usage？Please refer to the attached image


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "camunda/zeebe"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月26日(星期一) 下午5:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [camunda/zeebe] May I ask what is the reason for this? The CPU occupied by Zeebe has been consistently high, and the stack information as follows (Issue #13160)





 
The thread dump you pasted indicates all your threads are simply waiting or idling. Nothing really stands out there, to be honest. If this happens again, a thread dump would be useful if you could also check (say, via ps or htop or top) which thread specifically is using the CPU.

**Comment by bugbugmaker** [comment]
@Zelldon Can you give me some advice? How to troubleshoot and solve this problem

**Comment by megglos** [comment]
Hey @bugbugmaker can you give us some more information as asked by @npepinpe ? we would this to understand what exact thread was causing the high load to help you further.

**Comment by bugbugmaker** [comment]
> 



> Hey @bugbugmaker can you give us some more information as asked by @npepinpe ? we would this to understand what exact thread was causing the high load to help you further.



> unmanagedBlock



> Hey @bugbugmaker can you give us some more information as asked by @npepinpe ? we would this to understand what exact thread was causing the high load to help you further.

There is no way to provide more now. Because Zeebe has deleted the data and restarted. The specific situation is that after running Zeebe for a period of time, the CPU usage remains high. Restarting Zeebe cannot be lowered. Only data in the data directory can be deleted to restore normal operation. By examining the zeebe stack, it was found that the logsstream module occupied 94% of the CPU. Please refer to the stack information for specific code locations

"Broker O-zb actors 1 "Id=43 cpuUsage=94.13% deltaTime=190ms time=11748017ms RUNNABLE.

**Comment by megglos** [comment]
Hey @bugbugmaker ,
we can't really narrow this down further with the provided info, if you experience this again can you please provide a thread-dump for us to analyse and feel free to reopen. Closing for now.
