### ISSUE TITLE
TimeoutException when add interceptor to zeebe gateway cluster

### ISSUE THREAD

**Issue by kimnamcham** [camunda/zeebe#13171]
**Describe the bug**

Caused by: java.util.concurrent.TimeoutException: Timeout after: 30 SECONDS

` 2023-06-19 03:58:34.085 [] [main] INFO 

       org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLogger - 

 

 Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.

 2023-06-19 03:58:35.484 [] [main] ERROR

       org.springframework.boot.SpringApplication - Application run failed

 java.lang.IllegalStateException: Failed to execute CommandLineRunner

 	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:772) [spring-boot-3.0.5.jar:3.0.5]

 	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:753) [spring-boot-3.0.5.jar:3.0.5]

 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:317) [spring-boot-3.0.5.jar:3.0.5]

 	at io.camunda.zeebe.gateway.StandaloneGateway.main(StandaloneGateway.java:85) [camunda-zeebe-8.2.7.jar:8.2.7]

 Caused by: java.util.concurrent.TimeoutException: Timeout after: 30 SECONDS

 	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.get(CompletableActorFuture.java:132) ~[zeebe-scheduler-8.2.7.jar:8.2.7]

 	at io.camunda.zeebe.scheduler.FutureUtil.join(FutureUtil.java:32) ~[zeebe-scheduler-8.2.7.jar:8.2.7]

 	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.join(CompletableActorFuture.java:203) ~[zeebe-scheduler-8.2.7.jar:8.2.7]

 	at io.camunda.zeebe.gateway.StandaloneGateway.run(StandaloneGateway.java:110) ~[camunda-zeebe-8.2.7.jar:8.2.7]

 	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:769) ~[spring-boot-3.0.5.jar:3.0.5]

 	... 3 more`

**Environment:**
- OS: using camunda zeebe docker 
- Deploy environment: k8s
- Zeebe Version: 8.2.7
- Configuration: 

`env:
            - name: ZEEBE_BROKER_NETWORK_MAXMESSAGESIZE
              value: 4MB
            - name: ZEEBE_GATEWAY_NETWORK_MINKEEPALIVEINTERVAL
              value: 2m
            - name: ZEEBE_GATEWAY_CLUSTER_CLUSTERNAME
              value: zeebe-cluster
            - name: ZEEBE_GATEWAY_CLUSTER_MEMBERID
              value: gateway
            - name: ZEEBE_GATEWAY_THREADS_MANAGEMENTTHREADS
              value: '5'
            - name: ZEEBE_STANDALONE_GATEWAY
              value: 'true'
            - name: ZEEBE_GATEWAY_CLUSTER_INITIALCONTACTPOINTS
              value: >-
                zeebe-broker-1:26511,zeebe-broker-2:26512,zeebe-broker-3:26513,zeebe-broker-4:26514,zeebe-broker-5:26515
            - name: ZEEBE_GATEWAY_CLUSTER_NETWORK_PORT
              value: '26500'
            - name: ZEEBE_GATEWAY_HOST
              valueFrom:
                configMapKeyRef:
                  name: worker-node-config
                  key: ZEEBE_GATEWAY_HOST
            - name: ZEEBE_GATEWAY_PORT
              valueFrom:
                configMapKeyRef:
                  name: worker-node-config
                  key: ZEEBE_GATEWAY_PORT
            - name: ZEEBE_GATEWAY_CLUSTER_MEMBERSHIP_FAILURETIMEOUT
              value: 10s
            - name: ZEEBE_GATEWAY_CLUSTER_MEMBERSHIP_PROBETIMEOUT
              value: 500ms
            - name: ZEEBE_GATEWAY_CLUSTER_REQUESTTIMEOUT
              value: 30s
            - name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE
              value: none
            - name: ZEEBE_GATEWAY_INTERCEPTORS_0_ID
              value: logging-interceptor
            - name: ZEEBE_GATEWAY_INTERCEPTORS_0_JARPATH
              value: >-
                interceptor/interceptor-0.0.1-SNAPSHOT-jar-with-dependencies
            - name: ZEEBE_GATEWAY_INTERCEPTORS_0_CLASSNAME
              value: com.example.interceptor.LoggingInterceptor`

**Comment by npepinpe** [comment]
Can you share the logs? From the exception above, the gateway failed to start within 30 seconds, but it's unclear why without the complete start up logs.

**Comment by korthout** [comment]
Hi @kimnamcham 👋 This seems like a usage question to me. As @npepinpe pointed out, there's some information missing to answer this.

For questions like these, it is always better to open a help request topic on the Camunda forums: [https://forum.camunda.io/](https://forum.camunda.io/). By posting on our forums, you benefit from the experience of the Camunda experts and the Camunda community.

I'm closing this issue as we aim to use the GitHub issues for development purposes only.
