### ISSUE TITLE
DEADLINE_EXCEEDED: Time out between gateway and broker: Request ProtocolRequest{id=2528, subject=command-api-1, sender=0.0.0.0:26502, payload=byte[]{length=147, hash=-1159748294}} to 0.0.0.0:26501 timed out in PT10S

### ISSUE THREAD

**Issue by help-lixin** [camunda/zeebe#13177]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
19:50:23.167 [] [pool-3-thread-1] WARN  io.camunda.zeebe.client.job.worker - Worker default failed to handle job with key 2251799813688054 of type foo, sending fail command to broker
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method) ~[?:?]
	at java.lang.Thread.sleep(Thread.java:337) ~[?:?]
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:446) ~[?:?]
	at io.camunda.zeebe.example.process.ProcessInstanceWithResultCreator.lambda$openJobWorker$0(ProcessInstanceWithResultCreator.java:102) ~[classes/:?]
	at io.camunda.zeebe.client.impl.worker.JobRunnableFactory.executeJob(JobRunnableFactory.java:44) ~[zeebe-client-java-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.client.impl.worker.JobRunnableFactory.lambda$create$0(JobRunnableFactory.java:39) ~[zeebe-client-java-8.1.0.jar:8.1.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Exception in thread "main" io.camunda.zeebe.client.api.command.ClientStatusException: Time out between gateway and broker: Request ProtocolRequest{id=2528, subject=command-api-1, sender=0.0.0.0:26502, payload=byte[]{length=147, hash=-1159748294}} to 0.0.0.0:26501 timed out in PT10S
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.transformExecutionException(ZeebeClientFutureImpl.java:93)
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:50)
	at io.camunda.zeebe.example.process.ProcessInstanceWithResultCreator.main(ProcessInstanceWithResultCreator.java:76)
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: Time out between gateway and broker: Request ProtocolRequest{id=2528, subject=command-api-1, sender=0.0.0.0:26502, payload=byte[]{length=147, hash=-1159748294}} to 0.0.0.0:26501 timed out in PT10S
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:48)
	... 1 more
Caused by: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: Time out between gateway and broker: Request ProtocolRequest{id=2528, subject=command-api-1, sender=0.0.0.0:26502, payload=byte[]{length=147, hash=-1159748294}} to 0.0.0.0:26501 timed out in PT10S
	at io.grpc.Status.asRuntimeException(Status.java:535)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:470)
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:434)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:467)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:563)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:744)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

</p>
</details>

```
/*
 * Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH under
 * one or more contributor license agreements. See the NOTICE file distributed
 * with this work for additional information regarding copyright ownership.
 * Licensed under the Zeebe Community License 1.1. You may not use this file
 * except in compliance with the Zeebe Community License 1.1.
 */
package io.camunda.zeebe.example.process;

import io.camunda.zeebe.client.ZeebeClient;
import io.camunda.zeebe.client.ZeebeClientBuilder;
import io.camunda.zeebe.client.api.response.ProcessInstanceResult;

import java.time.Duration;
import java.util.Map;
import java.util.concurrent.TimeUnit;

/**
 * Example application that connects to a cluster on Camunda Cloud, or a locally deployed cluster.
 *
 * <p>When connecting to a cluster in Camunda Cloud, this application assumes that the following
 * environment variables are set:
 *
 * <ul>
 *   <li>ZEEBE_ADDRESS
 *   <li>ZEEBE_CLIENT_ID
 *   <li>ZEEBE_CLIENT_SECRET
 *   <li>ZEEBE_AUTHORIZATION_SERVER_URL
 * </ul>
 *
 * <p><strong>Hint:</strong> When you create client credentials in Camunda Cloud you have the option
 * to download a file with above lines filled out for you.
 *
 * <p>When {@code ZEEBE_ADDRESS} is not set, it connects to a broker running on localhost with
 * default ports
 */
public class ProcessInstanceWithResultCreator {
  public static void main(final String[] args) {
      final String defaultAddress = "192.168.8.19:26500";
      final String envVarAddress = System.getenv("ZEEBE_ADDRESS");

      final ZeebeClientBuilder clientBuilder;
      if (envVarAddress != null) {
          /* Connect to Camunda Cloud Cluster, assumes that credentials are set in environment variables.
           * See JavaDoc on class level for details
           */
          clientBuilder = ZeebeClient.newClientBuilder().gatewayAddress(envVarAddress);
      } else {
          // connect to local deployment; assumes that authentication is disabled
          clientBuilder = ZeebeClient.newClientBuilder().gatewayAddress(defaultAddress).usePlaintext();
      }

      final String bpmnProcessId = "demoProcessSingleTask";

      try (final ZeebeClient client = clientBuilder.build()) {

          openJobWorker(client); // open job workers so that task are executed and process is completed
          System.out.println("Creating process instance");
          final ProcessInstanceResult processInstanceResult =
                  client
                          .newCreateInstanceCommand()
                          // 根据流程定义的key进行实例启动
                          .processDefinitionKey(2251799813685249l)
                          .withResult() // to await the completion of process execution and return result
                          .send()
                          .join();

          System.out.println(
                  "Process instance created with key: "
                          + processInstanceResult.getProcessInstanceKey()
                          + " and completed with results: "
                          + processInstanceResult.getVariables());
      }
  }

  private static void openJobWorker(final ZeebeClient client) {
      client
              .newWorker()
              .jobType("foo")
              .handler((jobClient, job) -> {
                          System.out.println(job.getBpmnProcessId());
                          System.out.println(job.getProcessInstanceKey());
                          System.out.println(job.getElementId());
                          System.out.println(job.getElementInstanceKey());

                          System.out.println("start job");
                          // *********************************************************
                          // mock bussiness task process
                          // *********************************************************
                          TimeUnit.SECONDS.sleep(10 * 60 * 1000);
                          System.out.println("end job");

                          jobClient
                                  .newCompleteCommand(job.getKey())
                                  .variables(Map.of("job", job.getKey()))
                                  .send();
                      }
              )
              .timeout(Duration.ofSeconds(30 * 10000))
              .open();
  }
}

```

**Environment:**
- OS:  mac os
- Zeebe Version: 8.2.7
- Configuration: 

<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:zeebe="http://camunda.org/schema/zeebe/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:camunda="http://camunda.org/schema/1.0/bpmn" id="Definitions_1" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Zeebe Modeler" exporterVersion="0.8.0">
  <bpmn:process id="demoProcessSingleTask" isExecutable="true">
    <bpmn:startEvent id="start" name="start">
      <bpmn:outgoing>SequenceFlow_1sz6737</bpmn:outgoing>
    </bpmn:startEvent>
    <bpmn:sequenceFlow id="SequenceFlow_1sz6737" sourceRef="start" targetRef="taskA" />
    <bpmn:sequenceFlow id="SequenceFlow_06ytcxw" sourceRef="taskA" targetRef="end" />
    <bpmn:endEvent id="end" name="end">
      <bpmn:incoming>SequenceFlow_06ytcxw</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:serviceTask id="taskA" name="task A">
      <bpmn:extensionElements>
        <zeebe:taskDefinition type="foo" />
      </bpmn:extensionElements>
      <bpmn:incoming>SequenceFlow_1sz6737</bpmn:incoming>
      <bpmn:outgoing>SequenceFlow_06ytcxw</bpmn:outgoing>
    </bpmn:serviceTask>
  </bpmn:process>
</bpmn:definitions>

**Comment by npepinpe** [comment]
Hi @help-lixin, this can happen at any point if there is a timeout between your gateway and the broker - for example, if the broker is temporarily unavailable, being restarted, etc., but after the request was already sent. So depending on your deployment, this could be "normal" (after all, network issues occur), and is only a cause for concern if this happens regularly or a lot in succession.

**Comment by megglos** [comment]
Hey @help-lixin ,

we would close this request right now as this rather seems a question. 
Best reach out in the forum, where there are more people available that could help you clarifying your observation on timeouts.
https://forum.camunda.io/

**Comment by Sindhukarre** [comment]
what would be the solution if it keeps happening frequently? @npepinpe

**Comment by JiangZih** [comment]
@help-lixin @Sindhukarre  Have you resolved this issue? What is the reason behind it?
