### ISSUE TITLE
Operate post importer stops processing incidents

### ISSUE THREAD

**Issue by zalddeve** [camunda/zeebe#13189]
**Describe the bug**

Operate stops displaying newly-created incidents in the process instance graphs and there are java.lang.NullPointerException messages in the log.

**To Reproduce**

When the post import action of Operate is delayed, and there are both CREATED and RESOLVED intents for the same incident in the post importer queue, the importer begins to throw exceptions. As a result, no further incidents will be imported from the affected partition.

<details><summary>Documents in the operate-import-position-8.3.0_alias index</summary>
<p>

```json
{
  "hits": {
    "total": {
      "value": 1,
      "relation": "eq"
    },
    "max_score": 0,
    "hits": [
      {
        "_index": "dev-operate-import-position-8.3.0_",
        "_id": "1-incident",
        "_score": 0,
        "_source": {
          "id": "1-incident",
          "aliasName": "incident",
          "partitionId": 1,
          "position": 105412288,
          "sequence": 2251799813718599,
          "postImporterPosition": 105087730,
          "indexName": "dev-zeebe-record_incident_8.2.7_2023-06-21"
        }
      }
    ]
  }
}
```

</p>
</details>

<details><summary>Documents in the operate-post-importer-queue-8.3.0_alias index</summary>
<p>

```json
{
  "hits": {
    "total": {
      "value": 2,
      "relation": "eq"
    },
    "max_score": null,
    "hits": [
      {
        "_index": "dev-operate-post-importer-queue-8.3.0_2023-06-21",
        "_id": "2251800364909849-CREATED",
        "_score": null,
        "_source": {
          "id": "2251800364909849-CREATED",
          "key": 2251800364909849,
          "actionType": "INCIDENT",
          "intent": "CREATED",
          "creationTime": "2023-06-21T10:50:32.986+0000",
          "partitionId": 1,
          "processInstanceKey": 2251800364909829,
          "position": 105412191
        },
        "sort": [
          105412191
        ]
      },
      {
        "_index": "dev-operate-post-importer-queue-8.3.0_2023-06-21",
        "_id": "2251800364909849-RESOLVED",
        "_score": null,
        "_source": {
          "id": "2251800364909849-RESOLVED",
          "key": 2251800364909849,
          "actionType": "INCIDENT",
          "intent": "RESOLVED",
          "creationTime": "2023-06-21T10:51:23.079+0000",
          "partitionId": 1,
          "processInstanceKey": 2251800364909829,
          "position": 105412288
        },
        "sort": [
          105412288
        ]
      }
    ]
  }
}
```

</p>
</details>

<details><summary>The state of the incident in the dev-operate-incident-8.3.0_alias index is "PENDING"</summary>
<p>

```json
{
  "hits": {
    "total": {
      "value": 1,
      "relation": "eq"
    },
    "max_score": 1,
    "hits": [
      {
        "_index": "dev-operate-incident-8.3.0_2023-06-21",
        "_id": "2251800364909849",
        "_score": 1,
        "_source": {
          "id": "2251800364909849",
          "key": 2251800364909849,
          "partitionId": 1,
          "errorType": "JOB_NO_RETRIES",
          "errorMessage": "Only absolute URLs are supported",
          "errorMessageHash": 1406885563,
          "state": "PENDING",
          "flowNodeId": "fd3f1659-d3f7-41f4-842b-e1a81a4de424",
          "flowNodeInstanceKey": 2251800364909840,
          "jobKey": 2251800364909844,
          "processInstanceKey": 2251800364909829,
          "creationTime": "2023-06-21T10:50:27.164+0000",
          "processDefinitionKey": 2251800364765564,
          "bpmnProcessId": "f889a8af-11df-4d6d-a027-f44d4795a97e_c7e8386f-3e28-4fd8-7f08-08da5fdc1aaf_16",
          "treePath": null
        }
      }
    ]
  }
}
```

</p>
</details>

**Expected behavior**

Execute IncidentPostImportAction without any exception and import incidents to Operate.

**Log/Stacktrace**

Logs from the Zeebe Operate pod. The errors are still repeated every two seconds.

<details><summary>Full Stacktrace</summary>
<p>

```
2023-06-22 07:02:35.816 ERROR 8 --- [   postimport_1] i.c.o.z.p.IncidentPostImportAction       : Exception occurred when performing post import for partition 1: Cannot invoke "java.util.Set.size()" because the return value of "java.util.Map.get(Object)" is null. Will be retried...

java.lang.NullPointerException: Cannot invoke "java.util.Set.size()" because the return value of "java.util.Map.get(Object)" is null
	at io.camunda.operate.zeebeimport.post.IncidentPostImportAction.updateProcessInstancesState(IncidentPostImportAction.java:347) ~[operate-importer-8.2.7.jar!/:?]
	at io.camunda.operate.zeebeimport.post.IncidentPostImportAction.processIncidents(IncidentPostImportAction.java:175) ~[operate-importer-8.2.7.jar!/:?]
	at io.camunda.operate.zeebeimport.post.IncidentPostImportAction.processPendingIncidents(IncidentPostImportAction.java:134) ~[operate-importer-8.2.7.jar!/:?]
	at io.camunda.operate.zeebeimport.post.IncidentPostImportAction.performOneRound(IncidentPostImportAction.java:502) ~[operate-importer-8.2.7.jar!/:?]
	at io.camunda.operate.zeebeimport.post.IncidentPostImportAction.run(IncidentPostImportAction.java:510) ~[operate-importer-8.2.7.jar!/:?]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.0.9.jar!/:6.0.9]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]

2023-06-22 07:02:37.899 ERROR 8 --- [   postimport_1] i.c.o.z.p.IncidentPostImportAction       : Exception occurred when performing post import for partition 1: Cannot invoke "java.util.Set.size()" because the return value of "java.util.Map.get(Object)" is null. Will be retried...

java.lang.NullPointerException: Cannot invoke "java.util.Set.size()" because the return value of "java.util.Map.get(Object)" is null
	at io.camunda.operate.zeebeimport.post.IncidentPostImportAction.updateProcessInstancesState(IncidentPostImportAction.java:347) ~[operate-importer-8.2.7.jar!/:?]
	at io.camunda.operate.zeebeimport.post.IncidentPostImportAction.processIncidents(IncidentPostImportAction.java:175) ~[operate-importer-8.2.7.jar!/:?]
	at io.camunda.operate.zeebeimport.post.IncidentPostImportAction.processPendingIncidents(IncidentPostImportAction.java:134) ~[operate-importer-8.2.7.jar!/:?]
	at io.camunda.operate.zeebeimport.post.IncidentPostImportAction.performOneRound(IncidentPostImportAction.java:502) ~[operate-importer-8.2.7.jar!/:?]
	at io.camunda.operate.zeebeimport.post.IncidentPostImportAction.run(IncidentPostImportAction.java:510) ~[operate-importer-8.2.7.jar!/:?]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.0.9.jar!/:6.0.9]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

</p>
</details>

**Environment:**
- Openshift 4.12.19 Cluster
- Zeebe Version: 8.2.7
- Operate Version: 8.2.7
- Elasticsearch Version: 8.6.2

**Comment by megglos** [comment]
Hey @zalddeve ,

thanks for reporting! The Operate team is already looking into this, see this public issue https://github.com/camunda/issues/issues/211

Will thus close this one as duplicate.

**Comment by kimnamcham** [comment]
Same issuses:


 2023-07-04 04:20:51.401 ERROR 7 --- [   postimport_1] i.c.o.z.p.IncidentPostImportAction       : Exception occurred when performing post import for partition 3: null. Will be retried...

**Comment by dddpaul** [comment]
I have a similar issue with platform 8.3.4:

```
2024-01-08 15:48:35.602 ERROR 13 --- [   postimport_1] .p.ElasticsearchIncidentPostImportAction : Exception occurred when performing post import for partition 1: Process instance is not yet imported for incident processing. Incident id: 2251799813691386, process instance id: 2251799813691361. Will be retried...

io.camunda.operate.exceptions.OperateRuntimeException: Process instance is not yet imported for incident processing. Incident id: 2251799813691386, process instance id: 2251799813691361
        at io.camunda.operate.zeebeimport.post.ElasticsearchIncidentPostImportAction.checkDataAndCollectParentTreePaths(ElasticsearchIncidentPostImportAction.java:525) ~[operate-importer-8.3.4.jar!/:8.3.4]
        at io.camunda.operate.zeebeimport.post.ElasticsearchIncidentPostImportAction.searchForInstances(ElasticsearchIncidentPostImportAction.java:471) ~[operate-importer-8.3.4.jar!/:8.3.4]
        at io.camunda.operate.zeebeimport.post.ElasticsearchIncidentPostImportAction.processPendingIncidents(ElasticsearchIncidentPostImportAction.java:139) ~[operate-importer-8.3.4.jar!/:8.3.4]
        at io.camunda.operate.zeebeimport.post.ElasticsearchIncidentPostImportAction.performOneRound(ElasticsearchIncidentPostImportAction.java:588) ~[operate-importer-8.3.4.jar!/:8.3.4]
        at io.camunda.operate.zeebeimport.post.ElasticsearchIncidentPostImportAction.run(ElasticsearchIncidentPostImportAction.java:597) [operate-importer-8.3.4.jar!/:8.3.4]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-6.0.14.jar!/:6.0.14]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
```

Can't find a way to reproduce it yet.
