### ISSUE TITLE
RollingUpdateTest#shouldBeAbleToRestartContainerWithNewVersion

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#13217]
**Summary**

Again, a flaky `RollingUpdateTest`, although this time it's a different one ;)

- How often does the test fail? twice so far
- Does it block your work? not yet
- Do we suspect that it is a real failure? no

**Failures**

Seems to be something where the partition is not healthy fast enough.

<details><summary>Example assertion failure</summary>
<pre>
org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a io.camunda.zeebe.test.RollingUpdateTest [the topology contains all the brokers] Expected all partitions to be healthy, but partition <1> of broker <1> is <UNHEALTHY> within 2 minutes.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
	at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:769)
	at io.camunda.zeebe.test.RollingUpdateTest.shouldBeAbleToRestartContainerWithNewVersion(RollingUpdateTest.java:112)
</pre>
</details>

**Logs**

https://gist.github.com/npepinpe/05cfdc9a1e45d9e6c934416d7088183c

**Comment by deepthidevaki** [comment]
Test fails because partition 1 in broker 1 is not healthy. We see the following logs:

```
2023-06-27 04:17:02.306 [] [raft-server-1-raft-partition-partition-1] ERROR
      io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - An uncaught exception occurred, transition to inactive role
java.lang.NullPointerException: configuration cannot be null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907) ~[guava-31.1-jre.jar:?]
	at io.atomix.raft.cluster.impl.RaftClusterContext.configure(RaftClusterContext.java:296) ~[zeebe-atomix-cluster-8.2.0.jar:8.2.0]
	at io.atomix.raft.cluster.impl.RaftClusterContext.reset(RaftClusterContext.java:285) ~[zeebe-atomix-cluster-8.2.0.jar:8.2.0]
	at io.atomix.raft.roles.AbstractRole.updateTermAndLeader(AbstractRole.java:125) ~[zeebe-atomix-cluster-8.2.0.jar:8.2.0]
	at io.atomix.raft.roles.InactiveRole.onConfigure(InactiveRole.java:57) ~[zeebe-atomix-cluster-8.2.0.jar:8.2.0]
	at io.atomix.raft.impl.RaftContext.lambda$registerHandlers$6(RaftContext.java:280) ~[zeebe-atomix-cluster-8.2.0.jar:8.2.0]
	at io.atomix.raft.impl.RaftContext.lambda$runOnContext$21(RaftContext.java:295) ~[zeebe-atomix-cluster-8.2.0.jar:8.2.0]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:178) [zeebe-atomix-utils-8.2.0.jar:8.2.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]


2023-06-27 04:17:59.681 [Broker-1-HealthCheckService] [Broker-1-zb-actors-1] DEBUG
      io.camunda.zeebe.broker.system - Detected 'UNHEALTHY' components. The current health status of components: [Partition-1{status=UNHEALTHY, issue=HealthIssue[message=null, throwable=null, cause=raft-partition-partition-1{status=UNHEALTHY, issue=HealthIssue[message=null, throwable=java.lang.NullPointerException: configuration cannot be null, cause=null]}]}]
```

After NPE, the partition is still active although it is marked as unhealthy.

Closing this in favor for https://github.com/camunda/zeebe/issues/4159
