### ISSUE TITLE
When the deployment of a process definition failed, clients can still start new process instances of the actually non-existing process definition

### ISSUE THREAD

**Issue by romansmirnov** [camunda/zeebe#13254]
**Describe the bug**

When the command to deploy processes failed with, for example, `EXCEEDED_BATCH_RECORD_SIZE`, any processes - that have been cached during the deployment process - are still kept in cache afterward. That way, clients can start process instances of these processes. Once a leader change happened (or the broker restarted), the Stream Process fails to replay these started process instances:

```
java.lang.RuntimeException: java.lang.IllegalStateException: Expected to find a process deployed with key '2251799813685405' but not found.
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.lambda$replayNextEvent$4(ReplayStateMachine.java:169) ~[zeebe-stream-platform-8.2.4.jar:8.2.4]
	at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:33) ~[zeebe-scheduler-8.2.4.jar:8.2.4]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) ~[zeebe-scheduler-8.2.4.jar:8.2.4]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.2.4.jar:8.2.4]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.2.4.jar:8.2.4]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) [zeebe-scheduler-8.2.4.jar:8.2.4]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.2.4.jar:8.2.4]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) [zeebe-scheduler-8.2.4.jar:8.2.4]
Caused by: java.lang.IllegalStateException: Expected to find a process deployed with key '2251799813685405' but not found.
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.getFlowElement(DbProcessState.java:288) ~[zeebe-workflow-engine-8.2.4.jar:8.2.4]
	at io.camunda.zeebe.engine.state.appliers.ProcessInstanceElementActivatingApplier.createEventScope(ProcessInstanceElementActivatingApplier.java:261) ~[zeebe-workflow-engine-8.2.4.jar:8.2.4]
	at io.camunda.zeebe.engine.state.appliers.ProcessInstanceElementActivatingApplier.applyState(ProcessInstanceElementActivatingApplier.java:51) ~[zeebe-workflow-engine-8.2.4.jar:8.2.4]
	at io.camunda.zeebe.engine.state.appliers.ProcessInstanceElementActivatingApplier.applyState(ProcessInstanceElementActivatingApplier.java:32) ~[zeebe-workflow-engine-8.2.4.jar:8.2.4]
	at io.camunda.zeebe.engine.state.appliers.EventAppliers.applyState(EventAppliers.java:302) ~[zeebe-workflow-engine-8.2.4.jar:8.2.4]
	at io.camunda.zeebe.engine.Engine.replay(Engine.java:110) ~[zeebe-workflow-engine-8.2.4.jar:8.2.4]
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.lambda$replayEvent$7(ReplayStateMachine.java:230) ~[zeebe-stream-platform-8.2.4.jar:8.2.4]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:?]
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.replayEvent(ReplayStateMachine.java:230) ~[zeebe-stream-platform-8.2.4.jar:8.2.4]
	at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:?]
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.lambda$tryToReplayBatch$5(ReplayStateMachine.java:208) ~[zeebe-stream-platform-8.2.4.jar:8.2.4]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-8.2.4.jar:8.2.4]
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.tryToReplayBatch(ReplayStateMachine.java:206) ~[zeebe-stream-platform-8.2.4.jar:8.2.4]
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.lambda$replayNextEvent$3(ReplayStateMachine.java:165) ~[zeebe-stream-platform-8.2.4.jar:8.2.4]
	at io.camunda.zeebe.scheduler.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:28) ~[zeebe-scheduler-8.2.4.jar:8.2.4]
	at io.camunda.zeebe.scheduler.retry.RecoverableRetryStrategy.run(RecoverableRetryStrategy.java:48) ~[zeebe-scheduler-8.2.4.jar:8.2.4]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.2.4.jar:8.2.4]
	... 5 more
```

Basically, when processing a deployment command the following happens

1. `DeploymentCreateProcessor#processRecord()` transforms the given resources accordingly
https://github.com/camunda/zeebe/blob/e4c88b2a20f48e764118caefa5052199e12ad15e/engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/DeploymentCreateProcessor.java#L129-L135
2. If succeeded, the engine will create timers for any timer start event
https://github.com/camunda/zeebe/blob/e4c88b2a20f48e764118caefa5052199e12ad15e/engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/DeploymentCreateProcessor.java#L137-L142
3. When executing the `#createTimerIfTimerStartEvent()` it will try to get the process definition by key:
https://github.com/camunda/zeebe/blob/e4c88b2a20f48e764118caefa5052199e12ad15e/engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/DeploymentCreateProcessor.java#L193-L203
4. Getting the process definition by key will eventually put the process definition into a map `processesByProcessIdAndVersion` for caching purposes:
https://github.com/camunda/zeebe/blob/e4c88b2a20f48e764118caefa5052199e12ad15e/engine/src/main/java/io/camunda/zeebe/engine/state/deployment/DbProcessState.java#L201-L211
5. Once `#createTimerIfTimerStartEvent()` finishes, the engine will write a follow-up event to indicate the deployment has been created
https://github.com/camunda/zeebe/blob/e4c88b2a20f48e764118caefa5052199e12ad15e/engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/DeploymentCreateProcessor.java#L146
6. Writing this follow-up event might fail with `EXCEEDED_BATCH_RECORD_SIZE`

As a consequence, the RocksDB transaction gets rolled back, meaning, the process definitions are not stored in RocksDB. But the not successful deployed process definitions are still present in the map `processesByProcessIdAndVersion`. That way, when a client starts a process by `bpmnProcessId`, the engine will get the actually non-existing process definition from the map `processesByProcessIdAndVersion` and start a process instance eventually. And as long as the leader keeps the same and Zeebe does not restart, process instances of the non-existing process definition can get started.

Additionally, the `ProcessVersionManager#versionCache` caches the latest version of a process definition. The same applies here, when the deployment fails, the cached latest version has been already increased and stays present in the cache. Basically, since `processesByProcessIdAndVersion` contains a non-existing process definition (for example, with version `12`) and the `versionCache` points to the non-existing version `12` of that process definition, the engine will return the process definition from `processesByProcessIdAndVersion`

https://github.com/camunda/zeebe/blob/e4c88b2a20f48e764118caefa5052199e12ad15e/engine/src/main/java/io/camunda/zeebe/engine/state/deployment/DbProcessState.java#L214-L231

Before `versionCache` have been introduced, the engine would get the latest version from RocksDB which would not be `12` for sure. That way, the engine ensured that it always returns a process definition that actually exists.

**To Reproduce**
1. Deploy many processes at once (containing a process with `bpmnProcessId=foo` )
2. Ensure that the deployment fails with `EXCEEDED_BATCH_RECORD_SIZE`
3. Start a process instance by `bpmnProcessId=foo`  => The process instance gets started accordingly.
4. Stop the broker
5. Start the broker

**Expected behavior**
* Whenever a deployment fails, the client cannot start any process instance of any of those process definitions.
* To be more concrete, any process definitions that get cached when processing the deployment command must be removed when the deployment failed.
* Or as an alternative, don't cache any process definitions during deployment.
* The same applies to `ProcessVersionManager#versionCache`

**What is the impact of the issue?**
* Any follower cannot replay any events of process instances belonging to a non-existing process definition. That way, the stream processor will stop replaying anything. The follower won't create any new snapshots, and so on.
* If there is a failover, the new leader will fail to replay the events when recovering from the last snapshot. It will again stop the stream processor. No snapshots are taken anymore. The back pressure goes up to 100%. The partition gets unhealthy.
* It may result in process definitions that are available on partition >= 2 but not on partition 1. For example:
  1. Deploy the first version of a process `foo` that succeeds
  2. Deploy a new version of the process `foo` that fails with `EXCEEDED_BATCH_RECORD_SIZE` (try doing multiple times)
  3. Then redeploy the first version once again (and let it succeed)
  4. => It will result in a process definition with version `x` (`x > 1`) which gets distributed to other partitions but on partition 1 this process definition won't get persisted in RocksDB.
  5. So on partition > 1, there are running process instances referencing process definition with version `x`. But these process instances cannot be opened in Operate, because the process definition was never exported and imported.
* There is no way to recover from that. Only purging the clusters resolves the issue.

**Environment:**
- Zeebe Version: 8.2.4

---

related to #5723 
related to [SUPPORT-17483](https://jira.camunda.com/browse/SUPPORT-17483)
related to #12873

**Comment by Zelldon** [comment]
**Sidenote**: this might affect also other places where we have a transient state (cached data in the state) since we never roll back such cached data on errors.

**Comment by Zelldon** [comment]
Small assessment from my side:

Right now, it is hard to detect from the engine perspective when a transaction is rolled back. 

We could better handle the exceeding batch size, of course, but even then, it might be already part of our cache.

I haven't checked the code yet. It might make sense to avoid the cache here, but I'm not sure whether this is possible.

Alternatively, we could split the caches and store it in a second cache during processing, and when we are at the end of the command processing, we can put everything in the actual one.

Similarly, we could do this on the stream platform side. We have a primary cache object and a secondary cache object which is a copy which we give as an argument to the engine. On rollback, the secondary cache is cleared on success we persist the cache in our primary cache. 

This involves a lot of copying which might be suboptimal if you have cached a lot of data but would resolve our issue in a more general fashion which we can use also for other places.

Right now, i have no other or better idea yet.

**Comment by korthout** [comment]
So far, we know the following solutions may work:
1. only cache the processes when deployment successful
  - requires reworking the logic
2. when an exception is thrown, clear cache
  - may slow down regular processing slightly as cache needs to be rebuild
  - this also happens on leader changes
3. allowing the stream processor to invalidate new cache entries similar to state transaction rollbacks
  - more involved, but likely the most elegant solution
  - will allow us to add caches more easily in the future

As a quick solution to overcome this problem fast, I suggest using option 2 for the next patch release. 

@Zelldon @romansmirnov What do you think?

**Comment by romansmirnov** [comment]
@korthout, option 2 sounds like a good approach to get it fixed quickly. I share your assessment.

**Comment by Zelldon** [comment]
Agree :+1:

**Comment by korthout** [comment]
I was thinking a bit about how this case could've happened. We have several guarantees on our persisted state (e.g. all state changes must be covered by an event on the log), including some relational consistency checks. We do not have a foreign key relation from process instance to the process definition it belongs to. 

If we had such a check, the corrupted state would've been avoided. The affected partition would've been `DEAD` but recoverable after a patch. Such a check would avoid all errors (including the unknown ones) related to process instance creation where the process definition is actually not stored in state.

Keeping track of this foreign key relation would come at the cost of performance (two additional IO operations on process instance creation: one to store the additional entry in a new column family, and one to check the foreign key relation when the instance is being created in the state). 

In the past, we've made decisions to go for safety over speed, but here we'd have to consider that decision again.

**Comment by korthout** [comment]
Closing as fixed by:
- #13256 
- #13327 
- #13280 
- #13328 

However, we should follow up with:
- https://github.com/camunda/zeebe/issues/13259
- https://github.com/camunda/zeebe/issues/13254#issuecomment-1617550522
