### ISSUE TITLE
Number of files snapshot is slowly increasing over days

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#13470]
**Describe the bug**

In medic-cw-25 benchmark, the number of files is more than 1K on all partitions.

![image](https://github.com/camunda/zeebe/assets/1997478/f8c970d9-cbc1-49b0-bc92-f7e498f6d2bc)

Throughput also went down, and snapshoting is impacting processing. See throughput drop every 15 minutes.
![image](https://github.com/camunda/zeebe/assets/1997478/3e305c76-4e3e-44d8-af1f-f20018994f30)

Snapshot size is very low, around 10 - 20 MB

Other medic benchmarks looks fine. Although there might be trend to increase it slowly. In cw-26 there is a small increase, but not significant.
![image](https://github.com/camunda/zeebe/assets/1997478/41d5cb98-e801-4219-adc3-e0bc1bede49d)

[Copy of snapshot from zeebe-0, partition 1](https://github.com/camunda/zeebe/files/12036635/snapshots.zip)

**Comment by deepthidevaki** [comment]
This cluster also have many banned instances (Thanks @remcowesterhoud for noticing it)
![image](https://github.com/camunda/zeebe/assets/1997478/3239a73f-c2cd-4db4-a480-a1b38fcce93a)

medic-cw-26 also started accumulating banned instances
![image](https://github.com/camunda/zeebe/assets/1997478/4151556a-821a-4495-923e-62915e866330)

**Comment by remcowesterhoud** [comment]
@deepthidevaki I had a quick look at the logs and noticed this error occurs a lot:

```
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.protocol.impl.record.value.job.JobRecord.getDeadline()" because "job" is null
	at io.camunda.zeebe.engine.processing.job.JobTimeOutProcessor.processRecord(JobTimeOutProcessor.java:53) ~[zeebe-workflow-engine-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:142) ~[zeebe-workflow-engine-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:347) ~[zeebe-stream-platform-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$2(ProcessingStateMachine.java:268) ~[zeebe-stream-platform-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:98) ~[zeebe-db-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:268) ~[zeebe-stream-platform-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:227) ~[zeebe-stream-platform-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:203) ~[zeebe-stream-platform-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) [zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) [zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:203) [zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]

```

I found [this PR](https://github.com/camunda/zeebe/pull/13126), which should fix it. So the issue might already be resolved, just not on the old benchmarks.

**Comment by deepthidevaki** [comment]
Thanks @remcowesterhoud 
I see several offollowing errors 
`Expected to process record 'TypedRecordImpl{metadata=RecordMetadata{recordType=COMMAND, valueType=JOB, intent=TIME_OUT}, value={"deadline":1689240218183,"worker":"benchmark-worker","retries":3,"retryBackoff":0,"recurringTime":-1,"type":"benchmark-task","customHeaders":[packed value (length=1)],"variables":"gA==","errorMessage":"","errorCode":"","bpmnProcessId":"benchmark","processDefinitionVersion":1,"processDefinitionKey":2251799813685251,"processInstanceKey":6755400279622196,"elementId":"task","elementInstanceKey":6755400279622204}}' without errors, but exception occurred with message 'null'.`

**Comment by deepthidevaki** [comment]
Also see weird error message `Node is no longer leader for partition -2147483648, tried to respond on request with id -1`

**Comment by deepthidevaki** [comment]
I will close this issue assuming #13126 fixes it. The fix should be included in medic-cw-27 benchmarks. 
Please re-open if you observe this issue again.
