### ISSUE TITLE
NullPointerException: Cannot invoke "io.camunda.zeebe.engine.state.instance.TimerInstance.getElementInstanceKey()" because "timer" is null

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/zeebe#13598]
**Describe the bug**

NPE occurred on medic benchmark CW30. In the `DueDateTimerChecker` we ran into a NPE. In this part of the code we iterate through the due date column family to see which timers we need to trigger. We get the timer instances, but this returns null.

```java
dueDateColumnFamily.whileTrue(
        (key, nil) -> {
          final DbLong dueDate = key.first();

          boolean consumed = false;
          if (dueDate.getValue() <= timestamp) {
            final var elementAndTimerKey = key.second();
            final TimerInstance timerInstance = timerInstanceColumnFamily.get(elementAndTimerKey);
            consumed = consumer.visit(timerInstance);
          }

          if (!consumed) {
            nextDueDate = dueDate.getValue();
          }
          return consumed;
        });
```

This seems to be some inconsistency in the state. How could we have a due date in the state, but don't know about the timer accompanying it?

It is interesting how the issue only occurred once. This means the due date is removed from the column family and one point, otherwise I would expect it to fail every time the due date checker runs. This is not the case, benchmark runs fine even after the error, making me believe it only happened once before the state became consistent again.

**To Reproduce**

Not clear

**Expected behavior**

We should always be able to find the timer belonging to the due date.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.engine.state.instance.TimerInstance.getElementInstanceKey()" because "timer" is null
	at io.camunda.zeebe.engine.processing.timer.DueDateTimerChecker$WriteTriggerTimerCommandVisitor.visit(DueDateTimerChecker.java:119) ~[zeebe-workflow-engine-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.engine.state.instance.DbTimerInstanceState.lambda$processTimersWithDueDateBefore$1(DbTimerInstanceState.java:98) ~[zeebe-workflow-engine-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.visit(TransactionalColumnFamily.java:397) ~[zeebe-db-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$forEachInPrefix$20(TransactionalColumnFamily.java:376) ~[zeebe-db-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ColumnFamilyContext.withPrefixKey(ColumnFamilyContext.java:112) ~[zeebe-db-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.forEachInPrefix(TransactionalColumnFamily.java:360) ~[zeebe-db-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.forEachInPrefix(TransactionalColumnFamily.java:331) ~[zeebe-db-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$whileTrue$9(TransactionalColumnFamily.java:177) ~[zeebe-db-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$ensureInOpenTransaction$19(TransactionalColumnFamily.java:314) ~[zeebe-db-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.DefaultTransactionContext.runInNewTransaction(DefaultTransactionContext.java:61) ~[zeebe-db-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.DefaultTransactionContext.runInTransaction(DefaultTransactionContext.java:33) ~[zeebe-db-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.ensureInOpenTransaction(TransactionalColumnFamily.java:313) ~[zeebe-db-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.whileTrue(TransactionalColumnFamily.java:177) ~[zeebe-db-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.engine.state.instance.DbTimerInstanceState.processTimersWithDueDateBefore(DbTimerInstanceState.java:90) ~[zeebe-workflow-engine-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.timer.DueDateTimerChecker$TriggerTimersSideEffect.apply(DueDateTimerChecker.java:101) ~[zeebe-workflow-engine-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.timer.DueDateTimerChecker$TriggerTimersSideEffect.apply(DueDateTimerChecker.java:69) ~[zeebe-workflow-engine-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.scheduled.DueDateChecker$TriggerEntitiesTask.execute(DueDateChecker.java:119) ~[zeebe-workflow-engine-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.stream.impl.ProcessingScheduleServiceImpl.lambda$toRunnable$5(ProcessingScheduleServiceImpl.java:135) ~[zeebe-stream-platform-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) ~[zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:109) [zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:205) [zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]

```

</p>
</details>

**Environment:**
- OS: SaaS
- Zeebe Version: CW30 benchmark

**Comment by oleschoenburg** [comment]
Seems likely that this is connected to #12302

**Comment by oleschoenburg** [comment]
I've collected some data:

`dueDate=1690171003116`, corresponds to 2023-07-24T03:56:43.116Z
`elementInstance=4503599630633663`
`timerKey=4503599630633664`

**Comment by oleschoenburg** [comment]
How did we get an orphaned due date?
Either we created multiple due dates for the same timer or we missed deleting the due date when the timer was removed.
Just looking at the code for this in `DbTimerInstanceState`, both should not be possible.

**Comment by oleschoenburg** [comment]
So one theory is that the checker finds a due date that really exists but by the time it looks up the timer from the state, the timer is already removed. In that case the due date should have been removed too. This is something that I still need to verify. It'd mean that this is something that we could simply ignore and that resolves itself after a restart.

**Comment by korthout** [comment]
ZPA triage:
- @oleschoenburg is actively investigating the issue as part of #12302 (ps, let us know if this is not the case)
- @korthout will continue to assist with reviews
- marking as `upcoming`

**Comment by korthout** [comment]
When this is resolved please verify whether it resolves:
- https://github.com/camunda/zeebe/issues/13619
