### ISSUE TITLE
Uncaught `ArrayIndexOutOfBoundsException` when marking instance as interrupted

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#13779]
**Describe the bug**

An `ArrayIndexOutOfBoundsException` exception was thrown and not handled, killing the StreamProcessor actor. The exception did not occur again after failover.

**To Reproduce**

Not clear. The BPMN that caused this is not known.

**Expected behavior**

Ideally no `ArrayIndexOutOfBoundsException` but if that can't be prevented, the exception should be handled at an appropriate place. 

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index 164 out of bounds for length 163
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.lambda$replayNextEvent$4(ReplayStateMachine.java:169) ~[zeebe-stream-platform-8.2.8.jar:8.2.8]
	at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:33) ~[zeebe-scheduler-8.2.8.jar:8.2.8]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) ~[zeebe-scheduler-8.2.8.jar:8.2.8]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.2.8.jar:8.2.8]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.2.8.jar:8.2.8]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) [zeebe-scheduler-8.2.8.jar:8.2.8]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.2.8.jar:8.2.8]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:203) [zeebe-scheduler-8.2.8.jar:8.2.8]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 164 out of bounds for length 163
	at java.util.ArrayList.add(Unknown Source) ~[?:?]
	at java.util.ArrayList.add(Unknown Source) ~[?:?]
	at org.camunda.bpm.model.xml.impl.type.attribute.AttributeImpl.registerIncoming(AttributeImpl.java:240) ~[camunda-xml-model-7.18.0.jar:7.18.0]
	at org.camunda.bpm.model.xml.impl.type.reference.ElementReferenceCollectionBuilderImpl.performModelBuild(ElementReferenceCollectionBuilderImpl.java:57) ~[camunda-xml-model-7.18.0.jar:7.18.0]
	at org.camunda.bpm.model.xml.impl.type.child.ChildElementCollectionBuilderImpl.performModelBuild(ChildElementCollectionBuilderImpl.java:130) ~[camunda-xml-model-7.18.0.jar:7.18.0]
	at org.camunda.bpm.model.xml.impl.type.child.SequenceBuilderImpl.performModelBuild(SequenceBuilderImpl.java:58) ~[camunda-xml-model-7.18.0.jar:7.18.0]
	at org.camunda.bpm.model.xml.impl.type.ModelElementTypeBuilderImpl.performModelBuild(ModelElementTypeBuilderImpl.java:138) ~[camunda-xml-model-7.18.0.jar:7.18.0]
	at org.camunda.bpm.model.xml.impl.ModelBuilderImpl.build(ModelBuilderImpl.java:76) ~[camunda-xml-model-7.18.0.jar:7.18.0]
	at org.camunda.bpm.model.xml.impl.ModelInstanceImpl.registerGenericType(ModelInstanceImpl.java:111) ~[camunda-xml-model-7.18.0.jar:7.18.0]
	at org.camunda.bpm.model.xml.impl.util.ModelUtil.getModelElement(ModelUtil.java:91) ~[camunda-xml-model-7.18.0.jar:7.18.0]
	at org.camunda.bpm.model.xml.impl.util.ModelUtil.getModelElement(ModelUtil.java:52) ~[camunda-xml-model-7.18.0.jar:7.18.0]
	at org.camunda.bpm.model.xml.impl.util.ModelUtil.getModelElementCollection(ModelUtil.java:179) ~[camunda-xml-model-7.18.0.jar:7.18.0]
	at io.camunda.zeebe.model.bpmn.traversal.ModelWalker.getChildElements(ModelWalker.java:92) ~[zeebe-bpmn-model-8.2.8.jar:8.2.8]
	at io.camunda.zeebe.model.bpmn.traversal.ModelWalker.walk(ModelWalker.java:74) ~[zeebe-bpmn-model-8.2.8.jar:8.2.8]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.BpmnTransformer.transformDefinitions(BpmnTransformer.java:115) ~[zeebe-workflow-engine-8.2.8.jar:8.2.8]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.updateInMemoryState(DbProcessState.java:172) ~[zeebe-workflow-engine-8.2.8.jar:8.2.8]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.lookupPersistenceStateForProcessByKey(DbProcessState.java:351) ~[zeebe-workflow-engine-8.2.8.jar:8.2.8]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.getProcessByKey(DbProcessState.java:246) ~[zeebe-workflow-engine-8.2.8.jar:8.2.8]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.getFlowElement(DbProcessState.java:285) ~[zeebe-workflow-engine-8.2.8.jar:8.2.8]
	at io.camunda.zeebe.engine.state.appliers.EventSubProcessInterruptionMarker.markInstanceIfInterrupted(EventSubProcessInterruptionMarker.java:42) ~[zeebe-workflow-engine-8.2.8.jar:8.2.8]
	at io.camunda.zeebe.engine.state.appliers.ProcessEventTriggeringApplier.applyState(ProcessEventTriggeringApplier.java:54) ~[zeebe-workflow-engine-8.2.8.jar:8.2.8]
	at io.camunda.zeebe.engine.state.appliers.ProcessEventTriggeringApplier.applyState(ProcessEventTriggeringApplier.java:20) ~[zeebe-workflow-engine-8.2.8.jar:8.2.8]
	at io.camunda.zeebe.engine.state.appliers.EventAppliers.applyState(EventAppliers.java:302) ~[zeebe-workflow-engine-8.2.8.jar:8.2.8]
	at io.camunda.zeebe.engine.Engine.replay(Engine.java:108) ~[zeebe-workflow-engine-8.2.8.jar:8.2.8]
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.lambda$replayEvent$7(ReplayStateMachine.java:230) ~[zeebe-stream-platform-8.2.8.jar:8.2.8]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:?]
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.replayEvent(ReplayStateMachine.java:230) ~[zeebe-stream-platform-8.2.8.jar:8.2.8]
	at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:?]
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.lambda$tryToReplayBatch$5(ReplayStateMachine.java:208) ~[zeebe-stream-platform-8.2.8.jar:8.2.8]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-8.2.8.jar:8.2.8]
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.tryToReplayBatch(ReplayStateMachine.java:206) ~[zeebe-stream-platform-8.2.8.jar:8.2.8]
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.lambda$replayNextEvent$3(ReplayStateMachine.java:165) ~[zeebe-stream-platform-8.2.8.jar:8.2.8]
	at io.camunda.zeebe.scheduler.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:28) ~[zeebe-scheduler-8.2.8.jar:8.2.8]
	at io.camunda.zeebe.scheduler.retry.RecoverableRetryStrategy.run(RecoverableRetryStrategy.java:48) ~[zeebe-scheduler-8.2.8.jar:8.2.8]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.2.8.jar:8.2.8]
	... 5 more
```

</p>
</details>

**Environment:**
Zeebe 8.2.8

**Comment by korthout** [comment]
This uses the same transformer as when originally deployed. So what could be different now? 🤔 This seems very strange

**Comment by korthout** [comment]
ZPA triage:
- how can a replayed event have two different results? 🤔 
- how can a process when transformed lead to different behavior between when it deployed and when that deployment is transformed when read from state (cache was empty)? 🤔 
- it looks to @korthout as if this happened for an existing process instance, which makes it even stranger that we couldn't transform
- this seems really strange, maybe this hides an ugly race condition or other bug...
- perhaps there is a buffer that is being reused incorrectly.
- we have no good idea where to start investigating this
- **if this occurs again, we'll re-evaluate the priority. Please provide as much details as possible, preferably the bpmn model that causes this**

**Comment by lev-safro** [comment]
@lenaschoenburg @korthout is this still the case? I'm concerned that for the bug with high severity there were no actions taken for a long period of time.

Was the severity setup correctly? Also, what's the likelihood of this issue?

**Comment by lenaschoenburg** [comment]
I think this might have the same root cause as https://github.com/camunda/camunda/issues/20361.
If that's correct, I guess we could lower the severity to mid.

**Comment by marcosgvieira** [comment]
### 🧭 Triage Assessment

| Field | Value |
|------|-------|
| **Work type** | BUG |
| **Severity** | ⚠️ Mid |
| **Likelihood** | ℹ️ Low |
| **Confidence** | 0.9 |

---

### 📝 Rationale

The issue describes an unhandled ArrayIndexOutOfBoundsException that killed the StreamProcessor actor in Zeebe 8.2.8. The problem did not recur after failover, and the impact was considered small by the team, with partition recovery occurring automatically. The Core Features team owns Zeebe Engine and execution, so this is in scope. Severity is MID because the impact was noticeable but not critical (no data loss, system recovered, and a workaround—failover—was effective). Likelihood is LOW as the exception was not observed again and appears to be a rare edge case. There is no evidence of duplication or that the issue is already fixed.

---

🤖 _This issue was automatically triaged by an AI-based system as part of the Core Features triage workflow._

✋ **Want a human review?**
If you believe this assessment is incorrect or needs adjustment, feel free to update the details or request a manual triage by adding the **`triage:manual`** label.
