### ISSUE TITLE
NPE on missing decision requirements id

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#13847]
**Describe the bug**

If a user deploys a DMN decision with a missing decision id (DMN definitions id), a `NullPointerException` will be thrown since the value of the `decisionRequirementsId` is `null`.

While the end result is expected, Zeebe shouldn't log an error since a failed deployment should be expected in this use case.

**To Reproduce**

1. Remove the `definitions#id` attribute from the `decision-table.dmn` in [the Zeebe unit tests](https://github.com/camunda/zeebe/blob/5e0d5accee2e9875ac9b3d87ec00dfc8f9688011/engine/src/test/resources/dmn/decision-table.dmn#L2).
2. Run the [`DeploymentDmnTest#shouldDeployDmnResource()`](https://github.com/camunda/zeebe/blob/47550bbb98853a1ff9fdf9d77061ff93436d7549/engine/src/test/java/io/camunda/zeebe/engine/processing/deployment/DeploymentDmnTest.java#L53) test.
3. The test fails with an unexpected error.

**Expected behavior**

The deployment should fail with an (expected) failure message.

**Log/Stacktrace**
```
ERROR io.camunda.zeebe.broker.process - Unexpected error while processing resource '/dmn/decision-table.dmn'
java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "value" is null
	at io.camunda.zeebe.util.StringUtil.getBytes(StringUtil.java:39) ~[classes/:?]
	at io.camunda.zeebe.util.StringUtil.getBytes(StringUtil.java:35) ~[classes/:?]
	at io.camunda.zeebe.msgpack.property.StringProperty.setValue(StringProperty.java:30) ~[classes/:?]
	at io.camunda.zeebe.protocol.impl.record.value.deployment.DecisionRequirementsMetadataRecord.setDecisionRequirementsId(DecisionRequirementsMetadataRecord.java:94) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.deployment.transform.DmnResourceTransformer.appendMetadataToDeploymentEvent(DmnResourceTransformer.java:167) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.deployment.transform.DmnResourceTransformer.lambda$transformResource$0(DmnResourceTransformer.java:77) ~[classes/:?]
	at io.camunda.zeebe.util.Either$Right.map(Either.java:355) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.deployment.transform.DmnResourceTransformer.transformResource(DmnResourceTransformer.java:75) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transformResource(DeploymentTransformer.java:125) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transform(DeploymentTransformer.java:101) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.processRecord(DeploymentCreateProcessor.java:90) ~[classes/:?]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:139) ~[classes/:?]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:352) ~[classes/:?]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$2(ProcessingStateMachine.java:269) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[classes/:?]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:269) ~[classes/:?]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:228) ~[classes/:?]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:204) ~[classes/:?]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:109) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:205) [classes/:?]
10:38:57.020 [] INFO  io.camunda.zeebe.test - Test failed, following records were exported:
10:38:57.043 [] INFO  io.camunda.zeebe.test - Compact log representation:
--------
	['C'ommand/'E'event/'R'ejection] [valueType] [intent] - #[position]->#[source record position] K[key] - [summary of value]
	P9K999 - key; #999 - record position; "ID" element/process id; @"elementid"/[P9K999] - element with ID and key
	Keys are decomposed into partition id and per partition key (e.g. 2251799813685253 -> P1K005). If single partition, the partition is omitted.
	Long IDs are shortened (e.g. 'startEvent_5d56488e-0570-416c-ba2d-36d2a3acea78' -> 'star..acea78'
--------
C DPLY CREATE - #1->-1 -1 - 
```

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
- OS: Linux; Also observed in GCP logs [here](https://console.cloud.google.com/).
- Zeebe Version: 8.2.11
- Configuration: default

**Additional context:**
1. When Zeebe parses a DMN resource on deployment, it uses the `DmnScalaDecisionEngine#parse(dmnResource)` method. 
2. The method doesn't perform a null-check on the values [here](https://github.com/camunda/zeebe/blob/b387fe1b3301881059595d9a17eef779d91489fd/dmn/src/main/java/io/camunda/zeebe/dmn/impl/ParsedDmnScalaDrg.java#L76-L81)
3. A `ParsedDmnScalaDrg` instance is immediately produced where the `decisionRequirementsId` property is set to `null`.
4. The `DmnResourceTransformer` assumes the DMN resource is valid and tries to transform the data into a `DecisionRequirementsMetadataRecord`.
5. When the `DmnResourceTransformer` tries to set the `DecisionRequirementsMetadataRecord#decisionRequirementsId` an NPE is thrown since there are no bytes on a null value.

**Comment by koevskinikola** [comment]
Individual triage:
- The impact of this bug is small since the outcome is valid (i.e. the deployment fails due to an invalid resource).
- The behavior in Zeebe is buggy since it assumes a valid DMN resource, leading to an unexpected error that triggers an investigation when detected in the logs.
- Implementation `effort` is small since we only need to add a guard clause to prevent this situation.

**Comment by korthout** [comment]
ZPA triage:
- since this issue can be tackled in the DMN engine, please crease an issue for it there @koevskinikola 
- impact in zeebe is low because the deployment is rejected, this is just an error log (unexpected error)

**Comment by koevskinikola** [comment]
Since the bug should be fixed in the DMN engine, I created https://github.com/camunda/dmn-scala/issues/224 for it there.

Therefore, I'm closing this issue.

**Comment by rodrigo-lourenco-lopes** [comment]
A similar issue happened [here](https://console.cloud.google.com/errors/detail/CMrL-KeOkKftsAE;service=zeebe;time=P7D;locations=global?inv=1&invt=Abw2Ng&project=camunda-saas-prod-lhr) in 8.6.13.
The only difference is that the evaluation is being made on a process bpmn instead of a DMN table.

`Unexpected error while processing resource 'edpo_v2.bpmn'`

```
java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "value" is null
	at io.camunda.zeebe.util.StringUtil.getBytes(StringUtil.java:39) ~[zeebe-util-8.6.13.jar:8.6.13]
	at io.camunda.zeebe.util.StringUtil.getBytes(StringUtil.java:35) ~[zeebe-util-8.6.13.jar:8.6.13]
	at io.camunda.zeebe.util.buffer.BufferUtil.wrapString(BufferUtil.java:42) ~[zeebe-util-8.6.13.jar:8.6.13]
	at io.camunda.zeebe.engine.processing.deployment.model.element.AbstractFlowElement.<init>(AbstractFlowElement.java:23) ~[zeebe-workflow-engine-8.6.13.jar:8.6.13]
	at io.camunda.zeebe.engine.processing.deployment.model.element.ExecutableCompensation.<init>(ExecutableCompensation.java:19) ~[zeebe-workflow-engine-8.6.13.jar:8.6.13]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.CatchEventTransformer.lambda$transformCompensationEventDefinition$7(CatchEventTransformer.java:242) ~[zeebe-workflow-engine-8.6.13.jar:8.6.13]
	at java.base/java.util.Optional.ifPresent(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.CatchEventTransformer.transformCompensationEventDefinition(CatchEventTransformer.java:237) ~[zeebe-workflow-engine-8.6.13.jar:8.6.13]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.CatchEventTransformer.transformEventDefinition(CatchEventTransformer.java:91) ~[zeebe-workflow-engine-8.6.13.jar:8.6.13]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.CatchEventTransformer.transform(CatchEventTransformer.java:61) ~[zeebe-workflow-engine-8.6.13.jar:8.6.13]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.CatchEventTransformer.transform(CatchEventTransformer.java:47) ~[zeebe-workflow-engine-8.6.13.jar:8.6.13]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.TransformationVisitor.visit(TransformationVisitor.java:42) ~[zeebe-workflow-engine-8.6.13.jar:8.6.13]
	at io.camunda.zeebe.model.bpmn.traversal.TypeHierarchyVisitor.visit(TypeHierarchyVisitor.java:39) ~[zeebe-bpmn-model-8.6.13.jar:8.6.13]
	at io.camunda.zeebe.model.bpmn.traversal.ModelWalker.walk(ModelWalker.java:73) ~[zeebe-bpmn-model-8.6.13.jar:8.6.13]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.BpmnTransformer.transformDefinitions(BpmnTransformer.java:118) ~[zeebe-workflow-engine-8.6.13.jar:8.6.13]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.lambda$createMetadata$3(BpmnResourceTransformer.java:86) ~[zeebe-workflow-engine-8.6.13.jar:8.6.13]
	at io.camunda.zeebe.util.Either$Right.flatMap(Either.java:417) ~[zeebe-util-8.6.13.jar:8.6.13]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.createMetadata(BpmnResourceTransformer.java:79) ~[zeebe-workflow-engine-8.6.13.jar:8.6.13]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transformResource(DeploymentTransformer.java:161) ~[zeebe-workflow-engine-8.6.13.jar:8.6.13]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transform(DeploymentTransformer.java:117) ~[zeebe-workflow-engine-8.6.13.jar:8.6.13]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.transformAndDistributeDeployment(DeploymentCreateProcessor.java:164) ~[zeebe-workflow-engine-8.6.13.jar:8.6.13]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.processNewCommand(DeploymentCreateProcessor.java:115) ~[zeebe-workflow-engine-8.6.13.jar:8.6.13]
	at io.camunda.zeebe.engine.processing.streamprocessor.DistributedTypedRecordProcessor.processRecord(DistributedTypedRecordProcessor.java:33) ~[zeebe-workflow-engine-8.6.13.jar:8.6.13]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:129) ~[zeebe-workflow-engine-8.6.13.jar:8.6.13]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:370) ~[zeebe-stream-platform-8.6.13.jar:8.6.13]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$3(ProcessingStateMachine.java:280) ~[zeebe-stream-platform-8.6.13.jar:8.6.13]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:109) ~[zeebe-db-8.6.13.jar:8.6.13]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:280) ~[zeebe-stream-platform-8.6.13.jar:8.6.13]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:238) ~[zeebe-stream-platform-8.6.13.jar:8.6.13]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:84) [zeebe-scheduler-8.6.13.jar:8.6.13]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:43) [zeebe-scheduler-8.6.13.jar:8.6.13]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:125) [zeebe-scheduler-8.6.13.jar:8.6.13]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:127) [zeebe-scheduler-8.6.13.jar:8.6.13]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:104) [zeebe-scheduler-8.6.13.jar:8.6.13]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:224) [zeebe-scheduler-8.6.13.jar:8.6.13]
```

Are the processes also parsed in the DMN engine?

**Comment by rodrigo-lourenco-lopes** [comment]
Actually, the already existing issue https://github.com/camunda/camunda/issues/14040 describes better the issue above. I will link it there, sorry for the noise 😅
