### ISSUE TITLE
Unable to create new snapshot due to 'IOException: No space left on device'

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#13955]
**Describe the bug**

Google Error Reporting reported [this error](https://console.cloud.google.com/errors/detail/CIS745nl9fy3hQE;service=zeebe;time=P7D?project=camunda-cloud-240911). It occurred at a moment when the leader was Out Of Diskspace (OOD). The broker recovered independently after receiving more disk space.

The reported error log is surrounded by many logged errors stating:

<details><summary>Failed to acquire next segment, retrying synchronously now</summary>
<p>

```
java.util.concurrent.CompletionException: io.camunda.zeebe.journal.JournalException$OutOfDiskSpace: Not enough space to allocate a new journal segment. Required: 13661604004, Available: 6651944960
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
Caused by: io.camunda.zeebe.journal.JournalException$OutOfDiskSpace: Not enough space to allocate a new journal segment. Required: 13661604004, Available: 6651944960
	at io.camunda.zeebe.journal.file.SegmentLoader.checkDiskSpace(SegmentLoader.java:237) ~[zeebe-journal-8.2.11-SNAPSHOT.jar:8.2.11-SNAPSHOT]
	at io.camunda.zeebe.journal.file.SegmentLoader.mapNewSegment(SegmentLoader.java:211) ~[zeebe-journal-8.2.11-SNAPSHOT.jar:8.2.11-SNAPSHOT]
	at io.camunda.zeebe.journal.file.SegmentLoader.createUninitializedSegment(SegmentLoader.java:90) ~[zeebe-journal-8.2.11-SNAPSHOT.jar:8.2.11-SNAPSHOT]
	at io.camunda.zeebe.journal.file.SegmentsManager.createUninitializedSegment(SegmentsManager.java:336) ~[zeebe-journal-8.2.11-SNAPSHOT.jar:8.2.11-SNAPSHOT]
	at io.camunda.zeebe.journal.file.SegmentsManager.lambda$prepareNextSegment$1(SegmentsManager.java:322) ~[zeebe-journal-8.2.11-SNAPSHOT.jar:8.2.11-SNAPSHOT]
	... 7 more
```

</p>
</details> 

It may be relevant to mention that this did not occur on a stable version but on `8.2.11-SNAPSHOT-dmn-cache-f439306`, although that does not exclude other versions from experiencing this.

**To Reproduce**

NA

**Expected behavior**

I'd expect the leader to gracefully stepdown before spamming error logs on OOD.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.io.UncheckedIOException: java.io.IOException: No space left on device
	at io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore.newSnapshot(FileBasedSnapshotStore.java:547) ~[zeebe-snapshots-8.2.11-SNAPSHOT.jar:8.2.11-SNAPSHOT]
	at io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot.persistInternal(FileBasedTransientSnapshot.java:152) ~[zeebe-snapshots-8.2.11-SNAPSHOT.jar:8.2.11-SNAPSHOT]
	at io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot.lambda$persist$3(FileBasedTransientSnapshot.java:112) ~[zeebe-snapshots-8.2.11-SNAPSHOT.jar:8.2.11-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorControl.lambda$call$0(ActorControl.java:98) ~[zeebe-scheduler-8.2.11-SNAPSHOT.jar:8.2.11-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:86) [zeebe-scheduler-8.2.11-SNAPSHOT.jar:8.2.11-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.2.11-SNAPSHOT.jar:8.2.11-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.2.11-SNAPSHOT.jar:8.2.11-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:109) [zeebe-scheduler-8.2.11-SNAPSHOT.jar:8.2.11-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.2.11-SNAPSHOT.jar:8.2.11-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:205) [zeebe-scheduler-8.2.11-SNAPSHOT.jar:8.2.11-SNAPSHOT]
Caused by: java.io.IOException: No space left on device
	at java.io.RandomAccessFile.writeBytes(Native Method) ~[?:?]
	at java.io.RandomAccessFile.write(Unknown Source) ~[?:?]
	at io.camunda.zeebe.snapshots.impl.SnapshotChecksum.persist(SnapshotChecksum.java:64) ~[zeebe-snapshots-8.2.11-SNAPSHOT.jar:8.2.11-SNAPSHOT]
	at io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore.newSnapshot(FileBasedSnapshotStore.java:544) ~[zeebe-snapshots-8.2.11-SNAPSHOT.jar:8.2.11-SNAPSHOT]
	... 9 more
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: `8.2.11-SNAPSHOT-dmn-cache-f439306`
- Configuration:

**Comment by Zelldon** [comment]
This was also logged 21 M times (at the time of writing) https://console.cloud.google.com/errors/detail/CIeksZeH5JWWhAE;time=P1D?project=zeebe-io for a benchmark which run into OOD.

**Comment by megglos** [comment]
ZDP-Triage:
- impact: log costs explode if disks are full
- effective watermarks are actually dependent on snapshot sizes
- if this happens the broker should not retry immediatly, it is triggered be replication though => we need to throttle at least the log
- happens for snapshot and segment allocation
- disk speeded needed to get increased manually
- idea: we could start replication when this error occurs, eventually the follower may recover, if the snapshot is not too big

=> would be worth investing into throttling the log to reduce the cost impact of such situations

**Comment by Zelldon** [comment]
I had a short look (timeboxed) on this:

The reported error by Nico, is reported maybe 6 times last 30 days, and is not happen repeatedly. 

The mentioned error here https://github.com/camunda/zeebe/issues/13955#issuecomment-1688044861 happens over 200 million times. 

It is happening everytime we try to append an record. The problem I see is that we try to async create the segment, then join on the future and fail. We then again try to create it again force/synchronous. Here we see `"Failed to acquire next segment, retrying synchronously now."`

We should rethrow the out of disk exception in this case. We expect it even in higher levels here https://github.com/camunda/zeebe/blob/main/atomix/cluster/src/main/java/io/atomix/raft/roles/LeaderRole.java#L496

**Comment by Zelldon** [comment]
I was able to reproduce this issue with a test. When creating the first segment and we reach out of disk, we see the following exception: `io.camunda.zeebe.journal.JournalException$OutOfDiskSpace`, but after the first creation, the segments are created async. This means the type of exception changes to: `java.util.concurrent.CompletionException: io.camunda.zeebe.journal.JournalException$OutOfDiskSpace`. This is catched in the [SegmentsManager](https://github.com/camunda/zeebe/blob/main/journal/src/main/java/io/camunda/zeebe/journal/file/SegmentsManager.java#L134), and retried synchronously. The exception will be logged with the completion exception. If this now fails again with OutOfDisk for example, we will not reset the nextSegment future. This means on next try we will join on the future again, throw the exception again, log it again, and try it again synchronously. This produces our loop.

Test to verify whether we see always OutOfDisk exception. I found the issue from above via debugging. Not sure whether it is really possible to test is reliably.

```java
   @Test
  void shouldFailWithOODForAsyncSegmentCreation() {
    // given
    journalFactory = new TestJournalFactory("test", 2, createFailingSegmentAllocator(3));
    journal = journalFactory.journal(journalFactory.segmentsManager(directory));
    journal.append(1, journalFactory.entry());
    journal.append(2, journalFactory.entry());
    journal.append(3, journalFactory.entry());
    journal.append(4, journalFactory.entry());

    // when - then
    assertThatThrownBy(() -> journal.append(5, journalFactory.entry()))
        .isInstanceOf(OutOfDiskSpace.class)
        .hasMessage("Nope, no free space.");
  }


  /**
   * Creates a segment allocator, which should fail after the given segments count has been reached.
   * Failing will be done via throwing an OutOfDiskException.
   *
   * @param failAtSegmentCount the count which should be reached, until a OOD exception is thrown.
   * @return the failing segment allocator
   */
  private SegmentAllocator createFailingSegmentAllocator(final int failAtSegmentCount) {
    final AtomicInteger segmentCount = new AtomicInteger(0);
    return (channel, segmentSize) -> {
      if (segmentCount.incrementAndGet() == failAtSegmentCount) {
        throw new OutOfDiskSpace("Nope, no free space.");
      } else {
        SegmentAllocator.fill().allocate(channel, segmentSize);
      }
    };
  }
```
