### ISSUE TITLE
Flaky io.camunda.zeebe.broker.exporter.stream.ExporterDirectorTest#shouldConfigureAllExportersProperlyOnStart 

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#14005]
**Summary**

- How often does the test fail? 1
- Does it block your work? No
- Do we suspect that it is a real failure? No

**Failures**

```
Error:  Tests run: 18, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 11.98 s <<< FAILURE! -- in io.camunda.zeebe.broker.exporter.stream.ExporterDirectorTest
Error:  io.camunda.zeebe.broker.exporter.stream.ExporterDirectorTest.shouldConfigureAllExportersProperlyOnStart -- Time elapsed: 0.394 s <<< FAILURE!
java.lang.AssertionError: 

Expecting actual not to be null
	at io.camunda.zeebe.broker.exporter.stream.ExporterDirectorTest.lambda$shouldConfigureAllExportersProperlyOnStart$8(ExporterDirectorTest.java:226)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at io.camunda.zeebe.broker.exporter.stream.ExporterDirectorTest.shouldConfigureAllExportersProperlyOnStart(ExporterDirectorTest.java:224)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

**Logs**

[Test results for unit tests.zip](https://github.com/camunda/zeebe/files/12427550/Test.results.for.unit.tests.1.zip)

**Comment by korthout** [comment]
The ExporterDirector is owned by Zeebe Distributed Platform (ZDP), so I'm removing this issue from the Zeebe Process Automation (ZPA) team's project board
