### ISSUE TITLE
`StreamProcessorTest#shouldBlockProcessingIfSchedulingBlocks` sometimes blocks forever

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#14011]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? Twice on bors, reproducible locally
- Does it block your work? No
- Do we suspect that it is a real failure? No

**Failures**

The test does not finish sometimes. Reproducible by running the test repeatedly.

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Comment by oleschoenburg** [comment]
Might only happen when all `StreamProcessorTest` are run together in a loop. When I try to run just `shouldBlockProcessingIfSchedulingBlocks` in a loop I can't reproduce the deadlock but eventually run out of memory. I suspect that `StreamPlatformExtension` leaks something which would explain the OOM and possibly the deadlock because test cases would then influence each other.

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.agrona.concurrent.ManyToManyConcurrentArrayQueue.<init>(ManyToManyConcurrentArrayQueue.java:68)
	at io.camunda.zeebe.scheduler.ActorThread.<init>(ActorThread.java:39)
	at io.camunda.zeebe.scheduler.ActorScheduler$DefaultActorThreadFactory.newThread(ActorScheduler.java:234)
	at io.camunda.zeebe.scheduler.ActorThreadGroup.<init>(ActorThreadGroup.java:44)
	at io.camunda.zeebe.scheduler.CpuThreadGroup.<init>(CpuThreadGroup.java:16)
	at io.camunda.zeebe.scheduler.ActorScheduler$ActorSchedulerBuilder.initCpuBoundActorThreadGroup(ActorScheduler.java:205)
	at io.camunda.zeebe.scheduler.ActorScheduler$ActorSchedulerBuilder.build(ActorScheduler.java:217)
	at io.camunda.zeebe.stream.impl.StreamPlatformExtension$StreamProcessorTestContext.<init>(StreamPlatformExtension.java:102)
	at io.camunda.zeebe.stream.impl.StreamPlatformExtension.lambda$lookupOrCreate$1(StreamPlatformExtension.java:50)
	at io.camunda.zeebe.stream.impl.StreamPlatformExtension$$Lambda$407/0x00007fd6b0214870.apply(Unknown Source)
	at org.junit.platform.engine.support.store.NamespacedHierarchicalStore.lambda$getOrComputeIfAbsent$5(NamespacedHierarchicalStore.java:147)
	at org.junit.platform.engine.support.store.NamespacedHierarchicalStore$$Lambda$384/0x00007fd6b020b3f8.get(Unknown Source)
	at org.junit.platform.engine.support.store.NamespacedHierarchicalStore$MemoizingSupplier.computeValue(NamespacedHierarchicalStore.java:372)
	at org.junit.platform.engine.support.store.NamespacedHierarchicalStore$MemoizingSupplier.get(NamespacedHierarchicalStore.java:361)
	at org.junit.platform.engine.support.store.NamespacedHierarchicalStore$StoredValue.evaluate(NamespacedHierarchicalStore.java:308)
	at org.junit.platform.engine.support.store.NamespacedHierarchicalStore$StoredValue.access$200(NamespacedHierarchicalStore.java:287)
	at org.junit.platform.engine.support.store.NamespacedHierarchicalStore.getOrComputeIfAbsent(NamespacedHierarchicalStore.java:149)
	at org.junit.jupiter.engine.execution.NamespaceAwareStore.lambda$getOrComputeIfAbsent$2(NamespaceAwareStore.java:57)
	at org.junit.jupiter.engine.execution.NamespaceAwareStore$$Lambda$408/0x00007fd6b0214aa0.get(Unknown Source)
	at org.junit.jupiter.engine.execution.NamespaceAwareStore.accessStore(NamespaceAwareStore.java:90)
	at org.junit.jupiter.engine.execution.NamespaceAwareStore.getOrComputeIfAbsent(NamespaceAwareStore.java:57)
	at io.camunda.zeebe.stream.impl.StreamPlatformExtension.lookupOrCreate(StreamPlatformExtension.java:50)
	at io.camunda.zeebe.stream.impl.StreamPlatformExtension.lambda$injectFields$3(StreamPlatformExtension.java:66)
	at io.camunda.zeebe.stream.impl.StreamPlatformExtension$$Lambda$406/0x00007fd6b0214240.accept(Unknown Source)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
	at io.camunda.zeebe.stream.impl.StreamPlatformExtension.injectFields(StreamPlatformExtension.java:62)
	at io.camunda.zeebe.stream.impl.StreamPlatformExtension.lambda$beforeEach$0(StreamPlatformExtension.java:39)
	at io.camunda.zeebe.stream.impl.StreamPlatformExtension$$Lambda$404/0x00007fd6b020fd90.accept(Unknown Source)
	at java.base/java.util.Collections$SingletonList.forEach(Collections.java:4968)
	at io.camunda.zeebe.stream.impl.StreamPlatformExtension.beforeEach(StreamPlatformExtension.java:39)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachCallbacks$2(TestMethodTestDescriptor.java:167)
```

**Comment by deepthidevaki** [comment]
Observed this in https://github.com/camunda/zeebe/actions/runs/6039494592

Job for Unit tests timedout after 30 minutes. The test that is not completed is `io.camunda.zeebe.stream.impl.StreamProcessorTest`. However, I don't know which test case was blocking.
