### ISSUE TITLE
Static user task assignee value treated as number (leads to an exception)

### ISSUE THREAD

**Issue by zxuanhong** [camunda/zeebe#14109]
**Describe the bug**

When the user task assignee is set to a static number value (not a FEEL expression), the activation of the user task leads to an exception.

<img width="633" alt="image" src="https://github.com/camunda/zeebe/assets/62740686/2c846f19-9129-47a0-a1a9-0d312df25c66">

Exception:
```
Expected result of the expression '1547044236679495680' to be 'STRING', but was 'NUMBER'.
```

**To Reproduce**

1. Create a model with an assignee of a user task set to a static number value, e.g. `12345567`.
2. Deploy the model.
3. Start an instance of the model.
4. Let the instance reach the user task.

**Expected behavior**

The user task is executed and the task's assignee is set to `12345567` (string value).

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
08:01:33.484 [] INFO  io.camunda.zeebe.test - Test failed, following records were exported:
08:01:33.610 [] INFO  io.camunda.zeebe.test - Compact log representation:
--------
	['C'ommand/'E'event/'R'ejection] [valueType] [intent] - #[position]->#[source record position] K[key] - [summary of value]
	P9K999 - key; #999 - record position; "ID" element/process id; @"elementid"/[P9K999] - element with ID and key
	Keys are decomposed into partition id and per partition key (e.g. 2251799813685253 -> P1K005). If single partition, the partition is omitted.
	Long IDs are shortened (e.g. 'startEvent_5d56488e-0570-416c-ba2d-36d2a3acea78' -> 'star..acea78'
--------
C DPLY     CREATE         - #01-> -1  -1 - 
E PROC     CREATED        - #02->#01 K01 - process.xml -> "process" (version:1)
E DPLY     CREATED        - #03->#01 K02 - process.xml
C CREA     CREATE         - #04-> -1  -1 - new <process "process"> (default start)  (no vars)
C PI       ACTIVATE       - #05->#04 K03 - PROCESS "process" in <process "process"[K03]>
E CREA     CREATED        - #06->#04 K04 - new <process "process"> (default start)  (no vars)
E PI       ACTIVATING     - #07->#04 K03 - PROCESS "process" in <process "process"[K03]>
E PI       ACTIVATED      - #08->#04 K03 - PROCESS "process" in <process "process"[K03]>
C PI       ACTIVATE       - #09->#04  -1 - START_EVENT "startEv..da0e8bd" in <process "process"[K03]>
E PI       ACTIVATING     - #10->#04 K05 - START_EVENT "startEv..da0e8bd" in <process "process"[K03]>
E PI       ACTIVATED      - #11->#04 K05 - START_EVENT "startEv..da0e8bd" in <process "process"[K03]>
C PI       COMPLETE       - #12->#04 K05 - START_EVENT "startEv..da0e8bd" in <process "process"[K03]>
E PI       COMPLETING     - #13->#04 K05 - START_EVENT "startEv..da0e8bd" in <process "process"[K03]>
E PI       COMPLETED      - #14->#04 K05 - START_EVENT "startEv..da0e8bd" in <process "process"[K03]>
E PI       SEQ_FLOW_TAKEN - #15->#04 K06 - SEQUENCE_FLOW "sequenc..22d1677" in <process "process"[K03]>
C PI       ACTIVATE       - #16->#04 K07 - USER_TASK "task" in <process "process"[K03]>
E PI       ACTIVATING     - #17->#04 K07 - USER_TASK "task" in <process "process"[K03]>
E INCIDENT CREATED        - #18->#04 K08 - EXTRACT_VALUE_ERROR Expected result of the expression '1234567891011121314' to be 'STRING', but was 'NUMBER'.,  @"task"[K07] in <process "process"[K03]>

-------------- Deployed Processes ----------------------
process.xml -> "process" (version:1)[K01] ------
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:ns0="http://camunda.org/schema/zeebe/1.0" exporter="Zeebe BPMN Model" exporterVersion="${project.version}" id="definitions_75c21f8c-968a-4322-a009-827562ef7cd8" xmlns:modeler="http://camunda.org/schema/modeler/1.0" modeler:executionPlatform="Camunda Cloud" modeler:executionPlatformVersion="${project.version}" targetNamespace="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL">
  <process id="process" isExecutable="true">
    <startEvent id="startEvent_61a36e5e-4c70-4f51-879b-7e626da0e8bd">
      <outgoing>sequenceFlow_acf570d9-e7c2-4b21-bbb0-abfe122d1677</outgoing>
    </startEvent>
    <userTask id="task" name="task">
      <extensionElements>
        <ns0:assignmentDefinition assignee="1234567891011121314"/>
      </extensionElements>
      <incoming>sequenceFlow_acf570d9-e7c2-4b21-bbb0-abfe122d1677</incoming>
      <outgoing>sequenceFlow_af07740c-3c8f-43ba-9dc4-fc17cd763919</outgoing>
    </userTask>
    <sequenceFlow id="sequenceFlow_acf570d9-e7c2-4b21-bbb0-abfe122d1677" sourceRef="startEvent_61a36e5e-4c70-4f51-879b-7e626da0e8bd" targetRef="task"/>
    <endEvent id="endEvent_534843ee-82a6-4517-8f36-227ccc58fb59">
      <incoming>sequenceFlow_af07740c-3c8f-43ba-9dc4-fc17cd763919</incoming>
    </endEvent>
    <sequenceFlow id="sequenceFlow_af07740c-3c8f-43ba-9dc4-fc17cd763919" sourceRef="task" targetRef="endEvent_534843ee-82a6-4517-8f36-227ccc58fb59"/>
  </process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_2efdf830-44de-4ca3-bc61-fe5370e0e2ae">
    <bpmndi:BPMNPlane bpmnElement="process" id="BPMNPlane_d580e40c-3af7-4444-9a9c-b3b39ab750ff">
      <bpmndi:BPMNShape bpmnElement="startEvent_61a36e5e-4c70-4f51-879b-7e626da0e8bd" id="BPMNShape_7f7e5e4a-d4c3-4654-acac-0c086e6008b5">
        <dc:Bounds height="36.0" width="36.0" x="100.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="task" id="BPMNShape_8854f338-096c-4ef7-aaaf-18f865708d8b">
        <dc:Bounds height="80.0" width="100.0" x="186.0" y="78.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_acf570d9-e7c2-4b21-bbb0-abfe122d1677" id="BPMNEdge_061e7ea7-c454-4b68-a8b9-a68d5189a850">
        <di:waypoint x="136.0" y="118.0"/>
        <di:waypoint x="186.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="endEvent_534843ee-82a6-4517-8f36-227ccc58fb59" id="BPMNShape_d3ae1f10-bb2c-492c-9616-61628bdddd14">
        <dc:Bounds height="36.0" width="36.0" x="336.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_af07740c-3c8f-43ba-9dc4-fc17cd763919" id="BPMNEdge_2edec7f1-95a7-4f99-9724-097f787280db">
        <di:waypoint x="286.0" y="118.0"/>
        <di:waypoint x="336.0" y="118.0"/>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>


--------------- Decomposed keys (for debugging) -----------------
 -1 <-> -1
K01 <-> 2251799813685249
K02 <-> 2251799813685250
K03 <-> 2251799813685251
K04 <-> 2251799813685252
K05 <-> 2251799813685253
K06 <-> 2251799813685254
K07 <-> 2251799813685255
K08 <-> 2251799813685256


io.camunda.zeebe.test.util.stream.StreamWrapperException: No event found matching the criteria

	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.camunda.zeebe.test.util.stream.StreamWrapper.getFirst(StreamWrapper.java:91)
	at io.camunda.zeebe.engine.processing.bpmn.activity.UserTaskTest.shouldCreateJobWithAssigneeNumberAsStringHeader(UserTaskTest.java:322)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
```

</p>
</details>

**Environment:**
- OS:  linux
- Zeebe Version:  8.2.12
- Configuration:  n/a

**Comment by korthout** [comment]
Triage:
- Valid concern, the static value should be considered to be a string even when it is a number
- Workaround is to define it as a string literal expression `= "1547044236679495680"`
- Low hanging fruit, we think it's straightforward to resolve
- If anyone is interested in working on this, please let us know so we can help out

**Comment by zxuanhong** [comment]
@korthout That shouldn't be a problem. So I will close

**Comment by korthout** [comment]
Happy to hear that @zxuanhong 

I'd still like this bug to be fixed at some point, so I'll reopen it. It would be a great issue for any new onboarding team members to get familiar with the FEEL expression vs static expressions concepts.

**Comment by tmetzke** [comment]
Scope clarification:

* This only happens for number values (every other static value is treated as a string already).
* This only happens for the assignee attribute (the other user task fields `candidateGroups`, `candidateUsers`, `dueDate`, and `followUpDate` require specific input that is also validated and don't allow plain static number values).
