### ISSUE TITLE
Unexpected error in resolving last processed position.

### ISSUE THREAD

**Issue by rodrigo-lourenco-lopes** [camunda/zeebe#14251]
**Describe the bug**

Relates to: https://github.com/camunda/zeebe/issues/9949

Snapshot director is unable to retrieve the last processed position because the stream processor is closed and in the [reported error cases](https://console.cloud.google.com/logs/query%3Bquery=error_group%2528%22CLCz9Zv8-tiPnwE%22%2529%0AlogName:%22stdout%22%0Aresource.type=%22k8s_container%22%0Aresource.labels.project_id=%22camunda-saas-int-chaos%22%0Aresource.labels.namespace_name=%2233455ed8-641f-490c-9419-58824063ace2-zeebe%22%0Aresource.labels.container_name=%22zeebe%22%0Aresource.labels.pod_name=%22zeebe-0%22%0Aresource.labels.cluster_name=%22worker-chaos-1%22%0Aresource.labels.location=%22europe-west1%22%3BpinnedLogId=2023-09-08T11:08:17.500673340Z/sllxgukn2imybw7u%3BcursorTimestamp=2023-09-08T11:08:17.500673340Z%3BstartTime=2023-09-08T10:38:47.500Z%3BendTime=2023-09-08T11:38:47.500Z?project=camunda-saas-int-chaos) there was a version mismatch.

[Error group.](https://console.cloud.google.com/logs/query%3Bquery=error_group%2528%22CLCz9Zv8-tiPnwE%22%2529%0AlogName:%22stdout%22%0Aresource.type=%22k8s_container%22%0Aresource.labels.project_id=%22camunda-saas-int-chaos%22%0Aresource.labels.namespace_name=%2233455ed8-641f-490c-9419-58824063ace2-zeebe%22%0Aresource.labels.container_name=%22zeebe%22%0Aresource.labels.pod_name=%22zeebe-0%22%0Aresource.labels.cluster_name=%22worker-chaos-1%22%0Aresource.labels.location=%22europe-west1%22%3BpinnedLogId=2023-09-08T11:08:17.500673340Z/sllxgukn2imybw7u%3BcursorTimestamp=2023-09-08T11:08:17.500673340Z%3BstartTime=2023-09-08T10:38:47.500Z%3BendTime=2023-09-08T11:38:47.500Z?project=camunda-saas-int-chaos)

**To Reproduce**

As soon as the stream processor is closed the snapshot director will close.

**Expected behavior**

If we detect that the stream processor needs to be closed then we also should close the partition a related services.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.RuntimeException: Actor is closed
	at io.camunda.zeebe.scheduler.ActorJob.failFuture(ActorJob.java:170) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.scheduler.ClosedQueue.offer(ClosedQueue.java:84) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.scheduler.ClosedQueue.offer(ClosedQueue.java:15) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.scheduler.ActorTask.submit(ActorTask.java:99) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.scheduler.ActorControl.call(ActorControl.java:108) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.streamprocessor.StreamProcessor.getLastProcessedPositionAsync(StreamProcessor.java:418) ~[zeebe-workflow-engine-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.broker.system.partitions.impl.AsyncSnapshotDirector.prepareTakingSnapshot(AsyncSnapshotDirector.java:230) ~[zeebe-broker-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.broker.system.partitions.impl.AsyncSnapshotDirector.scheduleSnapshotOnRate(AsyncSnapshotDirector.java:191) ~[zeebe-broker-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.1.0.jar:8.1.0]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.1.0.jar:8.1.0]```

</p>
</details>

**Environment:**
- OS: <!-- [e.g. Linux] -->
- Zeebe Version: 8.1.0 and 8.3.0 snapshots
- Configuration: <!-- [e.g. exporters etc.] -->

**Comment by megglos** [comment]
ZDP-Triage:
- mostly noise when stream processor is already unhealthy
- would require to react on health changes to also shutdown the snapshot director
- putting as later for now as it is noise

**Comment by nicpuppa** [comment]
Happened again a prod cluster zeebe:8.2.12.

Logs [here](https://drive.google.com/drive/folders/1twYLqDzMQK4-M4AwSsR5_x2eZvqru3e6)
