### ISSUE TITLE
Cancel command fails because process is null (NPE)

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#14366]
**Describe the bug**

Error group: https://console.cloud.google.com/errors/detail/CJLK28eniZi1JA;service=zeebe;time=P7D?project=camunda-cloud-240911 (occurred 12 times yesterday on alpha6)

The cancelation of a process fails because the process model can't be found or is not available and the processing then fails with a NPE.

**To Reproduce**

Cancel a process I guess? I'm not 100% sure how this could happen in the log we also don't see the reference key, unfortunately. 

I tried with zbctl to cancel negative or non-existing but it didn't worked

```
$ zbctl cancel instance "-1"
Error: unknown shorthand flag: '1' in -1
$ zbctl cancel instance "1" --insecure
Error: rpc error: code = Unavailable desc = Expected to execute command on partition 0, but either it does not exist, or the gateway is not yet aware of it
```

For me it looks like it has to be a real key otherwise it will not be forwarded from the gateway to the right partition and written to the log.
🤷🏼 

I tried to reproduce this on SaaS:

1. Created a cluster with alpha6
2. Deployed a simple model with a user task
3. Created an instance
4. Canceled the instance in operate
5. Cancelation was successful

Not sure how to reproduce this, but I think this is clearly a regression.

**Expected behavior**

We can cancel a process instance without issues.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
<pre>
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.engine.state.deployment.DeployedProcess.getKey()" because "process" is null
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnBufferedMessageStartEventBehavior.findNextMessageToCorrelate(BpmnBufferedMessageStartEventBehavior.java:95) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnBufferedMessageStartEventBehavior.correlateNextBufferedMessage(BpmnBufferedMessageStartEventBehavior.java:76) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnBufferedMessageStartEventBehavior.correlateMessage(BpmnBufferedMessageStartEventBehavior.java:66) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.lambda$getPostTransitionAction$10(ProcessProcessor.java:212) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.lambda$getPostTransitionAction$11(ProcessProcessor.java:210) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:381) ~[zeebe-util-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.transitionTo(ProcessProcessor.java:182) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.onChildTerminated(ProcessProcessor.java:167) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.onChildTerminated(ProcessProcessor.java:27) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.lambda$onElementTerminated$5(BpmnStateTransitionBehavior.java:424) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.invokeElementContainerIfPresent(BpmnStateTransitionBehavior.java:474) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.onElementTerminated(BpmnStateTransitionBehavior.java:419) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.task.JobWorkerTaskProcessor.lambda$onTerminate$10(JobWorkerTaskProcessor.java:97) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at java.util.Optional.ifPresentOrElse(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.bpmn.task.JobWorkerTaskProcessor.onTerminate(JobWorkerTaskProcessor.java:86) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.task.JobWorkerTaskProcessor.onTerminate(JobWorkerTaskProcessor.java:25) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processEvent(BpmnStreamProcessor.java:153) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.lambda$processRecord$0(BpmnStreamProcessor.java:92) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:381) ~[zeebe-util-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processRecord(BpmnStreamProcessor.java:89) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:353) ~[zeebe-stream-platform-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$2(ProcessingStateMachine.java:269) ~[zeebe-stream-platform-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:98) ~[zeebe-db-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:269) ~[zeebe-stream-platform-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:228) ~[zeebe-stream-platform-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:204) ~[zeebe-stream-platform-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:109) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:204) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
"
</pre>
</details>

**Environment:**
- OS: 
- Zeebe Version: 8.3.0-alpha6
- Configuration:

**Comment by Zelldon** [comment]
I put the severity to high since I think we should take a look asap since it seems to be a regression due to our latest changes. I was not putting it as critical since I was not able to reproduce it easily, so there might be some weird circumstances that this happens not sure yet.

**Comment by nicpuppa** [comment]
This error seems to be related to this method `processState.getLatestProcessVersionByProcessId()`. This method is somehow implicated also in those bugs #14309 and #14055

**Comment by Zelldon** [comment]
@nicpuppa because of the stacktrace see above and the related log

```
ERROR 2023-09-19T11:42:39.114714745Z [resource.labels.containerName: zeebe] Expected to process record 'TypedRecordImpl{metadata=RecordMetadata{recordType=COMMAND, valueType=PROCESS_INSTANCE, intent=CANCEL, authorization=UNKNOWN}, value={"bpmnElementType":"UNSPECIFIED","elementId":"","bpmnProcessId":"","version":-1,"processDefinitionKey":-1,"processInstanceKey":-1,"flowScopeKey":-1,"bpmnEventType":"UNSPECIFIED","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1}}' without errors, but exception occurred with message 'Cannot invoke "io.camunda.zeebe.engine.state.deployment.DeployedProcess.getKey()" because "process" is null'.
  {
    "insertId": "0d4cq88vzwi3t76q",
    "jsonPayload": {
      "serviceContext": {
        "version": "8.3.0-alpha6",
        "service": "zeebe"
      },
      "message": "Expected to process record 'TypedRecordImpl{metadata=RecordMetadata{recordType=COMMAND, valueType=PROCESS_INSTANCE, intent=CANCEL, authorization=UNKNOWN}, value={\"bpmnElementType\":\"UNSPECIFIED\",\"elementId\":\"\",\"bpmnProcessId\":\"\",\"version\":-1,\"processDefinitionKey\":-1,\"processInstanceKey\":-1,\"flowScopeKey\":-1,\"bpmnEventType\":\"UNSPECIFIED\",\"parentProcessInstanceKey\":-1,\"parentElementInstanceKey\":-1}}' without errors, but exception occurred with message 'Cannot invoke \"io.camunda.zeebe.engine.state.deployment.DeployedProcess.getKey()\" because \"process\" is null'.",
      "@type": "type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent",
      "exception": "java.lang.NullPointerException: Cannot invoke \"io.camunda.zeebe.engine.state.deployment.DeployedProcess.getKey()\" because \"process\" is null\n\tat io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnBufferedMessageStartEventBehavior.findNextMessageToCorrelate(BpmnBufferedMessageStartEventBehavior.java:95) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]\n\tat io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnBufferedMessageStartEventBehavior.correlateNextBufferedMessage(BpmnBufferedMessageStartEventBehavior.java:76) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]\n\tat io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnBufferedMessageStartEventBehavior.correlateMessage(BpmnBufferedMessageStartEventBehavior.java:66) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]\n\tat io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.lambda$getPostTransitionAction$10(ProcessProcessor.java:212) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]\n\tat java.util.Optional.ifPresent(Unknown Source) ~[?:?]\n\tat io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.lambda$getPostTransitionAction$11(ProcessProcessor.java:210) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]\n\tat io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:381) ~[zeebe-util-8.3.0-alpha6.jar:8.3.0-alpha6]\n\tat io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.transitionTo(ProcessProcessor.java:182) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]\n\tat io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.onChildTerminated(ProcessProcessor.java:167) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]\n\tat io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.onChildTerminated(ProcessProcessor.java:27) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]\n\tat io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.lambda$onElementTerminated$5(BpmnStateTransitionBehavior.java:424) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]\n\tat io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.invokeElementContainerIfPresent(BpmnStateTransitionBehavior.java:474) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]\n\tat io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.onElementTerminated(BpmnStateTransitionBehavior.java:419) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]\n\tat io.camunda.zeebe.engine.processing.bpmn.task.JobWorkerTaskProcessor.lambda$onTerminate$10(JobWorkerTaskProcessor.java:97) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]\n\tat java.util.Optional.ifPresentOrElse(Unknown Source) ~[?:?]\n\tat io.camunda.zeebe.engine.processing.bpmn.task.JobWorkerTaskProcessor.onTerminate(JobWorkerTaskProcessor.java:86) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]\n\tat io.camunda.zeebe.engine.processing.bpmn.task.JobWorkerTaskProcessor.onTerminate(JobWorkerTaskProcessor.java:25) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]\n\tat io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processEvent(BpmnStreamProcessor.java:153) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]\n\tat io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.lambda$processRecord$0(BpmnStreamProcessor.java:92) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]\n\tat io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:381) ~[zeebe-util-8.3.0-alpha6.jar:8.3.0-alpha6]\n\tat io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processRecord(BpmnStreamProcessor.java:89) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]\n\tat io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]\n\tat io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:353) ~[zeebe-stream-platform-8.3.0-alpha6.jar:8.3.0-alpha6]\n\tat io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$2(ProcessingStateMachine.java:269) ~[zeebe-stream-platform-8.3.0-alpha6.jar:8.3.0-alpha6]\n\tat io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:98) ~[zeebe-db-8.3.0-alpha6.jar:8.3.0-alpha6]\n\tat io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:269) ~[zeebe-stream-platform-8.3.0-alpha6.jar:8.3.0-alpha6]\n\tat io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:228) ~[zeebe-stream-platform-8.3.0-alpha6.jar:8.3.0-alpha6]\n\tat io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:204) ~[zeebe-stream-platform-8.3.0-alpha6.jar:8.3.0-alpha6]\n\tat io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]\n\tat io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]\n\tat io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]\n\tat io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:109) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]\n\tat io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]\n\tat io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:204) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]\n",
      "context": {
        "threadName": "zb-actors-1",
        "loggerName": "io.camunda.zeebe.broker.process",
        "threadId": 16,
        "partitionId": "2",
        "threadPriority": 5,
        "actor-name": "StreamProcessor-2",
        "actor-scheduler": "Broker-2"
      }
    },
    "resource": {
      "type": "k8s_container",
      "labels": {
        "container_name": "zeebe",
        "pod_name": "zeebe-2",
        "location": "australia-southeast1",
        "namespace_name": "7832669d-388f-4728-8e2d-d4426c350cd4-zeebe",
        "cluster_name": "prod-worker-4",
        "project_id": "camunda-cloud-240911"
      }
    },
    "timestamp": "2023-09-19T11:42:39.114714745Z",
    "severity": "ERROR",
    "labels": {
      "k8s-pod/app_kubernetes_io/app": "zeebe",
      "k8s-pod/controller-revision-hash": "zeebe-5549d9794b",
      "k8s-pod/app_kubernetes_io/component": "gateway",
      "compute.googleapis.com/resource_name": "gke-prod-worker-4-spot-v1-fdaca0c3-n1r2",
      "k8s-pod/cloud_camunda_io/channel": "Alpha",
      "k8s-pod/cloud_camunda_io/salesPlan": "Trial_with_Low_Hardware",
      "k8s-pod/cloud_camunda_io/clusterPlan": "G3_Trial",
      "k8s-pod/statefulset_kubernetes_io/pod-name": "zeebe-2",
      "k8s-pod/cloud_camunda_io/orgId": "5b5e6afa_7ba5_455e_9aa1_4b2ad66d5cd2",
      "k8s-pod/cloud_camunda_io/generation": "Camunda_Platform_8_3_0_alpha6",
      "k8s-pod/cloud_camunda_io/internalSalesPlan": "false",
      "k8s-pod/cloud_camunda_io/clusterPlanType": "Trial_Cluster",
      "k8s-pod/cloud_camunda_io/salesPlanType": "trial"
    },
    "logName": "projects/camunda-cloud-240911/logs/stdout",
    "sourceLocation": {
      "file": "Engine.java",
      "line": "170",
      "function": "handleUnexpectedError"
    },
    "receiveTimestamp": "2023-09-19T11:42:44.167981019Z"
  }
```

**Comment by nicpuppa** [comment]
@Zelldon thank you for clarifying

**Comment by remcowesterhoud** [comment]
I wonder if this could have to do with deleting a process definition. I checked the related cluster and saw that one of the definition was deleted. The process version management was modified for this topic, so that aligns with the `processState.getLatestProcessVersionByProcessId()` being involved.

I tried reproducing it this morning but had no luck.

**Comment by nicpuppa** [comment]
@remcowesterhoud I noticed that the record value is a bit strange `value={"bpmnElementType":"UNSPECIFIED","elementId":"","bpmnProcessId":"","version":-1,"processDefinitionKey":-1,"processInstanceKey":-1,"flowScopeKey":-1,"bpmnEventType":"UNSPECIFIED","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1}`. Seems like an empty record

**Comment by remcowesterhoud** [comment]
> @remcowesterhoud I noticed that the record value is a bit strange
> 
> ```
> value{"bpmnElementType":"UNSPECIFIED","elementId":"","bpmnProcessId":"","version":-1,"processDefinitionKey":-1,"processInstanceKey":-1,"flowScopeKey":-1,"bpmnEventType":"UNSPECIFIED","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1}
> ```
> 
> Seems like an empty record

Yea I noticed that, but this is a red herring. It appears when cancelling a process instance we set process instance key as the command key. All the details of the record are left empty.

**Comment by korthout** [comment]
ZPA Triage:
- should be investigated before the 8.3 release
- shares a potential root cause with #14309
