### ISSUE TITLE
 NullPointerException: Cannot invoke `PartitionContext.getComponentHealthMonitor()` because `this.context` is null 

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#14458]
**Describe the bug**

NPE while the healthcheck service was trying to query the health of a Zeebe partition during shutdown.

**To Reproduce**

Occurs sometimes during shutdown.

**Expected behavior**

No NPE.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
 java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.broker.system.partitions.PartitionContext.getComponentHealthMonitor()" because "this.context" is null
	at io.camunda.zeebe.broker.system.partitions.ZeebePartition.getHealthReport(ZeebePartition.java:410) ~[zeebe-broker-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.health.CriticalComponentsHealthMonitor.getHealth(CriticalComponentsHealthMonitor.java:152) ~[zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.health.CriticalComponentsHealthMonitor.lambda$updateHealth$5(CriticalComponentsHealthMonitor.java:105) ~[zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at java.util.HashMap$KeySet.forEach(Unknown Source) ~[?:?]
	at io.camunda.zeebe.scheduler.health.CriticalComponentsHealthMonitor.updateHealth(CriticalComponentsHealthMonitor.java:105) ~[zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) ~[zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT] 
```

</p>
</details>

**Environment:**
- Zeebe Version: zeebe:8.3.0-SNAPSHOT-cw-39-706f1b0
- Error group: https://console.cloud.google.com/errors/detail/CKyTiNSSr_HjHw;service=zeebe;time=P7D?project=camunda-cloud-240911

**Comment by megglos** [comment]
ZDP-Triage:
- noise during shutdown
- easy fix though - e.g. check for null and return unhealthy in this case

**Comment by Aniket-kumar404** [comment]
I would like to work on this issue.

**Comment by rodrigo-lourenco-lopes** [comment]
This issue happened again in the medic benchmark: [zeebe:medic-y-2023-cw-38-be24882-benchmark](https://console.cloud.google.com/errors/detail/CKyTiNSSr_HjHw;service=zeebe;version=medic-y-2023-cw-38-be24882-benchmark;time=P7D?project=zeebe-io)

Error group: https://console.cloud.google.com/errors/detail/CKyTiNSSr_HjHw%3Bservice=zeebe%3Btime=P7D?project=zeebe-io
