### ISSUE TITLE
Enhance unrecoverable exceptions with more context

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#14472]
**Description**

Right now unrecoverable exceptions [in the ProcessingStateMachine are just rethrown](https://github.com/camunda/zeebe/blob/main/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java#L283), that is especially important for ZeebeDBInconsitencyExceptions, which happened [recently in an incident ](https://app.slack.com/client/T0PM0P1SA/C05TG4DLD5H).

The problem here is that we lack some context:

```
io.camunda.zeebe.db.ZeebeDbInconsistentException: Key DbCompositeKey{first=DbLong{2251799813994826}, second=optimus_entity_created_message} in ColumnFamily PROCESS_SUBSCRIPTION_BY_KEY already exists
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.assertKeyDoesNotExist(TransactionalColumnFamily.java:286) ~[zeebe-db-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$insert$0(TransactionalColumnFamily.java:80) ~[zeebe-db-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$ensureInOpenTransaction$19(TransactionalColumnFamily.java:314) ~[zeebe-db-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.DefaultTransactionContext.runInTransaction(DefaultTransactionContext.java:31) ~[zeebe-db-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.ensureInOpenTransaction(TransactionalColumnFamily.java:313) ~[zeebe-db-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.insert(TransactionalColumnFamily.java:75) ~[zeebe-db-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.state.message.DbProcessMessageSubscriptionState.put(DbProcessMessageSubscriptionState.java:82) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.state.appliers.ProcessMessageSubscriptionCreatingApplier.applyState(ProcessMessageSubscriptionCreatingApplier.java:28) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.state.appliers.ProcessMessageSubscriptionCreatingApplier.applyState(ProcessMessageSubscriptionCreatingApplier.java:15) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.state.appliers.EventAppliers.applyState(EventAppliers.java:327) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.streamprocessor.writers.ResultBuilderBackedEventApplyingStateWriter.appendFollowUpEvent(ResultBuilderBackedEventApplyingStateWriter.java:56) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.streamprocessor.writers.ResultBuilderBackedEventApplyingStateWriter.appendFollowUpEvent(ResultBuilderBackedEventApplyingStateWriter.java:42) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.common.CatchEventBehavior.subscribeToMessageEvent(CatchEventBehavior.java:271) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.common.CatchEventBehavior.lambda$subscribeToMessageEvents$7(CatchEventBehavior.java:246) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.common.CatchEventBehavior.subscribeToMessageEvents(CatchEventBehavior.java:246) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.common.CatchEventBehavior.lambda$subscribeToEvents$4(CatchEventBehavior.java:154) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.util.Either$Right.ifRight(Either.java:371) ~[zeebe-util-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.common.CatchEventBehavior.subscribeToEvents(CatchEventBehavior.java:152) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnEventSubscriptionBehavior.subscribeToEvents(BpmnEventSubscriptionBehavior.java:48) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.container.CallActivityProcessor.lambda$onActivate$0(CallActivityProcessor.java:64) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.util.Either$Right.flatMap(Either.java:366) ~[zeebe-util-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.container.CallActivityProcessor.onActivate(CallActivityProcessor.java:64) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.container.CallActivityProcessor.onActivate(CallActivityProcessor.java:29) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.lambda$processEvent$2(BpmnStreamProcessor.java:144) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:381) ~[zeebe-util-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processEvent(BpmnStreamProcessor.java:143) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.lambda$processRecord$0(BpmnStreamProcessor.java:92) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:381) ~[zeebe-util-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processRecord(BpmnStreamProcessor.java:89) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.incident.ResolveIncidentProcessor.lambda$attemptToContinueProcessProcessing$0(ResolveIncidentProcessor.java:105) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:381) ~[zeebe-util-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.incident.ResolveIncidentProcessor.attemptToContinueProcessProcessing(ResolveIncidentProcessor.java:103) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.processing.incident.ResolveIncidentProcessor.processRecord(ResolveIncidentProcessor.java:81) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[zeebe-workflow-engine-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:353) ~[zeebe-stream-platform-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$2(ProcessingStateMachine.java:269) ~[zeebe-stream-platform-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:98) ~[zeebe-db-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:269) ~[zeebe-stream-platform-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:228) ~[zeebe-stream-platform-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:204) ~[zeebe-stream-platform-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:109) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:204) [zeebe-scheduler-8.3.0-alpha6.jar:8.3.0-alpha6]
```

It would be great if we could add in the ProcessStateMachine, the current record which as processed, position, key etc. This makes it easier during investigation to track the issue down.

**Comment by megglos** [comment]
ZDP-Triage:
- could be an easy pick if all the information is available at the point of throwing
- pulling into ready to evaluate and resolve if easy to do
