### ISSUE TITLE
Timeout when closing BrokerClient during shutdown

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#14625]
**Describe the bug**

```
Exception when closing client. Ignoring

java.util.concurrent.TimeoutException: Timeout after: 300 SECONDS
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.get(CompletableActorFuture.java:135) ~[zeebe-scheduler-8.3.0-rc1.jar:8.3.0-rc1]
	at io.camunda.zeebe.scheduler.FutureUtil.join(FutureUtil.java:32) ~[zeebe-scheduler-8.3.0-rc1.jar:8.3.0-rc1]
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.join(CompletableActorFuture.java:206) ~[zeebe-scheduler-8.3.0-rc1.jar:8.3.0-rc1]
	at io.camunda.zeebe.scheduler.Actor.close(Actor.java:97) ~[zeebe-scheduler-8.3.0-rc1.jar:8.3.0-rc1]
	at io.camunda.zeebe.gateway.impl.broker.BrokerClientImpl.doAndLogException(BrokerClientImpl.java:185) [zeebe-gateway-8.3.0-rc1.jar:8.3.0-rc1]
	at io.camunda.zeebe.gateway.impl.broker.BrokerClientImpl.close(BrokerClientImpl.java:105) [zeebe-gateway-8.3.0-rc1.jar:8.3.0-rc1]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:221) [spring-beans-6.0.12.jar:6.0.12]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587) [spring-beans-6.0.12.jar:6.0.12]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:559) [spring-beans-6.0.12.jar:6.0.12]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1189) [spring-beans-6.0.12.jar:6.0.12]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:520) [spring-beans-6.0.12.jar:6.0.12]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1182) [spring-beans-6.0.12.jar:6.0.12]
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1110) [spring-context-6.0.12.jar:6.0.12]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1076) [spring-context-6.0.12.jar:6.0.12]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.doClose(ReactiveWebServerApplicationContext.java:149) [spring-boot-3.1.4.jar:3.1.4]
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1027) [spring-context-6.0.12.jar:6.0.12]
	at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:793) [spring-boot-3.1.4.jar:3.1.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:328) [spring-boot-3.1.4.jar:3.1.4]
	at io.camunda.zeebe.broker.StandaloneBroker.main(StandaloneBroker.java:78) [camunda-zeebe-8.3.0-rc1.jar:8.3.0-rc1]
```

**Impact**
Mostly noisy logs. Can block shutdown until the configured timeout.

**Expected behavior**

1. Close should not take 300 seconds
2. May be reduce the log level

**Log/Stacktrace**

[logs](https://console.cloud.google.com/errors/detail/CJf7497civ60-gE;service=zeebe;time=P7D?project=camunda-saas-int-chaos)

**Environment:**
- Zeebe Version: 8.3.0

**Comment by megglos** [comment]
ZDP-Triage:
- it's weird that the client isn't shutdown - it seems spring is not aware of the dependency on the broker client, we may need to explicitly close it
- would be worth assessing whether other beans are also affected
- it seems to only happen occasionally and not always
- putting as later for now assuming it doesn't happen too often, we can revisit prio if this is false

**Comment by npepinpe** [comment]
Occurred again in 8.3.1 - https://console.cloud.google.com/errors/detail/CJf7497civ60-gE;service=zeebe;time=P7D?project=camunda-saas-int

**Comment by rodrigo-lourenco-lopes** [comment]
Ocurred again in 8.3.3 and 8.3.0 here https://jira.camunda.com/browse/SUPPORT-19376

Customer also managed to find a way around ti by disabling all management metrics. ("management.metrics.enable.all" -> "false").

**Comment by npepinpe** [comment]
I think the support issue is a different problem, which is that we don't support starting a broker in-process for testing. Instead, zeebe-process-test should be used. But error itself can still occur due to implicit bean dependencies, so we should fix it anyway.

**Comment by oleschoenburg** [comment]
The hypothesis that the bean dependencies are not ordered correctly was good but not correct I think. The `BrokerClientConfiguration` depends on the `ActorScheduler`, so Spring should first close the client before closing the scheduler. https://github.com/camunda/zeebe/blob/8.3.0/dist/src/main/java/io/camunda/zeebe/broker/BrokerClientConfiguration.java

**Comment by oleschoenburg** [comment]
I think this could happen if the broker client was not actually started... It's usually started in `StandaloneBroker#run` but if we never get there (for example if configuration fails to evaluate), the request manager actor is never submitted, so closing it will hang forever.
