### ISSUE TITLE
Failure to delete pending snapshot leads to inactive partition until restart

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#14670]
**Describe the bug**

If a snapshot is being replicated during startup, and it fails to delete an existing pending snapshot directory (could be a leftover from a crash, or simply the replication restarting due to some errors), the partition transitions to inactive and is stuck, preventing startup from finishing.

**To Reproduce**

It seems to happen more often with large state, >= 8GB. Simply cause data loss on one node to force replication on restart, and it might happen.

**Expected behavior**

Even if an I/O error occurs during replication, it should be able to recover and retry the snapshot replication.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalStateException: Expected to delete pending received snapshot, but failed.
	at io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore.newReceivedSnapshot(FileBasedSnapshotStore.java:373) ~[zeebe-snapshots-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore.newReceivedSnapshot(FileBasedSnapshotStore.java:51) ~[zeebe-snapshots-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at io.atomix.raft.roles.PassiveRole.onInstall(PassiveRole.java:191) ~[zeebe-atomix-cluster-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at io.atomix.raft.roles.FollowerRole.onInstall(FollowerRole.java:83) ~[zeebe-atomix-cluster-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at io.atomix.raft.impl.RaftContext.lambda$registerHandlers$8(RaftContext.java:315) ~[zeebe-atomix-cluster-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at io.atomix.raft.impl.RaftContext.lambda$runOnContext$27(RaftContext.java:334) ~[zeebe-atomix-cluster-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:178) [zeebe-atomix-utils-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.nio.file.NoSuchFileException: /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/6651-18-6637-6635/001698.sst
	at sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.implDelete(Unknown Source) ~[?:?]
	at sun.nio.fs.AbstractFileSystemProvider.delete(Unknown Source) ~[?:?]
	at java.nio.file.Files.delete(Unknown Source) ~[?:?]
	at io.camunda.zeebe.util.FileUtil$FolderDeleter.visitFile(FileUtil.java:204) ~[zeebe-util-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at io.camunda.zeebe.util.FileUtil$FolderDeleter.visitFile(FileUtil.java:187) ~[zeebe-util-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at java.nio.file.Files.walkFileTree(Unknown Source) ~[?:?]
	at java.nio.file.Files.walkFileTree(Unknown Source) ~[?:?]
	at io.camunda.zeebe.util.FileUtil.deleteFolder(FileUtil.java:134) ~[zeebe-util-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore.newReceivedSnapshot(FileBasedSnapshotStore.java:371) ~[zeebe-snapshots-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	... 12 more
```

</p>
</details>

**Environment:**
- Zeebe Version: 8.4.0-SNAPSHOT

**Comment by npepinpe** [comment]
This error in particular implies that some SST file was deleted concurrently while the snapshot was being replicated.

I think this may occur when stopping the `PassiveRole` (when transitioning to another active role) while replication is on-going, since `newReceivedSnapshot` is executed in the calling thread, but `purgePendingSnapshots` is executed in the snapshot store actor.

**Comment by Zelldon** [comment]
Do we still clean up pending snapshots on restart? If so this would resolve it? Otherwise I guess snapshot has to be delete and node restarted?

**Comment by npepinpe** [comment]
We don't explicitly clean them on start up, but the bootstrap process (going from passive to an active role) will do it via `PassiveRole#stop`. So we sort of do :smile:

**Comment by megglos** [comment]
ZDP-Triage:
- it's a regression that blocks the startup
- it likely is also present in 8.3
- you can recover by restarting until it eventually suceeds
- fix should be a low hanging fruit

**Comment by rodrigo-lourenco-lopes** [comment]
I happened also 

> ZDP-Triage:
> 
> * it's a regression that blocks the startup
> * it likely is also present in 8.3
> * you can recover by restarting until it eventually suceeds
> * fix should be a low hanging fruit

As you suggested it also happened in 8.3.0: https://console.cloud.google.com/errors/detail/CKHbocnT7I_lMg;service=zeebe;time=P7D?project=camunda-saas-int-chaos

**Comment by npepinpe** [comment]
This happened a combined ~60 times in the last week in our benchmarks, so I would revisit the priority.

**Comment by nicpuppa** [comment]
This happened again on a production cluster (8.3.3):

[https://console.cloud.google.com/errors/detail/CLTpyYqLt-eV_AE;service=zeebe;time=P7D?project=camunda-cloud-240911](https://console.cloud.google.com/errors/detail/CLTpyYqLt-eV_AE;service=zeebe;time=P7D?project=camunda-cloud-240911)

**Comment by berkaycanbc** [comment]
This happened again in release benchmark cluster `release-8-4-0-alpha2`:

[GCP Logs](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22release-8-4-0-alpha2%22%0Aresource.labels.pod_name%3D%22release-8-4-0-alpha2-zeebe-0%22%20severity%3E%3DDEFAULT%0Aseverity%3DERROR;cursorTimestamp=2023-12-15T12:15:40.602202488Z;aroundTime=2023-12-15T12:30:00.428Z;duration=PT1H?project=zeebe-io)

**Comment by npepinpe** [comment]
Putting it back on our board to discuss if this is a release blocker, as it seems it can happen often.

**Comment by berkaycanbc** [comment]
Happened in one of our benchmark clusters and caused one of the partitions to go inactive.

[GCP Log](https://console.cloud.google.com/logs/query;query=resource.labels.namespace_name%3D%22medic-y-2023-cw-49-4eb6941-benchmark%22;pinnedLogId=2023-12-24T12:41:34.566753419Z%2F1e9zgmq6aroc5j8g;cursorTimestamp=2023-12-24T12:41:34.790301270Z;aroundTime=2023-12-24T12:30:00.000Z;duration=PT1H?referrer=search&project=zeebe-io)

**Comment by deepthidevaki** [comment]
The root cause, I think is the following:

1. Raft follower is receiving a snapshot.
2. Something failed. As a result follower aborts the pending snapshot. This abort is scheduled on the snapshot store actor.
3. Leader restarts sending snapshot.
4. Follower calls `newReceivedSnapshot()`. But this is executed on the Raft thread.
5. The `abort` in snapshot store actor and the delete partial snapshot in `newReceivedSnapshot` runs concurrently, that causes the issues.

Why was this not a problem before? Each time a new snapshot is received, a new pending directory with a unique name was created. So raft thread can create it on its thread without waiting for the snapshot store actor to delete a previously aborted snapshot.

Possible solutions:
1. `newReceivedSnapshot` should not delete anything. All changes to the snapshot directory must go through the SnapshotStore actor. If a snapshot directory with partial data exists, it should still return `SnapshotAlreadyExists`. The snapshot will eventually gets deleted and a new snapshot can be received.
2. Run `newReceivedSnapshot` should run on the snapshot store actor. Raft must wait on the returned future. `persistedSnapshotStore.newReceivedSnapshot(snapshotId).join()`

I think solution 2 is safer. This way we ensure that all operations on the snapshot are executed on a single actor.

**Comment by npepinpe** [comment]
Correct, solution 2 is the right one since we designed the snapshot store to synchronize operations to the underlying file system through its actor :+1:
