### ISSUE TITLE
Snapshot replication loop when replicating large state

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#14671]
**Describe the bug**

When trying to replicate a > 8GB snapshot across nodes during startup, I observe a loop happening, which sometimes does resolve itself, but it's not clear why it's happening or why it resolves itself.

Essentially, the new replication starts - then it gets aborted/rolled back (no clue why), and a new one starts with the exact same ID.

Severity is high in my opinion as it can turn a 4-5 minute partition startup into 25-30 minutes.

See the logs for more.

**To Reproduce**

Cause data loss on a node and restart it to force replication of a > 4GB snapshot.

**Expected behavior**

Snapshot replication does not rollback unless an error occurs. If an error occurs, sufficient information is provided for us to diagnose it.

**Log/Stacktrace**

<details><summary>Logs</summary>
 <p>

```json
{
  "severity": "INFO",
  "logging.googleapis.com/sourceLocation": {
    "function": "info",
    "file": "ContextualLogger.java",
    "line": 232
  },
  "message": "RaftServer{raft-partition-partition-2}{role=FOLLOWER} - Started receiving new snapshot FileBasedReceivedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/snapshots/7061-18-7045-7046, snapshotStore=SnapshotStore-2, metadata=FileBasedSnapshotId{index=7061, term=18, processedPosition=7045, exporterPosition=7046}} from 1",
  "serviceContext": {
    "service": "zeebe",
    "version": "np-large-state"
  },
  "context": {
    "threadId": 33,
    "partitionId": "2",
    "actor-scheduler": "Broker-2",
    "threadPriority": 5,
    "loggerName": "io.atomix.raft.roles.FollowerRole",
    "threadName": "raft-server-2-2",
    "actor-name": "raft-server-2"
  },
  "timestampSeconds": 1696965265,
  "timestampNanos": 369861253
}
{
  "severity": "INFO",
  "logging.googleapis.com/sourceLocation": {
    "function": "info",
    "file": "ContextualLogger.java",
    "line": 225
  },
  "message": "RaftServer{raft-partition-partition-2}{role=FOLLOWER} - Rolling back snapshot FileBasedReceivedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/snapshots/7061-18-7045-7046, snapshotStore=SnapshotStore-2, metadata=FileBasedSnapshotId{index=7061, term=18, processedPosition=7045, exporterPosition=7046}}",
  "serviceContext": {
    "service": "zeebe",
    "version": "np-large-state"
  },
  "context": {
    "threadId": 33,
    "partitionId": "2",
    "actor-scheduler": "Broker-2",
    "threadPriority": 5,
    "loggerName": "io.atomix.raft.roles.FollowerRole",
    "threadName": "raft-server-2-2",
    "actor-name": "raft-server-2"
  },
  "timestampSeconds": 1696965504,
  "timestampNanos": 682183412
}
{
  "severity": "INFO",
  "logging.googleapis.com/sourceLocation": {
    "function": "info",
    "file": "ContextualLogger.java",
    "line": 232
  },
  "message": "RaftServer{raft-partition-partition-2}{role=FOLLOWER} - Started receiving new snapshot FileBasedReceivedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/snapshots/7061-18-7045-7046, snapshotStore=SnapshotStore-2, metadata=FileBasedSnapshotId{index=7061, term=18, processedPosition=7045, exporterPosition=7046}} from 1",
  "serviceContext": {
    "service": "zeebe",
    "version": "np-large-state"
  },
  "context": {
    "threadId": 33,
    "partitionId": "2",
    "actor-scheduler": "Broker-2",
    "threadPriority": 5,
    "loggerName": "io.atomix.raft.roles.FollowerRole",
    "threadName": "raft-server-2-2",
    "actor-name": "raft-server-2"
  },
  "timestampSeconds": 1696965505,
  "timestampNanos": 529940213
}
{
  "severity": "INFO",
  "logging.googleapis.com/sourceLocation": {
    "function": "info",
    "file": "ContextualLogger.java",
    "line": 225
  },
  "message": "RaftServer{raft-partition-partition-2}{role=FOLLOWER} - Rolling back snapshot FileBasedReceivedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/snapshots/7061-18-7045-7046, snapshotStore=SnapshotStore-2, metadata=FileBasedSnapshotId{index=7061, term=18, processedPosition=7045, exporterPosition=7046}}",
  "serviceContext": {
    "service": "zeebe",
    "version": "np-large-state"
  },
  "context": {
    "threadId": 33,
    "partitionId": "2",
    "actor-scheduler": "Broker-2",
    "threadPriority": 5,
    "loggerName": "io.atomix.raft.roles.FollowerRole",
    "threadName": "raft-server-2-2",
    "actor-name": "raft-server-2"
  },
  "timestampSeconds": 1696965732,
  "timestampNanos": 455469070
}
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: 
- Configuration:

**Comment by npepinpe** [comment]
A quick look will show you the loop happens more or less every 4-5 minutes, which is could be the snapshot interval, but it might also line up with how much time it takes to replicate the snapshot at that size (from what I've seen, a 8GB snapshot takes about 4 minutes to replicate).

**Comment by npepinpe** [comment]
Enabling trace logging, we can see the following cause of the rollback:

> Sending InstallResponse{status=ERROR, error=RaftError{type=ILLEGAL_MEMBER_STATE, message=Snapshot chunk is received out of order}}

The offending request:

```
RaftServer{raft-partition-partition-2}{role=FOLLOWER} - Received InstallRequest{currentTerm=18, leader=1, index=7061, term=18, version=1, chunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1658200635}, nextChunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1686829786}, data=HeapByteBuffer{position=0, remaining=1447, limit=1447, capacity=1447, mark=java.nio.HeapByteBuffer[pos=0 lim=1447 cap=1447], hash=1714610875}, initial=true, complete=false}
```

As we can see, the leader sent an `initial=true` request again before we ever had a `complete=true` request for some reason. So why is the leader preemptively restarting the replication?

**Comment by npepinpe** [comment]
On the leader side, we see that the request right before re-sending the initial chunk timed out.

```
java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException: Request raft-partition-partition-2-install to np-large-state-zeebe-2.np-large-state-zeebe.np-large-state.svc:26502 timed out in PT2.5S
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$sendAndReceive$4(NettyMessagingService.java:248) ~[zeebe-atomix-cluster-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.99.Final.jar:4.1.99.Final]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.util.concurrent.TimeoutException: Request raft-partition-partition-2-install to np-large-state-zeebe-2.np-large-state-zeebe.np-large-state.svc:26502 timed out in PT2.5S
	at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$sendAndReceive$4(NettyMessagingService.java:250) ~[zeebe-atomix-cluster-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	... 7 more
```

Is it possible that on time out we just restart the whole thing? Oopsie.

**Comment by npepinpe** [comment]
Yes, on _any_ failure, the leader simply restarts the complete snapshot replication, regardless of what the failure is.

I think the behavior should instead be:

- On time out, retry the same request.
- On snapshot chunk out of order, the follower should return the expected next chunk. If there was none, it means it was the first one, so restart. If there was one, and the leader has it, send that. If the leader doesn't have it (i.e. the follower is just wrong), restart the replication.
- If the follower failed to parse the request (not corruption, but it cannot read the protocol message), then there is literally no point ever retrying. These nodes cannot communicate with each other, this is an unrecoverable error.

**Comment by npepinpe** [comment]
We can start with at least retrying time outs, since with large state, these seem to happen more often.

**Comment by npepinpe** [comment]
It turns out, with large state, it's possible to have files that are up to 100-250MB, but our timeout for install requests is static at 2.5s. This is very tight to transfer large files, which would explain why this happens more with large state. For example, in one snapshot I had the following:

```
9.1M -rw-r--r-- 2 zeebe zeebe 9.1M Oct 10 16:43 002409.sst
 13M -rw-r--r-- 2 zeebe zeebe  13M Oct 10 16:43 002410.sst
9.1M -rw-r--r-- 2 zeebe zeebe 9.1M Oct 10 16:43 002411.sst
118M -rw-r--r-- 1 zeebe zeebe 118M Oct 10 16:46 002412.sst
```

I suspect the 118M file is the one timing out (since it also happens to be the last one) and causing this loop.

**Comment by npepinpe** [comment]
Ah, I see this is somewhat a duplicate of https://github.com/camunda/zeebe/issues/11496, just made worse by having deal with a large state.
