### ISSUE TITLE
`RandomizedRaftTest#consistencyTestWithSnapshot` fails with uncaught exception

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#14694]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? Once so far: https://github.com/camunda/zeebe/actions/runs/6491028769/job/17627701526
- Does it block your work? No
- Do we suspect that it is a real failure? Possibly

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
java.lang.AssertionError: Uncaught exception
	at org.junit.Assert.fail(Assert.java:89)
	at io.atomix.raft.DeterministicSingleThreadContext$WrappedRunnable.run(DeterministicSingleThreadContext.java:112)
	at org.jmock.lib.concurrent.DeterministicScheduler$CallableRunnableAdapter.call(DeterministicScheduler.java:176)
	at org.jmock.lib.concurrent.DeterministicScheduler$ScheduledTask.run(DeterministicScheduler.java:251)
	at org.jmock.lib.concurrent.DeterministicScheduler.runNextPendingCommand(DeterministicScheduler.java:66)
	at org.jmock.lib.concurrent.DeterministicScheduler.runUntilIdle(DeterministicScheduler.java:56)
	at org.jmock.lib.concurrent.DeterministicScheduler.tick(DeterministicScheduler.java:45)
	at io.atomix.raft.ControllableRaftContexts.tick(ControllableRaftContexts.java:313)
	at io.atomix.raft.ControllableRaftContexts.tickElectionTimeout(ControllableRaftContexts.java:287)
	at io.atomix.raft.RaftOperation.run(RaftOperation.java:42)
	at io.atomix.raft.RandomizedRaftTest.consistencyTest(RandomizedRaftTest.java:180)
	at io.atomix.raft.RandomizedRaftTest.consistencyTestWithSnapshot(RandomizedRaftTest.java:96)
</pre>
</details>

**Hypotheses**
Not clear what happened. Unfortunately, the actual exception is lost because it is printed to stderr and not logged properly:
https://github.com/camunda/zeebe/blob/b7df1f5ee03d9187a1c15e640928be3aeb64f62d/atomix/cluster/src/test/java/io/atomix/raft/DeterministicSingleThreadContext.java#L106-L114

**Logs**

[randomized-raft-test.zip](https://github.com/camunda/zeebe/files/12878159/randomized-raft-test.zip)

**Comment by npepinpe** [comment]
Failed again here: https://github.com/camunda/zeebe/actions/runs/6734614844/job/18305905872?pr=14973
