### ISSUE TITLE
Impact of hot backups is not neglible

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#14696]
## Describe the bug

> **Note:**
> I marked it as critical for now, since I think this can have high impact on customers clusters and workload, and it is not yet clear why. Furthermore, since we advertise it as no impact on their workload. The cluster seemed to recover when a node was restarted.
>
> After we better assess the likelihood and impact we can also decrease the severiy.

It feels like the impact of hot backups is not negligible, and they are more cold than hot. Requests are timing out for several minutes. 

### Insights

Backup metrics show weird results first, that one partition took 3 backups the others only one. Furthermore, it took 2.5 minutes for most of them, the impact on processing was much higher.
![backup](https://github.com/camunda/zeebe/assets/2758593/f1383619-bc26-4f05-bd49-83a125122cd4)
![backup2](https://github.com/camunda/zeebe/assets/2758593/0b8fc416-c7ac-4ce7-b1af-fd32430672b0)
![backups](https://github.com/camunda/zeebe/assets/2758593/307b0ec8-608e-4191-a52e-57f39353fc5a)

We can see in the processing that the cluster was unavailable for almost 20 minutes!

![general](https://github.com/camunda/zeebe/assets/2758593/63b3aeb8-3f92-4309-adbb-aed1b6c8ce08)

Size of the cluster was not that high

![jouarnal](https://github.com/camunda/zeebe/assets/2758593/a53f7eb2-144f-4075-9702-6860601ab3ff)
![snap](https://github.com/camunda/zeebe/assets/2758593/4fac13e6-d163-454b-8037-90d7f33b6e68)

We can see in the processing that the batch processing is stuck for around 2,5 minutes and the processing queue was also not decreasing for a long time.

![processing](https://github.com/camunda/zeebe/assets/2758593/e721e636-1528-4836-bab2-d03fd48c6446)

**To Reproduce**

We created a cluster and took a backup of an empty cluster. Run some load stopped the load and took a new backup. In the console, the backups seem to be finished. When starting a new load and taking backups again we experience DEADLINE_EXCEEDINGS.

Worker fails with:
```
java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: NOT_FOUND: Command 'COMPLETE' rejected with code 'NOT_FOUND': Expected to complete job with key '6755399441223888', but no such job was found
    at java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[?:?]
    at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:?]
    at io.camunda.zeebe.ResponseChecker.run(ResponseChecker.java:41) [classes/:?]
Caused by: io.grpc.StatusRuntimeException: NOT_FOUND: Command 'COMPLETE' rejected with code 'NOT_FOUND': Expected to complete job with key '6755399441223888', but no such job was found
    at io.grpc.Status.asRuntimeException(Status.java:537) ~[grpc-api-1.58.0.jar:1.58.0]
    at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:481) ~[grpc-stub-1.58.0.jar:1.58.0]
    at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[grpc-api-1.58.0.jar:1.58.0]
    at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[grpc-api-1.58.0.jar:1.58.0]
    at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[grpc-api-1.58.0.jar:1.58.0]
    at io.micrometer.core.instrument.binder.grpc.MetricCollectingClientCallListener.onClose(MetricCollectingClientCallListener.java:57) ~[micrometer-core-1.11.5.jar:1.11.5]
    at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:567) ~[grpc-core-1.58.0.jar:1.58.0]
    at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:71) ~[grpc-core-1.58.0.jar:1.58.0]
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:735) ~[grpc-core-1.58.0.jar:1.58.0]
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:716) ~[grpc-core-1.58.0.jar:1.58.0]
    at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.58.0.jar:1.58.0]
    at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[grpc-core-1.58.0.jar:1.58.0]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
    at java.lang.Thread.run(Unknown Source) ~[?:?]
```
And
```
io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 71.999966534s. [closed=[], open=[[buffered_nanos=210122, remote_addr=[bada2734-1feb-4124-a615-3cd697dc544c.jfk-1.zeebe.camunda.io/34.160.130.184:443](http://bada2734-1feb-4124-a615-3cd697dc544c.jfk-1.zeebe.camunda.io/34.160.130.184:443)]]]
    at io.grpc.Status.asRuntimeException(Status.java:537) ~[grpc-api-1.58.0.jar:1.58.0]
    at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:481) [grpc-stub-1.58.0.jar:1.58.0]
    at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) [grpc-api-1.58.0.jar:1.58.0]
    at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) [grpc-api-1.58.0.jar:1.58.0]
    at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) [grpc-api-1.58.0.jar:1.58.0]
    at io.micrometer.core.instrument.binder.grpc.MetricCollectingClientCallListener.onClose(MetricCollectingClientCallListener.java:57) [micrometer-core-1.11.5.jar:1.11.5]
    at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:567) [grpc-core-1.58.0.jar:1.58.0]
    at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:71) [grpc-core-1.58.0.jar:1.58.0]
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:735) [grpc-core-1.58.0.jar:1.58.0]
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:716) [grpc-core-1.58.0.jar:1.58.0]
    at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.58.0.jar:1.58.0]
    at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) [grpc-core-1.58.0.jar:1.58.0]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
    at java.lang.Thread.run(Unknown Source) [?:?]
```

Deploying fails with:
```
io.camunda.zeebe.client.api.command.ClientStatusException: Time out between gateway and broker: Request ProtocolRequest{id=854786, subject=command-api-1, sender=zeebe-0.zeebe-broker-service.bada2734-1feb-4124-a615-3cd697dc544c-zeebe.svc.cluster.local:26502, payload=byte[]{length=2928, hash=-1631376698}} to zeebe-1.zeebe-broker-service.bada2734-1feb-4124-a615-3cd697dc544c-zeebe.svc.cluster.local:26501 timed out in PT15S
    at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.transformExecutionException(ZeebeClientFutureImpl.java:116) ~[zeebe-client-java-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
    at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:54) ~[zeebe-client-java-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
    at io.camunda.zeebe.Starter.deployProcess(Starter.java:199) [classes/:?]
    at io.camunda.zeebe.Starter.run(Starter.java:62) [classes/:?]
    at io.camunda.zeebe.App.createApp(App.java:55) [classes/:?]
    at io.camunda.zeebe.Starter.main(Starter.java:227) [classes/:?]
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: Time out between gateway and broker: Request ProtocolRequest{id=854786, subject=command-api-1, sender=zeebe-0.zeebe-broker-service.bada2734-1feb-4124-a615-3cd697dc544c-zeebe.svc.cluster.local:26502, payload=byte[]{length=2928, hash=-1631376698}} to zeebe-1.zeebe-broker-service.bada2734-1feb-4124-a615-3cd697dc544c-zeebe.svc.cluster.local:26501 timed out in PT15S
    at java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[?:?]
    at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:?]
    at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:52) ~[zeebe-client-java-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
    ... 4 more
Caused by: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: Time out between gateway and broker: Request ProtocolRequest{id=854786, subject=command-api-1, sender=zeebe-0.zeebe-broker-service.bada2734-1feb-4124-a615-3cd697dc544c-zeebe.svc.cluster.local:26502, payload=byte[]{length=2928, hash=-1631376698}} to zeebe-1.zeebe-broker-service.bada2734-1feb-4124-a615-3cd697dc544c-zeebe.svc.cluster.local:26501 timed out in PT15S
    at io.grpc.Status.asRuntimeException(Status.java:537) ~[grpc-api-1.58.0.jar:1.58.0]
    at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:481) ~[grpc-stub-1.58.0.jar:1.58.0]
    at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[grpc-api-1.58.0.jar:1.58.0]
    at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[grpc-api-1.58.0.jar:1.58.0]
    at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[grpc-api-1.58.0.jar:1.58.0]
    at io.micrometer.core.instrument.binder.grpc.MetricCollectingClientCallListener.onClose(MetricCollectingClientCallListener.java:57) ~[micrometer-core-1.11.5.jar:1.11.5]
    at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:567) ~[grpc-core-1.58.0.jar:1.58.0]
    at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:71) ~[grpc-core-1.58.0.jar:1.58.0]
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:735) ~[grpc-core-1.58.0.jar:1.58.0]
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:716) ~[grpc-core-1.58.0.jar:1.58.0]
    at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.58.0.jar:1.58.0]
    at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[grpc-core-1.58.0.jar:1.58.0]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
    at java.lang.Thread.run(Unknown Source) ~[?:?]

```

## Expected behavior

Hot backup has no impact on processing and availability.

## Additional details

This was discovered in preparation for a game day, we still have the cluster running. I will create an incident channel for it.

The cluster recovered only because a node was restarted.

## Environment:
- OS: 
- Zeebe Version: 8.3.0
- Configuration: trial cluster, with enabled hotbackups feature.

**Comment by Zelldon** [comment]
We investigated this further as part of an incident, and were not able to reproduce this yet.

**Comment by Zelldon** [comment]
I'm starting a test on a cluster in integration stage, where we have some more permissions.

**Comment by Zelldon** [comment]
We are not able to reproduce this right now. I will decrease the severity and try one more and close this if I'm not able to do so, since based on the metrics it might be also some problem with the starters/workers which we can't verify anymore.

**Comment by Zelldon** [comment]
I was delayed but will try it once more today, and close if I can't reproduce

**Comment by oleschoenburg** [comment]
@Zelldon Ping to share results or close the issue

**Comment by Zelldon** [comment]
@oleschoenburg I'm currently running an test will report tomorrow :)

**Comment by oleschoenburg** [comment]
Awesome, thanks for trying and documenting the results!
