### ISSUE TITLE
Uncaught exception in RandomizedRaftTest#consistencyTestWithSnapshot

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#14854]
**Describe the bug**

There was an uncaught exception in a `RandomizedRaftTest`. While it's a test, we typically treat errors there are real bugs until proven otherwise.

**To Reproduce**

See https://github.com/camunda/zeebe/actions/runs/6635585346/job/18026744026

**Expected behavior**

No uncaught exception :upside_down_face: 

**Log/Stacktrace**

I've uploaded the logs [here](https://drive.google.com/file/d/1MJs5fYmcCrULaX9IhR-emFqNmccqmhOr/view?usp=sharing). The file itself was 359MB, which is so cool :upside_down_face:

**Comment by deepthidevaki** [comment]
Was able to reproduce this locally. It fails due to `SnapshotAlreadyExists`. I thought we fixed it already. :thinking:
```
12:11:58.629 [raft-server-1] TRACE io.atomix.raft.roles.FollowerRole - RaftServer{1-partition-1}{role=FOLLOWER} - Received InstallRequest{currentTerm=1, leader=2, index=252, term=1, version=1, chunkId=HeapByteBuffer{position=0, remaining=7, limit=7, capacity=7, mark=java.nio.HeapByteBuffer[pos=0 lim=7 cap=7], hash=-1511131921}, nextChunkId=null, data=HeapByteBuffer{position=0, remaining=58, limit=58, capacity=58, mark=java.nio.HeapByteBuffer[pos=0 lim=58 cap=58], hash=2196820}, initial=true, complete=true}
12:11:58.629 [raft-server-1] INFO  io.atomix.raft.impl.RaftContext - RaftServer{1-partition-1} - Found leader 2
12:11:58.629 [raft-server-1] TRACE io.atomix.raft.impl.RaftContext - RaftServer{1-partition-1} - Set leader 2
12:11:58.629 [raft-server-1] DEBUG io.atomix.raft.roles.FollowerRole - RaftServer{1-partition-1}{role=FOLLOWER} - Received snapshot 252 chunk from 2
12:11:58.629 [raft-server-1] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{1-partition-1}{role=FOLLOWER} - Started receiving new snapshot io.atomix.raft.snapshot.InMemorySnapshot@2dd96ad from 2
12:11:58.629 [raft-server-1] DEBUG io.atomix.raft.roles.FollowerRole - RaftServer{1-partition-1}{role=FOLLOWER} - Committing snapshot io.atomix.raft.snapshot.InMemorySnapshot@2dd96ad
12:11:58.629 [raft-server-1] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{1-partition-1}{role=FOLLOWER} - Delete existing log (lastIndex '189') and replace with received snapshot (index '252'). First entry in the log will be at index 253
12:11:58.629 [raft-server-1] TRACE io.atomix.raft.storage.system.MetaStore - Store last flushed index 252
12:11:58.631 [raft-server-1] TRACE io.atomix.raft.storage.system.MetaStore - Store last flushed index -1
12:11:58.640 [raft-server-1] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{1-partition-1}{role=FOLLOWER} - Committed snapshot io.atomix.raft.snapshot.InMemorySnapshot@2dd96ad
12:11:58.640 [raft-server-1] TRACE io.atomix.raft.roles.FollowerRole - RaftServer{1-partition-1}{role=FOLLOWER} - Sending InstallResponse{status=OK}
12:11:58.640 [raft-server-1] DEBUG io.atomix.raft.impl.LogCompactor - RaftContext{1-partition-1} - Scheduling log compaction up to index 180
12:11:58.640 [raft-server-1] TRACE io.atomix.raft.impl.LogCompactor - RaftContext{1-partition-1} - Updated compactable index to 180
12:11:58.640 [raft-server-1] DEBUG io.atomix.raft.impl.LogCompactor - RaftContext{1-partition-1} - Compacted log up to index 80
12:11:58.640 [raft-server-1] TRACE io.atomix.raft.roles.FollowerRole - RaftServer{1-partition-1}{role=FOLLOWER} - Received InstallRequest{currentTerm=1, leader=2, index=252, term=1, version=1, chunkId=HeapByteBuffer{position=0, remaining=7, limit=7, capacity=7, mark=java.nio.HeapByteBuffer[pos=0 lim=7 cap=7], hash=-1511131921}, nextChunkId=null, data=HeapByteBuffer{position=0, remaining=58, limit=58, capacity=58, mark=java.nio.HeapByteBuffer[pos=0 lim=58 cap=58], hash=2196820}, initial=true, complete=true}
12:11:58.640 [raft-server-1] DEBUG io.atomix.raft.roles.FollowerRole - RaftServer{1-partition-1}{role=FOLLOWER} - Received snapshot 252 chunk from 2
12:11:58.640 [raft-server-1] ERROR io.atomix.raft.DeterministicSingleThreadContext - Uncaught exception
io.camunda.zeebe.snapshots.SnapshotException$SnapshotAlreadyExistsException: Snapshot with this ID is already persisted
	at io.atomix.raft.snapshot.TestSnapshotStore.newReceivedSnapshot(TestSnapshotStore.java:122) ~[test-classes/:?]
	at io.atomix.raft.roles.PassiveRole.onInstall(PassiveRole.java:191) ~[classes/:?]
	at io.atomix.raft.roles.FollowerRole.onInstall(FollowerRole.java:87) ~[classes/:?]
	at io.atomix.raft.impl.RaftContext.lambda$registerHandlers$8(RaftContext.java:315) ~[classes/:?]
	at io.atomix.raft.impl.RaftContext.lambda$runOnContext$27(RaftContext.java:334) ~[classes/:?]
```

Also probably same as #14694
