### ISSUE TITLE
Expected to delete pending received snapshot, but failed

### ISSUE THREAD

**Issue by nicpuppa** [camunda/zeebe#15115]
**Describe the bug**

This error:

```
java.lang.IllegalStateException: Expected to delete pending received snapshot, but failed.
	at io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore.newReceivedSnapshot(FileBasedSnapshotStore.java:371) ~[zeebe-snapshots-8.3.1.jar:8.3.1]
	at io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore.newReceivedSnapshot(FileBasedSnapshotStore.java:51) ~[zeebe-snapshots-8.3.1.jar:8.3.1]
	at io.atomix.raft.roles.PassiveRole.onInstall(PassiveRole.java:191) ~[zeebe-atomix-cluster-8.3.1.jar:8.3.1]
	at io.atomix.raft.roles.FollowerRole.onInstall(FollowerRole.java:83) ~[zeebe-atomix-cluster-8.3.1.jar:8.3.1]
	at io.atomix.raft.impl.RaftContext.lambda$registerHandlers$8(RaftContext.java:312) ~[zeebe-atomix-cluster-8.3.1.jar:8.3.1]
	at io.atomix.raft.impl.RaftContext.lambda$runOnContext$27(RaftContext.java:331) ~[zeebe-atomix-cluster-8.3.1.jar:8.3.1]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:178) [zeebe-atomix-utils-8.3.1.jar:8.3.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.nio.file.NoSuchFileException: /usr/local/zeebe/data/raft-partition/partitions/1/snapshots/1035818-69-1037496-1037510/000934.sst
	at sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.implDelete(Unknown Source) ~[?:?]
	at sun.nio.fs.AbstractFileSystemProvider.delete(Unknown Source) ~[?:?]
	at java.nio.file.Files.delete(Unknown Source) ~[?:?]
	at io.camunda.zeebe.util.FileUtil$FolderDeleter.visitFile(FileUtil.java:204) ~[zeebe-util-8.3.1.jar:8.3.1]
	at io.camunda.zeebe.util.FileUtil$FolderDeleter.visitFile(FileUtil.java:187) ~[zeebe-util-8.3.1.jar:8.3.1]
	at java.nio.file.Files.walkFileTree(Unknown Source) ~[?:?]
	at java.nio.file.Files.walkFileTree(Unknown Source) ~[?:?]
	at io.camunda.zeebe.util.FileUtil.deleteFolder(FileUtil.java:134) ~[zeebe-util-8.3.1.jar:8.3.1]
	at io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore.newReceivedSnapshot(FileBasedSnapshotStore.java:369) ~[zeebe-snapshots-8.3.1.jar:8.3.1]
	
```

happened after:

`Aborting received snapshot in dir /usr/local/zeebe/data/raft-partition/partitions/1/snapshots/1035818-69-1037496-1037510
`

The cause is not clear, but there ware multiple restart

<img width="2039" alt="Screenshot 2023-11-09 at 15 41 40" src="https://github.com/camunda/zeebe/assets/72783243/7d38613d-0c00-41c4-b774-64991a4f8f39">

<img width="2040" alt="Screenshot 2023-11-09 at 15 42 39" src="https://github.com/camunda/zeebe/assets/72783243/6e6d2c38-bebb-49a1-af8b-7f84b55a3eb1">

More logs [here](https://drive.google.com/drive/folders/1xKzsCvtlu9eXvFyumIb4os7VRLK0JOFv)

**Environment:**
- Zeebe Version:  8.3.1

**Comment by npepinpe** [comment]
I think it's a duplicate in the sense that the root cause is the same as this issue: https://github.com/camunda/zeebe/issues/14670
