### ISSUE TITLE
ScaleDownBrokersTest.shouldScaleDownClusterAgain is flaky

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#15218]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? just once [here](https://github.com/camunda/zeebe/actions/runs/6879684146/job/18712167107), but was reported and fixed before https://github.com/camunda/zeebe/issues/15118. It failed again in code including that fix.
- Does it block your work? I just retry
- Do we suspect that it is a real failure? 🤷 

```
Warning:  Flakes: 
Warning:  io.camunda.zeebe.it.clustering.dynamic.ScaleDownBrokersTest.shouldScaleDownCluster
Error:    Run 1: ScaleDownBrokersTest.shouldScaleDownCluster:77 » ConditionTimeout Condition with alias 'Process instances are created in all partitions' didn't complete within 10 seconds because condition io.camunda.zeebe.it.clustering.dynamic.Utils$$Lambda/0x00007f82511fe968 was not fulfilled.
[INFO]   Run 2: PASS
```

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Error:  io.camunda.zeebe.it.clustering.dynamic.ScaleDownBrokersTest.shouldScaleDownCluster -- Time elapsed: 24.41 s <<< ERROR!
org.awaitility.core.ConditionTimeoutException: Condition with alias 'Process instances are created in all partitions' didn't complete within 10 seconds because condition io.camunda.zeebe.it.clustering.dynamic.Utils$$Lambda/0x00007f82511fe968 was not fulfilled.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:954)
	at io.camunda.zeebe.it.clustering.dynamic.Utils.createInstanceWithAJobOnAllPartitions(Utils.java:90)
	at io.camunda.zeebe.it.clustering.dynamic.ScaleDownBrokersTest.shouldScaleDownCluster(ScaleDownBrokersTest.java:77)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

[Logs in Drive](https://drive.google.com/drive/folders/1Ve2YXKPS0LEbfOdHh0B13b5tGxDH_fIG)

**Comment by deepthidevaki** [comment]
Test fails because deployment is not distributed to Partition 2 with in the specified duration. I think retry delay for deployment distribution is not configurable. So probably a fix would be to increasing the waiting time.
