### ISSUE TITLE
ScaleResiliencyTest$ScaleDown.shouldContinueScaleDownAfterRestart is flaky

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#15231]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? 
  - Once so far.
- Does it block your work? 
  - Not really.
- Do we suspect that it is a real failure? 
  - Not sure.

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Assertion condition [List check single element] 
Expecting actual:
  class BrokerState {
    id: 2
    state: ACTIVE
    version: 2
    lastUpdatedAt: 2023-11-16T09:13:32.135700584Z
    partitions: []
}
to match 'Broker 2 has partition 2' predicate within 10 seconds.
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted
/

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 28.37 s <<< FAILURE! -- in io.camunda.zeebe.it.clustering.dynamic.ScaleResiliencyTest$ScaleDown
Error:  io.camunda.zeebe.it.clustering.dynamic.ScaleResiliencyTest$ScaleDown.shouldContinueScaleDownAfterRestart -- Time elapsed: 28.37 s <<< ERROR!
org.awaitility.core.ConditionTimeoutException: 
Assertion condition [List check single element] 
Expecting actual:
  class BrokerState {
    id: 2
    state: ACTIVE
    version: 2
    lastUpdatedAt: 2023-11-16T09:13:32.135700584Z
    partitions: []
}
to match 'Broker 2 has partition 2' predicate within 10 seconds.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
	at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:769)
	at io.camunda.zeebe.it.clustering.dynamic.ScaleResiliencyTest$ScaleDown.shouldContinueScaleDownAfterRestart(ScaleResiliencyTest.java:210)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.awaitility.core.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:101)
	at org.awaitility.core.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:81)
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:103)
	... 12 more
</pre>
</details>

[Test result archive](https://drive.google.com/file/d/1iVtdYDtFkpBmLCzvspbXvTVPADR4btf3/view?usp=drive_link) (internal drive link)

**Comment by oleschoenburg** [comment]
Possibly related to https://github.com/camunda/zeebe/pull/15690, at least I can't reproduce it when I revert that PR.

**Comment by koevskinikola** [comment]
Flakiness occured again here: https://github.com/camunda/zeebe/actions/runs/7288151832/job/19860207881

Error:
```
Warning:  Flakes: 
Warning:  io.camunda.zeebe.it.clustering.dynamic.ScaleResiliencyTest$ScaleDown.shouldContinueScaleDownAfterRestart
Error:    Run 1: ScaleResiliencyTest$ScaleDown.shouldContinueScaleDownAfterRestart:217 » ConditionTimeout Assertion condition [List check single element] 
Expecting actual:
  class BrokerState {
    id: 2
    state: ACTIVE
    version: 0
    lastUpdatedAt: -999999999-01-01T00:00+18:00
    partitions: [class PartitionState {
        id: 2
        state: ACTIVE
        priority: 1
    }]
}
to match 'Broker 2 has partition 2' predicate within 10 seconds.
[INFO]   Run 2: PASS
```

**Comment by oleschoenburg** [comment]
From a failed run:
```
16:16:50.019 [Broker-2] [ClusterTopologyManagerService] [zb-actors-1] DEBUG io.camunda.zeebe.topology.ClusterTopologyManagerImpl - Received new topology ClusterTopology[version=4, members={1=MemberState[version=0, lastUpdated=-1000000000-01-01T00:00:00Z, state=ACTIVE, partitions={1=PartitionState[state=ACTIVE, priority=1], 2=PartitionState[state=ACTIVE, priority=2]}], 2=MemberState[version=0, lastUpdated=-1000000000-01-01T00:00:00Z, state=ACTIVE, partitions={2=PartitionState[state=ACTIVE, priority=1]}], 0=MemberState[version=2, lastUpdated=2023-12-21T15:16:49.556896679Z, state=ACTIVE, partitions={1=PartitionState[state=ACTIVE, priority=2], 2=PartitionState[state=ACTIVE, priority=1]}]}, lastChange=Optional[CompletedChange[id=2, status=COMPLETED, startedAt=2023-12-21T15:16:49.524639634Z, completedAt=2023-12-21T15:16:49.556932877Z]], pendingChanges=Optional[ClusterChangePlan[id=4, version=1, status=IN_PROGRESS, startedAt=2023-12-21T15:16:50.018465407Z, completedOperations=[], pendingOperations=[PartitionLeaveOperation[memberId=2, partitionId=2]]]]]. Updating local topology to ClusterTopology[version=4, members={1=MemberState[version=0, lastUpdated=-1000000000-01-01T00:00:00Z, state=ACTIVE, partitions={1=PartitionState[state=ACTIVE, priority=1], 2=PartitionState[state=ACTIVE, priority=2]}], 2=MemberState[version=0, lastUpdated=-1000000000-01-01T00:00:00Z, state=ACTIVE, partitions={2=PartitionState[state=ACTIVE, priority=1]}], 0=MemberState[version=2, lastUpdated=2023-12-21T15:16:49.556896679Z, state=ACTIVE, partitions={1=PartitionState[state=ACTIVE, priority=2], 2=PartitionState[state=ACTIVE, priority=1]}]}, lastChange=Optional[CompletedChange[id=2, status=COMPLETED, startedAt=2023-12-21T15:16:49.524639634Z, completedAt=2023-12-21T15:16:49.556932877Z]], pendingChanges=Optional[ClusterChangePlan[id=4, version=1, status=IN_PROGRESS, startedAt=2023-12-21T15:16:50.018465407Z, completedOperations=[], pendingOperations=[PartitionLeaveOperation[memberId=2, partitionId=2]]]]]
16:16:50.019 [Broker-2] [ClusterTopologyManagerService] [zb-actors-1] INFO  io.camunda.zeebe.topology.ClusterTopologyManagerImpl - Applying topology change operation PartitionLeaveOperation[memberId=2, partitionId=2]
16:16:50.019 [Broker-2] [ClusterTopologyManagerService] [zb-actors-1] INFO  io.camunda.zeebe.topology.gossip.ClusterTopologyGossiper - Updated local gossipState to ClusterTopology[version=4, members={1=MemberState[version=0, lastUpdated=-1000000000-01-01T00:00:00Z, state=ACTIVE, partitions={1=PartitionState[state=ACTIVE, priority=1], 2=PartitionState[state=ACTIVE, priority=2]}], 2=MemberState[version=1, lastUpdated=2023-12-21T15:16:50.019548788Z, state=ACTIVE, partitions={2=PartitionState[state=LEAVING, priority=1]}], 0=MemberState[version=2, lastUpdated=2023-12-21T15:16:49.556896679Z, state=ACTIVE, partitions={1=PartitionState[state=ACTIVE, priority=2], 2=PartitionState[state=ACTIVE, priority=1]}]}, lastChange=Optional[CompletedChange[id=2, status=COMPLETED, startedAt=2023-12-21T15:16:49.524639634Z, completedAt=2023-12-21T15:16:49.556932877Z]], pendingChanges=Optional[ClusterChangePlan[id=4, version=1, status=IN_PROGRESS, startedAt=2023-12-21T15:16:50.018465407Z, completedOperations=[], pendingOperations=[PartitionLeaveOperation[memberId=2, partitionId=2]]]]]
16:16:50.019 [Broker-2] [ClusterTopologyManagerService] [zb-actors-1] DEBUG io.camunda.zeebe.gateway - Received new cluster topology with clusterSize 3
16:16:50.019 [Broker-2] [ClusterTopologyManagerService] [zb-actors-1] INFO  io.camunda.zeebe.topology.gossip.ClusterTopologyGossiper - Updated local gossipState to ClusterTopology[version=4, members={1=MemberState[version=0, lastUpdated=-1000000000-01-01T00:00:00Z, state=ACTIVE, partitions={1=PartitionState[state=ACTIVE, priority=1], 2=PartitionState[state=ACTIVE, priority=2]}], 2=MemberState[version=0, lastUpdated=-1000000000-01-01T00:00:00Z, state=ACTIVE, partitions={2=PartitionState[state=ACTIVE, priority=1]}], 0=MemberState[version=2, lastUpdated=2023-12-21T15:16:49.556896679Z, state=ACTIVE, partitions={1=PartitionState[state=ACTIVE, priority=2], 2=PartitionState[state=ACTIVE, priority=1]}]}, lastChange=Optional[CompletedChange[id=2, status=COMPLETED, startedAt=2023-12-21T15:16:49.524639634Z, completedAt=2023-12-21T15:16:49.556932877Z]], pendingChanges=Optional[ClusterChangePlan[id=4, version=1, status=IN_PROGRESS, startedAt=2023-12-21T15:16:50.018465407Z, completedOperations=[], pendingOperations=[PartitionLeaveOperation[memberId=2, partitionId=2]]]]]
16:16:50.019 [Broker-2] [ClusterTopologyManagerService] [zb-actors-1] DEBUG io.camunda.zeebe.gateway - Received new cluster topology with clusterSize 3
16:16:50.019 [Broker-2] [Startup] [zb-actors-1] INFO  io.camunda.zeebe.broker.partitioning.PartitionManagerImpl - Leaving partition 2
```

**Comment by berkaycanbc** [comment]
Occurred again here: https://github.com/camunda/zeebe/actions/runs/7319154009/job/19936666530#step:10:473

<details>
  <summary>Error Details</summary>

```
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 16.31 s <<< FAILURE! -- in io.camunda.zeebe.it.clustering.dynamic.ScaleResiliencyTest$ScaleDown
Error:  io.camunda.zeebe.it.clustering.dynamic.ScaleResiliencyTest$ScaleDown.shouldContinueScaleDownAfterRestart -- Time elapsed: 16.31 s <<< ERROR!
org.awaitility.core.ConditionTimeoutException: 
Assertion condition [List check single element] 
Expecting actual:
  class BrokerState {
    id: 2
    state: ACTIVE
    version: 0
    lastUpdatedAt: -999999999-01-01T00:00+18:00
    partitions: [class PartitionState {
        id: 2
        state: ACTIVE
        priority: 1
    }]
}
to match 'Broker 2 has partition 2' predicate within 10 seconds.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
	at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:769)
	at io.camunda.zeebe.it.clustering.dynamic.ScaleResiliencyTest$ScaleDown.shouldContinueScaleDownAfterRestart(ScaleResiliencyTest.java:217)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.lang.AssertionError: [List check single element] 
Expecting actual:
  class BrokerState {
    id: 2
    state: ACTIVE
    version: 0
    lastUpdatedAt: -999999999-01-01T00:00+18:00
    partitions: [class PartitionState {
        id: 2
        state: ACTIVE
        priority: 1
    }]
}
to match 'Broker 2 has partition 2' predicate.
	at io.camunda.zeebe.qa.util.topology.ClusterActuatorAssert.brokerHasPartitionAtState(ClusterActuatorAssert.java:104)
	at io.camunda.zeebe.it.clustering.dynamic.ScaleResiliencyTest$ScaleDown.lambda$shouldContinueScaleDownAfterRestart$1(ScaleResiliencyTest.java:220)
	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by mustafadagher** [comment]
This has been failing again recently. 
Example failure run: https://github.com/camunda/camunda/actions/runs/16748818438/job/47413690454?pr=36227

**Comment by entangled90** [comment]
I don't see any entry in the flaky tests dashboard for this class. 
However, I see that the last build failed by @mustafadagher  was a timeout (which lead to the job being cancelled). 
Is there a way to find more recent failures when it times out?
All the logs in the link are expired by now :-(
