### ISSUE TITLE
ScaleResiliencyTest$ScaleUp.shouldContinueScaleAfterRestart unstable

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#15351]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? once
- Does it block your work? maybe
- Do we suspect that it is a real failure? Maybe

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 21.20 s <<< FAILURE! -- in io.camunda.zeebe.it.clustering.dynamic.ScaleResiliencyTest$ScaleUp
Error:  io.camunda.zeebe.it.clustering.dynamic.ScaleResiliencyTest$ScaleUp.shouldContinueScaleAfterRestart -- Time elapsed: 21.20 s <<< ERROR!
java.util.NoSuchElementException: No available gateway for cluster
	at io.camunda.zeebe.qa.util.cluster.TestCluster.lambda$availableGateway$4(TestCluster.java:193)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.camunda.zeebe.qa.util.cluster.TestCluster.availableGateway(TestCluster.java:193)
	at io.camunda.zeebe.it.clustering.dynamic.Utils.scale(Utils.java:43)
	at io.camunda.zeebe.it.clustering.dynamic.ScaleResiliencyTest$ScaleUp.shouldContinueScaleAfterRestart(ScaleResiliencyTest.java:122)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**
[io.camunda.zeebe.it.clustering.dynamic.ScaleResiliencyTest.txt](https://github.com/camunda/zeebe/files/13457177/io.camunda.zeebe.it.clustering.dynamic.ScaleResiliencyTest.txt)
[io.camunda.zeebe.it.clustering.dynamic.ScaleResiliencyTest$ScaleUp.txt](https://github.com/camunda/zeebe/files/13457178/io.camunda.zeebe.it.clustering.dynamic.ScaleResiliencyTest.ScaleUp.txt)
[io.camunda.zeebe.it.clustering.dynamic.ScaleResiliencyTest$ScaleUp-2-output.txt](https://github.com/camunda/zeebe/files/13457179/io.camunda.zeebe.it.clustering.dynamic.ScaleResiliencyTest.ScaleUp-2-output.txt)
[io.camunda.zeebe.it.clustering.dynamic.ScaleResiliencyTest$ScaleUp-1-output.txt](https://github.com/camunda/zeebe/files/13457180/io.camunda.zeebe.it.clustering.dynamic.ScaleResiliencyTest.ScaleUp-1-output.txt)
[io.camunda.zeebe.it.clustering.dynamic.ScaleResiliencyTest$ScaleDown.txt](https://github.com/camunda/zeebe/files/13457181/io.camunda.zeebe.it.clustering.dynamic.ScaleResiliencyTest.ScaleDown.txt)
[io.camunda.zeebe.it.clustering.dynamic.ScaleResiliencyTest$ScaleDown-1-output.txt](https://github.com/camunda/zeebe/files/13457182/io.camunda.zeebe.it.clustering.dynamic.ScaleResiliencyTest.ScaleDown-1-output.txt)

**Comment by berkaycanbc** [comment]
Happened in one of the builds https://github.com/camunda/zeebe/actions/runs/6972188309/job/18993463592?pr=15307

**Comment by nicpuppa** [comment]
Happened again [here](https://github.com/camunda/zeebe/actions/runs/7003591770/job/19049629353?pr=15361)

**Comment by berkaycanbc** [comment]
Happened again https://github.com/camunda/zeebe/actions/runs/7019579999/job/19097316284?pr=15365
