### ISSUE TITLE
NullPointerException StraightThroughProcessingLoopValidator cannot fetch next element

### ISSUE THREAD

**Issue by rodrigo-lourenco-lopes** [camunda/zeebe#15369]
**Describe the bug**

StraightThroughProcessingLoopValidator cannot load the next element and gets a NullPointerException.

```
ava.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:?]
	at java.util.ImmutableCollections$List12.<init>(Unknown Source) ~[?:?]
	at java.util.List.of(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.deployment.model.validation.StraightThroughProcessingLoopValidator.lambda$getNextElements$4(StraightThroughProcessingLoopValidator.java:234) ~[zeebe-workflow-engine-8.3.3.jar:8.3.3]
	at java.util.Optional.map(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.deployment.model.validation.StraightThroughProcessingLoopValidator.getNextElements(StraightThroughProcessingLoopValidator.java:234) ~[zeebe-workflow-engine-8.3.3.jar:8.3.3]
	at io.camunda.zeebe.engine.processing.deployment.model.validation.StraightThroughProcessingLoopValidator.checkForStraightThroughProcessingLoop(StraightThroughProcessingLoopValidator.java:186) ~[zeebe-workflow-engine-8.3.3.jar:8.3.3]
	at io.camunda.zeebe.engine.processing.deployment.model.validation.StraightThroughProcessingLoopValidator.hasStraightThroughProcessingLoop(StraightThroughProcessingLoopValidator.java:106) ~[zeebe-workflow-engine-8.3.3.jar:8.3.3]
	at io.camunda.zeebe.engine.processing.deployment.model.validation.StraightThroughProcessingLoopValidator.validate(StraightThroughProcessingLoopValidator.java:68) ~[zeebe-workflow-engine-8.3.3.jar:8.3.3]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.lambda$transformResource$1(BpmnResourceTransformer.java:87) ~[zeebe-workflow-engine-8.3.3.jar:8.3.3]
	at io.camunda.zeebe.util.Either$Right.flatMap(Either.java:366) ~[zeebe-util-8.3.3.jar:8.3.3]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.lambda$transformResource$3(BpmnResourceTransformer.java:84) ~[zeebe-workflow-engine-8.3.3.jar:8.3.3]
	at io.camunda.zeebe.util.Either$Right.flatMap(Either.java:366) ~[zeebe-util-8.3.3.jar:8.3.3]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.transformResource(BpmnResourceTransformer.java:70) ~[zeebe-workflow-engine-8.3.3.jar:8.3.3]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transformResource(DeploymentTransformer.java:130) ~[zeebe-workflow-engine-8.3.3.jar:8.3.3]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transform(DeploymentTransformer.java:106) ~[zeebe-workflow-engine-8.3.3.jar:8.3.3]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.transformAndDistributeDeployment(DeploymentCreateProcessor.java:145) ~[zeebe-workflow-engine-8.3.3.jar:8.3.3]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.processNewCommand(DeploymentCreateProcessor.java:102) ~[zeebe-workflow-engine-8.3.3.jar:8.3.3]
	at io.camunda.zeebe.engine.processing.streamprocessor.DistributedTypedRecordProcessor.processRecord(DistributedTypedRecordProcessor.java:33) ~[zeebe-workflow-engine-8.3.3.jar:8.3.3]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[zeebe-workflow-engine-8.3.3.jar:8.3.3]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:356) ~[zeebe-stream-platform-8.3.3.jar:8.3.3]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$2(ProcessingStateMachine.java:272) ~[zeebe-stream-platform-8.3.3.jar:8.3.3]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:98) ~[zeebe-db-8.3.3.jar:8.3.3]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:272) ~[zeebe-stream-platform-8.3.3.jar:8.3.3]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:231) ~[zeebe-stream-platform-8.3.3.jar:8.3.3]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:207) ~[zeebe-stream-platform-8.3.3.jar:8.3.3]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) [zeebe-scheduler-8.3.3.jar:8.3.3]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) [zeebe-scheduler-8.3.3.jar:8.3.3]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:120) [zeebe-scheduler-8.3.3.jar:8.3.3]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.3.3.jar:8.3.3]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.3.3.jar:8.3.3]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.3.3.jar:8.3.3]
```

**To Reproduce**

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
```

</p>
</details>

[Camunda Cloud Logs 2023.json](https://github.com/camunda/zeebe/files/13477530/Camunda.Cloud.Logs.2023.json)

**Environment:**
- OS: 
- Zeebe Version: 8.3.3
- Configuration:

**Comment by koevskinikola** [comment]
ZPA individual triage:
- The failure happens during the validation that the process doesn't contain a straight-through processing loop. This validator was added to prevent a process like this from crashing the stream processor since it manages to create records faster than Zeebe can process them.
- It would be difficult to understand what exactly triggered the NPE, as the failure happened during deployment and the process is unavailable (since the deployment failed).
  - It looks like the NPE is thrown when it attempts to get the `None Start events` of a CallActivity ([src](https://github.com/camunda/zeebe/blob/87c2fc523653976a2659f5e6f7c90e670e6ba337/engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/model/validation/StraightThroughProcessingLoopValidator.java#L234)).
- Severity is `low`, as no process was deployed, so:
  - The user got feedback that something was wrong with their process.
  - Nothing was deployed to Zeebe.
- Size is `x-small` as we need to detect what is wrong and adjust the validator logic that I linked above.

**Comment by berkaycanbc** [comment]
ZPA Triage:

This issue can also be resolved with https://github.com/camunda/zeebe/issues/12560 where we might not need the straight through processing loop validator anymore.

**Comment by berkaycanbc** [comment]
Another occurrence on SaaS Prod: [LINK](https://console.cloud.google.com/errors/detail/CICVz8m9rKvTrQE;service=zeebe;time=P7D;locations=global?project=camunda-saas-prod)
Didn't download logs as it is not different than what is shared above. Needs to be tested locally to re-produce.
