### ISSUE TITLE
GatewayAuthenticationIdentityIT.getTopologyRequestSucceedsWithValidAuthToken is flaky

### ISSUE THREAD

**Issue by nicpuppa** [camunda/zeebe#15429]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail?
- Does it block your work?
- Do we suspect that it is a real failure?

**Failures**

```
Expecting
  <RetriableClientFutureImpl[Failed with the following stack trace:
io.grpc.StatusRuntimeException: CANCELLED
	at io.grpc.Status.asRuntimeException(Status.java:537)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:481)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:489)
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:453)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:486)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.io.IOException: Failed while requesting access token with status code 401 and message Unauthorized.
	at io.camunda.zeebe.client.impl.oauth.OAuthCredentialsProvider.fetchCredentials(OAuthCredentialsProvider.java:162)
	at io.camunda.zeebe.client.impl.oauth.OAuthCredentialsCache.computeIfMissingOrInvalid(OAuthCredentialsCache.java:100)
	at io.camunda.zeebe.client.impl.oauth.OAuthCredentialsProvider.applyCredentials(OAuthCredentialsProvider.java:84)
	at io.camunda.zeebe.client.impl.ZeebeCallCredentials.lambda$applyRequestMetadata$0(ZeebeCallCredentials.java:48)
	... 3 more
]>
to be completed within 5S.
```

**Logs**

[Test results for [IT] QA Integration Tests (2).zip](https://github.com/camunda/zeebe/files/13510468/Test.results.for.IT.QA.Integration.Tests.2.zip)

**Comment by npepinpe** [comment]
ZDP triage: we think OAuth and Identity integration fall into the ZPA domain, and we see you're already planning to work on it, so we'll remove it from our board :upside_down_face:

**Comment by ana-vinogradova-camunda** [comment]
Happened again, the build is [here](https://github.com/camunda/zeebe/actions/runs/7460242106/job/20297927347)

**Comment by koevskinikola** [comment]
Happened again [here](https://github.com/camunda/zeebe/actions/runs/7524909037/job/20480413981).

Test results are [here (internal)](https://drive.google.com/file/d/1w7pASCVlkpSkzeMDkMUZMrHPTz5dVOJQ/view?usp=drive_link).

**Comment by koevskinikola** [comment]
Happened again [here](https://github.com/camunda/zeebe/actions/runs/7553365764/job/20564039433).

**Comment by nicpuppa** [comment]
Happened again [here](https://github.com/camunda/zeebe/actions/runs/7803160810/job/21282284972?pr=15976)

**Comment by oleschoenburg** [comment]
And again here: https://github.com/camunda/zeebe/actions/runs/7806348629/job/21292519405

**Comment by npepinpe** [comment]
And again :upside_down_face: https://github.com/camunda/zeebe/actions/runs/7901725887/job/21565822997
