### ISSUE TITLE
Bootstrap step Cluster Topology Manager failed

### ISSUE THREAD

**Issue by nicpuppa** [camunda/zeebe#15499]
**Describe the bug**

```
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:774) ~[spring-boot-3.1.6.jar:3.1.6]
	at org.springframework.boot.SpringApplication.lambda$callRunners$3(SpringApplication.java:755) [spring-boot-3.1.6.jar:3.1.6]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:750) [spring-boot-3.1.6.jar:3.1.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:323) [spring-boot-3.1.6.jar:3.1.6]
	at io.camunda.zeebe.broker.StandaloneBroker.main(StandaloneBroker.java:78) [camunda-zeebe-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
Caused by: io.camunda.zeebe.util.exception.UncheckedExecutionException: Failed to start broker
	at io.camunda.zeebe.broker.Broker.internalStart(Broker.java:111) ~[zeebe-broker-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at io.camunda.zeebe.util.LogUtil.doWithMDC(LogUtil.java:23) ~[zeebe-util-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at io.camunda.zeebe.broker.Broker.start(Broker.java:85) ~[zeebe-broker-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at io.camunda.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:88) ~[camunda-zeebe-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771) ~[spring-boot-3.1.6.jar:3.1.6]
	... 12 more
Caused by: java.util.concurrent.ExecutionException: Startup failed in the following steps: [Cluster Topology Manager]. See suppressed exceptions for details.
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.get(CompletableActorFuture.java:145) ~[zeebe-scheduler-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.get(CompletableActorFuture.java:112) ~[zeebe-scheduler-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.FutureUtil.join(FutureUtil.java:21) ~[zeebe-scheduler-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.join(CompletableActorFuture.java:201) ~[zeebe-scheduler-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at io.camunda.zeebe.broker.Broker.internalStart(Broker.java:102) ~[zeebe-broker-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at io.camunda.zeebe.util.LogUtil.doWithMDC(LogUtil.java:23) ~[zeebe-util-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at io.camunda.zeebe.broker.Broker.start(Broker.java:85) ~[zeebe-broker-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at io.camunda.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:88) ~[camunda-zeebe-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771) ~[spring-boot-3.1.6.jar:3.1.6]
	... 12 more
Caused by: io.camunda.zeebe.scheduler.startup.StartupProcessException: Startup failed in the following steps: [Cluster Topology Manager]. See suppressed exceptions for details.
	at io.camunda.zeebe.scheduler.startup.StartupProcess.aggregateExceptionsSynchronized(StartupProcess.java:283) ~[zeebe-scheduler-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.startup.StartupProcess.completeStartupFutureExceptionallySynchronized(StartupProcess.java:184) ~[zeebe-scheduler-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.startup.StartupProcess.lambda$proceedWithStartupSynchronized$3(StartupProcess.java:168) ~[zeebe-scheduler-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:33) ~[zeebe-scheduler-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:96) ~[zeebe-scheduler-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) ~[zeebe-scheduler-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:120) ~[zeebe-scheduler-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) ~[zeebe-scheduler-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) ~[zeebe-scheduler-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) ~[zeebe-scheduler-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	Suppressed: io.camunda.zeebe.scheduler.startup.StartupProcessStepException: Bootstrap step Cluster Topology Manager failed
		at io.camunda.zeebe.scheduler.startup.StartupProcess.completeStartupFutureExceptionallySynchronized(StartupProcess.java:186) ~[zeebe-scheduler-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
		at io.camunda.zeebe.scheduler.startup.StartupProcess.lambda$proceedWithStartupSynchronized$3(StartupProcess.java:168) ~[zeebe-scheduler-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
		at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:33) ~[zeebe-scheduler-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
		at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:96) ~[zeebe-scheduler-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
		at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) ~[zeebe-scheduler-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
		at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:120) ~[zeebe-scheduler-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
		at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) ~[zeebe-scheduler-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
		at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) ~[zeebe-scheduler-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
		at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) ~[zeebe-scheduler-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
	Caused by: io.camunda.zeebe.topology.PersistedClusterTopology$UnexpectedVersion: Topology file /usr/local/zeebe/data/.topology.meta had version '8', but expected version '1'
		at io.camunda.zeebe.topology.PersistedClusterTopology.readFromFile(PersistedClusterTopology.java:97) ~[zeebe-cluster-topology-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
		at io.camunda.zeebe.topology.PersistedClusterTopology.ofFile(PersistedClusterTopology.java:59) ~[zeebe-cluster-topology-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
		at io.camunda.zeebe.topology.ClusterTopologyManagerService.<init>(ClusterTopologyManagerService.java:69) ~[zeebe-cluster-topology-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
		at io.camunda.zeebe.broker.partitioning.topology.DynamicClusterTopologyService.getClusterTopologyManagerService(DynamicClusterTopologyService.java:124) ~[zeebe-broker-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
		at io.camunda.zeebe.broker.partitioning.topology.DynamicClusterTopologyService.start(DynamicClusterTopologyService.java:54) ~[zeebe-broker-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
		at io.camunda.zeebe.broker.bootstrap.ClusterTopologyManagerStep.startup(ClusterTopologyManagerStep.java:33) ~[zeebe-broker-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
		at io.camunda.zeebe.broker.bootstrap.ClusterTopologyManagerStep.startup(ClusterTopologyManagerStep.java:16) ~[zeebe-broker-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
		at io.camunda.zeebe.broker.bootstrap.BrokerStepMetricDecorator.callDelegateAndUpdateTimer(BrokerStepMetricDecorator.java:62) ~[zeebe-broker-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
		at io.camunda.zeebe.broker.bootstrap.BrokerStepMetricDecorator.startup(BrokerStepMetricDecorator.java:44) ~[zeebe-broker-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
		at io.camunda.zeebe.broker.bootstrap.BrokerStepMetricDecorator.startup(BrokerStepMetricDecorator.java:25) ~[zeebe-broker-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
		at io.camunda.zeebe.scheduler.startup.StartupProcess.proceedWithStartupSynchronized(StartupProcess.java:162) ~[zeebe-scheduler-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
		at io.camunda.zeebe.scheduler.startup.StartupProcess.lambda$proceedWithStartupSynchronized$3(StartupProcess.java:170) ~[zeebe-scheduler-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
		at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) ~[zeebe-scheduler-8.4.0-SNAPSHOT.jar:8.4.0-SNAPSHOT]
		... 6 more

```

**Impact:**
Fails broker startup, the cluster is crashlooping

**Log/Stacktrace**

[link to logs group](https://console.cloud.google.com/errors/detail/CJfbwJe6l6PCpQE;service=zeebe;time=P7D?project=camunda-saas-int-chaos)

[link to logs](https://drive.google.com/drive/folders/1pIvOz3IKPF5Y6QiRJ8Moc-ZTxxAUFFmz)

**Environment:**
- Zeebe Version: zeebe:SNAPSHOT
- Env: camunda-saas-int-chaos

**Comment by nicpuppa** [comment]
From the logs we can see that this crashlooping started after a shutdown [internal logs](https://cloudlogging.app.goo.gl/BCvmNJkCFGgz1jbs6)

**Comment by oleschoenburg** [comment]
This error is expected, this PR introduced breaking changes on SNAPSHOT: https://github.com/camunda/zeebe/pull/15441

**Comment by nicpuppa** [comment]
I can assign this to you @oleschoenburg ?

**Comment by oleschoenburg** [comment]
I think we can close this issue. It's an expected error that we won't fix. Affected clusters need to be fixed manually or recreated.
