### ISSUE TITLE
ZeebeDbInconsistentException on migrating a service task with a message boundary event

### ISSUE THREAD

**Issue by saig0** [camunda/zeebe#15570]
**Describe the bug**

I try to migrate a process instance with a service task that has a message boundary event. The message boundary event is the same for the current and the new version of the process.

The migration fails with `ZeebeDbInconsistentException`. 

![Screenshot from 2023-12-12 14-01-18](https://github.com/camunda/zeebe/assets/4305769/17fbd160-efcf-46a4-a09a-4cdf36934860)

During the migration, Zeebe deletes and creates the event subscriptions for the active element instance. However, this is more complicated for message subscriptions because they can be managed on a different partition. Before removing the process message subscription from the state, it marks the subscript as "closing" until the deletion is acknowledged by a message subscription delete command (from the other partition). If Zeebe creates a new subscription for the same message name and correlation key, the state detects the existing subscription and throws the error.  

**To Reproduce**

<details><summary>Test case for MigrateProcessInstanceTest</summary>
 <p>

```
  @Test
  public void shouldMigrateServiceTaskWithMessageBoundaryEvent() {
    // given
    final String processId1 = helper.getBpmnProcessId();
    final String processId2 = helper.getBpmnProcessId() + "2";

    final var deployment =
        ENGINE
            .deployment()
            .withXmlResource(
                Bpmn.createExecutableProcess(processId1)
                    .startEvent()
                    .serviceTask("A", a -> a.zeebeJobType("A"))
                    .boundaryEvent("message")
                    .message(m -> m.name("message").zeebeCorrelationKeyExpression("key"))
                    .endEvent()
                    .done())
            .withXmlResource(
                Bpmn.createExecutableProcess(processId2)
                    .startEvent()
                    .serviceTask("B", a -> a.zeebeJobType("B"))
                    .boundaryEvent("message")
                    .message(m -> m.name("message").zeebeCorrelationKeyExpression("key"))
                    .endEvent()
                    .done())
            .deploy();

    final long otherProcessDefinitionKey =
        extractProcessDefinitionKeyByProcessId(deployment, processId2);

    final var processInstanceKey =
        ENGINE
            .processInstance()
            .ofBpmnProcessId(processId1)
            .withVariable("key", helper.getCorrelationValue())
            .create();

    // when
    final var event =
        ENGINE
            .processInstance()
            .withInstanceKey(processInstanceKey)
            .migration()
            .withTargetProcessDefinitionKey(otherProcessDefinitionKey)
            .addMappingInstruction("A", "B")
            .migrate();

    // then
    assertThat(event)
        .hasKey(processInstanceKey)
        .hasRecordType(RecordType.EVENT)
        .hasIntent(ProcessInstanceMigrationIntent.MIGRATED);
  }
```

</p>
</details>

**Expected behavior**

I can migrate a service task with a message boundary event. After the migration, the service task should be active and a message can correlate to the message boundary event. 

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
13:54:31.595 [StreamProcessor-1] ERROR io.camunda.zeebe.processor - Expected to process record 'LoggedEvent [position=27, key=2251799813685252, timestamp=1702385671579, sourceEventPosition=-1] RecordMetadata{recordType=COMMAND, valueType=PROCESS_INSTANCE_MIGRATION, intent=MIGRATE, authorization=JWT.eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJpc3MiOiJ6ZWViZS1nYXRld2F5IiwiYXVkIjoiemVlYmUtYnJva2VyIiwic3ViIjoiemVlYmUtY2xpZW50IiwiYXV0aG9yaXplZF90ZW5hbnRzIjpbIjxkZWZhdWx0PiJdfQ.}' successfully on stream processor, but caught unrecoverable exception.
13:54:31.596 [StreamProcessor-1] ERROR io.camunda.zeebe.logstreams - Actor StreamProcessor-1 failed in phase STARTED.
io.camunda.zeebe.db.ZeebeDbInconsistentException: Key DbCompositeKey{first=DbLong{2251799813685257}, second=DbTenantAwareKey[tenantKey=<default>, wrappedKey=message, placementType=PREFIX]} in ColumnFamily PROCESS_SUBSCRIPTION_BY_KEY already exists
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.assertKeyDoesNotExist(TransactionalColumnFamily.java:297) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$insert$0(TransactionalColumnFamily.java:81) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$ensureInOpenTransaction$19(TransactionalColumnFamily.java:325) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.DefaultTransactionContext.runInTransaction(DefaultTransactionContext.java:31) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.ensureInOpenTransaction(TransactionalColumnFamily.java:324) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.insert(TransactionalColumnFamily.java:76) ~[classes/:?]
	at io.camunda.zeebe.engine.state.message.DbProcessMessageSubscriptionState.put(DbProcessMessageSubscriptionState.java:91) ~[classes/:?]
	at io.camunda.zeebe.engine.state.appliers.ProcessMessageSubscriptionCreatingApplier.applyState(ProcessMessageSubscriptionCreatingApplier.java:28) ~[classes/:?]
	at io.camunda.zeebe.engine.state.appliers.ProcessMessageSubscriptionCreatingApplier.applyState(ProcessMessageSubscriptionCreatingApplier.java:15) ~[classes/:?]
	at io.camunda.zeebe.engine.state.appliers.EventAppliers.applyState(EventAppliers.java:354) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.streamprocessor.writers.ResultBuilderBackedEventApplyingStateWriter.appendFollowUpEvent(ResultBuilderBackedEventApplyingStateWriter.java:56) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.streamprocessor.writers.ResultBuilderBackedEventApplyingStateWriter.appendFollowUpEvent(ResultBuilderBackedEventApplyingStateWriter.java:42) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.common.CatchEventBehavior.subscribeToMessageEvent(CatchEventBehavior.java:271) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.common.CatchEventBehavior.lambda$subscribeToMessageEvents$7(CatchEventBehavior.java:245) ~[classes/:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at io.camunda.zeebe.engine.processing.common.CatchEventBehavior.subscribeToMessageEvents(CatchEventBehavior.java:245) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.common.CatchEventBehavior.lambda$subscribeToEvents$4(CatchEventBehavior.java:153) ~[classes/:?]
	at io.camunda.zeebe.util.Either$Right.ifRight(Either.java:371) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.common.CatchEventBehavior.subscribeToEvents(CatchEventBehavior.java:151) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnEventSubscriptionBehavior.subscribeToEvents(BpmnEventSubscriptionBehavior.java:48) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.processinstance.ProcessInstanceMigrationMigrateProcessor.tryMigrateElementInstance(ProcessInstanceMigrationMigrateProcessor.java:249) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.processinstance.ProcessInstanceMigrationMigrateProcessor.processRecord(ProcessInstanceMigrationMigrateProcessor.java:121) ~[classes/:?]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[classes/:?]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:360) ~[classes/:?]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$2(ProcessingStateMachine.java:275) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:98) ~[classes/:?]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:275) ~[classes/:?]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:233) ~[classes/:?]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:209) ~[classes/:?]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) ~[classes/:?]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:120) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [classes/:?]
13:54:36.582 [] INFO  io.camunda.zeebe.test - Test failed, following records were exported:
13:54:36.681 [] INFO  io.camunda.zeebe.test - Compact log representation:
--------
	['C'ommand/'E'event/'R'ejection] [valueType] [intent] - #[position]->#[source record position] K[key] - [summary of value]
	P9K999 - key; #999 - record position; "ID" element/process id; @"elementid"/[P9K999] - element with ID and key
	Keys are decomposed into partition id and per partition key (e.g. 2251799813685253 -> P1K005). If single partition, the partition is omitted.
	Long IDs are shortened (e.g. 'startEvent_5d56488e-0570-416c-ba2d-36d2a3acea78' -> 'star..acea78'
--------
C DPLY         CREATE         - #01-> -1  -1 - 
E PROC         CREATED        - #02->#01 K01 - process.xml -> "process..ryEvent" (version:1)
E PROC         CREATED        - #03->#01 K02 - process.xml -> "process..yEvent2" (version:1)
E DPLY         CREATED        - #04->#01 K03 - process.xml, process.xml
C CREA         CREATE         - #05-> -1  -1 - new <process "process..ryEvent"> (default start)  with variables: {key=correlation-shouldMigrateServiceTaskWithMessageBoundaryEvent}
E VAR          CREATED        - #06->#05 K05 - key->"correlation-shouldMigrateServiceTaskWithMessageBoundaryEvent" in <process [K04]>
C PI           ACTIVATE       - #07->#05 K04 - PROCESS "process..ryEvent" in <process "process..ryEvent"[K04]>
E CREA         CREATED        - #08->#05 K06 - new <process "process..ryEvent"> (default start)  with variables: {key=correlation-shouldMigrateServiceTaskWithMessageBoundaryEvent}
E PI           ACTIVATING     - #09->#05 K04 - PROCESS "process..ryEvent" in <process "process..ryEvent"[K04]>
E PI           ACTIVATED      - #10->#05 K04 - PROCESS "process..ryEvent" in <process "process..ryEvent"[K04]>
C PI           ACTIVATE       - #11->#05  -1 - START_EVENT "startEv..a7cd23c" in <process "process..ryEvent"[K04]>
E PI           ACTIVATING     - #12->#05 K07 - START_EVENT "startEv..a7cd23c" in <process "process..ryEvent"[K04]>
E PI           ACTIVATED      - #13->#05 K07 - START_EVENT "startEv..a7cd23c" in <process "process..ryEvent"[K04]>
C PI           COMPLETE       - #14->#05 K07 - START_EVENT "startEv..a7cd23c" in <process "process..ryEvent"[K04]>
E PI           COMPLETING     - #15->#05 K07 - START_EVENT "startEv..a7cd23c" in <process "process..ryEvent"[K04]>
E PI           COMPLETED      - #16->#05 K07 - START_EVENT "startEv..a7cd23c" in <process "process..ryEvent"[K04]>
E PI           SEQ_FLOW_TAKEN - #17->#05 K08 - SEQUENCE_FLOW "sequenc..9be549d" in <process "process..ryEvent"[K04]>
C PI           ACTIVATE       - #18->#05 K09 - SERVICE_TASK "A" in <process "process..ryEvent"[K04]>
E PI           ACTIVATING     - #19->#05 K09 - SERVICE_TASK "A" in <process "process..ryEvent"[K04]>
E PROC_MSG_SUB CREATING       - #20->#05 K10 - "message" (inter.) correlationKey: correlation-shouldMigrateServiceTaskWithMessageBoundaryEvent @[K09] in <process "process..ryEvent"[K04]> (no vars) (tenant: <default>)
C MSG_SUB      CREATE         - #21->#05  -1 - "message" (inter.) correlationKey: correlation-shouldMigrateServiceTaskWithMessageBoundaryEvent @[K09] in <process "process..ryEvent"[K04]> (no vars)
E JOB          CREATED        - #22->#05 K11 - K11 "A" @"A"[K09] 3 retries, in <process "process..ryEvent"[K04]> (no vars)
E PI           ACTIVATED      - #23->#05 K09 - SERVICE_TASK "A" in <process "process..ryEvent"[K04]>
E MSG_SUB      CREATED        - #24->#05 K12 - "message" (inter.) correlationKey: correlation-shouldMigrateServiceTaskWithMessageBoundaryEvent @[K09] in <process "process..ryEvent"[K04]> (no vars)
C PROC_MSG_SUB CREATE         - #25->#05  -1 - "message" (inter.) @[K09] in <process ?[K04]> (no vars) (tenant: <default>)
E PROC_MSG_SUB CREATED        - #26->#05 K10 - "message" (inter.) correlationKey: correlation-shouldMigrateServiceTaskWithMessageBoundaryEvent @[K09] in <process "process..ryEvent"[K04]> (no vars) (tenant: <default>)
C PI_MIGRATION MIGRATE        - #27-> -1 K04 - ProcessInstanceMigrationRecord {"processInstanceKey":2251799813685252,"targetProcessDefinitionKey":2251799813685250,"mappingInstructions":[{"sourceElementId":"A","targetElementId":"B"}]}
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: `8.4.0-SNAPSHOT`
- Configuration:

**Comment by berkaycanbc** [comment]
Since we will revert the changes of #15407, this issue will not exist anymore. (See the revert issue #15659)

We should re-open this issue if it occurs with the further implementation.

Closing this one. @saig0
