### ISSUE TITLE
Elasticsearch ILM Validation

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#15899]
**Describe the bug**

We should validate the inputs given for ILM configs. I recently ran into the issue that I was setting a wrong value (missing the unit), which caused the elastic search exporter to fail, but the broker was happily running. We could also easily add the expected unit (of days?)

From the given exception message it was also not super clear since it is hidden in the stack trace.

**To Reproduce**

Deploy our helm charts with enabled retention policy:

```
    # Retention can be used to define the data in Elasticsearch (ILM).
    retention:
      ## @param zeebe.retention.enabled if true, the ILM Policy is created and applied to the index templates.
      enabled: true
      ## @param zeebe.retention.minimumAge defines how old the data must be, before the data is deleted as a duration.
      minimumAge: 1
```

**Expected behavior**

We either accept the value or fail on the start, since we can detect this issue up front.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
io.camunda.zeebe.exporter.ElasticsearchExporterException: Failed to put index lifecycle management policy
	at io.camunda.zeebe.exporter.ElasticsearchClient.putIndexLifecycleManagementPolicy(ElasticsearchClient.java:220) ~[zeebe-elasticsearch-exporter-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.exporter.ElasticsearchExporter.createIndexLifecycleManagementPolicy(ElasticsearchExporter.java:306) ~[zeebe-elasticsearch-exporter-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.exporter.ElasticsearchExporter.createIndexTemplates(ElasticsearchExporter.java:193) ~[zeebe-elasticsearch-exporter-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.exporter.ElasticsearchExporter.export(ElasticsearchExporter.java:95) ~[zeebe-elasticsearch-exporter-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.lambda$export$5(ExporterContainer.java:181) ~[zeebe-broker-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.util.jar.ThreadContextUtil.runCheckedWithClassLoader(ThreadContextUtil.java:58) ~[zeebe-util-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.util.jar.ThreadContextUtil.runWithClassLoader(ThreadContextUtil.java:34) ~[zeebe-util-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.export(ExporterContainer.java:180) ~[zeebe-broker-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.exportRecord(ExporterContainer.java:167) ~[zeebe-broker-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.broker.exporter.stream.ExporterDirector$RecordExporter.export(ExporterDirector.java:528) ~[zeebe-broker-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.retry.BackOffRetryStrategy.run(BackOffRetryStrategy.java:51) ~[zeebe-scheduler-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:96) [zeebe-scheduler-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) [zeebe-scheduler-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
Caused by: org.elasticsearch.client.ResponseException: method [PUT], host [http://ck-test-helm-elasticsearch:9200], URI [/_ilm/policy/zeebe-record-retention-policy], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"x_content_parse_exception","reason":"[1:42] [phase] failed to parse field [min_age]"}],"type":"x_content_parse_exception","reason":"[1:42] [put_lifecycle_request] failed to parse field [policy]","caused_by":{"type":"x_content_parse_exception","reason":"[1:42] [lifecycle_policy] failed to parse field [phases]","caused_by":{"type":"x_content_parse_exception","reason":"[1:42] [phases] failed to parse field [delete]","caused_by":{"type":"x_content_parse_exception","reason":"[1:42] [phase] failed to parse field [min_age]","caused_by":{"type":"illegal_argument_exception","reason":"failed to parse setting [min_age] with value [1] as a time value: unit is missing or unrecognized"}}}}},"status":400}
	at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:347) ~[elasticsearch-rest-client-8.9.2.jar:8.9.2]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:313) ~[elasticsearch-rest-client-8.9.2.jar:8.9.2]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288) ~[elasticsearch-rest-client-8.9.2.jar:8.9.2]
	at io.camunda.zeebe.exporter.ElasticsearchClient.sendRequest(ElasticsearchClient.java:232) ~[zeebe-elasticsearch-exporter-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.exporter.ElasticsearchClient.putIndexLifecycleManagementPolicy(ElasticsearchClient.java:217) ~[zeebe-elasticsearch-exporter-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	... 16 more
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: SNAPSHOT 
- Configuration:

**Comment by korthout** [comment]
ZPA triage:
- validating the config of this exporter is our domain
- ensuring that the broker does not start when one of the exporters doesn't start is a ZDP responsibility
- severity is low (visible in logs and metrics), but inconvenient 
- priority: later, good first issue (focus on validation of Elasticsearch exporter configs; feel free to ask for more directions if needed)

@Zelldon Does the broker already support the described behavior: broker does not start when one of the exporters doesn't start?

**Comment by Zelldon** [comment]
I did this for ES. See #15928 unclear to me whether we want/need the same for OS. I let you @camunda/zeebe-process-automation decide such thing

**Comment by korthout** [comment]
OS's ISM only supports specific time units as well:
- https://opensearch.org/docs/latest/api-reference/units/
- https://opensearch.org/docs/latest/im-plugin/ism/policies/#rollover see `min_index_age`
- It [uses similar/thesame logic](https://github.com/opensearch-project/OpenSearch/blob/904c9a99987c5bb2b2db02a9e2c911af51f23616/libs/common/src/main/java/org/opensearch/common/unit/TimeValue.java#L379-L410) to parse the timevalue as Elasticsearch

**Comment by Zelldon** [comment]
I opened #15987 and will close this issue then as completed
