### ISSUE TITLE
Incorrect Form deployment throws NPE

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#15956]
**Describe the bug**

A `NullPointerException` is thrown when a `Form` resource is transformed and the JSON of the form can't be properly parsed.
A `JsonProcessingException` is thrown without a `Throwable` cause. However, we attempt to [extract the exception message](https://github.com/camunda/zeebe/blob/9a8e97854bd3a37cc0e0417cf4e36a1f2c4a3681/engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/transform/FormResourceTransformer.java#L82) from a `getCause` object that doesn't exist, resulting in an NPE.

**To Reproduce**

1. Deploy a Form that doesn't have a `formId`.
2. An NPE is thrown.

**Expected behavior**

No NPE is thrown, but a properly formatted error message is provided.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.NullPointerException: Cannot invoke "java.lang.Throwable.getMessage()" because the return value of "com.fasterxml.jackson.core.JsonProcessingException.getCause()" is null
	at io.camunda.zeebe.engine.processing.deployment.transform.FormResourceTransformer.parseFormId(FormResourceTransformer.java:82) ~[zeebe-workflow-engine-8.4.0-alpha2.jar:8.4.0-alpha2]
	at io.camunda.zeebe.engine.processing.deployment.transform.FormResourceTransformer.transformResource(FormResourceTransformer.java:58) ~[zeebe-workflow-engine-8.4.0-alpha2.jar:8.4.0-alpha2]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transformResource(DeploymentTransformer.java:130) ~[zeebe-workflow-engine-8.4.0-alpha2.jar:8.4.0-alpha2]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transform(DeploymentTransformer.java:106) ~[zeebe-workflow-engine-8.4.0-alpha2.jar:8.4.0-alpha2]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.transformAndDistributeDeployment(DeploymentCreateProcessor.java:151) ~[zeebe-workflow-engine-8.4.0-alpha2.jar:8.4.0-alpha2]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.processNewCommand(DeploymentCreateProcessor.java:105) ~[zeebe-workflow-engine-8.4.0-alpha2.jar:8.4.0-alpha2]
	at io.camunda.zeebe.engine.processing.streamprocessor.DistributedTypedRecordProcessor.processRecord(DistributedTypedRecordProcessor.java:33) ~[zeebe-workflow-engine-8.4.0-alpha2.jar:8.4.0-alpha2]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[zeebe-workflow-engine-8.4.0-alpha2.jar:8.4.0-alpha2]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:360) ~[zeebe-stream-platform-8.4.0-alpha2.jar:8.4.0-alpha2]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$2(ProcessingStateMachine.java:275) ~[zeebe-stream-platform-8.4.0-alpha2.jar:8.4.0-alpha2]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:98) ~[zeebe-db-8.4.0-alpha2.jar:8.4.0-alpha2]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:275) ~[zeebe-stream-platform-8.4.0-alpha2.jar:8.4.0-alpha2]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:233) ~[zeebe-stream-platform-8.4.0-alpha2.jar:8.4.0-alpha2]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:209) ~[zeebe-stream-platform-8.4.0-alpha2.jar:8.4.0-alpha2]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) [zeebe-scheduler-8.4.0-alpha2.jar:8.4.0-alpha2]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) [zeebe-scheduler-8.4.0-alpha2.jar:8.4.0-alpha2]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:120) [zeebe-scheduler-8.4.0-alpha2.jar:8.4.0-alpha2]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.4.0-alpha2.jar:8.4.0-alpha2]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.4.0-alpha2.jar:8.4.0-alpha2]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.4.0-alpha2.jar:8.4.0-alpha2]
```

</p>
</details>

**Environment:**
- OS:  Camunda SaaS (dev)
- Zeebe Version:  `8.4.0-alpha2`
- Configuration:

**Comment by koevskinikola** [comment]
Individual triage:
* Severity is `low` as no incorrect resource is deployed, but the error message provided is not very clear to the user.
* Priority is `later` as ZPA doesn't have a lot of capacity right now to fix the issue. 
* Size is `small` as it is a quick fix.

**Comment by rodrigo-lourenco-lopes** [comment]
This has happened again [here](https://console.cloud.google.com/logs/query;query=error_groups.id%3D%22CP35roSVzbahbg%22%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.location%3D%22us-east1%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.cluster_name%3D%22prod-worker-2%22%0Aresource.labels.pod_name%3D%22zeebe-1%22%0Aresource.labels.namespace_name%3D%2232d4f193-227e-4689-a711-9125dd449331-zeebe%22;cursorTimestamp=2024-04-19T14:30:36.094475413Z;startTime=2024-04-19T14:01:06.094Z;endTime=2024-04-19T15:01:06.094Z?project=camunda-cloud-240911).
