### ISSUE TITLE
Job backoff migration causes duplicate incidents

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#15954]
**Describe the bug**

With https://github.com/camunda/zeebe/issues/14329 we fixed an issue that would cause failed jobs with `retries > 0` to not be re-activated after a migration, i.e. the jobs aren't placed in the `JOB_BACKOFF` column family. 

However, the fix doesn't check if a failed job has `retries > 0` or if it already has an incident, which wouldn't make it activatable.

The above leads to a job with an incident being made activatable. When this type of job is processed, and failed again, it raises a second incident. If Zeebe has the `ZEEBE_BROKER_EXPERIMENTAL_CONSISTENCYCHECKS_ENABLEPRECONDITIONS` env var set to `true`, then a consistency violation error will be thrown by RocksDB, crashing the partition.

**To Reproduce**

1. Use Zeebe `8.1.21`, `8.2.19`, `8.3.4`, or `8.4.0`.
2. Set the `ZEEBE_BROKER_EXPERIMENTAL_CONSISTENCYCHECKS_ENABLEPRECONDITIONS` env var to `true`.
3. Set the `retries` of a job to `0` and `fail` it.
4. Migrate to the next patch version of Zeebe (`8.1.22`, `8.2.20`, `8.3.5`)
5. Activate the same job (from [3]) and fail it again.
6. An error will be thrown that an entry already exists in the `INCIDENT_JOBS` column family, and the partition will crash.

**Expected behavior**

Jobs with incidents are not made activatable after a migration.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
10:18:09.846 [Broker-0] [zb-actors-1] [StreamProcessor-1] ERROR io.camunda.zeebe.logstreams - Actor StreamProcessor-1 failed in phase STARTED.
io.camunda.zeebe.db.ZeebeDbInconsistentException: Key DbForeignKey[inner=DbLong{2251799819040844}, columnFamily=JOBS, match=Full, skip=io.camunda.zeebe.db.impl.DbForeignKey$$Lambda/0x00007f751880b920@57433d1d] in ColumnFamily INCIDENT_JOBS already exists
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.assertKeyDoesNotExist(TransactionalColumnFamily.java:297) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$insert$0(TransactionalColumnFamily.java:81) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$ensureInOpenTransaction$19(TransactionalColumnFamily.java:325) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.DefaultTransactionContext.runInTransaction(DefaultTransactionContext.java:31) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.ensureInOpenTransaction(TransactionalColumnFamily.java:324) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.insert(TransactionalColumnFamily.java:76) ~[classes/:?]
	at io.camunda.zeebe.engine.state.instance.DbIncidentState.createIncident(DbIncidentState.java:85) ~[classes/:?]
	at io.camunda.zeebe.engine.state.appliers.IncidentCreatedApplier.applyState(IncidentCreatedApplier.java:30) ~[classes/:?]
	at io.camunda.zeebe.engine.state.appliers.IncidentCreatedApplier.applyState(IncidentCreatedApplier.java:17) ~[classes/:?]
	at io.camunda.zeebe.engine.state.appliers.EventAppliers.applyState(EventAppliers.java:335) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.streamprocessor.writers.ResultBuilderBackedEventApplyingStateWriter.appendFollowUpEvent(ResultBuilderBackedEventApplyingStateWriter.java:56) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.streamprocessor.writers.ResultBuilderBackedEventApplyingStateWriter.appendFollowUpEvent(ResultBuilderBackedEventApplyingStateWriter.java:42) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.job.JobFailProcessor.raiseIncident(JobFailProcessor.java:173) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.job.JobFailProcessor.failJob(JobFailProcessor.java:135) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.job.JobFailProcessor.lambda$processRecord$0(JobFailProcessor.java:86) ~[classes/:?]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:381) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.job.JobFailProcessor.processRecord(JobFailProcessor.java:85) ~[classes/:?]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[classes/:?]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:356) ~[classes/:?]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$2(ProcessingStateMachine.java:272) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:98) ~[classes/:?]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:272) ~[classes/:?]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:231) ~[classes/:?]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:207) ~[classes/:?]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) ~[classes/:?]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:120) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [classes/:?]
10:18:09.857 [Broker-0] [zb-actors-0] [ZeebePartition-1] ERROR io.camunda.zeebe.broker.system - StreamProcessor-1 failed, marking it as dead: StreamProcessor-1{status=DEAD, issue=HealthIssue[message=null, throwable=io.camunda.zeebe.db.ZeebeDbInconsistentException: Key DbForeignKey[inner=DbLong{2251799819040844}, columnFamily=JOBS, match=Full, skip=io.camunda.zeebe.db.impl.DbForeignKey$$Lambda/0x00007f751880b920@57433d1d] in ColumnFamily INCIDENT_JOBS already exists, cause=null]}
```

</p>
</details>

**Environment:**
- OS:  Camudna SaaS and SM
- Zeebe Version:  `8.1.22`, `8.2.20`, `8.3.5`, `8.4.0`
- Configuration:  `ZEEBE_BROKER_EXPERIMENTAL_CONSISTENCYCHECKS_ENABLEPRECONDITIONS=true`

**Workaround**
* Setting `ZEEBE_BROKER_EXPERIMENTAL_CONSISTENCYCHECKS_ENABLEPRECONDITIONS=false` will avoid the issue from happening until a fix is provided.

**Additional context:**
* The bug can also be reproduced by starting a `StandaloneBroker` (on the `stable/8.3` branch) with [this (internal) partition data](https://drive.google.com/file/d/19SDLOKRu6jwxDeG05CNHrIL1wYZYL5ft/view?usp=sharing).
* The problematic code is [here](https://github.com/camunda/zeebe/blob/86db453f1aef24e2fb02e7a739dda12a12b1997c/engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbJobState.java#L288) (on branch `main`/`8.4`) since we don't exclude jobs with incidents/`retries < 1`.
* [Support case](https://jira.camunda.com/browse/SUPPORT-20055)
* [Support case](https://jira.camunda.com/browse/SUPPORT-20113)

**Comment by koevskinikola** [comment]
Individual triage:
* The bug is present in multiple minor versions of Zeebe `8.1.x` to `8.4.y`. The fix should be backported until `8.1`.
* The bug has a workaround, so it's `severity/mid`. However, for the following reasons I set it to `serverity/high`:
   * The workaround would disable consistency checks, so it might impact the correctness of the data for customers who have the ZEEBE_BROKER_EXPERIMENTAL_CONSISTENCYCHECKS_ENABLEPRECONDITIONS` flag explicitly set to `true`.
   * The bug may cause all the partitions of a cluster to fail, resulting in Zeebe being completely unavailable.
* Priority is set to `upcoming` due to the points above.

**Comment by nicpuppa** [comment]
I would like to work on this issue 👍

**Comment by abbasadel** [comment]
Increased the `likelihood` to `high` since it occurred 3 more times

**Comment by nicpuppa** [comment]
Should we backport the fix to stable 8.1, 8.2, 8.3, 8.4 right ? @abbasadel 

cc @Zelldon @oleschoenburg @koevskinikola

**Comment by oleschoenburg** [comment]
Yes, definitely :+1:

**Comment by nicpuppa** [comment]
reopened due to https://camunda.slack.com/archives/C04CABJF6FP/p1708509693973369 (internal).

We missed to migrate the jobs which have been marked activatable back to non activatable.
