### ISSUE TITLE
PKCS1 support broken due to missing libraries

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#15977]
**Describe the bug**

Although we should support PKCS1 out of the box (since we use Netty), it seems we explicitly scoped the BouncyCastle dependencies to `test` instead of `compile` or `runtime`. This means that while we can use PKCS1 private keys in our tests, it's not possible to do so in production.

**To Reproduce**

Here is a reproducer:

```java
final class Pkcs1SupportTest {
  @RegressionTest("")
  void shouldSupportPkcs1Key(final @TempDir Path tmpDir) throws IOException, CertificateException {
    // given
    final var certificate = new SelfSignedCertificate();
    final var pkcs1Key = convertToPkcs1(certificate.key(), tmpDir.resolve("private.key").toFile());
    final var containerCertPath = "/usr/local/zeebe/cert.crt";
    final var containerKeyPath = "/usr/local/zeebe/pkcs1.key";
    final var zeebe =
        new ZeebeContainer(DockerImageName.parse("camunda/zeebe:8.4.0"))
            .withCopyFileToContainer(
                MountableFile.forHostPath(certificate.certificate().toPath(), 511),
                containerCertPath)
            .withCopyFileToContainer(
                MountableFile.forHostPath(pkcs1Key.toPath(), 511), containerKeyPath)
            .withEnv("ZEEBE_BROKER_NETWORK_SECURITY_ENABLED", "true")
            .withEnv("ZEEBE_BROKER_NETWORK_SECURITY_CERTIFICATECHAINPATH", containerCertPath)
            .withEnv("ZEEBE_BROKER_NETWORK_SECURITY_PRIVATEKEYPATH", containerKeyPath)
            .withEnv("ZEEBE_BROKER_GATEWAY_SECURITY_ENABLED", "true")
            .withEnv("ZEEBE_BROKER_GATEWAY_SECURITY_CERTIFICATECHAINPATH", containerCertPath)
            .withEnv("ZEEBE_BROKER_GATEWAY_SECURITY_PRIVATEKEYPATH", containerKeyPath)
            .withoutTopologyCheck(); // avoid the missing TLS config by the client

    // when
    try (zeebe) {
      zeebe.start();

      // then
      SslAssert.assertThat(
              new InetSocketAddress(
                  zeebe.getExternalHost(), zeebe.getMappedPort(ZeebePort.INTERNAL.getPort())))
          .isSecuredBy(certificate);
      SslAssert.assertThat(
              new InetSocketAddress(
                  zeebe.getExternalHost(), zeebe.getMappedPort(ZeebePort.COMMAND.getPort())))
          .isSecuredBy(certificate);
      SslAssert.assertThat(
              new InetSocketAddress(
                  zeebe.getExternalHost(), zeebe.getMappedPort(ZeebePort.GATEWAY.getPort())))
          .isSecuredBy(certificate);
    }
  }

  private File convertToPkcs1(final PrivateKey key, final File dest) throws IOException {
    final var encoded = key.getEncoded();
    final var pkcs1Key = PrivateKeyInfo.getInstance(encoded).parsePrivateKey().toASN1Primitive();
    final var pkcs1Encoded = pkcs1Key.getEncoded();
    final var pemObject = new PemObject("RSA PRIVATE KEY", pkcs1Encoded);
    final var pemWriter = new PemWriter(new FileWriter(dest));

    pemWriter.writeObject(pemObject);
    pemWriter.close();

    return dest;
  }
}
```

The container will simply fail to start.

**Expected behavior**

We support PKCS1 one as expected by ensuring BouncyCastle is present at runtime.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
Caused by: java.util.concurrent.CompletionException: io.atomix.cluster.messaging.MessagingException: Failed to start messaging service; invalid server TLS configuration
                at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
                at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(Unknown Source) ~[?:?]
                at java.base/java.util.concurrent.CompletableFuture.thenCompose(Unknown Source) ~[?:?]
                at io.atomix.cluster.messaging.impl.NettyMessagingService.start(NettyMessagingService.java:371) ~[zeebe-atomix-cluster-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
                at io.atomix.cluster.AtomixCluster.startServices(AtomixCluster.java:244) ~[zeebe-atomix-cluster-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
                ... 5 more
        Caused by: io.atomix.cluster.messaging.MessagingException: Failed to start messaging service; invalid server TLS configuration
                at io.atomix.cluster.messaging.impl.NettyMessagingService.loadServerSslContext(NettyMessagingService.java:497) ~[zeebe-atomix-cluster-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
                at io.atomix.cluster.messaging.impl.NettyMessagingService.start(NettyMessagingService.java:371) ~[zeebe-atomix-cluster-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
                ... 5 more
        Caused by: java.lang.IllegalArgumentException: File does not contain valid private key: /usr/local/zeebe/pkcs1.key
                at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:390) ~[netty-handler-4.1.104.Final.jar:4.1.104.Final]
                at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:330) ~[netty-handler-4.1.104.Final.jar:4.1.104.Final]
                at io.netty.handler.ssl.SslContextBuilder.forServer(SslContextBuilder.java:68) ~[netty-handler-4.1.104.Final.jar:4.1.104.Final]
                at io.atomix.cluster.messaging.impl.NettyMessagingService.loadServerSslContext(NettyMessagingService.java:491) ~[zeebe-atomix-cluster-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
                at io.atomix.cluster.messaging.impl.NettyMessagingService.start(NettyMessagingService.java:371) ~[zeebe-atomix-cluster-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
                ... 5 more
        Caused by: java.security.spec.InvalidKeySpecException: Neither RSA, DSA nor EC worked
                at io.netty.handler.ssl.SslContext.getPrivateKeyFromByteBuffer(SslContext.java:1215) ~[netty-handler-4.1.104.Final.jar:4.1.104.Final]
                at io.netty.handler.ssl.SslContext.toPrivateKey(SslContext.java:1167) ~[netty-handler-4.1.104.Final.jar:4.1.104.Final]
                at io.netty.handler.ssl.SslContext.toPrivateKey(SslContext.java:1148) ~[netty-handler-4.1.104.Final.jar:4.1.104.Final]
                at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:388) ~[netty-handler-4.1.104.Final.jar:4.1.104.Final]
                at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:330) ~[netty-handler-4.1.104.Final.jar:4.1.104.Final]
                at io.netty.handler.ssl.SslContextBuilder.forServer(SslContextBuilder.java:68) ~[netty-handler-4.1.104.Final.jar:4.1.104.Final]
                at io.atomix.cluster.messaging.impl.NettyMessagingService.loadServerSslContext(NettyMessagingService.java:491) ~[zeebe-atomix-cluster-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
                at io.atomix.cluster.messaging.impl.NettyMessagingService.start(NettyMessagingService.java:371) ~[zeebe-atomix-cluster-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
                ... 5 more
        Caused by: java.security.spec.InvalidKeySpecException: java.security.InvalidKeyException: Unable to decode key
                at jdk.crypto.ec@21.0.1/sun.security.ec.ECKeyFactory.engineGeneratePrivate(Unknown Source) ~[jdk.crypto.ec:?]
                at java.base/java.security.KeyFactory.generatePrivate(Unknown Source) ~[?:?]
                at io.netty.handler.ssl.SslContext.getPrivateKeyFromByteBuffer(SslContext.java:1213) ~[netty-handler-4.1.104.Final.jar:4.1.104.Final]
                at io.netty.handler.ssl.SslContext.toPrivateKey(SslContext.java:1167) ~[netty-handler-4.1.104.Final.jar:4.1.104.Final]
                at io.netty.handler.ssl.SslContext.toPrivateKey(SslContext.java:1148) ~[netty-handler-4.1.104.Final.jar:4.1.104.Final]
                at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:388) ~[netty-handler-4.1.104.Final.jar:4.1.104.Final]
                at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:330) ~[netty-handler-4.1.104.Final.jar:4.1.104.Final]
                at io.netty.handler.ssl.SslContextBuilder.forServer(SslContextBuilder.java:68) ~[netty-handler-4.1.104.Final.jar:4.1.104.Final]
                at io.atomix.cluster.messaging.impl.NettyMessagingService.loadServerSslContext(NettyMessagingService.java:491) ~[zeebe-atomix-cluster-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
                at io.atomix.cluster.messaging.impl.NettyMessagingService.start(NettyMessagingService.java:371) ~[zeebe-atomix-cluster-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
                ... 5 more
        Caused by: java.security.InvalidKeyException: Unable to decode key
                at java.base/sun.security.pkcs.PKCS8Key.decode(Unknown Source) ~[?:?]
                at java.base/sun.security.pkcs.PKCS8Key.<init>(Unknown Source) ~[?:?]
                at jdk.crypto.ec@21.0.1/sun.security.ec.ECPrivateKeyImpl.<init>(Unknown Source) ~[jdk.crypto.ec:?]
                at jdk.crypto.ec@21.0.1/sun.security.ec.ECKeyFactory.implGeneratePrivate(Unknown Source) ~[jdk.crypto.ec:?]
                at jdk.crypto.ec@21.0.1/sun.security.ec.ECKeyFactory.engineGeneratePrivate(Unknown Source) ~[jdk.crypto.ec:?]
                at java.base/java.security.KeyFactory.generatePrivate(Unknown Source) ~[?:?]
                at io.netty.handler.ssl.SslContext.getPrivateKeyFromByteBuffer(SslContext.java:1213) ~[netty-handler-4.1.104.Final.jar:4.1.104.Final]
                at io.netty.handler.ssl.SslContext.toPrivateKey(SslContext.java:1167) ~[netty-handler-4.1.104.Final.jar:4.1.104.Final]
                at io.netty.handler.ssl.SslContext.toPrivateKey(SslContext.java:1148) ~[netty-handler-4.1.104.Final.jar:4.1.104.Final]
                at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:388) ~[netty-handler-4.1.104.Final.jar:4.1.104.Final]
                at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:330) ~[netty-handler-4.1.104.Final.jar:4.1.104.Final]
                at io.netty.handler.ssl.SslContextBuilder.forServer(SslContextBuilder.java:68) ~[netty-handler-4.1.104.Final.jar:4.1.104.Final]
                at io.atomix.cluster.messaging.impl.NettyMessagingService.loadServerSslContext(NettyMessagingService.java:491) ~[zeebe-atomix-cluster-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
                at io.atomix.cluster.messaging.impl.NettyMessagingService.start(NettyMessagingService.java:371) ~[zeebe-atomix-cluster-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
                ... 5 more
        Caused by: java.io.IOException: algid parse error, not a sequence
                at java.base/sun.security.x509.AlgorithmId.parse(Unknown Source) ~[?:?]
                at java.base/sun.security.pkcs.PKCS8Key.decode(Unknown Source) ~[?:?]
                at java.base/sun.security.pkcs.PKCS8Key.<init>(Unknown Source) ~[?:?]
                at jdk.crypto.ec@21.0.1/sun.security.ec.ECPrivateKeyImpl.<init>(Unknown Source) ~[jdk.crypto.ec:?]
                at jdk.crypto.ec@21.0.1/sun.security.ec.ECKeyFactory.implGeneratePrivate(Unknown Source) ~[jdk.crypto.ec:?]
                at jdk.crypto.ec@21.0.1/sun.security.ec.ECKeyFactory.engineGeneratePrivate(Unknown Source) ~[jdk.crypto.ec:?]
                at java.base/java.security.KeyFactory.generatePrivate(Unknown Source) ~[?:?]
                at io.netty.handler.ssl.SslContext.getPrivateKeyFromByteBuffer(SslContext.java:1213) ~[netty-handler-4.1.104.Final.jar:4.1.104.Final]
                at io.netty.handler.ssl.SslContext.toPrivateKey(SslContext.java:1167) ~[netty-handler-4.1.104.Final.jar:4.1.104.Final]
                at io.netty.handler.ssl.SslContext.toPrivateKey(SslContext.java:1148) ~[netty-handler-4.1.104.Final.jar:4.1.104.Final]
                at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:388) ~[netty-handler-4.1.104.Final.jar:4.1.104.Final]
                at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:330) ~[netty-handler-4.1.104.Final.jar:4.1.104.Final]
                at io.netty.handler.ssl.SslContextBuilder.forServer(SslContextBuilder.java:68) ~[netty-handler-4.1.104.Final.jar:4.1.104.Final]
                at io.atomix.cluster.messaging.impl.NettyMessagingService.loadServerSslContext(NettyMessagingService.java:491) ~[zeebe-atomix-cluster-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
                at io.atomix.cluster.messaging.impl.NettyMessagingService.start(NettyMessagingService.java:371) 
```

</p>
</details>

**Environment:**
- Zeebe Version: 8.4.0, 8.3.5, 8.2.20, 8.1.22

**Comment by npepinpe** [comment]
Support link: https://jira.camunda.com/browse/SUPPORT-19744
