### ISSUE TITLE
Exporter failure caused by large rejection messages

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#15989]
**Describe the bug**

A `REJECTION` record that has an extremely large `rejectionReason` in the [RecordMetadata](https://github.com/camunda/zeebe/blob/main/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/RecordMetadata.java#L52) is not serialized correctly.

The reason for the bad serialization is that Zeebe stores the `RecordMetadata` length in a `short` property (see [src1](https://github.com/camunda/zeebe/blob/c7bb35019a5ebdb0147388ebf4e170bc32efcdb8/logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/serializer/LogAppendEntrySerializer.java#L99), [src2](https://github.com/camunda/zeebe/blob/13e814dbdb145651f4b971b493e3b1043a45830b/logstreams/src/main/java/io/camunda/zeebe/logstreams/impl/log/LogEntryDescriptor.java#L95-L96)). If the length of the `RecordMetadata` object is longer than the maximum size of the `Short` type, a negative value is set instead.

As a result, the `REJECTION` record can't be de-serialized properly when it is exported. This leads to the exporter being blocked from exporting any records.

**To Reproduce**

1. Set the `ZEEBE_DEBUG=true` env var to enable the debug exporter.
2. Deploy a process with an incorrect FEEL expression with a large (>250KB) that would result in a large error message.
    * The [`CreateLargeDeploymentTest` IT](https://github.com/camunda/zeebe/blob/99571f7fbeacf3c03457aac0823fc6d76dc90456/qa/integration-tests/src/test/java/io/camunda/zeebe/it/client/command/CreateLargeDeploymentTest.java#L40) test can be modified for reproduction.
    * This [(internal) process](https://drive.google.com/file/d/1oToyQbh5-YVZau6cVDubPLGSnanpAFYa/view?usp=sharing) can be deployed in the test above. 
3. The deployment will be rejected.
4. The `REJECTION` record will fail to be exported.

**Expected behavior**

The `REJECTION` record is correctly serialized and exported.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
[Broker-0-Exporter-1] [-zb-fs-workers-0] ERROR io.camunda.zeebe.scheduler.retry.EndlessRetryStrategy - Caught exception class java.lang.IllegalArgumentException with message invalid offset: -9277, will retry...
java.lang.IllegalArgumentException: invalid offset: -9277
	at org.agrona.concurrent.UnsafeBuffer.boundsCheckWrap(UnsafeBuffer.java:2425) ~[agrona-1.17.2.jar:1.17.2]
	at org.agrona.concurrent.UnsafeBuffer.wrap(UnsafeBuffer.java:277) ~[agrona-1.17.2.jar:1.17.2]
	at io.camunda.zeebe.msgpack.spec.MsgPackReader.wrap(MsgPackReader.java:49) ~[classes/:?]
	at io.camunda.zeebe.msgpack.UnpackedObject.wrap(UnpackedObject.java:30) ~[classes/:?]
	at io.camunda.zeebe.logstreams.impl.log.LoggedEventImpl.readValue(LoggedEventImpl.java:106) ~[classes/:?]
	at io.camunda.zeebe.stream.impl.records.RecordValues.readRecordValue(RecordValues.java:34) ~[classes/:?]
	at io.camunda.zeebe.broker.exporter.stream.ExporterDirector$RecordExporter.wrap(ExporterDirector.java:511) ~[classes/:?]
	at io.camunda.zeebe.broker.exporter.stream.ExporterDirector.lambda$exportEvent$10(ExporterDirector.java:410) ~[classes/:?]
	at io.camunda.zeebe.scheduler.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:28) ~[classes/:?]
	at io.camunda.zeebe.scheduler.retry.EndlessRetryStrategy.run(EndlessRetryStrategy.java:51) ~[classes/:?]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:203) [classes/:?]
```

</p>
</details>

**Environment:**
- OS:  SM
- Zeebe Version:  `8.2.5`
- Configuration:  Set the env var `ZEEBE_DEBUG=true` to enable the debug exporter.

**Comment by koevskinikola** [comment]
Individual (ZPA) triage:
* The bug is marked as `critical` as there is currently no workaround. A cluster can't export any data once this bug occurs.
* Size is `medium` as it's currently not clear what the effort is to adjust the `metadataLength` field for the `LogEntryDescriptor` class
* Priority is `upcoming` due to the criticality of the bug.

**Comment by npepinpe** [comment]
ZDP triage: looks like an issue for us, and as it's critical we will work on it ASAP.

**Comment by npepinpe** [comment]
Do we need an ad-hoc patch release?
