### ISSUE TITLE
Regression in 8.4: Failed to build variable mapping expression

### ISSUE THREAD

**Issue by saig0** [camunda/zeebe#16043]
**Describe the bug**

I can't deploy a BPMN process to Zeebe 8.4.0. In previous versions (8.3.5), I deployed the process successfully. The deployment reports the following error:

```
Command 'CREATE' rejected with code 'INVALID_ARGUMENT': Expected to deploy new resources, but encountered the following errors:
'New BPMN Diagram.bpmn': Failed to build variable mapping expression: failed to parse expression '{apiKey:key,from:{name:"Me",email:"me@camunda.com"},to:{name:""You"",email:"you@camunda.com"},unMappedFieldNotUseInModel:{mailType:"mail"},content:{subject:"Hello",type:"text/plain",value:"This is a test."}}': Expected (start-of-input | ifOp | forOp | quantifiedOp | disjunction):1:1, found "{apiKey:ke"[ deploy-error ] 23/1/2024 8:37:14
``` 

![Screenshot from 2024-01-23 08-40-09](https://github.com/camunda/zeebe/assets/4305769/75e8e85a-c8ad-4689-a84b-53f6e246f068)

The process contains a SendGrid connector task with the configuration:
- Receiver Name = `"You"` (static value but with double-quotes)

**To Reproduce**

1. Deploy the BPMN process [regression-variable-mapping.bpmn](https://github.com/camunda/zeebe/files/14019955/regression-variable-mapping.bpmn.txt)
2. Verify that the deployment fails

**Expected behavior**

I can deploy the BPMN process.

If the static value is wrapped in double quotes then the double quotes are removed on parsing. When the variable mapping is applied, the process variable should be a string value `You` without double quotes (i.e. as JSON `"You"` and not `"\"You\""`).

**Log/Stacktrace**

This issue was reported as a [Support case](https://jira.camunda.com/browse/SUPPORT-20145). 

**Environment:**
- OS: 
- Zeebe Version: `8.4.0`
- Configuration:

**Comment by saig0** [comment]
## Workaround

Don't use double quotes in static values. They are not needed. A static value is interpreted as a string. 

In the case of the process, change the Receive Name `"You"` to `You` (no double quotes) or `="You"` (string literal).

**Comment by Zelldon** [comment]
@saig0 @abbasadel as written [here](https://camunda.slack.com/archives/C06EFPJ076W/p1706016589227629?thread_ts=1706012506.189009&cid=C06EFPJ076W) I think this issue is more problematic then we thought. I was able to reproduce this with a simple update test.


## Update Test

Setting up Camunda 8 SM (our benchmark charts) with following values:

- [values.83.txt](https://github.com/camunda/zeebe/files/14024840/values.83.txt)
- [values.84.txt](https://github.com/camunda/zeebe/files/14024842/values.84.txt)

Values for 8.3 I use to bootstrap the cluster. Then I use the model shared by @saig0 to deploy the process:

```
$ zbctl deploy --insecure /tmp/regression-variable-mapping.bpmn
{
  "key": "2251799813685250",
  "processes": [
    {
      "bpmnProcessId": "Process_0zc7ixs",
      "version": 1,
      "processDefinitionKey": "2251799813685249",
      "resourceName": "/tmp/regression-variable-mapping.bpmn"
    }
  ]
}
```

I create some instances (without instances it doesn't fail).

```
[cqjawa ck-update-test/ cluster: zeebe-cluster ns:ck-update-test]$ zbctl create instance 2251799813685249 --insecure
{
  "processDefinitionKey": "2251799813685249",
  "bpmnProcessId": "Process_0zc7ixs",
  "version": 1,
  "processInstanceKey": "2251799813685251"
}
[cqjawa ck-update-test/ cluster: zeebe-cluster ns:ck-update-test]$ zbctl create instance 2251799813685249 --insecure
{
  "processDefinitionKey": "2251799813685249",
  "bpmnProcessId": "Process_0zc7ixs",
  "version": 1,
  "processInstanceKey": "4503599627370497"
}
[cqjawa ck-update-test/ cluster: zeebe-cluster ns:ck-update-test]$ zbctl create instance 2251799813685249 --insecure
{
  "processDefinitionKey": "2251799813685249",
  "bpmnProcessId": "Process_0zc7ixs",
  "version": 1,
  "processInstanceKey": "6755399441055745"
}
```

Afterwards I do the upgrade to 8.4

```
cp values.84.txt values.yaml
make update
helm upgrade --namespace ck-update-test ck-update-test zeebe-benchmark/zeebe-benchmark --reuse-values -f values.yaml
W0123 14:47:49.188447   40837 warnings.go:70] spec.template.spec.containers[0].env[16].name: duplicate name "ZEEBE_LOG_LEVEL"
W0123 14:47:49.950730   40837 warnings.go:70] spec.template.spec.containers[0].env[25].name: duplicate name "K8S_NAMESPACE"
W0123 14:47:49.950745   40837 warnings.go:70] spec.template.spec.containers[0].env[26].name: duplicate name "K8S_NAME"
W0123 14:47:49.950750   40837 warnings.go:70] spec.template.spec.containers[0].env[31].name: duplicate name "ZEEBE_LOG_LEVEL"
Release "ck-update-test" has been upgraded. Happy Helming!
NAME: ck-update-test
LAST DEPLOYED: Tue Jan 23 14:47:46 2024
NAMESPACE: ck-update-test
STATUS: deployed
REVISION: 2
NOTES:
# Zeebe Benchmark

Installed Zeebe cluster with:

 * 3 Brokers
 * 2 Gateways

The benchmark is running with:

 * Starter replicas=0
 * Worker replicas=0
 * Publisher replicas=0
 * Timer replicas=0

```

We can see that the nodes come up, but are unhealthy. 
![unhealthy-reproduction](https://github.com/camunda/zeebe/assets/2758593/7f7222cc-7e42-46c8-8333-e0cdef95a8bf)


[Logs indicating](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22ck-update-test%22%0Alabels.k8s-pod%2Fapp%3D%22camunda-platform%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fcomponent%3D%22zeebe-broker%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22ck-update-test%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fmanaged-by%3D%22Helm%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22camunda-platform%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fpart-of%3D%22camunda-platform%22;pinnedLogId=2024-01-23T13:49:17.718985305Z%2F0cukdcxfj53ua6rk;summaryFields=labels%252F%2522k8s-pod%252Fstatefulset_kubernetes_io%252Fpod-name%2522:false:32:beginning;cursorTimestamp=2024-01-23T13:49:17.718985305Z;duration=PT5M?project=zeebe-io) the same issue:


```
java.lang.RuntimeException: java.lang.IllegalStateException: Failed to build variable mapping expression: failed to parse expression '{apiKey:key,from:{name:"Me",email:"me@camunda.com"},to:{name:""You"",email:"you@camunda.com"},unMappedFieldNotUseInModel:{mailType:"mail"},content:{subject:"Hello",type:"text/plain",value:"This is a test."}}': Expected (start-of-input | ifOp | forOp | quantifiedOp | disjunction):1:1, found "{apiKey:ke"
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.lambda$replayNextEvent$4(ReplayStateMachine.java:168) ~[zeebe-stream-platform-8.4.0.jar:8.4.0]
	at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:33) ~[zeebe-scheduler-8.4.0.jar:8.4.0]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:96) ~[zeebe-scheduler-8.4.0.jar:8.4.0]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) [zeebe-scheduler-8.4.0.jar:8.4.0]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:120) [zeebe-scheduler-8.4.0.jar:8.4.0]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.4.0.jar:8.4.0]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.4.0.jar:8.4.0]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.4.0.jar:8.4.0]
Caused by: java.lang.IllegalStateException: Failed to build variable mapping expression: failed to parse expression '{apiKey:key,from:{name:"Me",email:"me@camunda.com"},to:{name:""You"",email:"you@camunda.com"},unMappedFieldNotUseInModel:{mailType:"mail"},content:{subject:"Hello",type:"text/plain",value:"This is a test."}}': Expected (start-of-input | ifOp | forOp | quantifiedOp | disjunction):1:1, found "{apiKey:ke"
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.VariableMappingTransformer.parseExpression(VariableMappingTransformer.java:196) ~[zeebe-workflow-engine-8.4.0.jar:8.4.0]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.VariableMappingTransformer.transformInputMappings(VariableMappingTransformer.java:84) ~[zeebe-workflow-engine-8.4.0.jar:8.4.0]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.FlowNodeTransformer.lambda$transformIoMappings$1(FlowNodeTransformer.java:64) ~[zeebe-workflow-engine-8.4.0.jar:8.4.0]
	at java.base/java.util.Optional.map(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.FlowNodeTransformer.transformIoMappings(FlowNodeTransformer.java:62) ~[zeebe-workflow-engine-8.4.0.jar:8.4.0]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.FlowNodeTransformer.transform(FlowNodeTransformer.java:38) ~[zeebe-workflow-engine-8.4.0.jar:8.4.0]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.FlowNodeTransformer.transform(FlowNodeTransformer.java:21) ~[zeebe-workflow-engine-8.4.0.jar:8.4.0]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.TransformationVisitor.visit(TransformationVisitor.java:42) ~[zeebe-workflow-engine-8.4.0.jar:8.4.0]
	at io.camunda.zeebe.model.bpmn.traversal.TypeHierarchyVisitor.visit(TypeHierarchyVisitor.java:39) ~[zeebe-bpmn-model-8.4.0.jar:8.4.0]
	at io.camunda.zeebe.model.bpmn.traversal.ModelWalker.walk(ModelWalker.java:73) ~[zeebe-bpmn-model-8.4.0.jar:8.4.0]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.BpmnTransformer.transformDefinitions(BpmnTransformer.java:118) ~[zeebe-workflow-engine-8.4.0.jar:8.4.0]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.updateInMemoryState(DbProcessState.java:234) ~[zeebe-workflow-engine-8.4.0.jar:8.4.0]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.lookupPersistenceStateForProcessByKey(DbProcessState.java:438) ~[zeebe-workflow-engine-8.4.0.jar:8.4.0]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.getProcessByKeyAndTenant(DbProcessState.java:328) ~[zeebe-workflow-engine-8.4.0.jar:8.4.0]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.getFlowElement(DbProcessState.java:364) ~[zeebe-workflow-engine-8.4.0.jar:8.4.0]
	at io.camunda.zeebe.engine.state.appliers.ProcessInstanceElementActivatingApplier.createEventScope(ProcessInstanceElementActivatingApplier.java:267) ~[zeebe-workflow-engine-8.4.0.jar:8.4.0]
	at io.camunda.zeebe.engine.state.appliers.ProcessInstanceElementActivatingApplier.applyState(ProcessInstanceElementActivatingApplier.java:51) ~[zeebe-workflow-engine-8.4.0.jar:8.4.0]
	at io.camunda.zeebe.engine.state.appliers.ProcessInstanceElementActivatingApplier.applyState(ProcessInstanceElementActivatingApplier.java:32) ~[zeebe-workflow-engine-8.4.0.jar:8.4.0]
	at io.camunda.zeebe.engine.state.appliers.EventAppliers.applyState(EventAppliers.java:356) ~[zeebe-workflow-engine-8.4.0.jar:8.4.0]
	at io.camunda.zeebe.engine.Engine.replay(Engine.java:95) ~[zeebe-workflow-engine-8.4.0.jar:8.4.0]
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.lambda$replayEvent$7(ReplayStateMachine.java:231) ~[zeebe-stream-platform-8.4.0.jar:8.4.0]
	at java.base/java.util.Optional.ifPresent(Unknown Source) ~[?:?]
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.replayEvent(ReplayStateMachine.java:231) ~[zeebe-stream-platform-8.4.0.jar:8.4.0]
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source) ~[?:?]
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.lambda$tryToReplayBatch$5(ReplayStateMachine.java:207) ~[zeebe-stream-platform-8.4.0.jar:8.4.0]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:98) ~[zeebe-db-8.4.0.jar:8.4.0]
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.tryToReplayBatch(ReplayStateMachine.java:205) ~[zeebe-stream-platform-8.4.0.jar:8.4.0]
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.lambda$replayNextEvent$3(ReplayStateMachine.java:164) ~[zeebe-stream-platform-8.4.0.jar:8.4.0]
	at io.camunda.zeebe.scheduler.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:28) ~[zeebe-scheduler-8.4.0.jar:8.4.0]
	at io.camunda.zeebe.scheduler.retry.RecoverableRetryStrategy.run(RecoverableRetryStrategy.java:48) ~[zeebe-scheduler-8.4.0.jar:8.4.0]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) ~[zeebe-scheduler-8.4.0.jar:8.4.0]
	... 5 more

```

## Conclusion

This problem will arise if the customer has deployed a process model with double quotes (?) and has running instances with it. 

Since we don't support down-grading (due to data migration etc.) I see this issue as critical as there is no work-around. Let me know if you see one.

**Comment by nicpuppa** [comment]
Regression could have been introduced by this [PR](https://github.com/camunda/zeebe/pull/15449), I can try to have a look

cc @saig0 @Zelldon @abbasadel

**Comment by koevskinikola** [comment]
This bug might be related: https://github.com/camunda/zeebe/issues/16005

**Comment by Zelldon** [comment]
AFAIK it is at least it was discussed as part of this [incident](https://app.slack.com/client/T0PM0P1SA/C06EHK94W0P)

**Comment by nicpuppa** [comment]
After a first look, the issue seems to be related to the FEEL engine 👀 

cc @saig0

**Comment by Zelldon** [comment]
Releated [error group](https://console.cloud.google.com/errors/detail/CKGCu_C7vNvDKA;service=zeebe;time=P7D?project=camunda-saas-int-chaos) which was reported after Phil tested it in ultrachaos

**Comment by nicpuppa** [comment]
I probably root cause the issue, we missed an escape sequence [in this function](https://github.com/camunda/feel-scala/blob/281f1f137b08c3721efd474cdab6e69d9f7364cd/src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala#L693). This function parse the expression and remove the double escaping. We just need to add the double quotes here and translate them into single quotes

cc @saig0
