### ISSUE TITLE
Failed to submit a listener notification task on gateway shutdown

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#16063]
**Describe the bug**

During shutdown, a listener registration failed and caused an error in our logs.

[Error group ](https://console.cloud.google.com/logs/query;query=%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.pod_name%3D%22zeebe-gateway-775f64f76-kvptw%22%0Aresource.labels.cluster_name%3D%22production-worker-1%22%0Aresource.labels.namespace_name%3D%221b1ac625-0605-43f7-8cf4-49742e52f826-zeebe%22%0Aresource.labels.container_name%3D%22zeebe-gateway%22%0Aresource.labels.location%3D%22europe-west1%22;pinnedLogId=2024-01-19T19:32:53.088604257Z%2Ffiqjg0o53cpti0s3;cursorTimestamp=2024-01-19T19:32:53.088604257Z;startTime=2024-01-19T19:03:23.088Z;endTime=2024-01-19T20:03:23.088Z?project=camunda-cloud-240911)

**To Reproduce**

Start and shutdown the gateway immediately with requests coming in I guess?

**Expected behavior**

No error.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:934) ~[netty-common-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:351) ~[netty-common-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:344) ~[netty-common-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:836) ~[netty-common-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute0(SingleThreadEventExecutor.java:827) ~[netty-common-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:817) ~[netty-common-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:862) ~[netty-common-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:500) ~[netty-common-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:185) ~[netty-common-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:35) ~[netty-common-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:56) ~[netty-resolver-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31) ~[netty-resolver-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106) ~[netty-resolver-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:220) ~[netty-transport-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:47) ~[netty-transport-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:189) ~[netty-transport-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:175) ~[netty-transport-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590) ~[netty-common-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557) ~[netty-common-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492) ~[netty-common-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636) ~[netty-common-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625) ~[netty-common-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:105) ~[netty-common-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84) ~[netty-transport-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:990) ~[netty-transport-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516) ~[netty-transport-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429) ~[netty-transport-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486) ~[netty-transport-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[netty-common-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[netty-common-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:416) ~[netty-transport-classes-epoll-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.104.Final.jar:4.1.104.Final]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: 8.4.0 
- Configuration:

**Comment by npepinpe** [comment]
Look into this after https://github.com/camunda/zeebe/issues/16024

**Comment by koevskinikola** [comment]
Issue occurred again:
* Zeebe `8.5.0`
* Camunda SaaS Int
* Internal link to logs: https://drive.google.com/file/d/1MK10eq6RgCf-x2FHuCHBGxWYac9EVrF0/view?usp=sharing (internal link)
* [GCP logs](https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.container_name%3D%22zeebe-gateway%22%0Aresource.labels.project_id%3D%22camunda-saas-int%22%0Aresource.labels.cluster_name%3D%22worker-3%22%0Aresource.labels.namespace_name%3D%228505eb7f-25f8-4faa-9010-5b1ee0f789bd-zeebe%22%0Aresource.labels.location%3D%22europe-north1%22%0Aresource.labels.pod_name%3D%22zeebe-gateway-6cb96ccd5c-tnqnx%22;pinnedLogId=2024-07-04T09:11:51.394927610Z%2F36evj9jzuj087ayk;cursorTimestamp=2024-07-04T09:11:51.394927610Z;startTime=2024-07-04T08:42:21.394Z;endTime=2024-07-04T09:42:21.394Z?project=camunda-saas-int)
