### ISSUE TITLE
Deployment partition crashing after deploying a DMN without decision name

### ISSUE THREAD

**Issue by tmetzke** [camunda/zeebe#16104]
The following DMN 
![dmn](https://github.com/camunda/zeebe/assets/2758593/b49cbd4b-2fa2-4e43-b030-2e1405262ac7)

```
<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="https://www.omg.org/spec/DMN/20191111/MODEL/" id="_6f87b3aa-d613-4c41-93ad-832f021c8318" name="definitions" namespace="http://camunda.org/schema/1.0/dmn">
  <decision id="_51711_44808585-3491-42a8-87ea-3c4fcda46eff" name="">
    <decisionTable id="_07c6fdc3-7bdf-459a-a016-2ae12e474bd2">
      <input id="_f00d0717-d08a-4918-ad51-568788e92038" label="Percent Responsible (Loan Roles)">
        <inputExpression id="_0b922041-84c3-47bf-b94c-1dd423c394ae" typeRef="number">
          <text>proposedLoan.loanRoles.percentResponsible</text>
        </inputExpression>
      </input>
      <output id="_b304292d-98e5-4dde-8fbd-0de1981c97ea" label="" name="out" typeRef="string">
        <outputValues id="UnaryTests_1yu7moy">
          <text>"Approve","Decline","Review"</text>
        </outputValues>
      </output>
      <rule id="DecisionRule_1j6jzzn">
        <inputEntry id="UnaryTests_105fhm8">
          <text></text>
        </inputEntry>
        <outputEntry id="LiteralExpression_1ucr6zl">
          <text>"Approve"</text>
        </outputEntry>
      </rule>
    </decisionTable>
  </decision>
</definitions>
```

Can completely bork a running cluster, happened in this [incident](https://app.slack.com/client/T0PM0P1SA/C06F3FDRFHU). 

It will show with the following exception:

```
java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "value" is null
	at io.camunda.zeebe.util.StringUtil.getBytes(StringUtil.java:39) ~[zeebe-util-8.3.4.jar:8.3.4]
	at io.camunda.zeebe.util.StringUtil.getBytes(StringUtil.java:35) ~[zeebe-util-8.3.4.jar:8.3.4]
	at io.camunda.zeebe.msgpack.property.StringProperty.setValue(StringProperty.java:30) ~[zeebe-msgpack-value-8.3.4.jar:8.3.4]
	at io.camunda.zeebe.protocol.impl.record.value.deployment.DecisionRecord.setDecisionName(DecisionRecord.java:105) ~[zeebe-protocol-impl-8.3.4.jar:8.3.4]
	at io.camunda.zeebe.engine.processing.deployment.transform.DmnResourceTransformer.lambda$appendMetadataToDeploymentEvent$11(DmnResourceTransformer.java:210) ~[zeebe-workflow-engine-8.3.4.jar:8.3.4]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.deployment.transform.DmnResourceTransformer.appendMetadataToDeploymentEvent(DmnResourceTransformer.java:203) ~[zeebe-workflow-engine-8.3.4.jar:8.3.4]
	at io.camunda.zeebe.engine.processing.deployment.transform.DmnResourceTransformer.lambda$transformResource$0(DmnResourceTransformer.java:77) ~[zeebe-workflow-engine-8.3.4.jar:8.3.4]
	at io.camunda.zeebe.util.Either$Right.map(Either.java:355) ~[zeebe-util-8.3.4.jar:8.3.4]
	at io.camunda.zeebe.engine.processing.deployment.transform.DmnResourceTransformer.transformResource(DmnResourceTransformer.java:75) ~[zeebe-workflow-engine-8.3.4.jar:8.3.4]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transformResource(DeploymentTransformer.java:130) ~[zeebe-workflow-engine-8.3.4.jar:8.3.4]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transform(DeploymentTransformer.java:106) ~[zeebe-workflow-engine-8.3.4.jar:8.3.4]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.transformAndDistributeDeployment(DeploymentCreateProcessor.java:145) ~[zeebe-workflow-engine-8.3.4.jar:8.3.4]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.processNewCommand(DeploymentCreateProcessor.java:102) ~[zeebe-workflow-engine-8.3.4.jar:8.3.4]
	at io.camunda.zeebe.engine.processing.streamprocessor.DistributedTypedRecordProcessor.processRecord(DistributedTypedRecordProcessor.java:33) ~[zeebe-workflow-engine-8.3.4.jar:8.3.4]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[zeebe-workflow-engine-8.3.4.jar:8.3.4]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:356) ~[zeebe-stream-platform-8.3.4.jar:8.3.4]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$2(ProcessingStateMachine.java:272) ~[zeebe-stream-platform-8.3.4.jar:8.3.4]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:98) ~[zeebe-db-8.3.4.jar:8.3.4]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:272) ~[zeebe-stream-platform-8.3.4.jar:8.3.4]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:231) ~[zeebe-stream-platform-8.3.4.jar:8.3.4]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:207) ~[zeebe-stream-platform-8.3.4.jar:8.3.4]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) [zeebe-scheduler-8.3.4.jar:8.3.4]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) [zeebe-scheduler-8.3.4.jar:8.3.4]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:120) [zeebe-scheduler-8.3.4.jar:8.3.4]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.3.4.jar:8.3.4]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.3.4.jar:8.3.4]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.3.4.jar:8.3.4]
```

Later we will see a log like:

```
Detected 'UNHEALTHY' components. The current health status of components: [ZeebePartition-1{status=HEALTHY}, raft-partition-partition-1{status=HEALTHY}, SnapshotDirector-1{status=HEALTHY}, StreamProcessor-1{status=UNHEALTHY, issue=HealthIssue[message=not making progress, throwable=null, cause=null]}, Exporter-1{status=HEALTHY}, LogStream-1{status=HEALTHY}]
```

Zeebe cluster will end in an endless processing loop, which makes partition one unavailable, and no longer be able to use this partition nor deploy to it.

We were able to show this in the heap dump

![zeebe-1-current-event](https://github.com/camunda/zeebe/assets/2758593/4e2f9f14-f5d1-4431-a5cd-a50eb6b84bb2)
![error-looping](https://github.com/camunda/zeebe/assets/2758593/4520dab9-475b-44f2-9d5c-530362712307)

**We don't see a way to recover right now, yet.**

Data can be found [here](https://drive.google.com/drive/folders/1fDxB1KioCH-UhQoJWAZz-MCvhmGUiAkc?usp=drive_link).

_Originally posted by @Zelldon in https://github.com/camunda/zeebe/issues/14929#issuecomment-1910513329_

**Comment by tmetzke** [comment]
_Additional comments by @Zelldon in #14292:_

> Version of the incident 8.3.4

> I have set up a cluster in zeebe-io and was[ able to reproduce it.](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22us-east1%22%0Aresource.labels.cluster_name%3D%22prod-worker-2%22%0Aresource.labels.namespace_name%3D%22b295c6b1-26bb-4b4b-b40c-8e320eed0ca5-zeebe%22%0Aresource.labels.pod_name:%22zeebe-%22%0A-jsonPayload.context.loggerName%3D%22io.camunda.zeebe.broker.exporter%22%0Aresource.labels.pod_name%3D%22zeebe-1%22%0AjsonPayload.context.partitionId%3D%221%22;pinnedLogId=2024-01-24T12:43:03.080370676Z%2Fkncs9tsjjasu7dkm;summaryFields=resource%252Flabels%252Fpod_name,jsonPayload%252Fcontext%252FpartitionId:false:32:beginning;cursorTimestamp=2024-01-24T12:43:35.430213994Z;startTime=2024-01-24T11:00:00.000Z;endTime=2024-01-24T16:05:00.000Z?project=camunda-cloud-240911)
The cluster is now [unhealthy](https://grafana.dev.zeebe.io/d/zeebe-dashboard/zeebe?orgId=1&var-DS_PROMETHEUS=prometheus&var-cluster=All&var-namespace=ck-reproduce-dmn&var-pod=All&var-partition=All&from=1706199381561&to=1706199920514).
This means version 8.3.x, 8.4 and 8.5 are affected (afaik).

>
> I think this is quite severe since customers can easily destroy their partition one on their clusters with such DMN (missing the name).

**Comment by tmetzke** [comment]
_Additional comment by @tmetzke in #14929:_

> I drafted PR https://github.com/camunda/zeebe/pull/16103 to fix the partition crash. I provided some reasoning in the PR. It doesn't fix the NPE. I focused on preventing the partition crash which I think is due to missing default values in records, leading to a rejection that cannot be written.

**Comment by tmetzke** [comment]
I want to give this a manual test with the changes from #16103 to see if this prevents the partition from becoming unhealthy. I'll update here when I'm done.

**Comment by Zelldon** [comment]
@tmetzke you could try on my reproduction cluster

**Comment by tmetzke** [comment]
> @tmetzke you could try on my reproduction cluster

@Zelldon, thanks, I successfully tested locally but verifying with the reproduction cluster after updating would also be a good idea, I guess?

**Comment by Zelldon** [comment]
If you have a docker image we could update the cluster to the new image :)

**Comment by tmetzke** [comment]
> If you have a docker image we could update the cluster to the new image :)

Housekeeping cleaned that up already, I can't have all those images lying around here, cluttering my storage 😆
