### ISSUE TITLE
NPE when transitioning from leader in StreamProcessor

### ISSUE THREAD

**Issue by berkaycanbc** [camunda/zeebe#16127]
**Describe the bug**

A stream processor instance failed in STARTED phase on transition from LEADER role, because its `openFuture` instance was null. From the logs, we can observe that the StreamProcessor was closed previously.

We would expect the actor to have failed then, in the starting phase, but it seems it kept going into the STARTED phase, without a openFuture, resulting in the NPE.

See [ERROR (internal)](https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.pod_name%3D%22zeebe-0%22%0Aresource.labels.location%3D%22us-central1%22%0Aresource.labels.namespace_name%3D%22a735edce-10c6-4856-a6a7-77beca8c06df-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.cluster_name%3D%22prod-worker-3%22;pinnedLogId=2024-01-25T00:38:14.828899972Z%2Fr7x6p0re1czrwx94;cursorTimestamp=2024-01-25T00:38:14.858577883Z;startTime=2024-01-24T23:08:44.828Z;endTime=2024-01-25T01:08:44.828Z?project=camunda-cloud-240911)

**Expected behavior**

Actor should stop to progress to STARTING phase instead of producing NPE.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
"java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.scheduler.future.CompletableActorFuture.complete(Object)" because "this.openFuture" is null
	at io.camunda.zeebe.stream.impl.ProcessingScheduleServiceImpl.lambda$open$2(ProcessingScheduleServiceImpl.java:98) ~[zeebe-stream-platform-8.3.5.jar:8.3.5]
	at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) ~[zeebe-scheduler-8.3.5.jar:8.3.5]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:96) ~[zeebe-scheduler-8.3.5.jar:8.3.5]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) [zeebe-scheduler-8.3.5.jar:8.3.5]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:120) [zeebe-scheduler-8.3.5.jar:8.3.5]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.3.5.jar:8.3.5]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.3.5.jar:8.3.5]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.3.5.jar:8.3.5]
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version:  8.3.5
- Configuration: 

**Additional Context**
Very similar issue is reported here https://github.com/camunda/zeebe/issues/12201.

**Comment by deepthidevaki** [comment]
@berkaycanbc Could you please add what was the impact of this bug to help asses the severity?
- Does the partition became unavailable?
- Did this happened during a shutdown?
- Did it automatically recovered? etc.

**Comment by berkaycanbc** [comment]
@deepthidevaki Here are more details:

> Does the partition became unavailable?

No.

> Did this happened during a shutdown?

It might be but not exact, because the error is logged before the shutdown call.

> Did it automatically recovered? etc.

Yes, it automatically recovered after restart.

**Comment by oleschoenburg** [comment]
> It might be but not exact, because the error is logged before the shutdown call.

To me it looks correct, there was a shutdown shortly before the error occurred:

> 2024-01-25 01:38:14.545 Closing ZeebePartition 1
> 2024-01-25 01:38:14.828 Actor failed in phase 'STARTING'. Discard all jobs and stop immediately.

**Comment by npepinpe** [comment]
It looks like we missed triaging this and assigning a severity to this bug. This seems like a low severity issue, and I would push it to the backlog. Anyone?

**Comment by oleschoenburg** [comment]
That's because it was moved to the inbox immediately.

I agree it's low priority :+1:

**Comment by npepinpe** [comment]
Stack trace is different, but impact/cause were the same: node was transitioning to leader, and failed during startup due to an already completed future. I would increase the severity honestly, the stream processor was down for hours, which means no snapshot were taken, which means nothing was being processed, etc.

In fact, the node is still borked, and it's leader for the partition without having a stream processor. So I'm bumping this to mid.

**Comment by npepinpe** [comment]
@megglos - could you please re-triage this with ZPA?

**Comment by npepinpe** [comment]
Incident link: https://app.incident.io/camunda/incidents/1013

**Comment by megglos** [comment]
setting impact high, as processing is halted

**Comment by npepinpe** [comment]
Another relevant error which came from this: https://console.cloud.google.com/errors/detail/CLCz9Zv8-tiPnwE;service=zeebe;time=P7D?project=camunda-saas-prod

**Comment by npepinpe** [comment]
@megglos - actually, since the error occurs in the replay state machine, this is probably on the ZDP side to fix this :+1:

**Comment by npepinpe** [comment]
I'll extract it to a new issue.

**Comment by megglos** [comment]
turned out not ZPA related, removing from inbox
