### ISSUE TITLE
SegmentedJournalTest.shouldAppendEntriesOfDifferentSizesOverSegmentSize is flaky

### ISSUE THREAD

**Issue by berkaycanbc** [camunda/zeebe#16183]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? 1
- Does it block your work? no
- Do we suspect that it is a real failure? no

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Flakiness</summary>
<pre>
```
Error:    Run 1: SegmentedJournalTest.shouldAppendEntriesOfDifferentSizesOverSegmentSize » IO Failed to delete temp directory /tmp/junit2462505576042197558. The following paths could not be deleted (see suppressed exceptions for details): <root>, data
```
</pre>
</details>

<details><summary>Stack Trace</summary>
<pre>
```
Error:  Tests run: 41, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.310 s <<< FAILURE! -- in io.camunda.zeebe.journal.file.SegmentedJournalTest
Error:  io.camunda.zeebe.journal.file.SegmentedJournalTest.shouldAppendEntriesOfDifferentSizesOverSegmentSize -- Time elapsed: 0.031 s <<< ERROR!
java.io.IOException: Failed to delete temp directory /tmp/junit2462505576042197558. The following paths could not be deleted (see suppressed exceptions for details): <root>, data
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:261)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:261)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
	Suppressed: java.nio.file.DirectoryNotEmptyException: /tmp/junit2462505576042197558
		at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:289)
		at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:104)
		at java.base/java.nio.file.Files.delete(Files.java:1152)
		at java.base/java.nio.file.Files.walkFileTree(Files.java:2803)
		at java.base/java.nio.file.Files.walkFileTree(Files.java:2857)
		... 17 more
	Suppressed: java.nio.file.DirectoryNotEmptyException: /tmp/junit2462505576042197558/data
		at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:289)
		at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:104)
		at java.base/java.nio.file.Files.delete(Files.java:1152)
		at java.base/java.nio.file.Files.walkFileTree(Files.java:2803)
		at java.base/java.nio.file.Files.walkFileTree(Files.java:2857)
		... 17 more
```
</pre>
</details>

Build link: https://github.com/camunda/zeebe/actions/runs/7738233739/job/21098651174

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

Can be some sort of a race condition that delete directory called before deleting the file in it and that causes the issue.

**Comment by deepthidevaki** [comment]
The exception shown here occurs when junit5 try to delete the temp directory injected via `@TempDir` annotation. It is not from the test code. The journal is always closed after each test before the directory is deleted. I cannot find where the race condition is coming from. One potential cause is the async segment creation. But the code shows that this is handled during journal close.

The logs from the test is not available since the test run is from a couple of weeks ago. So cannot investigate this further.

@berkaycanbc FYI Please download and attach the logs from the test run when opening flaky test issues. The artifacts are stored only for a few days. So the link to the test run is not useful. 

I'm closing this issue as we don't have the logs to investigate this further. Please reopen with the logs when it reoccurs.

**Comment by oleschoenburg** [comment]
Happened again here: https://github.com/camunda/zeebe/actions/runs/7932631691

Logs: 
[Test results for unit tests.zip](https://github.com/camunda/zeebe/files/14312950/Test.results.for.unit.tests.7.zip)
