### ISSUE TITLE
Optimise would try connecting to Camunda 7 rest API even if Zeebe is enabled

### ISSUE THREAD

**Issue by ashprojects** [camunda/zeebe#16391]
**Description**

We just started with Camunda 8 Self Managed Helm chart. 
Optimise seems to be calling Engine-Rest (which I believe is from Camunda 7)

Top level exception:
```
19:57:19.449 [qtp769686615-22] ERROR o.c.o.rest.engine.EngineContext - Failed to validate engine camunda-bpm version with error message: Engine didn't respond. Can not verify this engine's version
org.camunda.optimize.service.exceptions.OptimizeRuntimeException: Engine didn't respond. Can not verify this engine's version
	at org.camunda.optimize.service.util.EngineVersionChecker.checkEngineVersionSupport(EngineVersionChecker.java:52)
	at org.camunda.optimize.rest.engine.EngineContext.getEngineClient(EngineContext.java:103)
	at org.camunda.optimize.service.status.StatusCheckingService.isEngineVersionRequestSuccessful(StatusCheckingService.java:110)
	at org.camunda.optimize.service.status.StatusCheckingService.isConnectedToEngine(StatusCheckingService.java:89)
	at org.camunda.optimize.service.status.StatusCheckingService.lambda$isConnectedToAtLeastOnePlatformEngineOrCloud$0(StatusCheckingService.java:68)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1800)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)
	at org.camunda.optimize.service.status.StatusCheckingService.isConnectedToAtLeastOnePlatformEngineOrCloud(StatusCheckingService.java:68)
	at org.camunda.optimize.rest.HealthRestService.getImportStatus(HealthRestService.java:30)
	at jdk.internal.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:146)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:189)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)

```

Optimise pod won't start because of this.

Here are the environment variable passed:
```
CAMUNDA_OPTIMIZE_ZEEBE_ENABLED=true
CAMUNDA_OPTIMIZE_ZEEBE_PARTITION_COUNT=20
OPTIMIZE_ELASTICSEARCH_HOST=[REDACTED]
OPTIMIZE_ELASTICSEARCH_HTTP_PORT=9243
CAMUNDA_OPTIMIZE_SECURITY_AUTH_COOKIE_SAME_SITE_ENABLED=false
CAMUNDA_OPTIMIZE_ELASTICSEARCH_SECURITY_USERNAME=elastic
CAMUNDA_OPTIMIZE_ELASTICSEARCH_SECURITY_PASSWORD=[REDACTED]
CAMUNDA_OPTIMIZE_ELASTICSEARCH_SSL_ENABLED=true

```

Is there a way for us to disable Camunda 7 connection in Optimise

Camunda Helm Chart: 9.1.0
Platform: Self Managed
Version: 8.4.2

Kindly respond

**Comment by PHWaechtler** [comment]
Hi @ashprojects, 
can you confirm whether you have identity enabled in your setup? 
Looking at the helm chart I think if you're missing Identity, the Optimize profile may not be set to CCSM correctly. Please try again with identity enabled or alternatively you can set `SPRING_PROFILES_ACTIVE` to `"ccsm"` manually. I will follow up with the helm chart team on this in the meantime.

**Comment by PHWaechtler** [comment]
We've reopened [this ](https://github.com/camunda/camunda-platform-helm/issues/1100)issue to look into adjusting the helm chart - closing this issue as it's in the wrong repo. @ashprojects, if you have further questions please refer to the helm issue instead

**Comment by PHWaechtler** [comment]
We've reopened [this](https://github.com/camunda/camunda-platform-helm/issues/1100) issue to look into adjusting the helm chart to ensure correct spring profile, closing this issue because its in the wrong repo. @ashprojects if you have any further questions please refer to the new issue in the helm repo instead

**Comment by ashprojects** [comment]
Thanks @PHWaechtler
