### ISSUE TITLE
No stream processor on leader

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#16453]
> Stack trace is different, but impact/cause were the same: node was transitioning to leader, and failed during startup due to an already completed future. I would increase the severity honestly, the stream processor was down for hours, which means no snapshot were taken, which means nothing was being processed, etc.
> 
> In fact, the node is still borked, and it's leader for the partition without having a stream processor. So I'm bumping this to mid.
>
> See: https://console.cloud.google.com/errors/detail/CMHYt76Zy4r6Og;service=zeebe;time=P7D?project=camunda-saas-prod

_Originally posted by @npepinpe in https://github.com/camunda/zeebe/issues/16127#issuecomment-1948006450_

Essentially, because of an already completed future, we failed to transition from follower to leader. This resulted in a node being leader for the partition but no stream processor running on the deployment partition, which led to:

- Unable to deploy new resources
- Unable to interact with process instances on partition 1
- 100% back pressure for partition 1, meaning users only see RESOURCE_EXHAUSTED
- Unable to take snapshots

See: https://console.cloud.google.com/errors/detail/CMHYt76Zy4r6Og;service=zeebe;time=P7D?project=camunda-saas-prod

And: https://app.incident.io/camunda/incidents/1013

<details><summary>Stacktrace</summary>

```
java.lang.IllegalStateException: Cannot complete future, the future is already completed  with value true
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.completeExceptionally(CompletableActorFuture.java:191) ~[zeebe-scheduler-8.4.3.jar:8.4.3]
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.completeExceptionally(CompletableActorFuture.java:198) ~[zeebe-scheduler-8.4.3.jar:8.4.3]
	at io.camunda.zeebe.scheduler.retry.RecoverableRetryStrategy.run(RecoverableRetryStrategy.java:59) ~[zeebe-scheduler-8.4.3.jar:8.4.3]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) ~[zeebe-scheduler-8.4.3.jar:8.4.3]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) [zeebe-scheduler-8.4.3.jar:8.4.3]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.4.3.jar:8.4.3]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.4.3.jar:8.4.3]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.4.3.jar:8.4.3]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.4.3.jar:8.4.3]
Caused by: java.lang.IllegalStateException: Cannot complete future, the future is already completed  with value true
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.complete(CompletableActorFuture.java:171) ~[zeebe-scheduler-8.4.3.jar:8.4.3]
	at io.camunda.zeebe.scheduler.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:29) ~[zeebe-scheduler-8.4.3.jar:8.4.3]
	at io.camunda.zeebe.scheduler.retry.RecoverableRetryStrategy.run(RecoverableRetryStrategy.java:48) ~[zeebe-scheduler-8.4.3.jar:8.4.3]
	... 6 more
```

</details>

Version affected: 8.4.3

**Comment by npepinpe** [comment]
Related: https://github.com/camunda/zeebe/issues/14251

**Comment by megglos** [comment]
Workaround: restart affected broker

**Comment by megglos** [comment]
happened in another incident last week (@megglos link it)

**Comment by megglos** [comment]
ZPA-Planning:
- affects availability of a partition until a restart
- we need to root-cause

**Comment by deepthidevaki** [comment]
This occurred due to #16429 combined with the fix https://github.com/camunda/zeebe/pull/16343 which was not included in that version. 

Since #16429 is fixed, I will consider this issue as resolved.
