### ISSUE TITLE
Flaky shouldRecoverAfterOutOfDiskSpaceAfterExporting: io.camunda.zeebe.it.health.DiskSpaceRecoveryIT$WithStandardContainerTes

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#16550]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail?
- Does it block your work?
- Do we suspect that it is a real failure?

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
org.awaitility.core.ConditionTimeoutException: 
Condition with alias 'until the disk is not full anymore' didn't complete within 3 minutes because assertion condition with alias until the disk is not full anymore 
Expecting code not to raise a throwable but caught
  "io.camunda.zeebe.client.api.command.ClientStatusException: Cannot accept requests for partition 1. Broker is out of disk space
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.transformExecutionException(ZeebeClientFutureImpl.java:116)
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:54)
	at io.camunda.zeebe.it.health.DiskSpaceRecoveryIT.publishMessage(DiskSpaceRecoveryIT.java:84)
	at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:63)
	at org.assertj.core.api.NotThrownAssert.isThrownBy(NotThrownAssert.java:43)
	at io.camunda.zeebe.it.health.DiskSpaceRecoveryIT$WithStandardContainerTest.lambda$shouldRecoverAfterOutOfDiskSpaceAfterExporting$1(DiskSpaceRecoveryIT.java:132)
	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Cannot accept requests for partition 1. Broker is out of disk space
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:52)
	... 11 more
Caused by: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Cannot accept requests for partition 1. Broker is out of disk space
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:481)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	... 3 more
".
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
	at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:769)
	at io.camunda.zeebe.it.health.DiskSpaceRecoveryIT$WithStandardContainerTest.shouldRecoverAfterOutOfDiskSpaceAfterExporting(DiskSpaceRecoveryIT.java:131)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.lang.AssertionError: 
Expecting code not to raise a throwable but caught
  "io.camunda.zeebe.client.api.command.ClientStatusException: Cannot accept requests for partition 1. Broker is out of disk space
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.transformExecutionException(ZeebeClientFutureImpl.java:116)
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:54)
	at io.camunda.zeebe.it.health.DiskSpaceRecoveryIT.publishMessage(DiskSpaceRecoveryIT.java:84)
	at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:63)
	at org.assertj.core.api.NotThrownAssert.isThrownBy(NotThrownAssert.java:43)
	at io.camunda.zeebe.it.health.DiskSpaceRecoveryIT$WithStandardContainerTest.lambda$shouldRecoverAfterOutOfDiskSpaceAfterExporting$1(DiskSpaceRecoveryIT.java:132)
	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Cannot accept requests for partition 1. Broker is out of disk space
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:52)
	... 11 more
Caused by: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Cannot accept requests for partition 1. Broker is out of disk space
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:481)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	... 3 more
"
	at io.camunda.zeebe.it.health.DiskSpaceRecoveryIT$WithStandardContainerTest.lambda$shouldRecoverAfterOutOfDiskSpaceAfterExporting$1(DiskSpaceRecoveryIT.java:132)
	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

https://github.com/camunda/zeebe/actions/runs/8024770580
[Test results for [IT] QA Integration Tests.zip](https://github.com/camunda/zeebe/files/14401732/Test.results.for.IT.QA.Integration.Tests.zip)

**Comment by koevskinikola** [comment]
Happened again [here](https://github.com/camunda/zeebe/actions/runs/8155024698/job/22289665009).

**Comment by deepthidevaki** [comment]
In a successful run we see the following logs
```
2024-03-06 07:21:42.191 [Broker-0] [zb-actors-0] [BrokerAdminServiceImpl] INFO 
      io.camunda.zeebe.broker.system - Resuming exporting on all partitions.
2024-03-06 07:21:56.964 [Broker-0] [zb-actors-1] [BrokerAdminServiceImpl] INFO 
      io.camunda.zeebe.broker.system - Triggering Snapshots on all partitions.
2024-03-06 07:21:56.976 [Broker-0] [zb-actors-1] [SnapshotStore-1] INFO 
      io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore - Committed new snapshot 319-1-478-480
2024-03-06 07:21:57.997 [Broker-0] [zb-actors-0] [DiskSpaceUsageMonitorActor] INFO 
      io.camunda.zeebe.broker.system - Disk space available again. Current available 10391552 bytes
2024-03-06 07:21:57.999 [Broker-0] [zb-actors-0] [ZeebePartition-1] INFO 
      io.camunda.zeebe.broker.system - Disk space usage is below threshold. Resuming stream processor.
2024-03-06 07:21:57.999 [Broker-0] [zb-actors-0] [ZeebePartition-1] INFO 
      io.camunda.zeebe.broker.system - ZeebePartition-1 recovered, marking it as healthy
2024-03-06 07:21:58.000 [Broker-0] [zb-actors-1] [HealthCheckService] INFO 
      io.camunda.zeebe.broker.system - Partition-1 recovered, marking it as healthy
```

But in the failed one after "Triggering Snapshots on all partitions", we don't see anything. It looks like no snapshot was taken. 
```
2024-02-23 20:42:36.644 [Broker-0] [zb-actors-1] [BrokerAdminServiceImpl] INFO 
      io.camunda.zeebe.broker.system - Resuming exporting on all partitions.
2024-02-23 20:43:10.695 [Broker-0] [zb-actors-1] [BrokerAdminServiceImpl] INFO 
      io.camunda.zeebe.broker.system - Triggering Snapshots on all partitions.

20:46:11.359 [] [] [ForkJoinPool-12-worker-1] INFO  io.camunda.zeebe.process.test.filters.logger.IncidentLogger - 
20:46:11.395 [] [] [ForkJoinPool-12-worker-1] INFO  io.camunda.zeebe.process.test.filters.logger.RecordStreamLogger - 
```

Have to root cause why snapshot was not taken. Possible hypothesis
1. It was triggered too early before the records were exported, so there was nothing to include in new snapshot
2. Exporting was not resumed.

**Comment by deepthidevaki** [comment]
In the runs where the test passes, following events occur in order

1. Transition to leader in term 1
2. StreamProcessor starts processing
3. Pauses Exporting
4. Writes many commands
5. DiskSpaceMonitor detects disk usage is above threshold
6. Pauses CommandApi and StreamProcessor (lastProcessedPosition = position of last command processed until now)
7. Resume exporting, wait until all records are exported
8. Takes snapshot, compact, disk is available again


In the runs where the test fails, following events occur in order
1. Transition to leader in term 1
2. StreamProcessor starts processing
3. Pauses Exporting
4. Writes many commands
5. Journal write fails because no free space.
   This is because DiskSpaceMonitor runs only periodically. So before it can pause accepting new commands, disk is already full.
6. Leader steps down, and becomes leader again (because it is a single node cluster)
8. By this time DiskSpaceMonitor detects disk usage is above threshold, Pauses CommandApi and StreamProcessor
7. Transition to leader in term 2 => stopping stream processor and restarting
8. Restart StreamProcessor with state=paused
9. Since it is paused, replay is also paused meaning lastProcessedPosition=UNSET
10. Resume exporting, wait until all records are exported
11. Triggers snapshot => No snapshot taken because lastProcessedPosition is unset.


Here there are two issues here:
1. When there is no snapshot, and replay is paused the `lastProcessedPosition` cannot be updated. (This is case in the flaky test)
1. If there is a snapshot before we went OOD, lastProcessedPosition can be taken from the snapshot position. However, I observed that when StreamProcesser in the Leader is currently replaying, it returns UNSET for `lastProcessedPosition`. This should be fixed to return the position from replayStateMachine.1

**Question**
Should we consider the case where there is no snapshot before we go OOD. The probability of this happening in a production cluster is very low.
- If we don't consider this case then fixing 2 will improve the situation.
- If we want to consider the case then we may have to NOT pause Replay during OOD. However, this is tricky as replaying events can write more data to runtime thus increasing the space required for rocksdb state. This can worsen the situation.
