### ISSUE TITLE
GrpcClientRule leaks http clients

### ISSUE THREAD

**Issue by megglos** [camunda/zeebe#16698]
**Describe the bug**

Running a single test class with a broker rule until it fails eventually ends up in a java.io.IOException: Too many open files for me after 100+ runs.

Looking at the threads I see countless httpclient ones (3k+), seems we leak apache client instances? The failure also happens on client creation within the embedded broker rule, see stack trace.

![image](https://github.com/camunda/zeebe/assets/209518/6cb20d04-986b-4082-bd57-5ab4dd1e9485)

**To Reproduce**

Loop `BrokerRestartTest` until failure

**Expected behavior**

Should run till the end of time.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalStateException: Unexpected failure opening I/O selector

	at org.apache.hc.core5.reactor.AbstractSingleCoreIOReactor.<init>(AbstractSingleCoreIOReactor.java:64)
	at org.apache.hc.core5.reactor.SingleCoreIOReactor.<init>(SingleCoreIOReactor.java:81)
	at org.apache.hc.core5.reactor.DefaultConnectingIOReactor.<init>(DefaultConnectingIOReactor.java:71)
	at org.apache.hc.client5.http.impl.async.HttpAsyncClientBuilder.build(HttpAsyncClientBuilder.java:965)
	at io.camunda.zeebe.client.impl.http.HttpClientFactory.createClient(HttpClientFactory.java:56)
	at io.camunda.zeebe.client.impl.ZeebeClientImpl.buildHttpClient(ZeebeClientImpl.java:172)
	at io.camunda.zeebe.client.impl.ZeebeClientImpl.<init>(ZeebeClientImpl.java:146)
	at io.camunda.zeebe.client.impl.ZeebeClientImpl.<init>(ZeebeClientImpl.java:138)
	at io.camunda.zeebe.client.impl.ZeebeClientImpl.<init>(ZeebeClientImpl.java:119)
	at io.camunda.zeebe.client.impl.ZeebeClientImpl.<init>(ZeebeClientImpl.java:109)
	at io.camunda.zeebe.client.impl.ZeebeClientBuilderImpl.build(ZeebeClientBuilderImpl.java:485)
	at io.camunda.zeebe.it.util.GrpcClientRule.before(GrpcClientRule.java:88)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:30)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
Caused by: java.io.IOException: Too many open files
	at java.base/sun.nio.ch.IOUtil.makePipe(Native Method)
	at java.base/sun.nio.ch.KQueueSelectorImpl.<init>(KQueueSelectorImpl.java:87)
	at java.base/sun.nio.ch.KQueueSelectorProvider.openSelector(KQueueSelectorProvider.java:36)
	at java.base/java.nio.channels.Selector.open(Selector.java:295)
	at org.apache.hc.core5.reactor.AbstractSingleCoreIOReactor.<init>(AbstractSingleCoreIOReactor.java:62)
	... 34 more

```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: 8.5.0-SNAPSHOT
- Configuration:

**Comment by wollefitz** [comment]
FYI: This bug also surfaced within Web Modeler. We downgraded to `8.5.0-alpha1` for now because there is no fixed version of the client yet.

**Comment by megglos** [comment]
@wollefitz we could do a RC release for you to make use of the latest client (increasing chances we catch other issues as well 😅 )

**Comment by megglos** [comment]
@wollefitz `8.5.0-RC1` containing the fix is available
