### ISSUE TITLE
Flaky cannotLeaveWhenNewConfigurationDoesNotHaveQuorum: io.atomix.raft.ReconfigurationTest$Leaving

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#16719]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? - observed 2-3 failures
- Does it block your work?
- Do we suspect that it is a real failure?

**Failures**

```
java.lang.AssertionError: 

Expecting actual throwable to be an instance of:
  java.util.concurrent.ExecutionException
but was:
  java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	at org.assertj.core.internal.Futures.assertFailedWithin(Futures.java:118)
	...(71 remaining lines not displayed - this can be changed with Assertions.setMaxStackTraceElementsDisplayed)
	at io.atomix.raft.ReconfigurationTest$Leaving.cannotLeaveWhenNewConfigurationDoesNotHaveQuorum(ReconfigurationTest.java:542)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

**Logs**

[Test results for unit tests.zip](https://github.com/camunda/zeebe/files/14496385/Test.results.for.unit.tests.zip)

**Comment by oleschoenburg** [comment]
I was able to reproduce locally:

```
14:53:11.141 [raft-server-0] TRACE io.atomix.raft.roles.LeaderRole - RaftServer{2}{role=LEADER} - Received ReconfigureRequest{index=0, term=0, members=[DefaultRaftMember{id=3, type=ACTIVE, updated=2024-03-08T13:53:10.409262686Z}, DefaultRaftMember{id=1, type=ACTIVE, updated=2024-03-08T13:53:10.409262686Z}]}
14:53:18.215 [raft-server-0] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{2} - Suspected network partition after 392 failures from 3 over a period of time 7177 > 1000, stepping down
```

In successful test runs, this detection of a network partition happens much earlier:

```
15:08:40.941 [raft-server-0] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{1} - Suspected network partition after 6 failures from 3 over a period of time 1003 > 1000, stepping down
```

As far as I can tell we rely on the detection of a network partition and the following step down to actually fail the reconfigure request.

What I don't understand is why it takes 7 seconds to suspect the network partition, much longer than the usual 1 second.

**Comment by oleschoenburg** [comment]
Some more details from a failed run:
```
16:30:53.572 [raft-server-0] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{1} - VersionedAppendRequest{version=2, term=1, leader=1, prevLogIndex=1, prevLogTerm=1, entries=0, commitIndex=1} to 3 failed: 561
16:30:53.572 [raft-server-0] TRACE io.atomix.raft.impl.RandomizedElectionTimer - Election timeout scheduled for PT0.989S
16:30:53.572 [raft-server-0] TRACE io.atomix.raft.roles.LeaderAppender - RaftServer{1} - Received AppendResponse{status=OK, term=1, succeeded=true, lastLogIndex=2, lastSnapshotIndex=0, configurationIndex=2} from 2
16:30:53.572 [raft-server-0] TRACE io.atomix.raft.roles.LeaderAppender - RaftServer{1} - Sending VersionedAppendRequest{version=2, term=1, leader=1, prevLogIndex=1, prevLogTerm=1, entries=0, commitIndex=1} to 3
16:30:53.572 [raft-server-0] TRACE io.atomix.raft.roles.LeaderAppender - RaftServer{1} - Sending VersionedAppendRequest{version=2, term=1, leader=1, prevLogIndex=2, prevLogTerm=1, entries=0, commitIndex=1} to 2
16:31:00.019 [raft-server-0] TRACE io.atomix.raft.roles.FollowerRole - RaftServer{2}{role=FOLLOWER} - Received InternalAppendRequest[term=1, leader=1, prevLogIndex=2, prevLogTerm=1, commitIndex=1, entries=[]]
16:31:00.019 [raft-server-0] TRACE io.atomix.raft.roles.FollowerRole - RaftServer{2}{role=FOLLOWER} - Sending AppendResponse{status=OK, term=1, succeeded=true, lastLogIndex=2, lastSnapshotIndex=0, configurationIndex=2}
16:31:00.020 [raft-server-0] TRACE io.atomix.raft.impl.RandomizedElectionTimer - Election timeout scheduled for PT0.963S
16:31:00.021 [raft-server-0] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{1} - VersionedAppendRequest{version=2, term=1, leader=1, prevLogIndex=1, prevLogTerm=1, entries=0, commitIndex=1} to 3 failed: 7010
```

So for some reason there's a gap of 7 seconds where apparently nothing happened :thinking:

**Comment by deepthidevaki** [comment]
It seems #16833 didn't fix it. https://github.com/camunda/zeebe/commit/0aa4274e04db28d7a1d5abad75d098b767d43ab6

**Comment by oleschoenburg** [comment]
Still the same issue, there's just a gap of ~3 seconds where nothing happens, leading to the timeout:
```
07:44:21.375 [raft-server-0] TRACE io.atomix.raft.roles.LeaderAppender - RaftServer{2} - Sending VersionedAppendRequest{version=2, term=2, leader=2, prevLogIndex=3, prevLogTerm=2, entries=0, commitIndex=2} to 1
07:44:21.375 [raft-server-0] TRACE io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - Received InternalAppendRequest[term=2, leader=2, prevLogIndex=3, prevLogTerm=2, commitIndex=2, entries=[]]
07:44:21.375 [raft-server-0] TRACE io.atomix.raft.roles.FollowerRole - RaftServer{1}{role=FOLLOWER} - Sending AppendResponse{status=OK, term=2, succeeded=true, lastLogIndex=3, lastSnapshotIndex=0, configurationIndex=3}
07:44:21.389 [raft-server-0] TRACE io.atomix.raft.roles.LeaderAppender - RaftServer{2} - Sending VersionedAppendRequest{version=2, term=2, leader=2, prevLogIndex=1, prevLogTerm=1, entries=0, commitIndex=2} to 3
07:44:23.793 [raft-server-0] TRACE io.atomix.raft.impl.RandomizedElectionTimer - Election timeout scheduled for PT0.713S
07:44:23.793 [raft-server-0] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{2} - VersionedAppendRequest{version=2, term=2, leader=2, prevLogIndex=3, prevLogTerm=2, entries=0, commitIndex=2} to 1 failed
java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.CompletableFuture$Timeout.run(CompletableFuture.java:2920) ~[?:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
07:44:23.793 [raft-server-0] TRACE io.atomix.raft.roles.LeaderAppender - RaftServer{2} - Sending VersionedAppendRequest{version=2, term=2, leader=2, prevLogIndex=3, prevLogTerm=2, entries=0, commitIndex=2} to 1
07:44:23.794 [raft-server-0] WARN  io.atomix.raft.roles.LeaderAppender - RaftServer{2} - Suspected network partition after 1954 failures from 3 over a period of time 3006 > 1000, stepping down
```

**Comment by oleschoenburg** [comment]
I cannot reproduce this anymore in >1.6k runs. While I'd like to understand why this still happens in CI, I'm now also thinking about ways to make this test a bt more robust.

**Comment by oleschoenburg** [comment]
Just increasing the timeout is probably enough to stabilize the test but is a bit unsatisfying :confused:

**Comment by deepthidevaki** [comment]
Can we somehow wait until the step down has happened? Does that make the test stable?
