### ISSUE TITLE
Actor call get() on future which has not completed

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#16777]
**Describe the bug**

An exception occurs when closing the broker client in the gateway.

**To Reproduce**

/

**Expected behavior**

The error doesn't occur.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalStateException: Actor call get() on future which has not completed. Actors must be non-blocking. Use actor.runOnCompletion().
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.get(CompletableActorFuture.java:125) ~[zeebe-scheduler-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.FutureUtil.join(FutureUtil.java:32) ~[zeebe-scheduler-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.join(CompletableActorFuture.java:208) ~[zeebe-scheduler-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.Actor.close(Actor.java:97) ~[zeebe-scheduler-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.broker.client.impl.BrokerClientImpl.doAndLogException(BrokerClientImpl.java:150) ~[zeebe-broker-client-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.broker.client.impl.BrokerClientImpl.close(BrokerClientImpl.java:79) ~[zeebe-broker-client-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:232) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:559) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1202) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:520) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1195) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1183) ~[spring-context-6.1.4.jar:6.1.4]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1144) ~[spring-context-6.1.4.jar:6.1.4]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.doClose(ReactiveWebServerApplicationContext.java:149) ~[spring-boot-3.2.3.jar:3.2.3]
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1090) ~[spring-context-6.1.4.jar:6.1.4]
	at org.springframework.boot.SpringApplication.close(SpringApplication.java:1463) ~[spring-boot-3.2.3.jar:3.2.3]
	at org.springframework.boot.SpringApplication.exit(SpringApplication.java:1400) ~[spring-boot-3.2.3.jar:3.2.3]
	at io.camunda.zeebe.broker.BrokerShutdownHelper.initiateShutdown(BrokerShutdownHelper.java:25) ~[camunda-zeebe-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.broker.StandaloneBroker.lambda$run$0(StandaloneBroker.java:92) ~[camunda-zeebe-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.broker.SpringBrokerBridge.initiateShutdown(SpringBrokerBridge.java:80) ~[zeebe-broker-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.broker.bootstrap.PartitionManagerStep.shutdownOnInconsistentTopology(PartitionManagerStep.java:115) ~[zeebe-broker-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.broker.bootstrap.PartitionManagerStep.lambda$startupInternal$0(PartitionManagerStep.java:56) ~[zeebe-broker-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.topology.ClusterTopologyManagerImpl.lambda$onGossipReceived$5(ClusterTopologyManagerImpl.java:203) ~[zeebe-cluster-topology-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) [zeebe-scheduler-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) [zeebe-scheduler-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
```

</p>
</details>

**Environment:**
- OS:  Camunda SaaS chaos
- Zeebe Version:  `8.5.0-SNAPSHOT`
- Configuration: 
- [Downloaded logs](https://drive.google.com/file/d/1-sTs-RyWTV_-zCbRqhtt4ENCg-6sjHze/view?usp=sharing) (internal)
- [GCP logs](https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.pod_name%3D%22zeebe-3%22%0Aresource.labels.cluster_name%3D%22worker-chaos-1%22%0Aresource.labels.project_id%3D%22camunda-saas-int-chaos%22%0Aresource.labels.namespace_name%3D%2269caf979-aa4e-4a8e-a1e1-bb491998fbdd-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.location%3D%22europe-west1%22;pinnedLogId=2024-03-07T01:54:34.021093289Z%2F2nz82a3rohuk9vhp;cursorTimestamp=2024-03-07T01:54:34.025777471Z;startTime=2024-03-07T01:25:04.021Z;endTime=2024-03-07T02:25:04.021Z?project=camunda-saas-int-chaos) (internal)

**Comment by oleschoenburg** [comment]
@deepthidevaki seems to be caused by your recent changes in https://github.com/camunda/zeebe/pull/16367
