### ISSUE TITLE
Transition from FOLLOWER on term 35 appears blocked

### ISSUE THREAD

**Issue by michaelholtermann** [camunda/zeebe#16955]
Hi,

after an update of the Broker from 8.4.2 to 8.4.5, one of the partitions remain in unhealthy state:
![image](https://github.com/camunda/zeebe/assets/83571016/6ab9c37e-7c66-445e-a9f5-6419425f3a3b)

Any help is appreciated.

I already tried to restart the instance, but with no success.

**Describe the bug**
We run the broker on a Kubernetes Stateful Set with 3 nodes with 3 partitions each.

When upgrading from 8.4.2 to 8.4.5 on a quite small instance with only a hand full of processes, one of the partition remains in an unhealthy state.

Much larger installations were updated just fine.

**To Reproduce**
n/a

**Expected behavior**

The partition becomes healthy, like the others do.

**Log/Stacktrace**

The following is the last exception from the log of that instance. There are some more before that, but I'm not sure which one might be relevant.

<details><summary>Last Exception</summary>
 <p>

```
2024-03-18 15:04:13.206 [] [atomix-cluster-heartbeat-sender] [] INFO 
      io.atomix.cluster.protocol.swim - 2 - Member added Member{id=0, address=process-control-tower-broker-0.process-control-tower-broker.services.svc.cluster.local:26502, properties={brokerInfo=EADJAAAABAAAAAAAAwAAAAMAAAADAAAAAAABCgAAAGNvbW1hbmRBcGlcAAAAcHJvY2Vzcy1jb250cm9sLXRvd2VyLWJyb2tlci0wLnByb2Nlc3MtY29udHJvbC10b3dlci1icm9rZXIuc2VydmljZXMuc3ZjLmNsdXN0ZXIubG9jYWw6MjY1MDEFAAAMAAAFAAAAOC40LjUFAAA=}}
2024-03-18 15:04:13.242 [Broker-2] [zb-actors-0] [] WARN 
      io.camunda.zeebe.topology.gossip.ClusterTopologyGossiper - Failed to sync with 0
java.util.concurrent.CompletionException: io.atomix.cluster.messaging.MessagingException$RemoteHandlerFailure: Remote handler failed to handle message, cause: Failed to handle message, host process-control-tower-broker-2.process-control-tower-broker.services.svc.cluster.local:26502 is not a known cluster member
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$executeOnPooledConnection$25(NettyMessagingService.java:626) ~[zeebe-atomix-cluster-8.4.5.jar:8.4.5]
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31) ~[guava-33.0.0-jre.jar:?]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$executeOnPooledConnection$26(NettyMessagingService.java:624) ~[zeebe-atomix-cluster-8.4.5.jar:8.4.5]
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
	at io.atomix.cluster.messaging.impl.AbstractClientConnection.dispatch(AbstractClientConnection.java:49) ~[zeebe-atomix-cluster-8.4.5.jar:8.4.5]
	at io.atomix.cluster.messaging.impl.AbstractClientConnection.dispatch(AbstractClientConnection.java:30) ~[zeebe-atomix-cluster-8.4.5.jar:8.4.5]
	at io.atomix.cluster.messaging.impl.NettyMessagingService$MessageDispatcher.channelRead0(NettyMessagingService.java:1109) ~[zeebe-atomix-cluster-8.4.5.jar:8.4.5]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.107.Final.jar:4.1.107.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.107.Final.jar:4.1.107.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.107.Final.jar:4.1.107.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.107.Final.jar:4.1.107.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.107.Final.jar:4.1.107.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.107.Final.jar:4.1.107.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.107.Final.jar:4.1.107.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.107.Final.jar:4.1.107.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.107.Final.jar:4.1.107.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.107.Final.jar:4.1.107.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.107.Final.jar:4.1.107.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.107.Final.jar:4.1.107.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.107.Final.jar:4.1.107.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[netty-transport-classes-epoll-4.1.107.Final.jar:4.1.107.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[netty-transport-classes-epoll-4.1.107.Final.jar:4.1.107.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[netty-transport-classes-epoll-4.1.107.Final.jar:4.1.107.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.107.Final.jar:4.1.107.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.107.Final.jar:4.1.107.Final]
	at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: io.atomix.cluster.messaging.MessagingException$RemoteHandlerFailure: Remote handler failed to handle message, cause: Failed to handle message, host process-control-tower-broker-2.process-control-tower-broker.services.svc.cluster.local:26502 is not a known cluster member
	... 22 more
2024-03-18 15:05:28.260 [Broker-2] [zb-actors-1] [ZeebePartition-3] WARN 
      io.camunda.zeebe.broker.system - ZeebePartition-3 failed, marking it as unhealthy: ZeebePartition-3{status=UNHEALTHY, issue=HealthIssue[message=Transition from FOLLOWER on term 35 appears blocked, step StreamProcessor has been running for PT1M27.825S, throwable=null, cause=null]}

```

</p>
</details>

**Environment:**
- OS: Linux, Docker `camunda/zeebe:8.4.5`
- Zeebe Version: 8.4.5
- Configuration:
```
            - name: ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT
              value: "3"
            - name: ZEEBE_BROKER_CLUSTER_CLUSTERSIZE
              value: "3"
            - name: ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR
              value: "3"
            - name: ZEEBE_BROKER_THREADS_CPUTHREADCOUNT
              value: "2"
            - name: ZEEBE_BROKER_THREADS_IOTHREADCOUNT
              value: "2"
            - name: ZEEBE_BROKER_GATEWAY_ENABLE
              value: "false"
            - name: ZEEBE_BROKER_EXPORTERS_HAZELCAST_JARPATH
              value: exporters/zeebe-hazelcast-exporter.jar
            - name: ZEEBE_BROKER_EXPORTERS_HAZELCAST_CLASSNAME
              value: io.zeebe.hazelcast.exporter.HazelcastExporter
```

**Comment by michaelholtermann** [comment]
Thanks for taking care :-)

Luckily this is a rather small Zeebe instance on a large volume, so I think it will keep working for some time 🤞

**Comment by michaelholtermann** [comment]
Good morning, @npepinpe,

are there any news on this topic?

If not, what do you think about following https://docs.camunda.io/docs/self-managed/zeebe-deployment/operations/cluster-scaling/ to create a new replica and drop the broken one?

**Comment by megglos** [comment]
@michaelholtermann could you provide us some more logs from the broker with the unhealthy partition? Especially before the exception log you provided? Did it eventually recover yet or is it still stuck?

**Comment by michaelholtermann** [comment]
@megglos I extracted something from the archives, I hope it's helpful, please let me now if I should pre-process this somehow.

The lines from above are present in this file.
[broken-broker-partition.txt](https://github.com/camunda/zeebe/files/14933943/broken-broker-partition.txt)

The partition is still unhealthy. It was restarted, meanwhile, with no success.

**Comment by npepinpe** [comment]
Putting it in the inbox, let's see if anyone has capacity next week to investigate.

**Comment by oleschoenburg** [comment]
This seems to be the underlying cause:
```
1706383036318376010	2024-03-18 14:04:00	2024-03-18 14:04:01	14022722241	process-control-tower-broker-2-6		User	Info	process-control-tower-broker	java.lang.IllegalStateException: Expected to find event with the snapshot position 1211014 in log stream, but nothing was found. Failed to recover 'StreamProcessor-3'.
1706383036318376011	2024-03-18 14:04:00	2024-03-18 14:04:01	14022722241	process-control-tower-broker-2-6		User	Info	process-control-tower-broker	\tat io.camunda.zeebe.stream.impl.StreamProcessor.recoverFromSnapshot(StreamProcessor.java:402) ~[zeebe-stream-platform-8.4.5.jar:8.4.5]
1706383036318376012	2024-03-18 14:04:00	2024-03-18 14:04:01	14022722241	process-control-tower-broker-2-6		User	Info	process-control-tower-broker	\tat io.camunda.zeebe.stream.impl.StreamProcessor.onActorStarted(StreamProcessor.java:162) ~[zeebe-stream-platform-8.4.5.jar:8.4.5]
1706383036318376013	2024-03-18 14:04:00	2024-03-18 14:04:01	14022722241	process-control-tower-broker-2-6		User	Info	process-control-tower-broker	\tat io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) [zeebe-scheduler-8.4.5.jar:8.4.5]
1706383036318376015	2024-03-18 14:04:00	2024-03-18 14:04:01	14022722241	process-control-tower-broker-2-6		User	Info	process-control-tower-broker	\tat io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) [zeebe-scheduler-8.4.5.jar:8.4.5]
1706383036318376017	2024-03-18 14:04:00	2024-03-18 14:04:01	14022722241	process-control-tower-broker-2-6		User	Info	process-control-tower-broker	\tat io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.4.5.jar:8.4.5]
1706383036318376019	2024-03-18 14:04:00	2024-03-18 14:04:01	14022722241	process-control-tower-broker-2-6		User	Info	process-control-tower-broker	\tat io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.4.5.jar:8.4.5]
1706383036318376020	2024-03-18 14:04:00	2024-03-18 14:04:01	14022722241	process-control-tower-broker-2-6		User	Info	process-control-tower-broker	\tat io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.4.5.jar:8.4.5]
1706383036318376021	2024-03-18 14:04:00	2024-03-18 14:04:01	14022722241	process-control-tower-broker-2-6		User	Info	process-control-tower-broker	\tat io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.4.5.jar:8.4.5]
1706383036318376022	2024-03-18 14:04:00	2024-03-18 14:04:01	14022722241	process-control-tower-broker-2-6		User	Info	process-control-tower-broker	2024-03-18 15:04:00.438 [Broker-2] [zb-actors-0] [StreamProcessor-3] ERROR
1706383036318376023	2024-03-18 14:04:00	2024-03-18 14:04:01	14022722241	process-control-tower-broker-2-6		User	Info	process-control-tower-broker	      io.camunda.zeebe.logstreams - Actor StreamProcessor-3 failed in phase STARTED.
```

@michaelholtermann Looks like the data for partition 3 on broker 2 is corrupted. Do you know what disks Zeebe is running on? We often see this when NFS is involved which we don't support.

**Comment by michaelholtermann** [comment]
Hi @oleschoenburg,

the broker is deployed in K8s as a Stateful Set (no Helm chart).

We run on AWS EKS, and the persistent volume is backed by AWS EBS gp2.

We run two handful of installations like this; this is the only one that shows this error.

**Comment by oleschoenburg** [comment]
Do you see the error message `Expected to find event with the snapshot position` on any of the other brokers?
If not, then the data seems to be corrupted on broker 2 only and you could recover it by deleting the data of partition 3 from broker 2. It will recover the partition data from the other two replicas.

Unfortunately we don't have a clue as to why the data was corrupted. The disk type "AWS EBS gp2" should be good. @michaelholtermann I assume that you haven't changed the default configuration much, for example to disable flushing?
Did anything notable happen before this issue appeared? For example a unclean node shutdown?

**Comment by oleschoenburg** [comment]
Then you could recover by running something like the following command on broker 2:
```
rm -rf data/raft-partition/partitions/3
```

After a restart, broker 2 will recover the missing data for partition 3 from the other two replicas and become healthy again.

**Comment by michaelholtermann** [comment]
I'll go this route and report back. This will take a few days.

I think we can close this issue now.

Thanks again for your support 👍
