### ISSUE TITLE
java.lang.InterruptedException: null when closing BrokerClient

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#17098]
**Describe the bug**

Look's like when closing the gateway we run into a an issue with the BrokerClient that shows with an error see [error group](https://console.cloud.google.com/errors/detail/CMqWpJbekIOrmwE;service=zeebe;version=8.5.0-SNAPSHOT-main-3008dfa6;time=P7D?project=camunda-saas-int-chaos)

```
DEBUG 2024-03-25T08:24:19.638633056Z Closing gateway broker client ...
DEBUG 2024-03-25T08:24:19.638981057Z Updating topology with clusterSize 3, partitionsCount 4 and replicationFactor 2
ERROR 2024-03-25T08:24:19.639189341Z Exception when closing client. Ignoring
```

**To Reproduce**

Not clear, happened during chaos experiment in SaaS.

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.InterruptedException: null
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source) ~[?:?]
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.get(CompletableActorFuture.java:139) ~[zeebe-scheduler-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.FutureUtil.join(FutureUtil.java:32) ~[zeebe-scheduler-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.join(CompletableActorFuture.java:208) ~[zeebe-scheduler-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.Actor.close(Actor.java:97) ~[zeebe-scheduler-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.broker.client.impl.BrokerClientImpl.doAndLogException(BrokerClientImpl.java:150) ~[zeebe-broker-client-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.broker.client.impl.BrokerClientImpl.close(BrokerClientImpl.java:76) ~[zeebe-broker-client-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:232) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:559) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1202) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:520) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1195) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1186) ~[spring-context-6.1.5.jar:6.1.5]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1147) ~[spring-context-6.1.5.jar:6.1.5]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.doClose(ReactiveWebServerApplicationContext.java:149) ~[spring-boot-3.2.4.jar:3.2.4]
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1093) ~[spring-context-6.1.5.jar:6.1.5]
	at org.springframework.boot.SpringApplication.close(SpringApplication.java:1463) ~[spring-boot-3.2.4.jar:3.2.4]
	at org.springframework.boot.SpringApplication.exit(SpringApplication.java:1400) ~[spring-boot-3.2.4.jar:3.2.4]
	at io.camunda.zeebe.broker.BrokerShutdownHelper.shutdown(BrokerShutdownHelper.java:31) ~[camunda-zeebe-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.broker.BrokerShutdownHelper.lambda$initiateShutdown$0(BrokerShutdownHelper.java:27) ~[camunda-zeebe-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at java.base/java.lang.VirtualThread.run(Unknown Source) ~[?:?]
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: Main (8.5.0-snapshot)
- Configuration:

**Comment by Zelldon** [comment]
@npepinpe might be related to the REST API changes? Not clear to me yet.

**Comment by npepinpe** [comment]
Could be I guess, though it's unclear as well to me. The BrokerClient fails to shutdown in time here, so basically it runs out the timeout on the join. 

From the logs:

![image](https://github.com/camunda/zeebe/assets/43373/85c835bd-1b3b-4b93-878e-eca3f980537d)

It looks like the topology manager is the one which was interrupted during close, meaning it was probably hanging...except almost no time elapsed according to the logged statements, so essentially the ActorThread was interrupted while closing the topology manager, but who knows why (the topology manager close method literally just closes the actor and nothing else)...

**Comment by megglos** [comment]
ZPA-Triage:
- falls into the domain of the distributed platform and the related gateway setup

**Comment by npepinpe** [comment]
ZDP triage: likely because the actor scheduler bean has no link to the broker client bean and they can be closed independently, leading to the actor thread getting interrupted on shutdown.

Impact is quite low, mostly noise, as the node is shutting down anyway.

**Comment by koevskinikola** [comment]
Error occured again on the `zeebe:release-8-5-12` benchmark.

[GCP logs](https://console.cloud.google.com/logs/query;query=error_groups.id%3D%22CMqWpJbekIOrmwE%22%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.pod_name%3D%22release-benchmark-8-5-12-zeebe-0%22%0Aresource.labels.namespace_name%3D%22release-benchmark-8-5-12%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.container_name%3D%22zeebe%22;cursorTimestamp=2025-02-23T09:44:23.927919537Z;startTime=2025-02-23T09:14:53.927Z;endTime=2025-02-23T10:14:53.927Z?inv=1&invt=Abqmsw&project=zeebe-io) (internal link).

**Comment by Hardikraja** [comment]
I opened a fix PR for this issue: #50650.

Summary:
- preserve interrupt status when broker client close is interrupted
- treat interruption during close as shutdown noise (debug) instead of error
- add test coverage in BrokerClientTest for interrupt status preservation

Verification:
- ./mvnw -pl zeebe/broker-client -DskipChecks clean test (47 tests, 0 failures)

**Comment by Hardikraja** [comment]
Update: the fix is now in PR #50650 and is ready for review.

Local verification:
- ./mvnw -pl zeebe/broker-client -DskipChecks clean test (47 tests, 0 failures)
