### ISSUE TITLE
TimerStartEventTest.shouldNotReTriggerTimerAfterDuplicateDeployment is flaky

### ISSUE THREAD

**Issue by berkaycanbc** [camunda/zeebe#17255]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? once
- Does it block your work? no
- Do we suspect that it is a real failure?

There is a flakiness reported previously for this test https://github.com/camunda/zeebe/issues/6975 but the cause is different, so I opened a new issue.

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Error:  Tests run: 22, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 24.75 s <<< FAILURE! -- in io.camunda.zeebe.engine.processing.timer.TimerStartEventTest
Error:  io.camunda.zeebe.engine.processing.timer.TimerStartEventTest.shouldNotReTriggerTimerAfterDuplicateDeployment -- Time elapsed: 5.478 s <<< ERROR!
io.camunda.zeebe.test.util.stream.StreamWrapperException: No event found matching the criteria
	at io.camunda.zeebe.test.util.stream.StreamWrapper.await(StreamWrapper.java:87)
	at io.camunda.zeebe.engine.processing.timer.TimerStartEventTest.shouldNotReTriggerTimerAfterDuplicateDeployment(TimerStartEventTest.java:250)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
</pre>
</details>

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

CI build: [link](https://github.com/camunda/zeebe/actions/runs/8529432987/job/23365202138#step:8:5496)
Downloaded logs: [link](https://drive.google.com/drive/folders/1_2F7XcnUNogzKGdw3rYvmKflDdzqO-li)

**Comment by berkaycanbc** [comment]
Occurred again: https://github.com/camunda/zeebe/actions/runs/8529432987/job/23383382360#step:8:5496
