### ISSUE TITLE
Tests that increase time by >5s are flaky

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#17258]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? Locally, every 60 runs or so, but also blocks CI [here](https://github.com/camunda/zeebe/actions/runs/8535911126?pr=17251)
- Does it block your work? It's annoying everyone
- Do we suspect that it is a real failure? No, the issue is related to the actor clock usage in tests

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

A typical failure is that something was not seen on the log:
```
io.camunda.zeebe.test.util.stream.StreamWrapperException: No event found matching the criteria
	at io.camunda.zeebe.test.util.stream.StreamWrapper.await(StreamWrapper.java:87)
	at io.camunda.zeebe.engine.processing.bpmn.subprocess.EmbeddedSubProcessTest.shouldTerminateSubProcessWithNonInterruptingBoundaryEvent(EmbeddedSubProcessTest.java:171)
```

This would happen after calling `ENGINE.increaseTime(<time>)` in the test where `<time>` is larger than 5s.

**Hypotheses**

> List any hypotheses if you have one; can be omitted

This issue exists because the test thread updates the actor clock (engine's clock), while the actor's scheduling of timersubscriptions occurs on a different thread. The timer subscriptions calculate their own delay inside this other thread, and can read the newly updated actor clock.

The result is that the engine schedules a timer in 1 minute, and moves the clock forward 1 minute. The actor then async schedules this timer 1 minute in the future (after the clock was changed). 

Tests that use timers under 5 seconds don't typically encounter this issue, because the timer is triggered naturally still while awaiting the recording exporter to see the events.

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
11:18:52.089 [StreamProcessor-1] DEBUG io.camunda.zeebe.engine.processing.scheduled.DueDateChecker{timer} - Scheduling next execution at 1712140012089
11:18:52.190 [AsyncProcessingScheduleActor-1] DEBUG io.camunda.zeebe.engine.processing.scheduled.DueDateChecker{timer} - Scheduling next execution at 1712140012190
11:18:52.190 [AsyncProcessingScheduleActor-1] DEBUG io.camunda.zeebe.util.actor - Scheduling at 1712140072190
11:18:52.190 [StreamProcessor-1] DEBUG io.camunda.zeebe.util.actor - Scheduling at 1712140072190
11:18:52.191 [AsyncProcessingScheduleActor-1] DEBUG io.camunda.zeebe.util.actor - Scheduling at 1712140072191
11:18:52.191 [AsyncProcessingScheduleActor-1] DEBUG io.camunda.zeebe.util.actor - Scheduling at 1712140072191
11:18:52.191 [AsyncProcessingScheduleActor-1] DEBUG io.camunda.zeebe.util.actor - Scheduling at 1712140072191
11:18:52.191 [AsyncProcessingScheduleActor-1] DEBUG io.camunda.zeebe.util.actor - Scheduling at 1712140072191
11:18:52.191 [AsyncProcessingScheduleActor-1] DEBUG io.camunda.zeebe.util.actor - Scheduling at 1712140072191
11:18:52.191 [AsyncProcessingScheduleActor-1] DEBUG io.camunda.zeebe.util.actor - Scheduling at 1712140072191
11:18:53.591 [AsyncProcessingScheduleActor-1] DEBUG io.camunda.zeebe.util.actor - Scheduling at 1712140073591
11:18:54.847 [AsyncProcessingScheduleActor-1] DEBUG io.camunda.zeebe.util.actor - Scheduling at 1712140074847
11:18:56.500 [AsyncProcessingScheduleActor-1] DEBUG io.camunda.zeebe.util.actor - Scheduling at 1712140076500
11:18:57.194 [] INFO  io.camunda.zeebe.test - Test failed, following records were exported:
11:18:57.204 [StreamProcessor-1] DEBUG io.camunda.zeebe.util.actor - Scheduling at 1712140077204
11:18:57.221 [] INFO  io.camunda.zeebe.test - Compact log representation:
--------
	[Timestamp] ['C'ommand/'E'event/'R'ejection] [valueType] [intent] - #[position]->#[source record position] K[key] - [summary of value]
	P9K999 - key; #999 - record position; "ID" element/process id; @"elementid"/[P9K999] - element with ID and key
	Keys are decomposed into partition id and per partition key (e.g. 2251799813685253 -> P1K005). If single partition, the partition is omitted.
	Long IDs are shortened (e.g. 'startEvent_5d56488e-0570-416c-ba2d-36d2a3acea78' -> 'star..acea78'
--------
12:26:52 C DPLY CREATE         - #01-> -1  -1 - 
12:26:52 E PROC CREATED        - #02->#01 K01 - process.xml -> "process..process" (version:1)
12:26:52 E DPLY CREATED        - #03->#01 K02 - process.xml
12:26:52 C CREA CREATE         - #04-> -1  -1 - new <process "process..process"> (default start)  (no vars)
12:26:52 C PI   ACTIVATE       - #05->#04 K03 - PROCESS "process..process" in <process "process..process"[K03]>
12:26:52 E CREA CREATED        - #06->#04 K04 - new <process "process..process"> (default start)  (no vars)
12:26:52 E PI   ACTIVATING     - #07->#04 K03 - PROCESS "process..process" in <process "process..process"[K03]>
12:26:52 E PI   ACTIVATED      - #08->#04 K03 - PROCESS "process..process" in <process "process..process"[K03]>
12:26:52 C PI   ACTIVATE       - #09->#04  -1 - START_EVENT "startEv..5cc6c44" in <process "process..process"[K03]>
12:26:52 E PI   ACTIVATING     - #10->#04 K05 - START_EVENT "startEv..5cc6c44" in <process "process..process"[K03]>
12:26:52 E PI   ACTIVATED      - #11->#04 K05 - START_EVENT "startEv..5cc6c44" in <process "process..process"[K03]>
12:26:52 C PI   COMPLETE       - #12->#04 K05 - START_EVENT "startEv..5cc6c44" in <process "process..process"[K03]>
12:26:52 E PI   COMPLETING     - #13->#04 K05 - START_EVENT "startEv..5cc6c44" in <process "process..process"[K03]>
12:26:52 E PI   COMPLETED      - #14->#04 K05 - START_EVENT "startEv..5cc6c44" in <process "process..process"[K03]>
12:26:52 E PI   SEQ_FLOW_TAKEN - #15->#04 K06 - SEQUENCE_FLOW "sequenc..f73ef87" in <process "process..process"[K03]>
12:26:52 C PI   ACTIVATE       - #16->#04 K07 - SUB_PROCESS "sub-process" in <process "process..process"[K03]>
12:26:52 E PI   ACTIVATING     - #17->#04 K07 - SUB_PROCESS "sub-process" in <process "process..process"[K03]>
12:26:52 E PI   ACTIVATED      - #18->#04 K07 - SUB_PROCESS "sub-process" in <process "process..process"[K03]>
12:26:52 C PI   ACTIVATE       - #19->#04  -1 - START_EVENT "startEv..733e819" in <process "process..process"[K03]>
12:26:52 E PI   ACTIVATING     - #20->#04 K08 - START_EVENT "startEv..733e819" in <process "process..process"[K03]>
12:26:52 E PI   ACTIVATED      - #21->#04 K08 - START_EVENT "startEv..733e819" in <process "process..process"[K03]>
12:26:52 C PI   COMPLETE       - #22->#04 K08 - START_EVENT "startEv..733e819" in <process "process..process"[K03]>
12:26:52 E PI   COMPLETING     - #23->#04 K08 - START_EVENT "startEv..733e819" in <process "process..process"[K03]>
12:26:52 E TIME CREATED        - #24->#04 K09 -  @"boundary"[K07]  in <process "K01"[K03]> due T12:27:07.088
12:26:52 E PI   COMPLETED      - #25->#04 K08 - START_EVENT "startEv..733e819" in <process "process..process"[K03]>
12:26:52 E PI   SEQ_FLOW_TAKEN - #26->#04 K10 - SEQUENCE_FLOW "sequenc..a2ae017" in <process "process..process"[K03]>
12:26:52 C PI   ACTIVATE       - #27->#04 K11 - SERVICE_TASK "task-1" in <process "process..process"[K03]>
12:26:52 E PI   ACTIVATING     - #28->#04 K11 - SERVICE_TASK "task-1" in <process "process..process"[K03]>
12:26:52 E JOB  CREATED        - #29->#04 K12 - K12 "task-1" @"task-1"[K11] (BPMN_ELEMENT), 3 retries, in <process "process..process"[K03]> (no vars)
12:26:52 E PI   ACTIVATED      - #30->#04 K11 - SERVICE_TASK "task-1" in <process "process..process"[K03]>
-------------- Deployed Processes ----------------------
process.xml -> "process..process" (version:1)[K01] ------
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:ns0="http://camunda.org/schema/zeebe/1.0" exporter="Zeebe BPMN Model" exporterVersion="8.5.0-SNAPSHOT" id="definitions_91db8f4f-a60a-44e5-9519-a9070dd27749" xmlns:modeler="http://camunda.org/schema/modeler/1.0" modeler:executionPlatform="Camunda Cloud" modeler:executionPlatformVersion="8.5.0-SNAPSHOT" targetNamespace="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL">
  <process id="process-with-sub-process" isExecutable="true">
    <startEvent id="startEvent_39149964-3978-478d-93bb-f76e35cc6c44">
      <outgoing>sequenceFlow_df512d80-0265-46a1-b277-70df9f73ef87</outgoing>
    </startEvent>
    <subProcess id="sub-process" name="sub-process">
      <incoming>sequenceFlow_df512d80-0265-46a1-b277-70df9f73ef87</incoming>
      <outgoing>sequenceFlow_916f3b68-7a21-4284-b039-a6c060777f7a</outgoing>
      <startEvent id="startEvent_896765f2-4dc7-4a02-8f2f-c333f733e819">
        <outgoing>sequenceFlow_4d1b7ab5-ae48-475a-bc0f-d68fea2ae017</outgoing>
      </startEvent>
      <serviceTask id="task-1" name="task-1">
        <extensionElements>
          <ns0:taskDefinition type="task-1"/>
        </extensionElements>
        <incoming>sequenceFlow_4d1b7ab5-ae48-475a-bc0f-d68fea2ae017</incoming>
        <outgoing>sequenceFlow_b6bef8ff-6026-42bf-977e-568c2c3c438b</outgoing>
      </serviceTask>
      <sequenceFlow id="sequenceFlow_4d1b7ab5-ae48-475a-bc0f-d68fea2ae017" sourceRef="startEvent_896765f2-4dc7-4a02-8f2f-c333f733e819" targetRef="task-1"/>
      <endEvent id="endEvent_476931c6-2a41-46d0-9052-e2ef02239bb0">
        <incoming>sequenceFlow_b6bef8ff-6026-42bf-977e-568c2c3c438b</incoming>
      </endEvent>
      <sequenceFlow id="sequenceFlow_b6bef8ff-6026-42bf-977e-568c2c3c438b" sourceRef="task-1" targetRef="endEvent_476931c6-2a41-46d0-9052-e2ef02239bb0"/>
    </subProcess>
    <sequenceFlow id="sequenceFlow_df512d80-0265-46a1-b277-70df9f73ef87" sourceRef="startEvent_39149964-3978-478d-93bb-f76e35cc6c44" targetRef="sub-process"/>
    <boundaryEvent attachedToRef="sub-process" cancelActivity="false" id="boundary" name="boundary">
      <outgoing>sequenceFlow_2751f838-fb2d-4250-8d95-73d815e0f237</outgoing>
      <timerEventDefinition id="timerEventDefinition_d846c17a-5ca7-4fee-808f-985dd7e1d8fc">
        <timeDuration id="timeDuration_727d13c8-9e24-4ea0-bd2f-c4774d0ce03b">PT15S</timeDuration>
      </timerEventDefinition>
    </boundaryEvent>
    <endEvent id="endEvent_ad9274d6-7322-485a-bce5-aa4ba09d164b">
      <incoming>sequenceFlow_2751f838-fb2d-4250-8d95-73d815e0f237</incoming>
    </endEvent>
    <sequenceFlow id="sequenceFlow_2751f838-fb2d-4250-8d95-73d815e0f237" sourceRef="boundary" targetRef="endEvent_ad9274d6-7322-485a-bce5-aa4ba09d164b"/>
    <endEvent id="endEvent_c81496ca-5896-4ec4-b099-902e4ec3da1e">
      <incoming>sequenceFlow_916f3b68-7a21-4284-b039-a6c060777f7a</incoming>
    </endEvent>
    <sequenceFlow id="sequenceFlow_916f3b68-7a21-4284-b039-a6c060777f7a" sourceRef="sub-process" targetRef="endEvent_c81496ca-5896-4ec4-b099-902e4ec3da1e"/>
  </process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_5ed248f2-1eab-4297-8888-2c078fc7d0eb">
    <bpmndi:BPMNPlane bpmnElement="process-with-sub-process" id="BPMNPlane_cda607ad-59ba-4c21-895f-d9011e32cfa1">
      <bpmndi:BPMNShape bpmnElement="startEvent_39149964-3978-478d-93bb-f76e35cc6c44" id="BPMNShape_eb7bda9e-beea-4886-8f34-cb591fde06ae">
        <dc:Bounds height="36.0" width="36.0" x="100.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="sub-process" id="BPMNShape_425f2c62-7f1f-4a84-975b-b34e88cf17df" isExpanded="true">
        <dc:Bounds height="200.0" width="372.0" x="186.0" y="18.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_df512d80-0265-46a1-b277-70df9f73ef87" id="BPMNEdge_b228c568-36ae-45fd-a937-22e88b928f74">
        <di:waypoint x="136.0" y="118.0"/>
        <di:waypoint x="186.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="startEvent_896765f2-4dc7-4a02-8f2f-c333f733e819" id="BPMNShape_6dab05e9-7208-47f7-adc9-3b28b28e87f7">
        <dc:Bounds height="36.0" width="36.0" x="236.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="task-1" id="BPMNShape_d047de44-de7e-496e-a9ee-878a22606512">
        <dc:Bounds height="80.0" width="100.0" x="322.0" y="78.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_4d1b7ab5-ae48-475a-bc0f-d68fea2ae017" id="BPMNEdge_c5155be3-e0e6-4bd6-be92-eaf57c305f70">
        <di:waypoint x="272.0" y="118.0"/>
        <di:waypoint x="322.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="endEvent_476931c6-2a41-46d0-9052-e2ef02239bb0" id="BPMNShape_1659291c-0784-4c3d-b411-d5e862a5e8a6">
        <dc:Bounds height="36.0" width="36.0" x="472.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_b6bef8ff-6026-42bf-977e-568c2c3c438b" id="BPMNEdge_27f72ec5-4340-436c-9d9d-5fc2681d4e39">
        <di:waypoint x="422.0" y="118.0"/>
        <di:waypoint x="472.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="boundary" id="BPMNShape_bcadbfcc-08f1-4a15-9843-9f0f7f5204e8">
        <dc:Bounds height="36.0" width="36.0" x="354.0" y="200.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="endEvent_ad9274d6-7322-485a-bce5-aa4ba09d164b" id="BPMNShape_b1f42828-fd3d-44e9-b3e6-0f2a8d326d3e">
        <dc:Bounds height="36.0" width="36.0" x="402.5" y="268.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_2751f838-fb2d-4250-8d95-73d815e0f237" id="BPMNEdge_10702b6c-61d7-4def-b783-531323d24388">
        <di:waypoint x="372.0" y="236.0"/>
        <di:waypoint x="372.0" y="286.0"/>
        <di:waypoint x="402.5" y="286.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="endEvent_c81496ca-5896-4ec4-b099-902e4ec3da1e" id="BPMNShape_070aaa51-a288-4139-9a5e-cdc39cf5ca5b">
        <dc:Bounds height="36.0" width="36.0" x="608.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_916f3b68-7a21-4284-b039-a6c060777f7a" id="BPMNEdge_25de16aa-2962-4d05-9200-6e81b7b6c37a">
        <di:waypoint x="558.0" y="118.0"/>
        <di:waypoint x="608.0" y="118.0"/>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>
--------------- Decomposed keys (for debugging) -----------------
 -1 <-> -1
K01 <-> 2251799813685249
K02 <-> 2251799813685250
K03 <-> 2251799813685251
K04 <-> 2251799813685252
K05 <-> 2251799813685253
K06 <-> 2251799813685254
K07 <-> 2251799813685255
K08 <-> 2251799813685256
K09 <-> 2251799813685257
K10 <-> 2251799813685258
K11 <-> 2251799813685259
K12 <-> 2251799813685260

io.camunda.zeebe.test.util.stream.StreamWrapperException: No event found matching the criteria
	at io.camunda.zeebe.test.util.stream.StreamWrapper.await(StreamWrapper.java:87)
	at io.camunda.zeebe.engine.processing.bpmn.subprocess.EmbeddedSubProcessTest.shouldTerminateSubProcessWithNonInterruptingBoundaryEvent(EmbeddedSubProcessTest.java:171)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:30)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
</pre>
</details>

**Comment by Zelldon** [comment]
Just want to mention that the ActorClock was never designed to be used in different threads. See https://github.com/camunda/zeebe/blob/main/zeebe/scheduler/src/main/java/io/camunda/zeebe/scheduler/ActorThread.java#L84 every actor thread per default gets its own clock. 

Only in tests we have the controlled clock (with the expectations there is no real concurrency around the timer/clocks)

The controllable clock is I think also not thread safe.

**Comment by Zelldon** [comment]
https://github.com/camunda/zeebe/issues/10400

**Comment by korthout** [comment]
>with the expectations there is no real concurrency around the timer/clocks

@Zelldon Why would there be this expectation? On tests we know that the stream processor and scheduled tasks run concurrently.

**Comment by Zelldon** [comment]
The controlled clock was created way before that with a different expectation than it currently used

**Comment by Zelldon** [comment]
Anyway right now it does long computations on volatile fields but these assignments are not atomic so this will not work
