### ISSUE TITLE
Flaky test `OpensearchExporterIT.shouldAddIndexLifecycleSettingsToExistingIndicesOnRerunWhenRetentionIsEnabled`

### ISSUE THREAD

**Issue by mustafadagher** [camunda/zeebe#17279]
**Summary**

- How often does the test fail? [once](https://github.com/camunda/zeebe/actions/runs/8541686929/attempts/1#summary-23401588329)
- Does it block your work? no
- Do we suspect that it is a real failure? no, it's most probably due to the async nature of opensearch update policy functions

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
shouldAddIndexLifecycleSettingsToExistingIndicesOnRerunWhenRetentionIsEnabled (Flaky Test): io.camunda.zeebe.exporter.opensearch.OpensearchExporterIT$IndexSettingsTest
org.awaitility.core.ConditionTimeoutException: 
Assertion condition defined as a Lambda expression in io.camunda.zeebe.exporter.opensearch.OpensearchExporterIT$IndexSettingsTest [ISM policy should not be configured] 
Expecting an empty Optional but was containing value: IndexISMPolicyDto[policyId=zeebe-record-retention-policy] within 10 seconds.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1006)
	at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:790)
	at io.camunda.zeebe.exporter.opensearch.OpensearchExporterIT$IndexSettingsTest.shouldAddIndexLifecycleSettingsToExistingIndicesOnRerunWhenRetentionIsEnabled(OpensearchExporterIT.java:299)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.lang.AssertionError: [ISM policy should not be configured] 
Expecting an empty Optional but was containing value: IndexISMPolicyDto[policyId=zeebe-record-retention-policy]
	at io.camunda.zeebe.exporter.opensearch.OpensearchExporterIT$IndexSettingsTest.assertHasNoISMPolicy(OpensearchExporterIT.java:428)
	at io.camunda.zeebe.exporter.opensearch.OpensearchExporterIT$IndexSettingsTest.lambda$shouldAddIndexLifecycleSettingsToExistingIndicesOnRerunWhenRetentionIsEnabled$0(OpensearchExporterIT.java:302)
	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
</pre>
</details>

**Hypotheses**
it's most probably due to the async nature of opensearch update policy functions

**Logs**

https://productionresultssa7.blob.core.windows.net/actions-results/47e02c5d-1cf1-4033-adbb-3610e895ac89/workflow-job-run-65e11684-88a0-5014-4a3a-b5bb082dc98b/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-04-03T16%3A57%3A18Z&sig=QnN0pMP9k0QxAZyYQQZm2GnO7nLdjFvNE3nbQFVe%2BSw%3D&sp=r&spr=https&sr=b&st=2024-04-03T16%3A47%3A13Z&sv=2021-12-02
<details><summary>Logs</summary>
<pre>
LOGS
</pre>
</details>

**Comment by megglos** [comment]
happened again here https://github.com/camunda/zeebe/actions/runs/8554947555/job/23441314613

**Comment by oleschoenburg** [comment]
@mustafadagher Occurs quite frequently now, could you take another look maybe?

**Comment by mustafadagher** [comment]
> @mustafadagher Occurs quite frequently now, could you take another look maybe?

I tried several times last week (and today again) to reproduce this locally, yet I couldn't!

As I mentioned on a [previous PR comment](https://github.com/camunda/zeebe/pull/17282#issuecomment-2036521636), this issue should never happen, and I'm not sure what would be the root cause in this case
>>It's failing at [this line](https://github.com/camunda/zeebe/blob/3b99b74d2390630c9b7aa8807065fd5f3bda4502/zeebe/exporters/opensearch-exporter/src/test/java/io/camunda/zeebe/exporter/opensearch/OpensearchExporterIT.java#L299), in the beginning of the test.
At this point above we are trying to create an index with retention initially NOT enabled. This assert is just making sure that this index has no lifecycle policy. which should always be the case. we are not adding or removing a policy at this point, so waiting can't help this failure.

If you could offer any help understand the possible reasons for this, I'd really appreciate it.
CC: @korthout

**Comment by megglos** [comment]
@mustafadagher as far as I can see this API is used to write the policy https://opensearch.org/docs/latest/im-plugin/ism/api/#add-policy which does nothing if the policy already exists.
Could that be the cause? a preexisting policy from a previous test?

**Comment by oleschoenburg** [comment]
Maybe this is a test setup issue? Perhaps one way to detect it is to create a different ISM policy per test, e.g. including the test name and logging the name when asserting that no ISM policy exists?

**Comment by mustafadagher** [comment]
@megglos @oleschoenburg I've created [this PR ](https://github.com/camunda/zeebe/pull/17386) hoping it would offer a solution, could you take a look at it?
