### ISSUE TITLE
NPE in user task import

### ISSUE THREAD

**Issue by sdorokhova** [camunda/zeebe#17611]
### Describe the bug

Such exception was discovered in code:
```
io.camunda.operate.exceptions.PersistenceException: java.lang.NullPointerException: Cannot invoke "io.camunda.operate.util.Tuple.getLeft()" because "fieldAndValueSupplier" is null
	at io.camunda.operate.zeebeimport.AbstractImportBatchProcessor.performImport(AbstractImportBatchProcessor.java:54) ~[operate-importer-common-8.5.0.jar!/:8.5.0]
	at io.camunda.operate.zeebeimport.ImportJob.processOneIndexBatch(ImportJob.java:161) ~[operate-importer-8.5.0.jar!/:8.5.0]
	at io.camunda.operate.zeebeimport.ImportJob.call(ImportJob.java:80) ~[operate-importer-8.5.0.jar!/:8.5.0]
	at io.camunda.operate.zeebeimport.elasticsearch.ElasticsearchRecordsReader.lambda$executeJob$5(ElasticsearchRecordsReader.java:561) ~[operate-importer-8.5.0.jar!/:8.5.0]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "io.camunda.operate.util.Tuple.getLeft()" because "fieldAndValueSupplier" is null
	at io.camunda.operate.zeebeimport.v8_5.processors.UserTaskZeebeRecordProcessor.getUpdateFields(UserTaskZeebeRecordProcessor.java:111) ~[operate-importer-8_5-8.5.0.jar!/:8.5.0]
	at io.camunda.operate.zeebeimport.v8_5.processors.UserTaskZeebeRecordProcessor.processUserTaskRecord(UserTaskZeebeRecordProcessor.java:145) ~[operate-importer-8_5-8.5.0.jar!/:8.5.0]
	at io.camunda.operate.zeebeimport.v8_5.processors.ImportBulkProcessor.processUserTask(ImportBulkProcessor.java:315) ~[operate-importer-8_5-8.5.0.jar!/:8.5.0]
	at io.camunda.operate.zeebeimport.v8_5.processors.ImportBulkProcessor.processZeebeRecords(ImportBulkProcessor.java:153) ~[operate-importer-8_5-8.5.0.jar!/:8.5.0]
	at io.camunda.operate.zeebeimport.AbstractImportBatchProcessor.lambda$performImport$0(AbstractImportBatchProcessor.java:41) ~[operate-importer-common-8.5.0.jar!/:8.5.0]
	at io.micrometer.core.instrument.AbstractTimer.recordCallable(AbstractTimer.java:175) ~[micrometer-core-1.12.4.jar!/:1.12.4]
	at io.camunda.operate.zeebeimport.AbstractImportBatchProcessor.withTimer(AbstractImportBatchProcessor.java:78) ~[operate-importer-common-8.5.0.jar!/:8.5.0]
	at io.camunda.operate.zeebeimport.AbstractImportBatchProcessor.withProcessingTimer(AbstractImportBatchProcessor.java:60) ~[operate-importer-common-8.5.0.jar!/:8.5.0]
	at io.camunda.operate.zeebeimport.AbstractImportBatchProcessor.performImport(AbstractImportBatchProcessor.java:39) ~[operate-importer-common-8.5.0.jar!/:8.5.0]
	... 7 more
```

### To Reproduce

TBD

### Current behavior

Import is blocked with NPE

### Expected behavior

No NPE, import progresses

### Environment

Operate Version: 8.5.0

### Additional context

* related incident: https://camunda.slack.com/archives/C06UH8S9JQP
* processing of the following Zeebe record caused the exception:
```
{
                "_index": "zeebe-record_user-task_8.5.0_2024-04-18",
                "_id": "1-275287",
                "_score": null,
                "_routing": "1",
                "_source": {
                    "partitionId": 1,
                    "value": {
                        "processInstanceKey": 2251799813822626,
                        "elementInstanceKey": 2251799813822630,
                        "tenantId": "<default>",
                        "bpmnProcessId": "Process_0a32bx6",
                        "processDefinitionKey": 2251799813822624,
                        "processDefinitionVersion": 1,
                        "elementId": "Activity_0fluidy",
                        "customHeaders": {},
                        "candidateGroupsList": [
                            "string"
                        ],
                        "candidateUsersList": [
                            "string"
                        ],
                        "creationTimestamp": 1713425582479,
                        "changedAttributes": [
                            "candidateGroupsList",
                            "candidateUsersList",
                            "dueDate",
                            "followUpDate"
                        ],
                        "externalFormReference": "",
                        "dueDate": "2024-04-03T20:22:18.305Z",
                        "userTaskKey": 2251799813822631,
                        "formKey": 2251799813822623,
                        "followUpDate": "2024-04-03T20:22:18.305Z",
                        "variables": {},
                        "action": "string",
                        "assignee": ""
                    },
                    "key": 2251799813822631,
                    "timestamp": 1713425730856,
                    "valueType": "USER_TASK",
                    "brokerVersion": "8.5.0",
                    "recordType": "EVENT",
                    "intent": "UPDATED",
                    "authorizations": {
                        "authorized_tenants": [
                            "<default>"
                        ]
                    },
                    "recordVersion": 1,
                    "sourceRecordPosition": 275285,
                    "rejectionType": "NULL_VAL",
                    "rejectionReason": "",
                    "position": 275287,
                    "sequence": 2251799813685252
                },
                "sort": [
                    2251799813685252
                ]
            }
```
* IMO the reason is in how `candidateGroupsList` and `candidateUsersList` fields are named, [in Operate code](https://github.com/camunda/zeebe/blob/8bd0c74ff7b98c192721cbcbfb9b290e1d1c43b6/operate/importer-8_5/src/main/java/io/camunda/operate/zeebeimport/v8_5/processors/UserTaskZeebeRecordProcessor.java#L96-L98) we use singular form
---------------------------------------------------------------------------------------------

### Definition of Ready - Checklist

- [ ] The bug has been reproduced by the assignee in the environment compatible with the provided one; otherwise, the issue is closed with a comment
- [ ] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] The issue has been labeled with an appropriate `Bug-area` label
- [ ] Necessary screenshots, screen recordings, or files are attached to the bug report

For UI changes required to solve the bug:

- [ ] Design input has been collected by the assignee

### :point_right: Handover Dev to QA

- Changed components:
- Side effects on other components:
- Handy resources:
  BPMN/DMN models, plugins, scripts, REST API endpoints + example payload, etc :
  
- Example projects:

- Commands/Steps needed to test; Versions to validate:

- Docker file / HELM chart : in case that it needed to be tested via docker share the version contain the fixed along with version of other services .

- Release version ( in which version this fixed/feature will be released):

**Comment by sdorokhova** [comment]
The import of user tasks is blocked in the affected cluster (ILM is disabled), I propose to fix this ASAP.
