### ISSUE TITLE
[Spring Zeebe SDK] Token not refreshed

### ISSUE THREAD

**Issue by nicpuppa** [camunda/zeebe#17799]
**Describe the bug**

The Zeebe token is not refreshed after 5 minutes

```
2024-04-24T17:43:46.401+03:00  WARN 85729 --- [ault-executor-2] io.camunda.zeebe.client.job.poller     : Failed to activate jobs for worker demoService#foo and job type foo

io.grpc.StatusRuntimeException: UNAUTHENTICATED: Failed to parse bearer token, see cause for details
	at io.grpc.Status.asRuntimeException(Status.java:533) ~[grpc-api-1.62.2.jar:1.62.2]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:481) ~[grpc-stub-1.62.2.jar:1.62.2]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574) ~[grpc-core-1.62.2.jar:1.62.2]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72) ~[grpc-core-1.62.2.jar:1.62.2]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742) ~[grpc-core-1.62.2.jar:1.62.2]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723) ~[grpc-core-1.62.2.jar:1.62.2]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.62.2.jar:1.62.2]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[grpc-core-1.62.2.jar:1.62.2]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
```

**To Reproduce**

- Install camunda platform 8.5 SM
- Unzip demo-application [token_not_refreshed.zip](https://github.com/camunda/zeebe/files/15105575/token_not_refreshed.zip)
- Run application and wait 5 Minutes:
```
mvn package
java -jar target/token-not-refreshed-0.0.1-SNAPSHOT.jar
```

**Expected behavior**

Token is refreshed

**Environment:**
- OS: 
- Zeebe Version:  8.5
- Configuration:

**Comment by nicpuppa** [comment]
@megglos had a first look into this bug. It seems that the sdk is using a custom Auth Provider Impl, not the same of the Java Client. 

Seems that the [logic](https://github.com/camunda/zeebe/blob/stable/8.5/spring-boot-starter-camunda-sdk/src/main/java/io/camunda/zeebe/spring/client/configuration/ZeebeClientConfigurationSpringImpl.java#L208-L210) for refreshing the token is missing in the SDK.

**Comment by megglos** [comment]
> Seems that the [logic](https://github.com/camunda/zeebe/blob/stable/8.5/spring-boot-starter-camunda-sdk/src/main/java/io/camunda/zeebe/spring/client/configuration/ZeebeClientConfigurationSpringImpl.java#L208-L210) for refreshing the token is missing in the SDK.

To add on that, refreshing the token in case of a 401. There is some general refresh logic based on the expiry date of the token, however if for some reason that isn't effective or the token became invalid the setup may seem to miss forcing a refresh.
