### ISSUE TITLE
Flaky test `shouldStaySoftPausedAfterRestart`

### ISSUE THREAD

**Issue by mustafadagher** [camunda/zeebe#17836]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? two times so far ([last failure](https://github.com/camunda/zeebe/actions/runs/8834204251/job/24255327709?pr=17581))
- Does it block your work? no
- Do we suspect that it is a real failure? Not sure

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
shouldStaySoftPausedAfterRestart (Flaky Test): io.camunda.zeebe.it.management.ExportingEndpointIT
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at io.camunda.zeebe.it.management.ExportingEndpointIT.shouldStaySoftPausedAfterRestart(ExportingEndpointIT.java:352)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**[Logs](https://drive.google.com/file/d/1yQ9YUdehYeJ0HXqmTt0InIihEckbr9WF/view?usp=drive_link)**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
LOGS
</pre>
</details>

**Comment by mustafadagher** [comment]
again [here](https://github.com/camunda/zeebe/actions/runs/8834204251)

**Comment by megglos** [comment]
@rodrigo-lourenco-lopes related to recent changes?

**Comment by megglos** [comment]
and here https://github.com/camunda/zeebe/actions/runs/8843685913/job/24284274246

**Comment by megglos** [comment]
failed again on https://github.com/camunda/zeebe/commit/872a9d07d15476f633c06fac1add0d1ff478780f

**Comment by romansmirnov** [comment]
Failed again on https://github.com/camunda/zeebe/actions/runs/8849769813/job/24302493580?pr=17730

```
Error:  io.camunda.zeebe.it.management.ExportingEndpointIT.shouldStaySoftPausedAfterRestart -- Time elapsed: 11.85 s <<< FAILURE!
java.lang.AssertionError: Exported positions are not -1 after soft pause. Exported positions: [Partition 1 -> position -1, Partition 2 -> position 3]
	at io.camunda.zeebe.it.management.ExportingEndpointIT.shouldStaySoftPausedAfterRestart(ExportingEndpointIT.java:373)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at io.camunda.zeebe.it.management.ExportingEndpointIT.shouldStaySoftPausedAfterRestart(ExportingEndpointIT.java:357)
	... 7 more
```
