### ISSUE TITLE
UNAUTHENTICATED error after 5 minutes

### ISSUE THREAD

**Issue by ana-vinogradova-camunda** [camunda/zeebe#18138]
**Describe the bug**

When running demo application then after 5 Minutes `UNAUTHENTICATED` error is received.

**To Reproduce**

Run demo-application for 5 minutes, the above error will appear.

**Expected behavior**

No error should be present.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
io.grpc.StatusRuntimeException: UNAUTHENTICATED: Failed to parse bearer token, see cause for details
	at io.grpc.Status.asRuntimeException(Status.java:533) ~[grpc-api-1.62.2.jar:1.62.2]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:481) ~[grpc-stub-1.62.2.jar:1.62.2]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574) ~[grpc-core-1.62.2.jar:1.62.2]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72) ~[grpc-core-1.62.2.jar:1.62.2]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742) ~[grpc-core-1.62.2.jar:1.62.2]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723) ~[grpc-core-1.62.2.jar:1.62.2]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.62.2.jar:1.62.2]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[grpc-core-1.62.2.jar:1.62.2]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
```

</p>
</details>

**Comment by nicpuppa** [comment]
@ana-vinogradova-camunda this is a duplicate of https://github.com/camunda/zeebe/issues/17799

**Comment by ana-vinogradova-camunda** [comment]
Closing as a duplicate of https://github.com/camunda/zeebe/issues/17799
