### ISSUE TITLE
Unexpected error in resolving last processed position

### ISSUE THREAD

**Issue by sayan-mitra** [camunda/zeebe#18352]
**Describe the bug**

Getting this error in zeebe broker logs: **Unexpected error in resolving last processed position.**

This seems to leading to back-pressure errors at gateway for job workers/client.

**To Reproduce**

Started receiving this error from last night, restarting broker also leads to same error after starting up
No other insights how to proceed further. 

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
[Broker-0-SnapshotDirector-1] [Broker-0-zb-actors-0] ERROR
      io.camunda.zeebe.logstreams.snapshot - Unexpected error in resolving last processed position.
java.lang.RuntimeException: Actor is closed
 at io.camunda.zeebe.scheduler.ActorJob.failFuture(ActorJob.java:170) ~[zeebe-scheduler-8.2.0.jar:8.2.0]
 at io.camunda.zeebe.scheduler.ClosedQueue.offer(ClosedQueue.java:84) ~[zeebe-scheduler-8.2.0.jar:8.2.0]
 at io.camunda.zeebe.scheduler.ClosedQueue.offer(ClosedQueue.java:15) ~[zeebe-scheduler-8.2.0.jar:8.2.0]
 at io.camunda.zeebe.scheduler.ActorTask.submit(ActorTask.java:99) ~[zeebe-scheduler-8.2.0.jar:8.2.0]
 at io.camunda.zeebe.scheduler.ActorControl.call(ActorControl.java:83) ~[zeebe-scheduler-8.2.0.jar:8.2.0]
 at io.camunda.zeebe.stream.impl.StreamProcessor.getLastProcessedPositionAsync(StreamProcessor.java:446) ~[zeebe-stream-platform-8.2.0.jar:8.2.0]
 at io.camunda.zeebe.broker.system.partitions.impl.AsyncSnapshotDirector.trySnapshot(AsyncSnapshotDirector.java:235) ~[zeebe-broker-8.2.0.jar:8.2.0]
 at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) [zeebe-scheduler-8.2.0.jar:8.2.0]
 at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.2.0.jar:8.2.0]
 at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.2.0.jar:8.2.0]
 at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) [zeebe-scheduler-8.2.0.jar:8.2.0]
 at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.2.0.jar:8.2.0]
 at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) [zeebe-scheduler-8.2.0.jar:8.2.0]
```

</p>
</details>

**Environment:**
- OS:  [Running on K8s]
- Zeebe Version: [ghcr.io/camunda-community-hub/zeebe-with-hazelcast-exporter:8.5.0-1.4.1-SNAPSHOT](http://ghcr.io/camunda-community-hub/zeebe-with-hazelcast-exporter:8.5.0-1.4.1-SNAPSHOT)
- Configuration: [Zeebe, Zeebe Gateway and Hazelcast Exporter]

**Comment by oleschoenburg** [comment]
This is the result of a previous error. Could you search your logs for the first error log before the "Unexpected error in resolving last processed position" errors started?

**Comment by sayan-mitra** [comment]
```
"2024-05-06 15:20:53.006 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-2] ERROR",
"      io.camunda.zeebe.logstreams - Actor Broker-0-StreamProcessor-1 failed in phase STARTED.",
"java.lang.RuntimeException: Cannot handle event with version newer than what is implemented by broker (4 > 3)",
"
```

this was the last error before the Actor Closed error started coming up.

Tried making some sense of it but not quite sure which version got updated. Can you please provide some insights @oleschoenburg.

Thanks

**Comment by oleschoenburg** [comment]
Your stacktrace indicates Zeebe version 8.2.0 but in your issue description you mention 8.5.0. Did you upgrade between versions recently? Which versions are actually running, and are all brokers on the same version?

**Comment by sayan-mitra** [comment]
Thanks for the input.
Validated that this happened recently, where the zeebe-gateway got updated to 8.5 while the zeebe broker was still in 8.2

Is this the reason for the above error? 
Please suggest a way, will updating the zeebe broker to 8.5 will fix this or we will have to remove the partition data(events) completely ?

**Comment by oleschoenburg** [comment]
Yes, this is most likely the reason for the error. Note that we don't allow skipping minor versions when upgrading. It might work if you upgrade brokers to 8.5 now but unfortunately I can't promise that you won't encounter other issues.

**Comment by sayan-mitra** [comment]
It seems to be working after updating the zeebe-broker version, thanks for all the help 🚀 

@oleschoenburg can you please point me to the documentation around stream processor and it's working to make myself better aware of the system.

**Comment by oleschoenburg** [comment]
@sayan-mitra I'm glad you got it working again!
There's some documentation here: https://docs.camunda.io/docs/next/components/zeebe/technical-concepts/technical-concepts-overview/
The rest is mostly in code.
