### ISSUE TITLE
Operate import does not work for Opensearch with `UnsupportedOperationException`

### ISSUE THREAD

**Issue by sdorokhova** [camunda/zeebe#18452]
### Describe the bug

Since 67bbaf1afa679e2bf1af192780c1d1519563a62b Operate import does not work for Opensearch with `UnsupportedOperationException`

### To Reproduce

1. Start Operate with Opensearch
2. Deploy and start process

### Current behavior

Process is not visible in UI and following exception is logged:
```
2024-05-13T12:14:40.208+02:00 ERROR 19220 --- [       import_2] i.c.o.z.ImportJob                        : java.lang.UnsupportedOperationException: Not yet implemented

io.camunda.operate.exceptions.PersistenceException: java.lang.UnsupportedOperationException: Not yet implemented
	at io.camunda.operate.zeebeimport.AbstractImportBatchProcessor.performImport(AbstractImportBatchProcessor.java:54) ~[classes/:?]
	at io.camunda.operate.zeebeimport.ImportJob.processOneIndexBatch(ImportJob.java:161) ~[classes/:?]
	at io.camunda.operate.zeebeimport.ImportJob.call(ImportJob.java:80) ~[classes/:?]
	at io.camunda.operate.zeebeimport.opensearch.OpensearchRecordsReader.lambda$executeJob$6(OpensearchRecordsReader.java:526) ~[classes/:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.UnsupportedOperationException: Not yet implemented
	at io.camunda.operate.store.opensearch.OpensearchImportStore.getConcurrencyMode(OpensearchImportStore.java:120) ~[classes/:?]
	at io.camunda.operate.zeebeimport.processors.ListViewZeebeRecordProcessor.processProcessInstanceRecord(ListViewZeebeRecordProcessor.java:253) ~[classes/:?]
	at io.camunda.operate.zeebeimport.processors.ImportBulkProcessor.processProcessInstanceRecords(ImportBulkProcessor.java:295) ~[classes/:?]
	at io.camunda.operate.zeebeimport.processors.ImportBulkProcessor.processZeebeRecords(ImportBulkProcessor.java:132) ~[classes/:?]
	at io.camunda.operate.zeebeimport.AbstractImportBatchProcessor.lambda$performImport$0(AbstractImportBatchProcessor.java:41) ~[classes/:?]
	at io.micrometer.core.instrument.AbstractTimer.recordCallable(AbstractTimer.java:175) ~[micrometer-core-1.12.5.jar:1.12.5]
	at io.camunda.operate.zeebeimport.AbstractImportBatchProcessor.withTimer(AbstractImportBatchProcessor.java:78) ~[classes/:?]
	at io.camunda.operate.zeebeimport.AbstractImportBatchProcessor.withProcessingTimer(AbstractImportBatchProcessor.java:60) ~[classes/:?]
	at io.camunda.operate.zeebeimport.AbstractImportBatchProcessor.performImport(AbstractImportBatchProcessor.java:39) ~[classes/:?]
	... 7 more
```

### Expected behavior

Operate shows process in UI.

### Environment

- OS: [e.g. MacOS]
- Browser: [e.g. chrome, safari]
- Operate Version: 8.5.1, 8.6.0-alpha1

### Additional context

---------------------------------------------------------------------------------------------

### Definition of Ready - Checklist

- [ ] The bug has been reproduced by the assignee in the environment compatible with the provided one; otherwise, the issue is closed with a comment
- [ ] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] The issue has been labeled with an appropriate `Bug-area` label
- [ ] Necessary screenshots, screen recordings, or files are attached to the bug report

For UI changes required to solve the bug:

- [ ] Design input has been collected by the assignee

### :point_right: Handover Dev to QA

- Changed components:
- Side effects on other components:
- Handy resources:
  BPMN/DMN models, plugins, scripts, REST API endpoints + example payload, etc :
  
- Example projects:

- Commands/Steps needed to test; Versions to validate:

- Docker file / HELM chart : in case that it needed to be tested via docker share the version contain the fixed along with version of other services .

- Release version ( in which version this fixed/feature will be released):

**Comment by gogroup-official** [comment]
i have same a problem
