### ISSUE TITLE
ModelParseException: SAXException while parsing input stream

### ISSUE THREAD

**Issue by pihme** [camunda/zeebe#5490]
**Describe the bug**
Observed as error in production logs.

**Expected behavior**
- SAXParisng exceptions are not logged as error

**Log/Stacktrace**
https://console.cloud.google.com/errors/CK7AzeKf3rSTYA?service=zeebe&time=P7D&project=camunda-cloud-240911
https://console.cloud.google.com/errors/COn7jpDXj4qlPQ?service=zeebe&time=P7D&project=camunda-cloud-240911

**Environment:**
Camunda Cloud / Prod / 0.24.2, 0.24.3

**Comment by npepinpe** [comment]
It seems we already handle this properly from a user POV, so we should simply not log this particular error.

**Comment by npepinpe** [comment]
Happened again with 0.26.1:

```
org.camunda.bpm.model.xml.ModelParseException: SAXException while parsing input stream
	at org.camunda.bpm.model.xml.impl.util.DomUtil.parseInputStream(DomUtil.java:245) ~[camunda-xml-model-7.14.0.jar:7.14.0]
	at org.camunda.bpm.model.xml.impl.parser.AbstractModelParser.parseModelFromStream(AbstractModelParser.java:131) ~[camunda-xml-model-7.14.0.jar:7.14.0]
	at io.zeebe.model.bpmn.impl.BpmnParser.parseModelFromStream(BpmnParser.java:62) ~[zeebe-bpmn-model-0.26.1.jar:0.26.1]
	at io.zeebe.model.bpmn.Bpmn.doReadModelFromInputStream(Bpmn.java:390) ~[zeebe-bpmn-model-0.26.1.jar:0.26.1]
	at io.zeebe.model.bpmn.Bpmn.readModelFromStream(Bpmn.java:284) ~[zeebe-bpmn-model-0.26.1.jar:0.26.1]
	at io.zeebe.engine.processing.deployment.transform.DeploymentTransformer.readWorkflowDefinition(DeploymentTransformer.java:213) ~[zeebe-workflow-engine-0.26.1.jar:0.26.1]
	at io.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transformResource(DeploymentTransformer.java:108) ~[zeebe-workflow-engine-0.26.1.jar:0.26.1]
	at io.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transform(DeploymentTransformer.java:86) ~[zeebe-workflow-engine-0.26.1.jar:0.26.1]
	at io.zeebe.engine.processing.deployment.TransformingDeploymentCreateProcessor.processRecord(TransformingDeploymentCreateProcessor.java:69) ~[zeebe-workflow-engine-0.26.1.jar:0.26.1]
	at io.zeebe.engine.processing.streamprocessor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:51) ~[zeebe-workflow-engine-0.26.1.jar:0.26.1]
	at io.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.lambda$processInTransaction$2(ProcessingStateMachine.java:269) ~[zeebe-workflow-engine-0.26.1.jar:0.26.1]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:79) ~[zeebe-db-0.26.1.jar:0.26.1]
	at io.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processInTransaction(ProcessingStateMachine.java:260) ~[zeebe-workflow-engine-0.26.1.jar:0.26.1]
	at io.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processEvent(ProcessingStateMachine.java:229) ~[zeebe-workflow-engine-0.26.1.jar:0.26.1]
	at io.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.tryToReadNextEvent(ProcessingStateMachine.java:205) ~[zeebe-workflow-engine-0.26.1.jar:0.26.1]
	at io.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.readNextEvent(ProcessingStateMachine.java:196) ~[zeebe-workflow-engine-0.26.1.jar:0.26.1]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.26.1.jar:0.26.1]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.26.1.jar:0.26.1]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-0.26.1.jar:0.26.1]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-0.26.1.jar:0.26.1]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-0.26.1.jar:0.26.1]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-0.26.1.jar:0.26.1]
Caused by: org.xml.sax.SAXException: Fatal Error: URI=null Line=18: The prefix "zeebe" for element "zeebe:taskDefinition" is not bound.
	at org.camunda.bpm.model.xml.impl.util.DomUtil$DomErrorHandler.fatalError(DomUtil.java:207) ~[camunda-xml-model-7.14.0.jar:7.14.0]
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(Unknown Source) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) ~[?:?]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source) ~[?:?]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source) ~[?:?]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source) ~[?:?]
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source) ~[?:?]
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source) ~[?:?]
	at javax.xml.parsers.DocumentBuilder.parse(Unknown Source) ~[?:?]
	at org.camunda.bpm.model.xml.impl.util.DomUtil.parseInputStream(DomUtil.java:240) ~[camunda-xml-model-7.14.0.jar:7.14.0]
	... 21 more
```

**Comment by saig0** [comment]
Let's verify if the exception is logged and which rejection message is returned.
