### ISSUE TITLE
IllegalStateException: Log reader inconsistent with log writer

### ISSUE THREAD

**Issue by pihme** [camunda/zeebe#5493]
**Describe the bug**
Error observed in production logs.

**Log/Stacktrace**
https://console.cloud.google.com/errors/CNvDkoOl5JG8_QE?service=zeebe&time=P7D&project=camunda-cloud-240911

**Environment:**
Camunda Cloud / Prod / 0.24.3

**Comment by deepthidevaki** [comment]
Logs before this exception:
```
W 2020-10-02T15:29:30.562814Z RaftServer{raft-partition-partition-2} - InstallRequest{currentTerm=5287, leader=1, index=409299, term=5287, timestamp=1601652026469, version=1, chunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1808734558}, nextChunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1886340113}, data=HeapByteBuffer{position=0, remaining=929, limit=929, capacity=929, mark=java.nio.HeapByteBuffer[pos=0 lim=929 cap=929], hash=-986223176}, initial=true, complete=false} to 0 failed: java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException: Request type raft-partition-partition-2-install timed out in 5000 milliseconds 
W 2020-10-02T15:29:36.293952Z RaftServer{raft-partition-partition-2} - InstallRequest{currentTerm=5287, leader=1, index=409299, term=5287, timestamp=1601652026469, version=1, chunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1808734558}, nextChunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1886340113}, data=HeapByteBuffer{position=0, remaining=929, limit=929, capacity=929, mark=java.nio.HeapByteBuffer[pos=0 lim=929 cap=929], hash=-986223176}, initial=true, complete=false} to 0 failed: java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException: Request type raft-partition-partition-2-install timed out in 5000 milliseconds 
W 2020-10-02T15:29:38.204861Z RaftServer{raft-partition-partition-2} - AppendRequest{term=5287, leader=1, prevLogIndex=409311, prevLogTerm=5287, entries=0, commitIndex=409311} to 2 failed: java.util.concurrent.CompletionException: java.net.ConnectException 
W 2020-10-02T15:29:38.435210Z RaftServer{raft-partition-partition-2}{role=FOLLOWER} - Poll request to 2 failed: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: zeebe-2.zeebe-broker-service.6122e231-7df7-4e0e-9f83-bbbd4eebbefc-zeebe.svc.cluster.local/10.28.3.51:26502 
W 2020-10-02T15:29:38.453370Z RaftServer{raft-partition-partition-2} - AppendRequest{term=5287, leader=1, prevLogIndex=409311, prevLogTerm=5287, entries=0, commitIndex=409311} to 2 failed: java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: zeebe-2.zeebe-broker-service.6122e231-7df7-4e0e-9f83-bbbd4eebbefc-zeebe.svc.cluster.local/10.28.3.51:26502 
W 2020-10-02T15:29:38.698744Z RaftServer{raft-partition-partition-2} - AppendRequest{term=5287, leader=1, prevLogIndex=409311, prevLogTerm=5287, entries=0, commitIndex=409311} to 2 failed: java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: zeebe-2.zeebe-broker-service.6122e231-7df7-4e0e-9f83-bbbd4eebbefc-zeebe.svc.cluster.local/10.28.3.51:26502 
W 2020-10-02T15:29:41.976953Z RaftServer{raft-partition-partition-2} - InstallRequest{currentTerm=5287, leader=1, index=409299, term=5287, timestamp=1601652026469, version=1, chunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1808734558}, nextChunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1886340113}, data=HeapByteBuffer{position=0, remaining=929, limit=929, capacity=929, mark=java.nio.HeapByteBuffer[pos=0 lim=929 cap=929], hash=-986223176}, initial=true, complete=false} to 0 failed: java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException: Request type raft-partition-partition-2-install timed out in 5000 milliseconds 
W 2020-10-02T15:29:42.433863Z RaftServer{raft-partition-partition-2}{role=FOLLOWER} - Poll request to 2 failed: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: zeebe-2.zeebe-broker-service.6122e231-7df7-4e0e-9f83-bbbd4eebbefc-zeebe.svc.cluster.local/10.28.3.51:26502 
W 2020-10-02T15:29:46.444719Z RaftServer{raft-partition-partition-2} - Suspected network partition after 6 failures from 2 over a period of time 8740 > 5000, stepping down 
W 2020-10-02T15:29:47.117162Z RaftServer{raft-partition-partition-2}{role=FOLLOWER} - Poll request to 2 failed: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: zeebe-2.zeebe-broker-service.6122e231-7df7-4e0e-9f83-bbbd4eebbefc-zeebe.svc.cluster.local/10.28.3.51:26502 
W 2020-10-02T15:29:50.533154Z RaftServer{raft-partition-partition-2} - ConfigureRequest{term=5288, leader=1, index=0, timestamp=1588940989858, members=[DefaultRaftMember{id=2, type=ACTIVE, updated=2020-05-08T12:29:49.858608Z}, DefaultRaftMember{id=1, type=BOOTSTRAP, updated=2020-05-08T12:29:49.858608Z}, DefaultRaftMember{id=0, type=ACTIVE, updated=2020-05-08T12:29:49.858608Z}]} to 2 failed: java.util.concurrent.CompletionException: io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message 
W 2020-10-02T15:29:51.127676Z RaftServer{raft-partition-partition-2} - AppendRequest{term=5288, leader=1, prevLogIndex=409311, prevLogTerm=5287, entries=0, commitIndex=409311} to 2 failed: java.util.concurrent.CompletionException: io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message 
W 2020-10-02T15:29:51.130697Z RaftServer{raft-partition-partition-2} - ConfigureRequest{term=5288, leader=1, index=0, timestamp=1588940989858, members=[DefaultRaftMember{id=2, type=ACTIVE, updated=2020-05-08T12:29:49.858608Z}, DefaultRaftMember{id=1, type=BOOTSTRAP, updated=2020-05-08T12:29:49.858608Z}, DefaultRaftMember{id=0, type=ACTIVE, updated=2020-05-08T12:29:49.858608Z}]} to 2 failed: java.util.concurrent.CompletionException: io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message 
W 2020-10-02T15:29:56.127791Z RaftServer{raft-partition-partition-2} - InstallRequest{currentTerm=5288, leader=1, index=409299, term=5287, timestamp=1601652026469, version=1, chunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1808734558}, nextChunkId=HeapByteBuffer{position=0, remaining=10, limit=10, capacity=10, mark=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10], hash=1886340113}, data=HeapByteBuffer{position=0, remaining=929, limit=929, capacity=929, mark=java.nio.HeapByteBuffer[pos=0 lim=929 cap=929], hash=-986223176}, initial=true, complete=false} to 0 failed: java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException: Request type raft-partition-partition-2-install timed out in 5000 milliseconds 
W 2020-10-02T15:45:25.688121Z RaftServer{raft-partition-partition-2}{role=FOLLOWER} - Poll request to 2 failed: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: zeebe-2.zeebe-broker-service.6122e231-7df7-4e0e-9f83-bbbd4eebbefc-zeebe.svc.cluster.local/10.28.3.51:26502 
W 2020-10-02T15:45:25.702114Z RaftServer{raft-partition-partition-2}{role=CANDIDATE} - io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: zeebe-2.zeebe-broker-service.6122e231-7df7-4e0e-9f83-bbbd4eebbefc-zeebe.svc.cluster.local/10.28.3.51:26502 
W 2020-10-02T15:45:29.756051Z RaftServer{raft-partition-partition-2} - ConfigureRequest{term=5290, leader=0, index=0, timestamp=1588940989926, members=[DefaultRaftMember{id=0, type=ACTIVE, updated=2020-05-08T12:29:49.926644Z}, DefaultRaftMember{id=2, type=ACTIVE, updated=2020-05-08T12:29:49.926644Z}, DefaultRaftMember{id=1, type=ACTIVE, updated=2020-05-08T12:29:49.926644Z}]} to 2 failed: java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: zeebe-2.zeebe-broker-service.6122e231-7df7-4e0e-9f83-bbbd4eebbefc-zeebe.svc.cluster.local/10.28.3.51:26502 
W 2020-10-02T15:45:29.796093Z RaftServer{raft-partition-partition-2} - ConfigureRequest{term=5290, leader=0, index=0, timestamp=1588940989926, members=[DefaultRaftMember{id=0, type=ACTIVE, updated=2020-05-08T12:29:49.926644Z}, DefaultRaftMember{id=2, type=ACTIVE, updated=2020-05-08T12:29:49.926644Z}, DefaultRaftMember{id=1, type=ACTIVE, updated=2020-05-08T12:29:49.926644Z}]} to 2 failed: java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: zeebe-2.zeebe-broker-service.6122e231-7df7-4e0e-9f83-bbbd4eebbefc-zeebe.svc.cluster.local/10.28.3.51:26502 
W 2020-10-02T15:45:29.803742Z RaftServer{raft-partition-partition-2} - AppendRequest{term=5290, leader=0, prevLogIndex=409312, prevLogTerm=5289, entries=0, commitIndex=409313} to 2 failed: java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: zeebe-2.zeebe-broker-service.6122e231-7df7-4e0e-9f83-bbbd4eebbefc-zeebe.svc.cluster.local/10.28.3.51:26502 
E 2020-10-02T15:46:03.339277Z RaftServer{raft-partition-partition-2}{role=LEADER} - Error on appending entry ZeebeEntry{term=5290, timestamp=1601653563338, lowestPosition=2035814842154, highestPosition=2035814842154}, retry. 
E 2020-10-02T15:46:03.340260Z RaftServer{raft-partition-partition-2}{role=LEADER} - Error on appending entry ZeebeEntry{term=5290, timestamp=1601653563338, lowestPosition=2035814842154, highestPosition=2035814842154}, retry. 
E 2020-10-02T15:46:03.341036Z RaftServer{raft-partition-partition-2}{role=LEADER} - Error on appending entry ZeebeEntry{term=5290, timestamp=1601653563338, lowestPosition=2035814842154, highestPosition=2035814842154}, retry. 
E 2020-10-02T15:46:03.341625Z RaftServer{raft-partition-partition-2}{role=LEADER} - Error on appending entry ZeebeEntry{term=5290, timestamp=1601653563338, lowestPosition=2035814842154, highestPosition=2035814842154}, retry. 
E 2020-10-02T15:46:03.342277Z RaftServer{raft-partition-partition-2}{role=LEADER} - Error on appending entry ZeebeEntry{term=5290, timestamp=1601653563338, lowestPosition=2035814842154, highestPosition=2035814842154}, retry. 
E 2020-10-02T15:46:03.347175Z RaftServer{raft-partition-partition-2}{role=LEADER} - Error on appending entry ZeebeEntry{term=5290, timestamp=1601653563338, lowestPosition=2035814842154, highestPosition=2035814842154}, retry. 
exception: "io.atomix.storage.StorageException: java.io.IOException: No space left on device
	at io.atomix.storage.journal.FileChannelJournalSegmentWriter.append(FileChannelJournalSegmentWriter.java:147) ~[atomix-storage-0.24.3.jar:0.24.3]
	at io.atomix.storage.journal.MappableJournalSegmentWriter.append(MappableJournalSegmentWriter.java:131) ~[atomix-storage-0.24.3.jar:0.24.3]
	at io.atomix.storage.journal.SegmentedJournalWriter.append(SegmentedJournalWriter.java:55) ~[atomix-storage-0.24.3.jar:0.24.3]
	at io.atomix.storage.journal.DelegatingJournalWriter.append(DelegatingJournalWriter.java:46) ~[atomix-storage-0.24.3.jar:0.24.3]
	at io.atomix.raft.roles.LeaderRole.tryToAppend(LeaderRole.java:636) ~[atomix-cluster-0.24.3.jar:0.24.3]
	at io.atomix.raft.roles.LeaderRole.append(LeaderRole.java:608) ~[atomix-cluster-0.24.3.jar:0.24.3]
	at io.atomix.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:693) ~[atomix-cluster-0.24.3.jar:0.24.3]
	at io.atomix.raft.roles.LeaderRole.lambda$appendEntry$10(LeaderRole.java:667) ~[atomix-cluster-0.24.3.jar:0.24.3]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) [atomix-utils-0.24.3.jar:0.24.3]
E 2020-10-02T15:46:12.248816Z RaftServer{raft-partition-partition-2} - An uncaught exception occurred, transition to inactive role 
java.lang.IllegalStateException: Log reader inconsistent with log writer

        at io.atomix.raft.roles.PassiveRole.replaceExistingEntry (PassiveRole.java:681)
        at io.atomix.raft.roles.PassiveRole.tryToAppend (PassiveRole.java:630)
        at io.atomix.raft.roles.PassiveRole.appendEntries (PassiveRole.java:591)
        at io.atomix.raft.roles.PassiveRole.handleAppend (PassiveRole.java:443)
        at io.atomix.raft.roles.ActiveRole.onAppend (ActiveRole.java:51)
        at io.atomix.raft.roles.FollowerRole.onAppend (FollowerRole.java:197)
        at io.atomix.raft.impl.RaftContext.lambda$registerHandlers$12 (RaftContext.java:213)
        at io.atomix.raft.impl.RaftContext.lambda$runOnContext$19 (RaftContext.java:224)
        at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run (SingleThreadContext.java:188)
        at java.util.concurrent.Executors$RunnableAdapter.call (Unknown Source)
        at java.util.concurrent.FutureTask.run (Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker (Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run (Unknown Source)
        at java.lang.Thread.run (Unknown Source)
```

Another occurence:

```
E 2020-10-02T14:26:53.327780Z RaftServer{raft-partition-partition-4}{role=LEADER} - Error on appending entry ZeebeEntry{term=4786, timestamp=1601648813322, lowestPosition=1846836416740, highestPosition=1846836416740}, retry. 
E 2020-10-02T14:26:53.337282Z RaftServer{raft-partition-partition-4}{role=LEADER} - Error on appending entry ZeebeEntry{term=4786, timestamp=1601648813322, lowestPosition=1846836416740, highestPosition=1846836416740}, retry. 
E 2020-10-02T14:26:53.341373Z RaftServer{raft-partition-partition-4}{role=LEADER} - Error on appending entry ZeebeEntry{term=4786, timestamp=1601648813322, lowestPosition=1846836416740, highestPosition=1846836416740}, retry. 
E 2020-10-02T14:26:53.350158Z RaftServer{raft-partition-partition-4}{role=LEADER} - Error on appending entry ZeebeEntry{term=4786, timestamp=1601648813322, lowestPosition=1846836416740, highestPosition=1846836416740}, retry. 
E 2020-10-02T14:26:53.351677Z Failed to append block with last event position 1846836416740. 
I 2020-10-02T14:26:53.371976Z Close appender for log stream logstream-raft-partition-partition-4 
E 2020-10-02T14:26:53.372593Z logstream-raft-partition-partition-4 failed, marking it as unhealthy 
D 2020-10-02T14:26:53.373605Z Dispatcher closed 
I 2020-10-02T14:26:53.374455Z On closing logstream logstream-raft-partition-partition-4 close 3 readers 
I 2020-10-02T14:26:53.375147Z Close log storage with name logstream-raft-partition-partition-4 
D 2020-10-02T14:26:53.379122Z Detected unhealthy components. The current health status of components: {Raft-4=HEALTHY, Broker-0-StreamProcessor-4=HEALTHY, ZeebePartition-4=HEALTHY, logstream-raft-partition-partition-4=UNHEALTHY} 
W 2020-10-02T14:26:56.549626Z RaftServer{raft-partition-partition-4} - ConfigureRequest{term=4787, leader=0, index=0, timestamp=1588940990190, members=[DefaultRaftMember{id=2, type=ACTIVE, updated=2020-05-08T12:29:50.190155Z}, DefaultRaftMember{id=1, type=ACTIVE, updated=2020-05-08T12:29:50.190155Z}, DefaultRaftMember{id=0, type=BOOTSTRAP, updated=2020-05-08T12:29:50.190155Z}]} to 2 failed: java.util.concurrent.CompletionException: io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message 
E 2020-10-02T14:27:00.178925Z RaftServer{raft-partition-partition-4} - An uncaught exception occurred, transition to inactive role 

```

In both cases it seems to have occurred after the node went out of disk space. It is not expected. It seems there is no corrupted data. But need more investigation.

**Comment by npepinpe** [comment]
Would be interesting to improve the error message to write the expected position and the actual position, as we do with most error messages.

**Comment by npepinpe** [comment]
Let's scope it as only adding more context to the error. What is the reader position, what's the writer position, what are the expected bounds, etc. As it is, the message doesn't give us much to diagnose.

**Comment by Zelldon** [comment]
I think this never occurred again and we have replaced the dispatcher so I will close this for now
