### ISSUE TITLE
ElasticsearchExporter.createRootIndexTemplate throws NPE

### ISSUE THREAD

**Issue by saig0** [camunda/zeebe#5620]
**Describe the bug**
A NPE is thrown in `ElasticsearchExporter.createRootIndexTemplate (ElasticsearchExporter.java:180)` when trying to export a record.

**To Reproduce**
This issue occurred in Camunda Cloud: https://console.cloud.google.com/errors/CMrgk72Hq8yaXg?service=zeebe&time=P7D&project=camunda-cloud-240911

It seems to be related to a `No space left on device` exception that happens at the same time: https://console.cloud.google.com/logs/query;query=%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultratest%22%0Aresource.labels.namespace_name%3D%224e6de936-a992-4f41-b171-2025b4f182e6-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0A;timeRange=2020-10-16T21:26:54.043Z%2F2020-10-16T22:26:54.043Z;pinnedLogId=2020-10-16T21:56:03.929259Z%2Fvg0mqv7m67z9qbhcn?project=camunda-cloud-240911

**Expected behavior**
No NPE is thrown in the exporter. The failure message indicates the actual error.  

**Log/Stacktrace**
From the Camunda cloud: https://console.cloud.google.com/errors/CMrgk72Hq8yaXg?service=zeebe&time=P7D&project=camunda-cloud-240911

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.NullPointerException: null
at io.zeebe.exporter.ElasticsearchExporter.createRootIndexTemplate (ElasticsearchExporter.java:180)
at io.zeebe.exporter.ElasticsearchExporter.createIndexTemplates (ElasticsearchExporter.java:133)
at io.zeebe.exporter.ElasticsearchExporter.export (ElasticsearchExporter.java:80)
at io.zeebe.broker.exporter.stream.ExporterDirector$ExporterContainer.export (ExporterDirector.java:440)
at io.zeebe.broker.exporter.stream.ExporterDirector$RecordExporter.export (ExporterDirector.java:367)
at io.zeebe.util.retry.BackOffRetryStrategy.run (BackOffRetryStrategy.java:51)
at io.zeebe.util.sched.ActorJob.invoke (ActorJob.java:76)
at io.zeebe.util.sched.ActorJob.execute (ActorJob.java:39)
at io.zeebe.util.sched.ActorTask.execute (ActorTask.java:118)
at io.zeebe.util.sched.ActorThread.executeCurrentTask (ActorThread.java:107)
at io.zeebe.util.sched.ActorThread.doWork (ActorThread.java:91)
at io.zeebe.util.sched.ActorThread.run (ActorThread.java:204)
```

</p>
</details>

**Environment:**
 - OS: Camunda Cloud
 - Zeebe Version: `0.24.4`
 - Configuration: ES exporter

**Comment by npepinpe** [comment]
I think I figured out what happened - the exporter director fails initially due to no disk space left on device. It seems starting a transaction causes RocksDB to write something to disk, which is a little strange but out of scope for this issue. 

You can see this from this log statement:

```
"Uncaught exception in 'Broker-1-Exporter-1' in phase 'STARTED'. Continuing with next job."
 "io.zeebe.db.ZeebeDbException: Unexpected error occurred during RocksDB transaction.
	at io.zeebe.db.impl.rocksdb.transaction.DefaultDbContext.runInTransaction(DefaultDbContext.java:142) ~[zeebe-db-0.24.4.jar:0.24.4]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.ensureInOpenTransaction(ZeebeTransactionDb.java:173) ~[zeebe-db-0.24.4.jar:0.24.4]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.getValue(ZeebeTransactionDb.java:186) ~[zeebe-db-0.24.4.jar:0.24.4]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.get(ZeebeTransactionDb.java:181) ~[zeebe-db-0.24.4.jar:0.24.4]
	at io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.get(TransactionalColumnFamily.java:63) ~[zeebe-db-0.24.4.jar:0.24.4]
	at io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.get(TransactionalColumnFamily.java:134) ~[zeebe-db-0.24.4.jar:0.24.4]
	at io.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.get(TransactionalColumnFamily.java:58) ~[zeebe-db-0.24.4.jar:0.24.4]
	at io.zeebe.broker.exporter.stream.ExportersState.getPosition(ExportersState.java:65) ~[zeebe-broker-0.24.4.jar:0.24.4]
	at io.zeebe.broker.exporter.stream.ExportersState.getPosition(ExportersState.java:56) ~[zeebe-broker-0.24.4.jar:0.24.4]
	at io.zeebe.broker.exporter.stream.ExporterDirector.onSnapshotRecovered(ExporterDirector.java:223) ~[zeebe-broker-0.24.4.jar:0.24.4]
	at io.zeebe.broker.exporter.stream.ExporterDirector.onActorStarted(ExporterDirector.java:143) ~[zeebe-broker-0.24.4.jar:0.24.4]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) ~[zeebe-util-0.24.4.jar:0.24.4]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.24.4.jar:0.24.4]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:118) [zeebe-util-0.24.4.jar:0.24.4]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.24.4.jar:0.24.4]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.24.4.jar:0.24.4]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:204) [zeebe-util-0.24.4.jar:0.24.4]
Caused by: org.rocksdb.RocksDBException: While appending to file: /usr/local/zeebe/data/raft-partition/partitions/1/runtime/000552.log: No space left on device
	at org.rocksdb.Transaction.commit(Native Method) ~[rocksdbjni-6.8.1.jar:?]
	at org.rocksdb.Transaction.commit(Transaction.java:206) ~[rocksdbjni-6.8.1.jar:?]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.commitInternal(ZeebeTransaction.java:117) ~[zeebe-db-0.24.4.jar:0.24.4]
	at io.zeebe.db.impl.rocksdb.transaction.DefaultDbContext.runInNewTransaction(DefaultDbContext.java:164) ~[zeebe-db-0.24.4.jar:0.24.4]
	at io.zeebe.db.impl.rocksdb.transaction.DefaultDbContext.runInTransaction(DefaultDbContext.java:135) ~[zeebe-db-0.24.4.jar:0.24.4]
	... 16 more
"
```

As you can see from our code (on 0.24.4 anyway), we initialize the exporter position and then open it. However, we failed to initialize it, which means the exporter was not opened...and yet we still tried to export it.

So a few things which went wrong here, but primarily, we broke the exporter API contract - `open` must __always__ be called before `export`, which in this case did not happen. I don't have the perfect solution in mind, but we should definitely not export to exporters which failed to be opened and/or exported (for whichever reason).

**Comment by npepinpe** [comment]
I'm upping the severity as this causes us to be unable to export any data, and out of disk space may not always be the reason why we fail to open an exporter.

**Comment by npepinpe** [comment]
The problem here is primarily that when we fail to open an exporter, we just keep going and will try to use it. If the exporter fails to open, we should not try to use - we can still use the other ones though. I'm open to suggestion on better handling this - stepping down? Should we allow a node to be leader if it can't export to all exporters? :thinking:

**Comment by saig0** [comment]
Marking priority as `later later` because it seems that it doesn't happen often and it could be resolved by restarting/increasing the disk space.

Please comment if you think this should have a higher priority.

**Comment by saig0** [comment]
@npepinpe thank you for the insides :+1: 

As proposed, I'm closing the issue.
