### ISSUE TITLE
Wrong response is send back for deployment when partitions are not available

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#5702]
**Describe the bug**
When sending an deployment command to the Gateway and no partition is available then the returned response is `NOT_FOUND` instead of `PARTITON_NOT_AVAILABLE`.

See chaos day summary https://github.com/zeebe-io/zeebe-chaos/tree/master/chaos-days/2020-10-27

**To Reproduce**
 
 * Start a gateway without brokers.
 * Send a deployment to the gateway.

**Expected behavior**

`PARTITION_NOT_AVAILABLE` or something similar as response, but not `NOT_FOUND`.

**Log/Stacktrace**
If possible add the full stacktrace or Zeebe log which contains the issue. 

<details><summary>Full Stacktrace</summary>
 <p>

```
11:01:18.035 [main] WARN  io.zeebe.Starter - Failed to deploy workflow, retrying
io.zeebe.client.api.command.ClientStatusException: Expected to execute command, but this command refers to an element that doesn't exist.
	at io.zeebe.client.impl.ZeebeClientFutureImpl.transformExecutionException(ZeebeClientFutureImpl.java:93) ~[app.jar:0.24.2]
	at io.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:50) ~[app.jar:0.24.2]
	at io.zeebe.Starter.deployWorkflow(Starter.java:128) [app.jar:0.24.2]
	at io.zeebe.Starter.run(Starter.java:55) [app.jar:0.24.2]
	at io.zeebe.App.createApp(App.java:50) [app.jar:0.24.2]
	at io.zeebe.Starter.main(Starter.java:142) [app.jar:0.24.2]
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: NOT_FOUND: Expected to execute command, but this command refers to an element that doesn't exist.
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:?]
	at io.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:48) ~[app.jar:0.24.2]
	... 4 more
Caused by: io.grpc.StatusRuntimeException: NOT_FOUND: Expected to execute command, but this command refers to an element that doesn't exist.
	at io.grpc.Status.asRuntimeException(Status.java:533) ~[app.jar:0.24.2]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:460) ~[app.jar:0.24.2]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[app.jar:0.24.2]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[app.jar:0.24.2]
	at me.dinowernli.grpc.prometheus.MonitoringClientCallListener.onClose(MonitoringClientCallListener.java:50) ~[app.jar:0.24.2]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426) ~[app.jar:0.24.2]
	at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66) ~[app.jar:0.24.2]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689) ~[app.jar:0.24.2]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577) ~[app.jar:0.24.2]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751) ~[app.jar:0.24.2]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740) ~[app.jar:0.24.2]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[app.jar:0.24.2]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[app.jar :0.24.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

</p>
</details>

**Environment:**
 - OS: k8
 - Zeebe Version: SNAPSHOT (0.25+)
 - Configuration: -

**Comment by EEM86** [comment]
@Zelldon hello, seems I should fix this. Assign me, please.

**Comment by npepinpe** [comment]
Hi @EEM86, go for it! Don't hesitate to ask here or in the Slack channel if you have any questions!

**Comment by npepinpe** [comment]
I would propose fixing this once #5791 is merged, as it will be easier to test by simply adding a test case to the existing IT.

**Comment by EEM86** [comment]
> 
> 
> Hi @EEM86, go for it! Don't hesitate to ask here or in the Slack channel if you have any questions!

I've seen it is done. Sorry, had a busy week.

**Comment by npepinpe** [comment]
It's not done yet, but the PR I referenced will help simplify the implementation here, so I just proposed we wait for that PR to be merged. No rush :slightly_smiling_face:

**Comment by Zelldon** [comment]
This is fixed now.

I tested this and it returns a much better error message now:

```
$ zbctl status
Error: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: first record does not look like a TLS handshake"
[zell playground/ cluster: zeebe-cluster ns:zell-playground]$ zbctl --insecure status
Cluster size: 0
Partitions count: 0
Replication factor: 0
Gateway version: 1.9.0
Brokers:

$ zbctl --insecure deploy workflow.bpmn 
Error: rpc error: code = Unavailable desc = Expected to execute command on partition 1, but either it does not exist, or the gateway is not yet aware of it
```
