### ISSUE TITLE
ClassCastException: ExecutableFlowElementContainer cannot be cast to ExecutableMultiInstanceBody

### ISSUE THREAD

**Issue by MiguelPires** [camunda/zeebe#6152]
**Describe the bug**
A ClassCastException occurred in a production cluster when casting an `ExecutableFlowElementContainer` to `ExecutableMultiInstanceBody`. The impact isn't very severe since this only happened once and the cluster isn't under heavy use. Since this is not a recurrent problem, my first thought was that the workflow may be broken but since this is a production cluster I need access permission before I validate that.

**Log/Stacktrace**
```
"Expected to process event 'TypedEventImpl{metadata=RecordMetadata{recordType=EVENT, intentValue=255, intent=ELEMENT_TERMINATED, requestStreamId=-2147483648, requestId=-1, protocolVersion=3, valueType=WORKFLOW_INSTANCE, rejectionType=NULL_VAL, rejectionReason=, brokerVersion=0.26.0}, value={"bpmnProcessId":"[REDACTED]","version":20,"workflowKey":2251799833995714,"workflowInstanceKey":2251799833995735,"elementId":"Activity_0xgc3oq","flowScopeKey":2251799833995821,"bpmnElementType":"SUB_PROCESS","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1}}' without errors, but exception occurred with message 'class io.zeebe.engine.processing.deployment.model.element.ExecutableFlowElementContainer cannot be cast to class io.zeebe.engine.processing.deployment.model.element.ExecutableMultiInstanceBody (io.zeebe.engine.processing.deployment.model.element.ExecutableFlowElementContainer and io.zeebe.engine.processing.deployment.model.element.ExecutableMultiInstanceBody are in unnamed module of loader 'app')' ."

java.lang.ClassCastException: class io.zeebe.engine.processing.deployment.model.element.ExecutableFlowElementContainer cannot be cast to class io.zeebe.engine.processing.deployment.model.element.ExecutableMultiInstanceBody (io.zeebe.engine.processing.deployment.model.element.ExecutableFlowElementContainer and io.zeebe.engine.processing.deployment.model.element.ExecutableMultiInstanceBody are in unnamed module of loader 'app')
	at io.zeebe.engine.processing.bpmn.container.MultiInstanceBodyProcessor.onChildTerminated(MultiInstanceBodyProcessor.java:33) ~[zeebe-workflow-engine-0.26.0.jar:0.26.0]
	at io.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.onElementTerminated(BpmnStateTransitionBehavior.java:259) ~[zeebe-workflow-engine-0.26.0.jar:0.26.0]
	at io.zeebe.engine.processing.bpmn.container.SubProcessProcessor.onTerminated(SubProcessProcessor.java:119) ~[zeebe-workflow-engine-0.26.0.jar:0.26.0]
	at io.zeebe.engine.processing.bpmn.container.SubProcessProcessor.onTerminated(SubProcessProcessor.java:21) ~[zeebe-workflow-engine-0.26.0.jar:0.26.0]
	at io.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processEvent(BpmnStreamProcessor.java:124) ~[zeebe-workflow-engine-0.26.0.jar:0.26.0]
	at io.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processRecord(BpmnStreamProcessor.java:95) ~[zeebe-workflow-engine-0.26.0.jar:0.26.0]
	at io.zeebe.engine.processing.streamprocessor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:51) ~[zeebe-workflow-engine-0.26.0.jar:0.26.0]
	at io.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.lambda$processInTransaction$2(ProcessingStateMachine.java:269) ~[zeebe-workflow-engine-0.26.0.jar:0.26.0]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:79) ~[zeebe-db-0.26.0.jar:0.26.0]
	at io.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processInTransaction(ProcessingStateMachine.java:260) ~[zeebe-workflow-engine-0.26.0.jar:0.26.0]
	at io.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processEvent(ProcessingStateMachine.java:229) ~[zeebe-workflow-engine-0.26.0.jar:0.26.0]
	at io.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.tryToReadNextEvent(ProcessingStateMachine.java:205) ~[zeebe-workflow-engine-0.26.0.jar:0.26.0]
	at io.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.readNextEvent(ProcessingStateMachine.java:196) ~[zeebe-workflow-engine-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-0.26.0.jar:0.26.0]
```

https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22production%22%0Aresource.labels.namespace_name%3D%228b3cf719-9734-468e-b38a-f1ad6ef8dec3-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22;timeRange=2021-01-21T16:29:20.080Z%2F2021-01-21T17:29:20.080Z;pinnedLogId=2021-01-21T16:58:49.978393Z%2Fvqlqifq8665m003my?authuser=1&project=camunda-cloud-240911

</p>
</details>

**Environment:**
 - Production cluster, single broker
 - Zeebe Version: 0.26
 - Configuration: [e.g. exporters etc.]

**Comment by MiguelPires** [comment]
I couldn't reproduce this by running a workflow with multi-instance and forcing it to terminate in that element. Maybe someone with better knowledge of BPMN engine internals can weigh in on what might be happening. @saig0 @korthout

**Comment by saig0** [comment]
I looked into it but it's hard to say what went wrong. We would need the BPMN and the data of the workflow instance.
Maybe, it is related to the reprocessing issue and the state was restored not correctly. But I can not see an indication of it in the logs.

**Comment by korthout** [comment]
I have reproduced the error in a test in the above commit (in branch `korthout-test-6152`).

**Comment by korthout** [comment]
This error occurs on a specific failure: a terminating event subprocess inside a multi-instance subprocess. It's a bug in the engine that needs to be fixed, but IMO it is not a widely used feature.

@npepinpe this can be given priority now.

**Comment by npepinpe** [comment]
@korthout Please add the link to the Google drive folder so we can come back to this later.

**Comment by korthout** [comment]
[Link to gdrive](https://docs.google.com/document/d/14kdNYGRGXg0qqa8Yap6zLZko2ZAgIMtRZXKnb6Z099A/edit?usp=sharing)

**Comment by saig0** [comment]
Test case: https://github.com/zeebe-io/zeebe/commit/2d3f90aef1ceea153deec08da39f3788d0488a20

![image](https://user-images.githubusercontent.com/4305769/106443682-0e632400-647d-11eb-91a4-0c5bb57b5bd4.png)

Steps to Reproduce: 
* create an instance
* publish a message to trigger the event subprocess
* await until both tasks are entered
* cancel the workflow instance

**Comment by saig0** [comment]
:heavy_check_mark: I can't reproduce the bug anymore since version 8.0.21. It seems that we fixed the bug on the way. Great. :tada:
