### ISSUE TITLE
NoSuchElementException: null during parallel role transition to leader and follower

### ISSUE THREAD

**Issue by pihme** [camunda/zeebe#6293]
**Describe the bug**
Observed in error logs: https://console.cloud.google.com/errors/CJrRuvi3l7OKzgE?service=zeebe&time=P7D&project=camunda-cloud-240911

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.util.NoSuchElementException: null
	at io.atomix.storage.journal.MappedJournalSegmentReader.next(MappedJournalSegmentReader.java:102) ~[atomix-storage-0.26.0.jar:0.26.0]
	at io.atomix.storage.journal.SegmentedJournalReader.next(SegmentedJournalReader.java:118) ~[atomix-storage-0.26.0.jar:0.26.0]
	at io.atomix.storage.journal.DelegatingJournalReader.next(DelegatingJournalReader.java:66) ~[atomix-storage-0.26.0.jar:0.26.0]
	at io.zeebe.logstreams.storage.atomix.AtomixLogStorageReader.findEntry(AtomixLogStorageReader.java:156) ~[zeebe-logstreams-0.26.0.jar:0.26.0]
	at io.zeebe.logstreams.storage.atomix.AtomixLogStorageReader.read(AtomixLogStorageReader.java:55) ~[zeebe-logstreams-0.26.0.jar:0.26.0]
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.lambda$readBlockIntoBuffer$1(LogStreamReaderImpl.java:193) ~[zeebe-logstreams-0.26.0.jar:0.26.0]
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.executeReadMethod(LogStreamReaderImpl.java:197) ~[zeebe-logstreams-0.26.0.jar:0.26.0]
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.readBlockIntoBuffer(LogStreamReaderImpl.java:192) ~[zeebe-logstreams-0.26.0.jar:0.26.0]
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.readNextAddress(LogStreamReaderImpl.java:225) ~[zeebe-logstreams-0.26.0.jar:0.26.0]
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.hasNext(LogStreamReaderImpl.java:156) ~[zeebe-logstreams-0.26.0.jar:0.26.0]
	at io.zeebe.engine.processing.streamprocessor.ReProcessingStateMachine.scanLog(ReProcessingStateMachine.java:174) ~[zeebe-workflow-engine-0.26.0.jar:0.26.0]
	at io.zeebe.engine.processing.streamprocessor.ReProcessingStateMachine.startRecover(ReProcessingStateMachine.java:150) ~[zeebe-workflow-engine-0.26.0.jar:0.26.0]
	at io.zeebe.engine.processing.streamprocessor.StreamProcessor.onActorStarted(StreamProcessor.java:119) ~[zeebe-workflow-engine-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-0.26.0.jar:0.26.0]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-0.26.0.jar:0.26.0]
```

</p>
</details>

<details><summary>Log</summary>
 <p>

```
Debug 2021-02-10 02:50:43.001 CET "Partition role transitioning from FOLLOWER to CANDIDATE"
Debug 2021-02-10 02:50:54.195 CET "Partition role transitioning from CANDIDATE to LEADER"
Debug 2021-02-10 02:50:54.195 CET "Closing Zeebe-Partition-1: ConsumeReplicatedSnapshots"
Debug 2021-02-10 02:50:54.195 CET "Closing Zeebe-Partition-1: ConsumeReplicatedSnapshots closed successfully"
Debug 2021-02-10 02:50:54.195 CET "Closing Zeebe-Partition-1: LogDeletionService"
Debug 2021-02-10 02:50:54.196 CET "Closing Zeebe-Partition-1: LogDeletionService closed successfully"
Debug 2021-02-10 02:50:54.196 CET "Closing Zeebe-Partition-1: StateController"
Debug 2021-02-10 02:50:54.196 CET "Closing Zeebe-Partition-1: StateController closed successfully"
Debug 2021-02-10 02:50:54.196 CET "Closing Zeebe-Partition-1: SnapshotReplication"
Debug 2021-02-10 02:50:54.196 CET "Closing Zeebe-Partition-1: SnapshotReplication closed successfully"
Debug 2021-02-10 02:50:54.196 CET "Closing Zeebe-Partition-1: RaftLogReader"
Debug 2021-02-10 02:50:54.196 CET "Closing Zeebe-Partition-1: RaftLogReader closed successfully"
Debug 2021-02-10 02:50:54.196 CET "Partition 1 closed all previous open resources, before transitioning."
Debug 2021-02-10 02:51:01.313 CET "Available snapshot: FileBasedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/355053699-16444-1612921715229-4695207595-4695207597, metadata=FileBasedSnapshotMetadata{index=355053699, term=16444, timestamp=2021-02-10 01:48:35,229, processedPosition=4695207595, exporterPosition=4695207597}}"
Debug 2021-02-10 02:51:22.484 CET "Opened database from '/usr/local/zeebe/data/raft-partition/partitions/1/runtime'."
Debug 2021-02-10 02:51:22.484 CET "Recovered state from snapshot 'FileBasedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/355053699-16444-1612921715229-4695207595-4695207597, metadata=FileBasedSnapshotMetadata{index=355053699, term=16444, timestamp=2021-02-10 01:48:35,229, processedPosition=4695207595, exporterPosition=4695207597}}'"
Debug 2021-02-10 02:51:22.485 CET "Partition role transitioning from LEADER to FOLLOWER"
Debug 2021-02-10 02:51:22.485 CET "Partition role transitioning from FOLLOWER to CANDIDATE"
Debug 2021-02-10 02:51:22.485 CET "Partition role transitioning from CANDIDATE to FOLLOWER"
Debug 2021-02-10 02:51:22.485 CET "Partition role transitioning from FOLLOWER to CANDIDATE"
Debug 2021-02-10 02:51:26.617 CET "Partition role transitioning from CANDIDATE to FOLLOWER"
Debug 2021-02-10 02:51:26.790 CET "Configured log appender back pressure at partition 1 as AppenderVegasCfg{initialLimit=1024, maxConcurrency=32768, alphaLimit=0.7, betaLimit=0.95}. Window limiting is disabled"
Debug 2021-02-10 02:51:26.791 CET "Recovering state of partition 1 from snapshot"
Info 2021-02-10 02:51:26.792 CET "Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@3e0daf95)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@a77eaa3, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@3b5e2a3c, configuration: Configuration(false)]"
Info 2021-02-10 02:51:30.961 CET "Recovered state of partition 1 from snapshot at position 4695207598"
Info 2021-02-10 02:51:30.961 CET "Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@1d841c54)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@4ea66976, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@7b31b0f3, configuration: Configuration(false)]"
Info 2021-02-10 02:51:30.963 CET Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@31746a63)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@c2fa6a5, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@71bf838f, configuration: Configuration(false)]"
Debug 2021-02-10 02:51:30.965 CET "Partition 1 transition complete, installed 11 resources!"
Debug 2021-02-10 02:51:30.965 CET "Recovering exporter from snapshot"
Debug 2021-02-10 02:51:30.966 CET "Closing Zeebe-Partition-1: ExporterDirector"
Error 2021-02-10 02:51:31.231 CET "Actor Broker-1-StreamProcessor-1 failed in phase STARTED."
Debug 2021-02-10 02:51:31.397 CET "Failed to append block with last event position 4695208988. This can happen during a leader change."
```

</p>
</details>

**Environment:**
 - OS: Linux / Camunda Cloud
 - Zeebe Version: 0.26.0

**Comment by pihme** [comment]
Analysis:

Root cause seems to be a race condition between one process completing the transition to leader and another process (of the same broker) transitioning to follower.

Filtered Log:

Leader transition starts:
```
Debug 2021-02-10 02:50:43.001 CET "Partition role transitioning from FOLLOWER to CANDIDATE"
Debug 2021-02-10 02:50:54.195 CET "Partition role transitioning from CANDIDATE to LEADER"
Debug 2021-02-10 02:50:54.195 CET "Closing Zeebe-Partition-1: ConsumeReplicatedSnapshots"
Debug 2021-02-10 02:50:54.195 CET "Closing Zeebe-Partition-1: ConsumeReplicatedSnapshots closed successfully"
Debug 2021-02-10 02:50:54.195 CET "Closing Zeebe-Partition-1: LogDeletionService"
Debug 2021-02-10 02:50:54.196 CET "Closing Zeebe-Partition-1: LogDeletionService closed successfully"
Debug 2021-02-10 02:50:54.196 CET "Closing Zeebe-Partition-1: StateController"
Debug 2021-02-10 02:50:54.196 CET "Closing Zeebe-Partition-1: StateController closed successfully"
Debug 2021-02-10 02:50:54.196 CET "Closing Zeebe-Partition-1: SnapshotReplication"
Debug 2021-02-10 02:50:54.196 CET "Closing Zeebe-Partition-1: SnapshotReplication closed successfully"
Debug 2021-02-10 02:50:54.196 CET "Closing Zeebe-Partition-1: RaftLogReader"
Debug 2021-02-10 02:50:54.196 CET "Closing Zeebe-Partition-1: RaftLogReader closed successfully"
Debug 2021-02-10 02:50:54.196 CET "Partition 1 closed all previous open resources, before transitioning."
Debug 2021-02-10 02:51:01.313 CET "Available snapshot: FileBasedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/355053699-16444-1612921715229-4695207595-4695207597, metadata=FileBasedSnapshotMetadata{index=355053699, term=16444, timestamp=2021-02-10 01:48:35,229, processedPosition=4695207595, exporterPosition=4695207597}}"
Debug 2021-02-10 02:51:22.484 CET "Opened database from '/usr/local/zeebe/data/raft-partition/partitions/1/runtime'."
Debug 2021-02-10 02:51:22.484 CET "Recovered state from snapshot 'FileBasedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/355053699-16444-1612921715229-4695207595-4695207597, metadata=FileBasedSnapshotMetadata{index=355053699, term=16444, timestamp=2021-02-10 01:48:35,229, processedPosition=4695207595, exporterPosition=4695207597}}'"
```

Then there is a flurry of activity with different transitions happening almost instantly:

```
Debug 2021-02-10 02:51:22.485 CET "Partition role transitioning from LEADER to FOLLOWER"
Debug 2021-02-10 02:51:22.485 CET "Partition role transitioning from FOLLOWER to CANDIDATE"
Debug 2021-02-10 02:51:22.485 CET "Partition role transitioning from CANDIDATE to FOLLOWER"
Debug 2021-02-10 02:51:22.485 CET "Partition role transitioning from FOLLOWER to CANDIDATE"
Debug 2021-02-10 02:51:26.617 CET "Partition role transitioning from CANDIDATE to FOLLOWER"
```

Net result is that the desired state is now FOLLOWER

However, the transition to leader is still running in the background and then those two processed collide.

```
Debug 2021-02-10 02:51:26.790 CET "Configured log appender back pressure at partition 1 as AppenderVegasCfg{initialLimit=1024, maxConcurrency=32768, alphaLimit=0.7, betaLimit=0.95}. Window limiting is disabled"
Debug 2021-02-10 02:51:26.791 CET "Recovering state of partition 1 from snapshot"
Info 2021-02-10 02:51:26.792 CET "Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@3e0daf95)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@a77eaa3, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@3b5e2a3c, configuration: Configuration(false)]"
Info 2021-02-10 02:51:30.961 CET "Recovered state of partition 1 from snapshot at position 4695207598"
Info 2021-02-10 02:51:30.961 CET "Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@1d841c54)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@4ea66976, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@7b31b0f3, configuration: Configuration(false)]"
Info 2021-02-10 02:51:30.963 CET Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@31746a63)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@c2fa6a5, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@71bf838f, configuration: Configuration(false)]"
Debug 2021-02-10 02:51:30.965 CET "Partition 1 transition complete, installed 11 resources!"
Debug 2021-02-10 02:51:30.965 CET "Recovering exporter from snapshot"
Debug 2021-02-10 02:51:30.966 CET "Closing Zeebe-Partition-1: ExporterDirector"
Error 2021-02-10 02:51:31.231 CET "Actor Broker-1-StreamProcessor-1 failed in phase STARTED."
Debug 2021-02-10 02:51:31.397 CET "Failed to append block with last event position 4695208988. This can happen during a leader change."
```

**Comment by npepinpe** [comment]
@pihme - not 100% bootstrapping but I would say somewhat related

**Comment by pihme** [comment]
This should no longer happen as transitions for one partition are serialized. However, since we never knew the reason for the bug in the first place, and since the transitions were supposed to be serialized in the past, as well, I keep the bug open.

**Comment by npepinpe** [comment]
As this hasn't happened again for almost a year, I would propose to close it. Feel free to re-open.
