### ISSUE TITLE
Suspected Memory Leak on Gateway

### ISSUE THREAD

**Issue by mohnishkodnani** [camunda/zeebe#6654]
**Describe the bug**
There seems to be a memory leak in the gateway code path when broker is not available.  I had a broker deployed on K8s and overnight it was dying due to OOM. 
When looked at the jvm_memory_bytes_used for gateway I saw a steep incline. 
The JVM memory area that went up was "direct" memory , the non-heap portion. 

**To Reproduce**
Steps to reproduce the behavior
Make Broker not available to gateway and measure jvm_memory_bytes_used.

If possible add a minimal reproducer code sample
- Currently, its on a K8s environment, no specific code.

**Expected behavior**
Memory steady or constant. 

**Log/Stacktrace**
Gateway Log : Have rotated, but full of statements like this
```
2021-03-25 16:18:24.261 [io.zeebe.gateway.impl.broker.BrokerRequestManager] [gateway-scheduler-zb-actors-0] ERROR
      io.zeebe.gateway - Expected to handle gRPC request, but an unexpected error occurred
io.zeebe.gateway.impl.broker.RequestRetriesExhaustedException: Expected to execute the command on one of the partitions, but all failed; there are no more partitions available to retry. Please try again. If the error persists contact your zeebe operator
    at io.zeebe.gateway.impl.broker.RequestRetryHandler.sendRequestWithRetry(RequestRetryHandler.java:126) ~[zeebe-gateway-1.0.0-alpha2.jar:1.0.0-alpha2]
    at io.zeebe.gateway.impl.broker.RequestRetryHandler.lambda$sendRequestWithRetry$1(RequestRetryHandler.java:113) ~[zeebe-gateway-1.0.0-alpha2.jar:1.0.0-alpha2]
    at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
    at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
    at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
    at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
    at io.zeebe.gateway.impl.broker.BrokerRequestManager.lambda$sendRequestInternal$2(BrokerRequestManager.java:150) ~[zeebe-gateway-1.0.0-alpha2.jar:1.0.0-alpha2]
    at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:33) [zeebe-util-1.0.0-alpha2.jar:1.0.0-alpha2]
    at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-1.0.0-alpha2.jar:1.0.0-alpha2]
    at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.0.0-alpha2.jar:1.0.0-alpha2]
    at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.0.0-alpha2.jar:1.0.0-alpha2]
    at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.0.0-alpha2.jar:1.0.0-alpha2]
    at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.0.0-alpha2.jar:1.0.0-alpha2]
    at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.0.0-alpha2.jar:1.0.0-alpha2]
    Suppressed: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: lnp-zeebe-0.lnp-zeebe.blah.svc.130.blah.io/x.x.x.x:26501
    Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
        at io.netty.channel.unix.Errors.throwConnectException(Errors.java:124) ~[netty-transport-native-unix-common-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.unix.Socket.finishConnect(Socket.java:252) ~[netty-transport-native-unix-common-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:673) ~[netty-transport-native-epoll-4.1.59.Final-linux-x86_64.jar:4.1.59.Final]
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:650) ~[netty-transport-native-epoll-4.1.59.Final-linux-x86_64.jar:4.1.59.Final]
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:530) ~[netty-transport-native-epoll-4.1.59.Final-linux-x86_64.jar:4.1.59.Final]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:470) ~[netty-transport-native-epoll-4.1.59.Final-linux-x86_64.jar:4.1.59.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.59.Final-linux-x86_64.jar:4.1.59.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.59.Final.jar:4.1.59.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.59.Final.jar:4.1.59.Final]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
    Suppressed: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: lnp-zeebe-0.lnp-zeebe.blah.svc.130.blah.io/x.x.x.x:26501
    Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
```

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
 - OS: Linux
 - Zeebe Version: 1.0.0-alpha2
 - Configuration: 
 Broker and Gateway Version: 1.0.0-alpha2
Broker CPU requests: 2 , limits : 8
Broker Mem requests: 2Gi, limit: 4Gi.
Disk: /usr/local/zeebe/data -> Mounted as an EmptyDir ( medium : InMemory) to simulate RAM disk. Rest is probably a HDD on the node itself.

Gateway CPU requests: 500m, limit : 1
Gateway Memory requests: 2Gi, limit : 4Gi
No Exporters 
 
<img width="1012" alt="Screen Shot 2021-03-25 at 09 16 03" src="https://user-images.githubusercontent.com/7194964/112507620-0a040a80-8d4c-11eb-8119-7e3e54bca376.png">

**Comment by npepinpe** [comment]
Thanks for reporting this! I assume from your comment that you're using the standalone gateway, correct?

Would it be possible for you to take a heap dump and share it? Even though it's direct memory, we should be able to track the most likely suspect (instances of `DirectByteBuffer`).

In the meantime I can try reproducing it as well.

**Comment by npepinpe** [comment]
I found a heap memory leak in NettyMessagingService - for every request, we keep a reference to the future in a list so we can close them all if the service is shut down. When the request completes successfully, the future is removed from the open futures list. But if there was an error, it remains there.

That doesn't explain the direct memory usage however...

**Comment by npepinpe** [comment]
I ran it for quite a while now with the set up you mentioned, and while I can see the heap growing (so there's definitely a leak there), the direct memory is very stable.

What requests are you sending in general? I tried with different ones, but maybe I'm not triggering the right code path.

**Comment by mohnishkodnani** [comment]
Unfortunately, the pod was in crash back off loop and i couldnt get into the pod. In a few days i will try to repeat the test and see the behavior. I am starting a workflow with results ( 1 task that completes immediately). 
```
class ThroughputSimulation extends Simulation {
  val baseHttpProtocol =
    http.baseUrl("http://httpsearch.blah.svc.zyx.blah.io:10000")
  val scene = scenario("throughput")
    .exec(http("Search").get("/search").queryParam("nkw", "testing"))

  setUp(
    scene.inject(
      incrementUsersPerSec(10)
        .times(10)
        .eachLevelLasting(1.minutes)
        .separatedByRampsLasting(1.minute)
        .startingFrom(0)
    )
  ).protocols(baseHttpProtocol)
```
This was the load test ( I actually didnt want to stress but by mistake launched it to see the behavior)
This is the gatling framework code. I left it overnight and checked in the morning. The broker pod had crashed about 90 times already when i saw it. 
The metrics for the graph i showed  
`jvm_memory_bytes_used{namespace=~"$namespace",pod=~"$pod",area="nonheap"}`

In the URL endpoint the code is the following
```
    val requestF = zeebeClient
      .newCreateInstanceCommand()
      .bpmnProcessId("lnp")
      .latestVersion()
      .variables(JMap.of("keywords", keywords))
      .withResult()
      .send()
      .toCompletableFuture
      .asScala
      .map(_.getVariables)
    requestF
```

**Comment by mohnishkodnani** [comment]
I have also put up the setup details in the zeebe slack channel.

**Comment by npepinpe** [comment]
Opened https://github.com/camunda-cloud/zeebe/issues/6878 for the heap memory leak detected.

**Comment by tuoluofusijiyang** [comment]
Did you fix this problem? I also encountered it
