### ISSUE TITLE
IllegalStateException: Not expected to have an active sequence flow count lower then zero!

### ISSUE THREAD

**Issue by saig0** [camunda/zeebe#6778]
**Describe the bug**
On reprocessing, the stream processor ran in an endless loop.

```
java.lang.IllegalStateException: Not expected to have an active sequence flow count lower then zero!
``` 

Followed by

```
Catched exception class io.zeebe.engine.processing.bpmn.BpmnProcessingException with message 
Expected to take transition to 'ELEMENT_ACTIVATED' but element instance is in state 'SEQUENCE_FLOW_TAKEN'. 
[context: {intent=SEQUENCE_FLOW_TAKEN, elementId=Activity_0v8ebms, bpmnElementType=SUB_PROCESS, 
elementInstanceKey=4503599646176568, flowScopeKey=4503599646085191, processInstanceKey=4503599646085191,
parentProcessInstanceKey=-1, parentElementInstanceKey=-1, bpmnProcessId=BENCH-PERF, processVersion=1, 
processDefinitionKey=2251799813685261}], will retry...
```

**To Reproduce**

Not clear.

![image](https://user-images.githubusercontent.com/4305769/114393011-d7567080-9b99-11eb-8c0f-caa9a1d83659.png)

It seems to be related to the termination of an (event-) subprocess.

```
"Don't process event because of an illegal state transition: Expected element instance to be in state 'ELEMENT_TERMINATED' or one of '[]' but was 'ELEMENT_TERMINATING'. [context: {intent=ELEMENT_TERMINATED, elementId=Activity_0sul25s, bpmnElementType=SUB_PROCESS, elementInstanceKey=4503599646086641, flowScopeKey=4503599646085191, processInstanceKey=4503599646085191, parentProcessInstanceKey=-1, parentElementInstanceKey=-1, bpmnProcessId=BENCH-PERF, processVersion=1, processDefinitionKey=2251799813685261}]"
```

**Expected behavior**
This issue is probably caused by the [current work in the workflow engine](https://github.com/camunda-cloud/zeebe/milestone/51) that applies event sourcing to the stream processors.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalStateException: Not expected to have an active sequence flow count lower then zero!
	at io.zeebe.engine.state.instance.ElementInstance.decrementActiveSequenceFlows(ElementInstance.java:168) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.activateElementInstanceInFlowScope(BpmnStateTransitionBehavior.java:245) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.bpmn.sequenceflow.SequenceFlowProcessor.onSequenceFlowTaken(SequenceFlowProcessor.java:96) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.bpmn.sequenceflow.SequenceFlowProcessor.onActivating(SequenceFlowProcessor.java:52) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.bpmn.sequenceflow.SequenceFlowProcessor.onActivating(SequenceFlowProcessor.java:30) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processEvent(BpmnStreamProcessor.java:165) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processRecord(BpmnStreamProcessor.java:106) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.streamprocessor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:54) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.streamprocessor.ReProcessingStateMachine.reprocessRecord(ReProcessingStateMachine.java:405) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.streamprocessor.ReProcessingStateMachine.lambda$chooseOperationForEvent$7(ReProcessingStateMachine.java:371) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.streamprocessor.ReProcessingStateMachine.lambda$processUntilDone$4(ReProcessingStateMachine.java:343) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:36) ~[zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.retry.EndlessRetryStrategy.run(EndlessRetryStrategy.java:50) ~[zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
```

</p>
</details>

<details><summary>Follow-up Exception</summary>
 <p>

```
io.zeebe.engine.processing.bpmn.BpmnProcessingException: Expected to take transition to 'ELEMENT_ACTIVATED' but element instance is in state 'SEQUENCE_FLOW_TAKEN'. [context: {intent=SEQUENCE_FLOW_TAKEN, elementId=Activity_0v8ebms, bpmnElementType=SUB_PROCESS, elementInstanceKey=4503599646176568, flowScopeKey=4503599646085191, processInstanceKey=4503599646085191, parentProcessInstanceKey=-1, parentElementInstanceKey=-1, bpmnProcessId=BENCH-PERF, processVersion=1, processDefinitionKey=2251799813685261}]
	at io.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.verifyTransition(BpmnStateTransitionBehavior.java:175) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.transitionTo(BpmnStateTransitionBehavior.java:161) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.transitionToActivated(BpmnStateTransitionBehavior.java:92) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.bpmn.container.SubProcessProcessor.lambda$onActivating$1(SubProcessProcessor.java:53) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.Either$Right.ifRightOrLeft(Either.java:238) ~[zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.bpmn.container.SubProcessProcessor.onActivating(SubProcessProcessor.java:52) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.bpmn.container.SubProcessProcessor.onActivating(SubProcessProcessor.java:23) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processEvent(BpmnStreamProcessor.java:165) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processRecord(BpmnStreamProcessor.java:106) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.streamprocessor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:54) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.streamprocessor.ReProcessingStateMachine.reprocessRecord(ReProcessingStateMachine.java:405) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.streamprocessor.ReProcessingStateMachine.lambda$chooseOperationForEvent$7(ReProcessingStateMachine.java:371) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.engine.processing.streamprocessor.ReProcessingStateMachine.lambda$processUntilDone$4(ReProcessingStateMachine.java:343) ~[zeebe-workflow-engine-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:36) ~[zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.retry.EndlessRetryStrategy.run(EndlessRetryStrategy.java:50) ~[zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.0.0-alpha4.jar:1.0.0-alpha4]
```

</p>
</details>

Error Reporting:
* https://console.cloud.google.com/errors/CMry7a29qqy7Rw?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911
* https://console.cloud.google.com/errors/CIudxdnGhOOp7AE?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911

Log: https://console.cloud.google.com/logs/query;query=%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultratest%22%0Aresource.labels.namespace_name%3D%2299936d0e-e21b-493c-8b96-6d79ac11c40d-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22;timeRange=2021-04-12T10:06:14.712Z%2F2021-04-12T11:06:14.712Z;pinnedLogId=2021-04-12T10:35:15.759906Z%2F32bhcwg42mromx;cursorTimestamp=2021-04-12T10:35:15.789511Z?project=camunda-cloud-240911 

**Environment:**
 - OS: Camunda Cloud (ultratest)
 - Zeebe Version: 1.0.0-alpha4
 - Configuration:

**Comment by saig0** [comment]
It is expected that this issue will be solved when the migration is done because it replaces the whole reprocessing by event applying.

**Comment by Zelldon** [comment]
Seems to happen again with https://console.cloud.google.com/errors/detail/CJG2u-KVh-_LigE;service=zeebe;version=8.0.2;time=P7D?project=camunda-cloud-240911

```
"Expected to process record 'TypedEventImpl{metadata=RecordMetadata{recordType=COMMAND, intentValue=255, intent=ACTIVATE_ELEMENT, requestStreamId=-2147483648, requestId=-1, protocolVersion=3, valueType=PROCESS_INSTANCE, rejectionType=NULL_VAL, rejectionReason=, brokerVersion=8.0.2}, value={"bpmnProcessId":"epp-processing","version":46,"processDefinitionKey":2251799814498262,"processInstanceKey":4503599627984972,"elementId":"Gateway_04dcjj2","flowScopeKey":4503599627984972,"bpmnElementType":"PARALLEL_GATEWAY","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1}}' without errors, but exception occurred with message 'Not expected to have an active sequence flow count lower then zero!'."
```

I will try to get more data

**Comment by Zelldon** [comment]
Seems to happen again with https://console.cloud.google.com/errors/detail/CJG2u-KVh-_LigE;service=zeebe;version=8.0.2;time=P7D?project=camunda-cloud-240911

```
"Expected to process record 'TypedEventImpl{metadata=RecordMetadata{recordType=COMMAND, intentValue=255, intent=ACTIVATE_ELEMENT, requestStreamId=-2147483648, requestId=-1, protocolVersion=3, valueType=PROCESS_INSTANCE, rejectionType=NULL_VAL, rejectionReason=, brokerVersion=8.0.2}, value={"bpmnProcessId":"epp-processing","version":46,"processDefinitionKey":2251799814498262,"processInstanceKey":4503599627984972,"elementId":"Gateway_04dcjj2","flowScopeKey":4503599627984972,"bpmnElementType":"PARALLEL_GATEWAY","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1}}' without errors, but exception occurred with message 'Not expected to have an active sequence flow count lower then zero!'."
```

I will try to get more data

**Comment by Zelldon** [comment]
It seems that the error was produced by an model where the gateway was taken multiple times (at least twice). 

Since this is confidential data I put it into our gdrive https://drive.google.com/drive/u/0/folders/1NIgMxfWjZ5T16mDQ9DEdHMpr1SVg0w9F

**Comment by remcowesterhoud** [comment]
I have added a version of the process to the drive that doesn't require any variables, for easier debugging.

\cc @saig0

**Comment by remcowesterhoud** [comment]
I have also just added a none_event_repro file. Creating an instance of this will result in the exception.

**Comment by remcowesterhoud** [comment]
**Hypothesis**
I have created a minimalistic process to reproduce the issue:
<img width="689" alt="image" src="https://user-images.githubusercontent.com/5787702/177592820-3e686284-aabc-4888-9214-a52981c92d2d.png">

It all has to do with when we reset the number of taken sequence flows. This happens in the completed applier. This in combination with activating the parallel gateway through a command causes this behaviour.

When starting the process the following happens:

1. We take sequence flow 1, 2 and 3
2. 1 arrives at the joining gateway. The number of taken sequence flows is 1
3. 2 and 3 arrive at the exclusive gateway. Both taking sequence flow 4.
4. The first sequence flow 4 arrives at the joining gateway. The number of taken sequence flows is 2. This is equal to the amount of incoming sequence flow so we send an activate command.
5. The second sequence flow 4 arrives at the joining gateway. The 1st command has not yet been processed. The joining gateway is not yet activated and completed, thus the number of taken sequence flows has not been reset! Another command to activate the joining gateway is written.
6. The first activate command is handled. The number of active sequence flows is decremented by 2 (the amount of incoming sequence flows). This is fine as we have 3 active sequence flows at this stage.
7. The second command is handled. The number of active sequence flows is decremented by 2 again. This results in an exception as there only is 1 more active sequence flow.

**Comment by saig0** [comment]
@remcowesterhoud great analysis :+1: I can confirm the behavior :heavy_check_mark:

**Comment by Zelldon** [comment]
In my opinion, this bug is critical (at least high severity), there is no work-around and the process instances are stuck in this case. Plus: As a SaaS user it is hard to detect what went wrong.

**Comment by remcowesterhoud** [comment]
I would argue there is a workaround, which is fixing the model. Strictly looking at the labels that means med would fit the best:  "Marks a bug as having a noticeable impact but with a known workaround". I'm still happy to fix it right now as I don't think it'll be a difficult thing.
