### ISSUE TITLE
IOException: Input/output error

### ISSUE THREAD

**Issue by pihme** [camunda/zeebe#7563]
**Describe the bug**
Observed in production log: https://console.cloud.google.com/errors/CM6i3o-01um0CA?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911

https://console.cloud.google.com/errors/CNSBlaP43ISTSg?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911

**Log/Stacktrace**
<details><summary>Full Stacktrace</summary>
 <p>

```
java.io.IOException: Input/output error
	at java.nio.MappedByteBuffer.force0(Native Method) ~[?:?]
	at java.nio.MappedByteBuffer.force(Unknown Source) ~[?:?]
	at io.camunda.zeebe.journal.file.MappedJournalSegmentWriter.flush(MappedJournalSegmentWriter.java:259) ~[zeebe-journal-1.1.0-alpha1.jar:1.1.0-alpha1]
	at io.camunda.zeebe.journal.file.MappedJournalSegmentWriter.close(MappedJournalSegmentWriter.java:265) ~[zeebe-journal-1.1.0-alpha1.jar:1.1.0-alpha1]
	at io.camunda.zeebe.journal.file.JournalSegment.close(JournalSegment.java:178) ~[zeebe-journal-1.1.0-alpha1.jar:1.1.0-alpha1]
	at io.camunda.zeebe.journal.file.SegmentedJournal.lambda$close$1(SegmentedJournal.java:218) ~[zeebe-journal-1.1.0-alpha1.jar:1.1.0-alpha1]
	at java.lang.Iterable.forEach(Unknown Source) ~[?:?]
	at io.camunda.zeebe.journal.file.SegmentedJournal.close(SegmentedJournal.java:215) ~[zeebe-journal-1.1.0-alpha1.jar:1.1.0-alpha1]
	at org.agrona.CloseHelper.close(CloseHelper.java:111) ~[agrona-1.10.0.jar:1.10.0]
	at io.atomix.raft.storage.log.RaftLog.close(RaftLog.java:205) ~[zeebe-atomix-cluster-1.1.0-alpha1.jar:1.1.0-alpha1]
	at io.atomix.raft.impl.RaftContext.close(RaftContext.java:621) ~[zeebe-atomix-cluster-1.1.0-alpha1.jar:1.1.0-alpha1]
	at io.atomix.raft.impl.DefaultRaftServer.lambda$shutdown$2(DefaultRaftServer.java:136) ~[zeebe-atomix-cluster-1.1.0-alpha1.jar:1.1.0-alpha1]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) [zeebe-atomix-utils-1.1.0-alpha1.jar:1.1.0-alpha1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

Related exception at about the same time:
```

java.nio.file.FileSystemException: /usr/local/zeebe/data/raft-partition/partitions/2/runtime: Input/output error

        at sun.nio.fs.UnixException.translateToIOException (Unknown Source)
        at sun.nio.fs.UnixException.rethrowAsIOException (Unknown Source)
        at sun.nio.fs.UnixException.rethrowAsIOException (Unknown Source)
        at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes (Unknown Source)
        at sun.nio.fs.UnixFileSystemProvider.readAttributes (Unknown Source)
        at sun.nio.fs.LinuxFileSystemProvider.readAttributes (Unknown Source)
        at java.nio.file.Files.readAttributes (Unknown Source)
        at java.nio.file.FileTreeWalker.getAttributes (Unknown Source)
        at java.nio.file.FileTreeWalker.visit (Unknown Source)
        at java.nio.file.FileTreeWalker.walk (Unknown Source)
        at java.nio.file.Files.walkFileTree (Unknown Source)
        at java.nio.file.Files.walkFileTree (Unknown Source)
        at io.camunda.zeebe.util.FileUtil.deleteFolderIfExists (FileUtil.java:60)
        at io.camunda.zeebe.broker.system.partitions.impl.StateControllerImpl.close (StateControllerImpl.java:159)
        at io.camunda.zeebe.broker.system.partitions.impl.steps.StateControllerPartitionStep.close (StateControllerPartitionStep.java:48)
        at io.camunda.zeebe.broker.system.partitions.impl.PartitionTransitionImpl.closeNextStep (PartitionTransitionImpl.java:171)
        at io.camunda.zeebe.broker.system.partitions.impl.PartitionTransitionImpl.lambda$closeNextStep$3 (PartitionTransitionImpl.java:188)
        at io.camunda.zeebe.util.sched.future.FutureContinuationRunnable.run (FutureContinuationRunnable.java:28)
        at io.camunda.zeebe.util.sched.ActorJob.invoke (ActorJob.java:76)
        at io.camunda.zeebe.util.sched.ActorJob.execute (ActorJob.java:39)
        at io.camunda.zeebe.util.sched.ActorTask.execute (ActorTask.java:122)
        at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask (ActorThread.java:94)
        at io.camunda.zeebe.util.sched.ActorThread.doWork (ActorThread.java:78)
        at io.camunda.zeebe.util.sched.ActorThread.run (ActorThread.java:191)
```

</p>
</details>

<details><summary>Log</summary>
 <p>

```
D 2021-07-30T18:14:17.301074Z Closing ZeebePartition 1 
D 2021-07-30T18:14:17.302312Z Closing Zeebe-Partition-1: ConsumeReplicatedSnapshots 
D 2021-07-30T18:14:17.303113Z Closing Zeebe-Partition-1: ConsumeReplicatedSnapshots closed successfully 
D 2021-07-30T18:14:17.303411Z Closing Zeebe-Partition-1: LogDeletionService 
D 2021-07-30T18:14:17.304196Z Closing Zeebe-Partition-1: LogDeletionService closed successfully 
D 2021-07-30T18:14:17.304467Z Closing Zeebe-Partition-1: StateController 
E 2021-07-30T18:14:17.319562Z Unexpected error occurred while closing the state snapshot controller for partition 1. 
D 2021-07-30T18:14:17.332740Z Closing Zeebe-Partition-1: StateController closed successfully 
D 2021-07-30T18:14:17.333087Z Closing Zeebe-Partition-1: SnapshotReplication 
D 2021-07-30T18:14:17.333468Z Closing Zeebe-Partition-1: SnapshotReplication closed successfully 
D 2021-07-30T18:14:17.333715Z Closing Zeebe-Partition-1: RaftLogReader 
D 2021-07-30T18:14:17.334026Z Closing Zeebe-Partition-1: RaftLogReader closed successfully 
D 2021-07-30T18:14:17.334277Z Partition 1 closed all previous open resources, before transitioning. 
D 2021-07-30T18:14:17.334556Z Partition 1 transition complete, installed 0 resources! 
D 2021-07-30T18:14:17.335086Z Closing Broker-1 partitions [1/3]: partition 1 closed in 36 ms 
I 2021-07-30T18:14:17.335377Z Closing Broker-1 partitions [2/3]: partition 2 
D 2021-07-30T18:14:17.335842Z Discard job io.camunda.zeebe.broker.system.partitions.ZeebePartition$$Lambda$1247/0x000000084083c040 QUEUED from fastLane of Actor Broker-1-ZeebePartition-2. 
D 2021-07-30T18:14:17.336633Z Closing ZeebePartition 2 
D 2021-07-30T18:14:17.337017Z Closing Zeebe-Partition-2: ConsumeReplicatedSnapshots 
D 2021-07-30T18:14:17.337296Z Closing Zeebe-Partition-2: ConsumeReplicatedSnapshots closed successfully 
D 2021-07-30T18:14:17.337545Z Closing Zeebe-Partition-2: LogDeletionService 
D 2021-07-30T18:14:17.337968Z Closing Zeebe-Partition-2: LogDeletionService closed successfully 
D 2021-07-30T18:14:17.338212Z Closing Zeebe-Partition-2: StateController 
E 2021-07-30T18:14:17.350283Z Unexpected error occurred while closing the state snapshot controller for partition 2. 
D 2021-07-30T18:14:17.351150Z Closing Zeebe-Partition-2: StateController closed successfully 
D 2021-07-30T18:14:17.351408Z Closing Zeebe-Partition-2: SnapshotReplication 
D 2021-07-30T18:14:17.351764Z Closing Zeebe-Partition-2: SnapshotReplication closed successfully 
D 2021-07-30T18:14:17.352055Z Closing Zeebe-Partition-2: RaftLogReader 
D 2021-07-30T18:14:17.352344Z Closing Zeebe-Partition-2: RaftLogReader closed successfully 
D 2021-07-30T18:14:17.352606Z Partition 2 closed all previous open resources, before transitioning. 
D 2021-07-30T18:14:17.352893Z Partition 2 transition complete, installed 0 resources! 
D 2021-07-30T18:14:17.353367Z Closing Broker-1 partitions [2/3]: partition 2 closed in 18 ms 
I 2021-07-30T18:14:17.353639Z Closing Broker-1 partitions [3/3]: partition 3 
D 2021-07-30T18:14:17.354641Z Closing ZeebePartition 3 
D 2021-07-30T18:14:17.355010Z Closing Zeebe-Partition-3: ConsumeReplicatedSnapshots 
D 2021-07-30T18:14:17.355328Z Closing Zeebe-Partition-3: ConsumeReplicatedSnapshots closed successfully 
D 2021-07-30T18:14:17.355569Z Closing Zeebe-Partition-3: LogDeletionService 
D 2021-07-30T18:14:17.355985Z Closing Zeebe-Partition-3: LogDeletionService closed successfully 
D 2021-07-30T18:14:17.356271Z Closing Zeebe-Partition-3: StateController 
E 2021-07-30T18:14:17.368403Z Unexpected error occurred while closing the state snapshot controller for partition 3. 
D 2021-07-30T18:14:17.369206Z Closing Zeebe-Partition-3: StateController closed successfully 
D 2021-07-30T18:14:17.369480Z Closing Zeebe-Partition-3: SnapshotReplication 
D 2021-07-30T18:14:17.369806Z Closing Zeebe-Partition-3: SnapshotReplication closed successfully 
D 2021-07-30T18:14:17.370072Z Closing Zeebe-Partition-3: RaftLogReader 
D 2021-07-30T18:14:17.370346Z Closing Zeebe-Partition-3: RaftLogReader closed successfully 
D 2021-07-30T18:14:17.370624Z Partition 3 closed all previous open resources, before transitioning. 
D 2021-07-30T18:14:17.370884Z Partition 3 transition complete, installed 0 resources! 
D 2021-07-30T18:14:17.371320Z Closing Broker-1 partitions [3/3]: partition 3 closed in 17 ms 
I 2021-07-30T18:14:17.372071Z Closing Broker-1 partitions succeeded. Closed 3 steps in 73 ms. 
D 2021-07-30T18:14:17.372348Z Closing Broker-1 [3/14]: zeebe partitions closed in 73 ms 
I 2021-07-30T18:14:17.372642Z Closing Broker-1 [4/14]: leader management request handler 
D 2021-07-30T18:14:17.373209Z Closing Broker-1 [4/14]: leader management request handler closed in 1 ms 
I 2021-07-30T18:14:17.373475Z Closing Broker-1 [5/14]: disk space monitor 
D 2021-07-30T18:14:17.373823Z Closing Broker-1 [5/14]: disk space monitor closed in 0 ms 
I 2021-07-30T18:14:17.374092Z Closing Broker-1 [6/14]: monitoring services 
D 2021-07-30T18:14:17.374443Z Closing Broker-1 [6/14]: monitoring services closed in 0 ms 
I 2021-07-30T18:14:17.374666Z Closing Broker-1 [7/14]: embedded gateway 
D 2021-07-30T18:14:17.381770Z Closing gateway broker client ... 
D 2021-07-30T18:14:17.382596Z topology manager closed 
D 2021-07-30T18:14:17.383318Z Gateway broker client closed. 
D 2021-07-30T18:14:17.383588Z Closing Broker-1 [7/14]: embedded gateway closed in 9 ms 
I 2021-07-30T18:14:17.383856Z Closing Broker-1 [8/14]: topology manager 
D 2021-07-30T18:14:17.384321Z Closing Broker-1 [8/14]: topology manager closed in 0 ms 
I 2021-07-30T18:14:17.384571Z Closing Broker-1 [9/14]: cluster services 
D 2021-07-30T18:14:17.384848Z Closing Broker-1 [9/14]: cluster services closed in 0 ms 
I 2021-07-30T18:14:17.385128Z Closing Broker-1 [10/14]: subscription api 
D 2021-07-30T18:14:17.385614Z Closing Broker-1 [10/14]: subscription api closed in 0 ms 
I 2021-07-30T18:14:17.385835Z Closing Broker-1 [11/14]: command api handler 
D 2021-07-30T18:14:17.386754Z Closing Broker-1 [11/14]: command api handler closed in 0 ms 
I 2021-07-30T18:14:17.387083Z Closing Broker-1 [12/14]: command api transport 
I 2021-07-30T18:14:19.403164Z Stopped 
D 2021-07-30T18:14:19.403814Z Closing Broker-1 [12/14]: command api transport closed in 2016 ms 
I 2021-07-30T18:14:19.404259Z Closing Broker-1 [13/14]: membership and replication protocol 
I 2021-07-30T18:14:19.405693Z RaftServer{raft-partition-partition-3} - Transitioning to INACTIVE 
I 2021-07-30T18:14:19.406086Z RaftServer{raft-partition-partition-2} - Transitioning to INACTIVE 
I 2021-07-30T18:14:19.406112Z RaftServer{raft-partition-partition-1} - Transitioning to INACTIVE 
D 2021-07-30T18:14:19.408602Z Closing segment: JournalSegment{id=1, index=1} 
D 2021-07-30T18:14:19.408606Z Closing segment: JournalSegment{id=1, index=1} 
D 2021-07-30T18:14:19.408607Z Closing segment: JournalSegment{id=1, index=1} 
E 2021-07-30T18:14:19.409316Z RaftServer{raft-partition-partition-3} - Failed to close raft log 
E 2021-07-30T18:14:19.409319Z RaftServer{raft-partition-partition-1} - Failed to close raft log 
I 2021-07-30T18:14:19.411413605Z {} 
I 2021-07-30T18:14:19.412097Z Stopped 
I 2021-07-30T18:14:19.412387Z Stopped 
I 2021-07-30T18:14:19.412744Z Stopped 
I 2021-07-30T18:14:19.413916Z Stopped 
I 2021-07-30T18:14:19.414491Z 1 - Member deactivated: Member{id=1, address=zeebe-1.zeebe-broker-service.fe8fb0fb-bf8e-4302-896c-f7b7e29a9562-zeebe.svc.cluster.local:26502, properties={brokerInfo=EADJAAAAAwABAAAAAwAAAAMAAAADAAAAAAABCgAAAGNvbW1hbmRBcGlfAAAAemVlYmUtMS56ZWViZS1icm9rZXItc2VydmljZS5mZThmYjBmYi1iZjhlLTQzMDItODk2Yy1mN2I3ZTI5YTk1NjItemVlYmUuc3ZjLmNsdXN0ZXIubG9jYWw6MjY1MDEFAAMBAAAAAQIAAAABAwAAAAEMAAAMAAAAMS4xLjAtYWxwaGExBQADAQAAAAECAAAAAQMAAAAB, event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}} 
I 2021-07-30T18:14:19.415429Z Stopped 
I 2021-07-30T18:14:19.415985Z Left 
I 2021-07-30T18:14:19.416780Z Stopped 
W 2021-07-30T18:14:19.431952Z RaftServer{raft-partition-partition-2} - AppendRequest{term=480, leader=0, prevLogIndex=479, prevLogTerm=480, entries=0, commitIndex=479} to 1 failed: java.util.concurrent.CompletionException: io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message 
W 2021-07-30T18:14:19.432975Z RaftServer{raft-partition-partition-2} - AppendRequest{term=480, leader=0, prevLogIndex=479, prevLogTerm=480, entries=0, commitIndex=479} to 1 failed: java.util.concurrent.CompletionException: io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message 
W 2021-07-30T18:14:19.586100Z RaftServer{raft-partition-partition-1} - AppendRequest{term=484, leader=0, prevLogIndex=480, prevLogTerm=484, entries=0, commitIndex=480} to 1 failed: java.util.concurrent.CompletionException: io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message 
W 2021-07-30T18:14:19.587044Z RaftServer{raft-partition-partition-1} - AppendRequest{term=484, leader=0, prevLogIndex=480, prevLogTerm=484, entries=0, commitIndex=480} to 1 failed: java.util.concurrent.CompletionException: io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message 
W 2021-07-30T18:14:19.647896Z RaftServer{raft-partition-partition-3} - AppendRequest{term=480, leader=0, prevLogIndex=475, prevLogTerm=480, entries=0, commitIndex=475} to 1 failed: java.util.concurrent.CompletionException: io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message 
W 2021-07-30T18:14:19.648870Z RaftServer{raft-partition-partition-3} - AppendRequest{term=480, leader=0, prevLogIndex=475, prevLogTerm=480, entries=0, commitIndex=475} to 1 failed: java.util.concurrent.CompletionException: io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message 
W 2021-07-30T18:14:19.681763Z RaftServer{raft-partition-partition-2} - AppendRequest{term=480, leader=0, prevLogIndex=479, prevLogTerm=480, entries=0, commitIndex=479} to 1 failed: java.util.concurrent.CompletionException: io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message 
W 2021-07-30T18:14:19.836184Z RaftServer{raft-partition-partition-1} - AppendRequest{term=484, leader=0, prevLogIndex=480, prevLogTerm=484, entries=0, commitIndex=480} to 1 failed: java.util.concurrent.CompletionException: io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message 
W 2021-07-30T18:14:19.898068Z RaftServer{raft-partition-partition-3} - AppendRequest{term=480, leader=0, prevLogIndex=475, prevLogTerm=480, entries=0, commitIndex=475} to 1 failed: java.util.concurrent.CompletionException: io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message 
D 2021-07-30T18:14:20.738427Z Received REACHABILITY_CHANGED for broker 1, do nothing. 
I 2021-07-30T18:14:20.739133925Z {} 
D 2021-07-30T18:14:20.922811Z Received REACHABILITY_CHANGED for broker 1, do nothing. 
I 2021-07-30T18:14:20.923320325Z {} 
I 2021-07-30T18:14:23.434443Z Stopped 
I 2021-07-30T18:14:23.435407Z Stopped 
```

</p>
</details>

**Environment:**
Camunda Cloud; 1.1.0-alpha1

**Comment by pihme** [comment]
Broker is restarting constantly after that.

**Comment by npepinpe** [comment]
It's difficult to prioritize at the moment. One part is the error doesn't give us much, so hard to tell what's the underlying cause. But from the logs, it sounds like the broker was shutting down? If this is the only time it happens, then the severity would be low, as failing to synchronize/flush on shutdown is the equivalent of a torn write, which we can recover from gracefully.

Do we have any more info? Maybe the disk was full? We've seen these errors also happen when the disk is full. The other time was when changing the file permissions out-of-process, but I would expect we didn't do this here (though if this was on dev I suppose it could be someone fiddling with things).

**Comment by pihme** [comment]
Disk was not full. Other than that little additional info. Cluster has almost no traffic and is on dev stage. I would consider it low priority

**Comment by Zelldon** [comment]
Doesn't seem to occur for a long time, so I will close it for now
