### ISSUE TITLE
Completion exception on partition shutdown

### ISSUE THREAD

**Issue by pihme** [camunda/zeebe#7596]
**Describe the bug**
Observed in ultrachaos logs: https://console.cloud.google.com/errors/CNujqfHLua-oMw?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.util.concurrent.CompletionException: java.lang.InterruptedException
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
	at io.atomix.raft.impl.DefaultRaftServer.lambda$shutdown$2(DefaultRaftServer.java:137) ~[zeebe-atomix-cluster-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:174) ~[zeebe-atomix-utils-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source) ~[?:?]
	at io.camunda.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:133) ~[zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.FutureUtil.join(FutureUtil.java:32) ~[zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.future.CompletableActorFuture.join(CompletableActorFuture.java:201) ~[zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.Actor.close(Actor.java:65) ~[zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.broker.partitioning.PartitionManagerImpl.lambda$stop$1(PartitionManagerImpl.java:81) ~[zeebe-broker-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	... 11 more
```

</p>
</details>

**Environment:**
Camunda Cloud, Ultrachaos cluster; 1.2.0 SNAPSHOT

**Comment by pihme** [comment]
Virtually no impact; broker was able to restart thereafter. 

Also this was most likely part of a nightly QA run and the nightly QA run had no errors whatsoever.

**Comment by npepinpe** [comment]
Normally we would prioritize issues part of a milestone as planned, but for this one I would make an exception and leave it in the backlog, mostly because I suspect we won't actually spend time on this particular issue but more on the systemic cause, and it might simply get resolved through this. Let me know if you disagree :+1:

**Comment by Zelldon** [comment]
Haven't occurred for long time so I will close this
