### ISSUE TITLE
NPE on becoming leader  in medic CW42 benchmark

### ISSUE THREAD

**Issue by pihme** [camunda/zeebe#8041]
**Describe the bug**
Observed this in benchmark of CW42. NPE at various classes, presumably all related to the same root cause:
* CommandAPI https://console.cloud.google.com/errors/CK6N3tr5wZWOjwE?service=zeebe-broker&time=P7D&project=zeebe-io
* LeaderManagementRequestHandler https://console.cloud.google.com/errors/COrcqIrGkP217gE?service=zeebe-broker&time=P7D&project=zeebe-io
* SubscriptionApiCommandMessageHandler https://console.cloud.google.com/errors/CI7Lj-qK0dfZcg?service=zeebe-broker&time=P7D&project=zeebe-io
* QueryRequestHandler https://console.cloud.google.com/errors/CNzTm6ixkOznBw?service=zeebe-broker&time=P7D&project=zeebe-io

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
Leader Management Request Handler:

java.lang.NullPointerException: null
	at io.camunda.zeebe.broker.system.management.LeaderManagementRequestHandler.lambda$onBecomingLeader$2(LeaderManagementRequestHandler.java:79) ~[zeebe-broker-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) ~[zeebe-util-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:95) [zeebe-util-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:192) [zeebe-util-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]

Command API:

java.lang.NullPointerException: null
	at io.camunda.zeebe.broker.transport.commandapi.CommandApiServiceImpl.lambda$onBecomingLeader$2(CommandApiServiceImpl.java:104) ~[zeebe-broker-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorControl.lambda$call$0(ActorControl.java:136) ~[zeebe-util-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:62) ~[zeebe-util-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:95) [zeebe-util-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:192) [zeebe-util-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]


Subscription API:

java.lang.NullPointerException: null
	at io.camunda.zeebe.broker.engine.impl.SubscriptionApiCommandMessageHandlerService.lambda$onBecomingLeader$2(SubscriptionApiCommandMessageHandlerService.java:73) ~[zeebe-broker-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) ~[zeebe-util-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:95) [zeebe-util-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:192) [zeebe-util-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]

Query Request Handler:

java.lang.NullPointerException: value cannot be null
	at java.util.Objects.requireNonNull(Objects.java:246) ~[?:?]
	at org.agrona.collections.Int2ObjectHashMap.put(Int2ObjectHashMap.java:318) ~[agrona-1.12.0.jar:1.12.0]
	at org.agrona.collections.Int2ObjectHashMap.put(Int2ObjectHashMap.java:304) ~[agrona-1.12.0.jar:1.12.0]
	at org.agrona.collections.Int2ObjectHashMap.put(Int2ObjectHashMap.java:35) ~[agrona-1.12.0.jar:1.12.0]
	at io.camunda.zeebe.broker.transport.commandapi.QueryApiRequestHandler.lambda$addPartition$0(QueryApiRequestHandler.java:65) ~[zeebe-broker-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) ~[zeebe-util-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:95) [zeebe-util-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:192) [zeebe-util-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]

```

</p>
</details>

<details><summary>Log (ERROR and WARNING only)</summary>
 <p>

```
E 2021-10-21T08:45:15.475993Z medic-cw-42-11f5233fa-benchmark-zeebe-gateway-76bcc66d69-5h5zn Expected to handle gRPC request, but an unexpected error occurred  medic-cw-42-11f5233fa-benchmark-zeebe-gateway-76bcc66d69-5h5zn
E 2021-10-21T08:45:15.486121Z medic-cw-42-11f5233fa-benchmark-zeebe-gateway-76bcc66d69-5h5zn Expected to handle gRPC request, but an unexpected error occurred  medic-cw-42-11f5233fa-benchmark-zeebe-gateway-76bcc66d69-5h5zn
E 2021-10-21T08:45:15.496078Z medic-cw-42-11f5233fa-benchmark-zeebe-gateway-76bcc66d69-5h5zn Expected to handle gRPC request, but an unexpected error occurred  medic-cw-42-11f5233fa-benchmark-zeebe-gateway-76bcc66d69-5h5zn
W 2021-10-21T08:47:14.515877Z medic-cw-42-11f5233fa-benchmark-zeebe-0 Locations list is empty. No resources will be served unless a custom ResourceResolver is configured as an alternative to PathResourceResolver.  medic-cw-42-11f5233fa-benchmark-zeebe-0
W 2021-10-21T08:47:14.666192Z medic-cw-42-11f5233fa-benchmark-zeebe-1 Locations list is empty. No resources will be served unless a custom ResourceResolver is configured as an alternative to PathResourceResolver.  medic-cw-42-11f5233fa-benchmark-zeebe-1
W 2021-10-21T08:47:15.824051Z medic-cw-42-11f5233fa-benchmark-zeebe-2 Locations list is empty. No resources will be served unless a custom ResourceResolver is configured as an alternative to PathResourceResolver.  medic-cw-42-11f5233fa-benchmark-zeebe-2
W 2021-10-21T08:47:46.369452Z medic-cw-42-11f5233fa-benchmark-zeebe-0 RaftServer{raft-partition-partition-3}{role=FOLLOWER} - Poll request to 1 failed: io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message  medic-cw-42-11f5233fa-benchmark-zeebe-0
W 2021-10-21T08:47:46.370124Z medic-cw-42-11f5233fa-benchmark-zeebe-0 RaftServer{raft-partition-partition-3}{role=FOLLOWER} - Poll request to 2 failed: io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message  medic-cw-42-11f5233fa-benchmark-zeebe-0
W 2021-10-21T08:47:49.737813Z medic-cw-42-11f5233fa-benchmark-zeebe-0 RaftServer{raft-partition-partition-3}{role=FOLLOWER} - Poll request to 1 failed: io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message  medic-cw-42-11f5233fa-benchmark-zeebe-0
W 2021-10-21T08:47:51.218026Z medic-cw-42-11f5233fa-benchmark-zeebe-2 RaftServer{raft-partition-partition-3} - ConfigureRequest{term=6, leader=2, index=0, timestamp=1634546549451, members=[DefaultRaftMember{id=2, type=ACTIVE, updated=2021-10-18T08:42:29.451Z}, DefaultRaftMember{id=1, type=ACTIVE, updated=2021-10-18T08:42:29.451Z}, DefaultRaftMember{id=0, type=ACTIVE, updated=2021-10-18T08:42:29.451Z}]} to 1 failed: java.util.concurrent.CompletionException: io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message  medic-cw-42-11f5233fa-benchmark-zeebe-2
W 2021-10-21T08:47:51.224342Z medic-cw-42-11f5233fa-benchmark-zeebe-2 RaftServer{raft-partition-partition-3} - ConfigureRequest{term=6, leader=2, index=0, timestamp=1634546549451, members=[DefaultRaftMember{id=2, type=ACTIVE, updated=2021-10-18T08:42:29.451Z}, DefaultRaftMember{id=1, type=ACTIVE, updated=2021-10-18T08:42:29.451Z}, DefaultRaftMember{id=0, type=ACTIVE, updated=2021-10-18T08:42:29.451Z}]} to 1 failed: java.util.concurrent.CompletionException: io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message  medic-cw-42-11f5233fa-benchmark-zeebe-2
W 2021-10-21T08:47:51.226048Z medic-cw-42-11f5233fa-benchmark-zeebe-2 RaftServer{raft-partition-partition-3} - AppendRequest{term=6, leader=2, prevLogIndex=238233402, prevLogTerm=5, entries=0, commitIndex=0} to 1 failed: java.util.concurrent.CompletionException: io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message  medic-cw-42-11f5233fa-benchmark-zeebe-2
E 2021-10-21T08:47:58.746670Z medic-cw-42-11f5233fa-benchmark-zeebe-2 Uncaught exception in 'Broker-2-ManagementRequestHandler' in phase 'STARTED'. Continuing with next job.  medic-cw-42-11f5233fa-benchmark-zeebe-2
E 2021-10-21T08:47:58.747575Z medic-cw-42-11f5233fa-benchmark-zeebe-2 Uncaught exception in 'Broker-2-CommandApiService' in phase 'STARTED'. Continuing with next job.  medic-cw-42-11f5233fa-benchmark-zeebe-2
E 2021-10-21T08:47:58.753360Z medic-cw-42-11f5233fa-benchmark-zeebe-2 Uncaught exception in 'Broker-2-SubscriptionApi' in phase 'STARTED'. Continuing with next job.  medic-cw-42-11f5233fa-benchmark-zeebe-2
E 2021-10-21T08:47:58.753460Z medic-cw-42-11f5233fa-benchmark-zeebe-2 Uncaught exception in 'Broker-2-QueryApi' in phase 'STARTED'. Continuing with next job.  medic-cw-42-11f5233fa-benchmark-zeebe-2
E 2021-10-21T08:48:05.362970Z medic-cw-42-11f5233fa-benchmark-zeebe-0 Uncaught exception in 'Broker-0-ManagementRequestHandler' in phase 'STARTED'. Continuing with next job.  medic-cw-42-11f5233fa-benchmark-zeebe-0
E 2021-10-21T08:48:05.364630Z medic-cw-42-11f5233fa-benchmark-zeebe-0 Uncaught exception in 'Broker-0-CommandApiService' in phase 'STARTED'. Continuing with next job.  medic-cw-42-11f5233fa-benchmark-zeebe-0
E 2021-10-21T08:48:05.369744Z medic-cw-42-11f5233fa-benchmark-zeebe-0 Uncaught exception in 'Broker-0-SubscriptionApi' in phase 'STARTED'. Continuing with next job.  medic-cw-42-11f5233fa-benchmark-zeebe-0
E 2021-10-21T08:48:05.369748Z medic-cw-42-11f5233fa-benchmark-zeebe-0 Uncaught exception in 'Broker-0-QueryApi' in phase 'STARTED'. Continuing with next job.  medic-cw-42-11f5233fa-benchmark-zeebe-0

```

</p>
</details>

**Environment:**
 - medic benchmark CW 42

**Comment by korthout** [comment]
Seen again in `1.3.0-alpha1` on `02f1c338-5f14-4beb-9fe5-a0295a6fe6b8-zeebe` - [error1](https://console.cloud.google.com/errors/CNzTm6ixkOznBw?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911), [error2](https://console.cloud.google.com/errors/COrcqIrGkP217gE?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911), [error3](https://console.cloud.google.com/errors/CI7Lj-qK0dfZcg?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911)

**Comment by deepthidevaki** [comment]
Happened again
```
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.logstreams.log.LogStream.newLogStreamRecordWriter()" because "logStream" is null

        at io.camunda.zeebe.broker.transport.commandapi.CommandApiServiceImpl.lambda$onBecomingLeader$2 (CommandApiServiceImpl.java:104)
        at io.camunda.zeebe.util.sched.ActorControl.lambda$call$0 (ActorControl.java:136)
        at io.camunda.zeebe.util.sched.ActorJob.invoke (ActorJob.java:62)
        at io.camunda.zeebe.util.sched.ActorJob.execute (ActorJob.java:39)
        at io.camunda.zeebe.util.sched.ActorTask.execute (ActorTask.java:122)
        at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask (ActorThread.java:95)
        at io.camunda.zeebe.util.sched.ActorThread.doWork (ActorThread.java:78)
        at io.camunda.zeebe.util.sched.ActorThread.run (ActorThread.java:192)
```

It looks like we notify `onBecomingLeader` even if leader transition is cancelled.
[Logs](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2021-11-23T14%3A54%3A32.947968090Z&dateRangeStart=2021-11-23T13%3A55%3A05.106Z&dateRangeEnd=2021-11-23T15%3A55%3A05.106Z&project=camunda-cloud-240911&minLogLevel=0&customFacets=jsonPayload.context.partitionId&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.pod_name%3D%22zeebe-3%22%0Aresource.labels.cluster_name%3D%22integration-worker-1%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.namespace_name%3D%2245bd3eba-6974-4ae1-bf7a-14a817f97b80-zeebe%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Atimestamp%3D%222021-11-23T14%3A54%3A32.355762251Z%22%0AinsertId%3D%22coy1v3w72ru6muys%22&interval=JUMP_TO_TIME&scrollTimestamp=2021-11-23T14%3A54%3A32.355762251Z)

```
I 2021-11-23T14:54:32.354855713Z 3 Prepare transition from LEADER on term 23 to LEADER - preparing LogStorage  3
I 2021-11-23T14:54:32.355068851Z 3 Preparing transition from LEADER on term 23 completed  3
I 2021-11-23T14:54:32.355252707Z 3 Transition to LEADER on term 23 starting  3
I 2021-11-23T14:54:32.355405576Z 3 Cancelling transition to LEADER on term 23  3
I 2021-11-23T14:54:32.355629189Z 3 Prepare transition from FOLLOWER on term 24 to FOLLOWER  3
E 2021-11-23T14:54:32.355762251Z Uncaught exception in 'Broker-3-CommandApiService' in phase 'STARTED'. Continuing with next job.  
I 2021-11-23T14:54:32.355765626Z 3 Prepare transition from FOLLOWER on term 24 to FOLLOWER - preparing ExporterDirector  3
I 2021-11-23T14:54:32.355884073Z 3 Prepare transition from FOLLOWER on term 24 to FOLLOWER - preparing SnapshotDirector  3

```

**Comment by korthout** [comment]
Happened again in https://console.cloud.google.com/errors/detail/CKi6g4rY0dHFvAE;service=zeebe;time=P7D?project=camunda-saas-prod

**Comment by remcowesterhoud** [comment]
@npepinpe Ole kindly pointed out to me that the stack trace I linked is related to the Job Push topic. It might be same problem, different location. But I'd still wanted to make you aware of this.

I've put this back in the ZDP inbox for visibility.

**Comment by npepinpe** [comment]
It's very likely the same root cause :smile:

**Comment by megglos** [comment]
ZDP-Triage:
- @deepthidevaki : IIRC it's noise without functional impact, needs validation though. Assumption: one node is transitioning to leader but this gets canceled, this causes these NPEs to occur.
- putting back into backlog for later for now under this assumption


@remcowesterhoud did this cause any noticable interruption, required a restart or was it "just" noise?

**Comment by remcowesterhoud** [comment]
It was just noise
