### ISSUE TITLE
NPE when scheduling Actor to check pending process message subscriptions

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/zeebe#8642]
**Describe the bug**

A NullPointerException occurred when scheduling an actor to check for pending process message subscriptions in a 30 second interval.
```java
private void scheduleTimer() {
    if (timer == null) {
      timer = actor.runAtFixedRate(SUBSCRIPTION_CHECK_INTERVAL, this::checkPendingSubscriptions);
    }
  }
```
In this case actor was null. This seems to have occurred when the broker was being shutdown.

**To Reproduce**

Not tried. It seems to have happened by shutting down the cluster.

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.util.sched.ActorControl.runAtFixedRate(java.time.Duration, java.lang.Runnable)" because "this.actor" is null
	at io.camunda.zeebe.engine.processing.message.PendingProcessMessageSubscriptionChecker.scheduleTimer(PendingProcessMessageSubscriptionChecker.java:69) ~[zeebe-workflow-engine-1.3.0.jar:1.3.0]
	at io.camunda.zeebe.engine.processing.message.PendingProcessMessageSubscriptionChecker.onResumed(PendingProcessMessageSubscriptionChecker.java:64) ~[zeebe-workflow-engine-1.3.0.jar:1.3.0]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor.lambda$resumeProcessing$11(StreamProcessor.java:444) ~[zeebe-workflow-engine-1.3.0.jar:1.3.0]
	at io.camunda.zeebe.util.sched.ActorControl.lambda$call$0(ActorControl.java:136) ~[zeebe-util-1.3.0.jar:1.3.0]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:62) ~[zeebe-util-1.3.0.jar:1.3.0]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.3.0.jar:1.3.0]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.3.0.jar:1.3.0]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:95) [zeebe-util-1.3.0.jar:1.3.0]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.3.0.jar:1.3.0]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:192) [zeebe-util-1.3.0.jar:1.3.0] 
```

</p>
</details>

<details><summary>Surrounding logs</summary>
 <p>
https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.pod_name%3D%22zeebe-1%22%0Aresource.labels.namespace_name%3D%222d7cd1f4-2711-4f9c-8cf7-7b8d887970df-zeebe%22%0Aresource.labels.cluster_name%3D%22production-worker-1%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.location%3D%22europe-west1%22%0Alabels.%22k8s-pod%2Fstatefulset_kubernetes_io%2Fpod-name%22%3D%22zeebe-1%22%0Alabels.%22k8s-pod%2Fapp_kubernetes_io%2Fcomponent%22%3D%22gateway%22;timeRange=2022-01-24T18:30:34.458Z%2F2022-01-24T19:30:34.458Z;pinnedLogId=2022-01-24T19:00:04.458609818Z%2Fzsv4lnn1az3kwuxb;cursorTimestamp=2022-01-24T19:00:06.140812079Z?project=camunda-cloud-240911

```
Info 2022-01-24 20:00:04.243 CET zeebe"Prepare transition from FOLLOWER on term 26 to INACTIVE - preparing LogStorage"
Info 2022-01-24 20:00:04.243 CET zeebe"Preparing transition from FOLLOWER on term 26 completed"
Info 2022-01-24 20:00:04.243 CET zeebe"Transition to INACTIVE on term 26 starting"
Info 2022-01-24 20:00:04.243 CET zeebe"Transition to INACTIVE on term 26 - transitioning LogStorage"
Info 2022-01-24 20:00:04.243 CET zeebe"Transition to INACTIVE on term 26 - transitioning LogStream"
Info 2022-01-24 20:00:04.243 CET zeebe"Transition to INACTIVE on term 26 - transitioning ZeebeDb"
Info 2022-01-24 20:00:04.244 CET zeebe"Transition to INACTIVE on term 26 - transitioning QueryService"
Info 2022-01-24 20:00:04.244 CET zeebe"Transition to INACTIVE on term 26 - transitioning StreamProcessor"
Info 2022-01-24 20:00:04.244 CET zeebe"Transition to INACTIVE on term 26 - transitioning SnapshotDirector"
Info 2022-01-24 20:00:04.244 CET zeebe"Transition to INACTIVE on term 26 - transitioning ExporterDirector"
Info 2022-01-24 20:00:04.244 CET zeebe"Transition to INACTIVE on term 26 completed"
Debug 2022-01-24 20:00:04.245 CET zeebe"Shutdown was called with context: io.camunda.zeebe.broker.system.partitions.PartitionStartupAndTransitionContextImpl@6b186dc6"
Info 2022-01-24 20:00:04.245 CET zeebe"Shutdown RocksDB metric timer"
Info 2022-01-24 20:00:04.245 CET zeebe"Shutdown LogDeletionService"
Debug 2022-01-24 20:00:04.246 CET zeebe"Finished shutdown process"
Debug 2022-01-24 20:00:04.357 CET zeebe"Closed database from '/usr/local/zeebe/data/raft-partition/partitions/2/runtime'."
Debug 2022-01-24 20:00:04.426 CET zeebe"Received metadata change from Broker 1, partitions {1=FOLLOWER, 2=FOLLOWER}, terms {} and health {1=UNHEALTHY, 2=UNHEALTHY}."
Debug 2022-01-24 20:00:04.440 CET zeebe"Configured log appender back pressure at partition 1 as AppenderVegasCfg{initialLimit=1024, maxConcurrency=32768, alphaLimit=0.7, betaLimit=0.95}. Window limiting is disabled"
Debug 2022-01-24 20:00:04.441 CET zeebe"Recovering state of partition 1 from snapshot"
Info 2022-01-24 20:00:04.442 CET zeebe"Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@72f68c0)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@7d7a19fa, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@57013eea, configuration: Configuration(false)]"
Info 2022-01-24 20:00:04.444 CET zeebe"Recovered state of partition 1 from snapshot at position -1"
Info 2022-01-24 20:00:04.444 CET zeebe"Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@1c5b8eb)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@7dd0b97b, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@5048caf2, configuration: Configuration(false)]"
Info 2022-01-24 20:00:04.445 CET zeebe"Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@ee0587f)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@22cebba8, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@5a2dc5eb, configuration: Configuration(false)]"
Info 2022-01-24 20:00:04.446 CET zeebe"Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@4c249b06)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@400b015d, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@174ff10f, configuration: Configuration(false)]"
Info 2022-01-24 20:00:04.448 CET zeebe"Processor starts replay of events. [snapshot-position: -1, replay-mode: PROCESSING]"
Debug 2022-01-24 20:00:04.448 CET zeebe"Detected 'HEALTHY' components. The current health status of components: [raft-partition-partition-1{status=HEALTHY}, Broker-1-LogStream-1{status=HEALTHY}, Broker-1-StreamProcessor-1{status=HEALTHY}]"
Info 2022-01-24 20:00:04.448 CET zeebe"Processor finished replay, with [lastProcessedPosition: -1, lastWrittenPosition: -1]"
Info 2022-01-24 20:00:04.448 CET zeebe"Cancelling transition to LEADER on term 28"
Debug 2022-01-24 20:00:04.451 CET zeebe"Paused processing for partition 1"
Error 2022-01-24 20:00:04.458 CET zeebe"Actor Broker-1-StreamProcessor-1 failed in phase STARTED."
```

</p>
</details>

**Environment:**
 - OS: Camunda Cloud
 - Zeebe Version: 1.3.0
 - Cluster: 2d7cd1f4-2711-4f9c-8cf7-7b8d887970df (cluster is not available anymore)

**Comment by npepinpe** [comment]
As this seemed to occur only in shutdown, the impact was quite minimal. I would still expect the actor control to always be set, but I'll double check to see if it makes sense, and if not we can reprioritize.
