### ISSUE TITLE
ClusteredSnapshotTest.shouldKeepIndexAndTerm

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#8669]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? Once
- Does it block your work? Failed on my PR
- Do we suspect that it is a real failure? Yes

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
[ERROR] Tests run: 12, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 660.709 s <<< FAILURE! - in io.camunda.zeebe.it.clustering.ClusteredSnapshotTest

[2022-01-26T12:55:30.912Z] [ERROR] ClusteredSnapshotTest.shouldKeepIndexAndTerm  Time elapsed: 310.693 s  <<< ERROR!

[2022-01-26T12:55:30.912Z] java.util.concurrent.CompletionException: java.util.concurrent.ExecutionException: Shutdown failed in the following steps: [Partition Manager]. See suppressed exceptions for details.

[2022-01-26T12:55:30.912Z] 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)

[2022-01-26T12:55:30.912Z] 	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:761)

[2022-01-26T12:55:30.912Z] 	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)

[2022-01-26T12:55:30.912Z] 	at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2182)

[2022-01-26T12:55:30.912Z] 	at io.camunda.zeebe.broker.Broker.lambda$close$1(Broker.java:168)

[2022-01-26T12:55:30.912Z] 	at io.camunda.zeebe.util.LogUtil.doWithMDC(LogUtil.java:23)

[2022-01-26T12:55:30.912Z] 	at io.camunda.zeebe.broker.Broker.close(Broker.java:163)

[2022-01-26T12:55:30.912Z] 	at zeebe.qa.integration.tests@1.4.0-SNAPSHOT/io.camunda.zeebe.it.clustering.ClusteringRule.stopBroker(ClusteringRule.java:653)

[2022-01-26T12:55:30.912Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

[2022-01-26T12:55:30.912Z] 	at zeebe.qa.integration.tests@1.4.0-SNAPSHOT/io.camunda.zeebe.it.clustering.ClusteringRule.restartCluster(ClusteringRule.java:528)

[2022-01-26T12:55:30.912Z] 	at zeebe.qa.integration.tests@1.4.0-SNAPSHOT/io.camunda.zeebe.it.clustering.ClusteredSnapshotTest.restartCluster(ClusteredSnapshotTest.java:282)

[2022-01-26T12:55:30.912Z] 	at zeebe.qa.integration.tests@1.4.0-SNAPSHOT/io.camunda.zeebe.it.clustering.ClusteredSnapshotTest.shouldKeepIndexAndTerm(ClusteredSnapshotTest.java:166)

[2022-01-26T12:55:30.912Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[2022-01-26T12:55:30.912Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)

[2022-01-26T12:55:30.912Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[2022-01-26T12:55:30.912Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)

[2022-01-26T12:55:30.912Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)

[2022-01-26T12:55:30.912Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

[2022-01-26T12:55:30.912Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)

[2022-01-26T12:55:30.912Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)

[2022-01-26T12:55:30.912Z] 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)

[2022-01-26T12:55:30.912Z] 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)

[2022-01-26T12:55:30.912Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)

[2022-01-26T12:55:30.912Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)

[2022-01-26T12:55:30.912Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)

[2022-01-26T12:55:30.912Z] 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)

[2022-01-26T12:55:30.912Z] 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)

[2022-01-26T12:55:30.912Z] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)

[2022-01-26T12:55:30.912Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)

[2022-01-26T12:55:30.912Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)

[2022-01-26T12:55:30.912Z] 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)

[2022-01-26T12:55:30.912Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)

[2022-01-26T12:55:30.912Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)

[2022-01-26T12:55:30.913Z] 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)

[2022-01-26T12:55:30.913Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)

[2022-01-26T12:55:30.913Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)

[2022-01-26T12:55:30.913Z] 	at org.junit.runners.Suite.runChild(Suite.java:128)

[2022-01-26T12:55:30.913Z] 	at org.junit.runners.Suite.runChild(Suite.java:27)

[2022-01-26T12:55:30.913Z] 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)

[2022-01-26T12:55:30.913Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)

[2022-01-26T12:55:30.913Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)

[2022-01-26T12:55:30.913Z] 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)

[2022-01-26T12:55:30.913Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)

[2022-01-26T12:55:30.913Z] 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)

[2022-01-26T12:55:30.913Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)

[2022-01-26T12:55:30.913Z] 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)

[2022-01-26T12:55:30.913Z] 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)

[2022-01-26T12:55:30.913Z] 	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)

[2022-01-26T12:55:30.913Z] 	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)

[2022-01-26T12:55:30.913Z] 	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)

[2022-01-26T12:55:30.913Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)

[2022-01-26T12:55:30.913Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)

[2022-01-26T12:55:30.913Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)

[2022-01-26T12:55:30.913Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)

[2022-01-26T12:55:30.913Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)

[2022-01-26T12:55:30.913Z] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)

[2022-01-26T12:55:30.913Z] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)

[2022-01-26T12:55:30.913Z] 	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)

[2022-01-26T12:55:30.913Z] 	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)

[2022-01-26T12:55:30.913Z] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.lambda$execute$1(JUnitPlatformProvider.java:199)

[2022-01-26T12:55:30.913Z] 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)

[2022-01-26T12:55:30.913Z] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:193)

[2022-01-26T12:55:30.913Z] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)

[2022-01-26T12:55:30.913Z] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:120)

[2022-01-26T12:55:30.913Z] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)

[2022-01-26T12:55:30.913Z] 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)

[2022-01-26T12:55:30.913Z] 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)

[2022-01-26T12:55:30.913Z] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)

[2022-01-26T12:55:30.913Z] Caused by: java.util.concurrent.ExecutionException: Shutdown failed in the following steps: [Partition Manager]. See suppressed exceptions for details.

[2022-01-26T12:55:30.913Z] 	at io.camunda.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:141)

[2022-01-26T12:55:30.913Z] 	at io.camunda.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:108)

[2022-01-26T12:55:30.913Z] 	at io.camunda.zeebe.util.sched.FutureUtil.join(FutureUtil.java:21)

[2022-01-26T12:55:30.913Z] 	at io.camunda.zeebe.util.sched.future.CompletableActorFuture.join(CompletableActorFuture.java:196)

[2022-01-26T12:55:30.913Z] 	at io.camunda.zeebe.broker.Broker.lambda$close$0(Broker.java:170)

[2022-01-26T12:55:30.913Z] 	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757)

[2022-01-26T12:55:30.913Z] 	... 66 more

[2022-01-26T12:55:30.913Z] Caused by: io.camunda.zeebe.util.startup.StartupProcessException: Shutdown failed in the following steps: [Partition Manager]. See suppressed exceptions for details.

[2022-01-26T12:55:30.913Z] 	at io.camunda.zeebe.util.startup.StartupProcess.aggregateExceptionsSynchronized(StartupProcess.java:282)

[2022-01-26T12:55:30.913Z] 	at io.camunda.zeebe.util.startup.StartupProcess.completeShutdownFutureSynchronized(StartupProcess.java:265)

[2022-01-26T12:55:30.913Z] 	at io.camunda.zeebe.util.startup.StartupProcess.proceedWithShutdownSynchronized(StartupProcess.java:230)

[2022-01-26T12:55:30.913Z] 	at io.camunda.zeebe.util.startup.StartupProcess.lambda$proceedWithShutdownSynchronized$6(StartupProcess.java:250)

[2022-01-26T12:55:30.913Z] 	at io.camunda.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28)

[2022-01-26T12:55:30.913Z] 	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:82)

[2022-01-26T12:55:30.913Z] 	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:44)

[2022-01-26T12:55:30.913Z] 	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122)

[2022-01-26T12:55:30.913Z] 	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97)

[2022-01-26T12:55:30.913Z] 	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80)

[2022-01-26T12:55:30.914Z] 	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189)

[2022-01-26T12:55:30.914Z] 	Suppressed: io.camunda.zeebe.util.startup.StartupProcessStepException: Bootstrap step Partition Manager failed

[2022-01-26T12:55:30.914Z] 		at io.camunda.zeebe.util.startup.StartupProcess.lambda$proceedWithShutdownSynchronized$6(StartupProcess.java:244)

[2022-01-26T12:55:30.914Z] 		at io.camunda.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:33)

[2022-01-26T12:55:30.914Z] 		... 6 more

[2022-01-26T12:55:30.914Z] 	Caused by: java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException: Timeout after: 300 SECONDS

[2022-01-26T12:55:30.914Z] 		at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)

[2022-01-26T12:55:30.914Z] 		at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)

[2022-01-26T12:55:30.914Z] 		at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)

[2022-01-26T12:55:30.914Z] 		at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)

[2022-01-26T12:55:30.914Z] 		at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)

[2022-01-26T12:55:30.914Z] 		at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)

[2022-01-26T12:55:30.914Z] 		at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)

[2022-01-26T12:55:30.914Z] 		at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)

[2022-01-26T12:55:30.914Z] 		at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

[2022-01-26T12:55:30.914Z] 	Caused by: java.util.concurrent.TimeoutException: Timeout after: 300 SECONDS

[2022-01-26T12:55:30.914Z] 		at io.camunda.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:131)

[2022-01-26T12:55:30.914Z] 		at io.camunda.zeebe.util.sched.FutureUtil.join(FutureUtil.java:32)

[2022-01-26T12:55:30.914Z] 		at io.camunda.zeebe.util.sched.future.CompletableActorFuture.join(CompletableActorFuture.java:201)

[2022-01-26T12:55:30.914Z] 		at io.camunda.zeebe.util.sched.Actor.close(Actor.java:96)

[2022-01-26T12:55:30.914Z] 		at io.camunda.zeebe.broker.partitioning.PartitionManagerImpl.stopPartition(PartitionManagerImpl.java:211)

[2022-01-26T12:55:30.914Z] 		at io.camunda.zeebe.broker.partitioning.PartitionManagerImpl.lambda$stopPartitions$6(PartitionManagerImpl.java:203)

[2022-01-26T12:55:30.914Z] 		at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)

[2022-01-26T12:55:30.914Z] 		... 6 more

[2022-01-26T12:55:30.914Z] 

[2022-01-26T12:55:30.914Z] [INFO] Running io.camunda.zeebe.it.clustering.ClusteredSnapshotTest

[2022-01-26T12:56:27.161Z] [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 56.547 s - in io.camunda.zeebe.it.clustering.ClusteredSnapshotTest

[2022-01-26T12:56:27.161Z] [INFO] 

[2022-01-26T12:56:27.161Z] [INFO] Results:

[2022-01-26T12:56:27.161Z] [INFO] 

[2022-01-26T12:56:27.161Z] [WARNING] Flakes: 

[2022-01-26T12:56:27.161Z] [WARNING] ClusteredSnapshotTest.shouldKeepIndexAndTerm

[2022-01-26T12:56:27.161Z] [INFO]   Run 1: PASS

[2022-01-26T12:56:27.161Z] [ERROR]   Run 2: java.util.concurrent.ExecutionException: Shutdown failed in the following steps: [Partition Manager]. See suppressed exceptions for details.

[2022-01-26T12:56:27.161Z] [INFO]   Run 3: PASS

[2022-01-26T12:56:27.161Z] [INFO] 

[2022-01-26T12:56:27.161Z] [INFO] 
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

IDK

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

Unfortunately the logs can't be read.

```
Stacktrace
Failed to read test report file /home/jenkins/agent/workspace/be_zell-8644-flaky-exporter-test/qa/integration-tests/target/failsafe-reports/TEST-io.camunda.zeebe.it.clustering.ClusteredSnapshotTest-it-testrun.xml
org.dom4j.DocumentException: Error on line 193 of document  : XML document structures must start and end within the same entity.
	at org.dom4j.io.SAXReader.read(SAXReader.java:511)
	at org.dom4j.io.SAXReader.read(SAXReader.java:392)
	at hudson.tasks.junit.SuiteResult.parse(SuiteResult.java:177)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:378)
	at hudson.tasks.junit.TestResult.parsePossiblyEmpty(TestResult.java:308)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:224)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:196)
	at hudson.tasks.junit.TestResult.<init>(TestResult.java:151)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:146)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3329)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:376)
	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:122)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.xml.sax.SAXParseException; lineNumber: 193; columnNumber: 28; XML document structures must start and end within the same entity.
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.endEntity(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.endEntity(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.endEntity(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.scanData(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanCDATASection(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.dom4j.io.SAXReader.read(SAXReader.java:494)
	... 18 more
```

**Comment by Zelldon** [comment]
The tests are so slow :snail: Takes 2 minutes to execute both (explicit trigger snapshot / implicit snapshot by advancing clock).

I run them now 33 times (~33 min) I will keep that until I reach 1 hour. If I see no failure I will close this issue. We can reopen it if it appears again.

**Comment by Zelldon** [comment]
pics or didn't happen 
![runs](https://user-images.githubusercontent.com/2758593/153549889-42af5566-8c94-471f-ad70-7f14e223a42e.png)

**Comment by Zelldon** [comment]
Seems to appear again https://github.com/camunda/zeebe/actions/runs/3129706396/jobs/5079122042

**Comment by deepthidevaki** [comment]
I'm not able to reproduce this. I have added some more logs to the test. Please report and share the logs, if you see this flaky test again.
