### ISSUE TITLE
`LongPollingActivateJobsTest.shouldUnblockRequestWhenJobsAvailable` is flaky

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#8671]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? At least once in this PR: https://github.com/camunda-cloud/zeebe/pull/8614
- Does it block your work? No
- Do we suspect that it is a real failure? Not sure

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Wanted but not invoked:
serverStreamObserver.onCompleted();
-> at io.camunda.zeebe.gateway.api.job.LongPollingActivateJobsTest.shouldUnblockRequestWhenJobsAvailable(LongPollingActivateJobsTest.java:119)
However, there were exactly 4 interactions with this mock:
serverStreamObserver.isCancelled();
-> at io.camunda.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.isCanceled(LongPollingActivateJobsRequest.java:113)
serverStreamObserver.isCancelled();
-> at io.camunda.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.isCanceled(LongPollingActivateJobsRequest.java:113)
serverStreamObserver.isCancelled();
-> at io.camunda.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.isCanceled(LongPollingActivateJobsRequest.java:113)
serverStreamObserver.onNext(
    jobs {
  key: 4503599627370496
  type: "test"
  processInstanceKey: 123
  bpmnProcessId: "stubProcess"
  processDefinitionVersion: 23
  processDefinitionKey: 4532
  elementId: "stubActivity"
  elementInstanceKey: 459
  customHeaders: "{\"foo\":12,\"bar\":\"val\"}"
  retries: 12
  deadline: 123123123
  variables: "{\"foo\":13,\"bar\":\"world\"}"
}
);
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
Wanted but not invoked:
serverStreamObserver.onCompleted();
-> at io.camunda.zeebe.gateway.api.job.LongPollingActivateJobsTest.shouldUnblockRequestWhenJobsAvailable(LongPollingActivateJobsTest.java:119)
However, there were exactly 4 interactions with this mock:
serverStreamObserver.isCancelled();
-> at io.camunda.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.isCanceled(LongPollingActivateJobsRequest.java:113)
serverStreamObserver.isCancelled();
-> at io.camunda.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.isCanceled(LongPollingActivateJobsRequest.java:113)
serverStreamObserver.isCancelled();
-> at io.camunda.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.isCanceled(LongPollingActivateJobsRequest.java:113)
serverStreamObserver.onNext(
    jobs {
  key: 4503599627370496
  type: "test"
  processInstanceKey: 123
  bpmnProcessId: "stubProcess"
  processDefinitionVersion: 23
  processDefinitionKey: 4532
  elementId: "stubActivity"
  elementInstanceKey: 459
  customHeaders: "{\"foo\":12,\"bar\":\"val\"}"
  retries: 12
  deadline: 123123123
  variables: "{\"foo\":13,\"bar\":\"world\"}"
}
);
-> at io.camunda.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.onResponse(LongPollingActivateJobsRequest.java:88)
	at io.camunda.zeebe.gateway.api.job.LongPollingActivateJobsTest.shouldUnblockRequestWhenJobsAvailable(LongPollingActivateJobsTest.java:119)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.lambda$execute$1(JUnitPlatformProvider.java:199)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:193)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
Standard Output
14:09:30.855 [main] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-fs-workers'
14:09:30.856 [-zb-fs-workers-0] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-fs-workers': closed successfully
14:09:30.857 [main] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-actors'
14:09:30.859 [-zb-actors-11] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-actors': closed successfully
</pre>
</details>

**Comment by korthout** [comment]
Next to this test, I also saw LongPollingActivateJobsTest.shouldUseLargeRequestTimeout [being unstable](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1831/pipeline).

**Comment by Zelldon** [comment]
Unstable or bugs hiding :bug: :thinking:
