### ISSUE TITLE
Pipeline fails org.apache.maven.surefire.booter.SurefireBooterForkException

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#8758]
**Description**
```
[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1120)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1121)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1122)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1123)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1124)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1125)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1126)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1127)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1128)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1129)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1130)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1131)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1132)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1133)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1134)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1135)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1136)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1137)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1138)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1139)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1140)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1141)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1142)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1143)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1144)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1145)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1146)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1147)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1148)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1149)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1150)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1151)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1152)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1153)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1154)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1155)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1156)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1157)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1158)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1159)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1160)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1161)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1162)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1163)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1164)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1165)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1166)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1167)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1168)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1169)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1170)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1171)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1172)[](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline#step-181-log-1173)[2022-02-10T05:27:10.094Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project zeebe-workflow-engine: There are test failures.

[2022-02-10T05:27:10.095Z] [ERROR] 

[2022-02-10T05:27:10.095Z] [ERROR] Please refer to /home/jenkins/agent/workspace/camunda-cloud_zeebe_staging/engine/target/surefire-reports for the individual test results.

[2022-02-10T05:27:10.095Z] [ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.

[2022-02-10T05:27:10.095Z] [ERROR] ExecutionException Error creating properties files for forking

[2022-02-10T05:27:10.095Z] [ERROR] ExecutionException Error creating properties files for forking

[2022-02-10T05:27:10.095Z] [ERROR] ExecutionException Error creating properties files for forking

[2022-02-10T05:27:10.095Z] [ERROR] ExecutionException Error creating properties files for forking

[2022-02-10T05:27:10.095Z] [ERROR] ExecutionException Error creating properties files for forking

[2022-02-10T05:27:10.095Z] [ERROR] ExecutionException Error creating properties files for forking

[2022-02-10T05:27:10.095Z] [ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: ExecutionException Error creating properties files for forking

[2022-02-10T05:27:10.095Z] [ERROR] ExecutionException Error creating properties files for forking

[2022-02-10T05:27:10.095Z] [ERROR] ExecutionException Error creating properties files for forking

[2022-02-10T05:27:10.095Z] [ERROR] ExecutionException Error creating properties files for forking

[2022-02-10T05:27:10.095Z] [ERROR] ExecutionException Error creating properties files for forking

[2022-02-10T05:27:10.095Z] [ERROR] ExecutionException Error creating properties files for forking

[2022-02-10T05:27:10.095Z] [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.awaitResultsDone(ForkStarter.java:532)

[2022-02-10T05:27:10.095Z] [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.runSuitesForkOnceMultiple(ForkStarter.java:405)

[2022-02-10T05:27:10.095Z] [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:321)

[2022-02-10T05:27:10.095Z] [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:266)

[2022-02-10T05:27:10.095Z] [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1314)

[2022-02-10T05:27:10.095Z] [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1159)

[2022-02-10T05:27:10.095Z] [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:932)

[2022-02-10T05:27:10.095Z] [ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)

[2022-02-10T05:27:10.095Z] [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)

[2022-02-10T05:27:10.095Z] [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)

[2022-02-10T05:27:10.095Z] [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)

[2022-02-10T05:27:10.095Z] [ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)

[2022-02-10T05:27:10.095Z] [ERROR] 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)

[2022-02-10T05:27:10.095Z] [ERROR] 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:186)

[2022-02-10T05:27:10.095Z] [ERROR] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

[2022-02-10T05:27:10.095Z] [ERROR] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)

[2022-02-10T05:27:10.095Z] [ERROR] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

[2022-02-10T05:27:10.095Z] [ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)

[2022-02-10T05:27:10.095Z] [ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)

[2022-02-10T05:27:10.095Z] [ERROR] 	at java.base/java.lang.Thread.run(Thread.java:833)

[2022-02-10T05:27:10.095Z] [ERROR] Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: Error creating properties files for forking

[2022-02-10T05:27:10.095Z] [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:604)

[2022-02-10T05:27:10.095Z] [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.access$700(ForkStarter.java:121)

[2022-02-10T05:27:10.095Z] [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter$1.call(ForkStarter.java:393)

[2022-02-10T05:27:10.095Z] [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter$1.call(ForkStarter.java:370)

[2022-02-10T05:27:10.095Z] [ERROR] 	... 4 more

[2022-02-10T05:27:10.095Z] [ERROR] Caused by: java.io.IOException: No such file or directory

[2022-02-10T05:27:10.095Z] [ERROR] 	at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)

[2022-02-10T05:27:10.095Z] [ERROR] 	at java.base/java.io.File.createTempFile(File.java:2170)

[2022-02-10T05:27:10.095Z] [ERROR] 	at org.apache.maven.surefire.booter.SystemPropertyManager.writePropertiesFile(SystemPropertyManager.java:77)

[2022-02-10T05:27:10.095Z] [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.BooterSerializer.serialize(BooterSerializer.java:187)

[2022-02-10T05:27:10.095Z] [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:585)

[2022-02-10T05:27:10.095Z] [ERROR] 	... 7 more

[2022-02-10T05:27:10.095Z] [ERROR] -> [Help 1]

[2022-02-10T05:27:10.095Z] [ERROR] 

[2022-02-10T05:27:10.095Z] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.

[2022-02-10T05:27:10.095Z] [ERROR] Re-run Maven using the -X switch to enable full debug logging.

[2022-02-10T05:27:10.096Z] [ERROR] 

[2022-02-10T05:27:10.096Z] [ERROR] For more information about the errors and possible solutions, please read the following ar
```

https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1797/pipeline

**Comment by npepinpe** [comment]
Seems to be happening more frequently :thinking:

**Comment by npepinpe** [comment]
Ole had a good idea, if `/tmp` is mounted as `tmpfs`, then you may run out of "disk space" if you were actually out of memory, preventing Surefire from creating this file.

**Comment by npepinpe** [comment]
OK, I think I might know what's going on. Since we have multiple stages running in parallel, multiple parent maven processes will create child forks in parallel, and they might be interfering with each other as they all operate on the same workspace. You can see the error doesn't happen in the IT stage since there we only have one maven process (with children, but still from the same parent process coordinating it all).

I'm not 100% sure though, because looking at their code, the file should still be somewhat unique, even if it generates on with the same prefix in the same directory, there should be some random suffix. I don't know how random though, so maybe there are collisions sometimes?

This is the line which creates the file/fails: https://github.com/apache/maven-surefire/blob/959c1e9cabb8d06c72f5ebd7eb6e56e9987eccf8/maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/booterclient/ForkStarter.java#L576

So either there are collisions, or somehow those files are cleaned up between runs? We could try tentatively with a different tmpdir, I suppose, or just point tmpdir to /tmp (which is a fallback on some platforms).

**Comment by npepinpe** [comment]
I'm adding this to the GHA KR, as we can close this once we've migrated off Jenkins.
