### ISSUE TITLE
IOException: Duplicate accept detected.

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#9016]
**Describe the bug**

Following error is logged:

```
java.io.IOException: Duplicate accept detected. This is a known OS bug. Please consider reporting that you are affected: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1924298
```

I see no evidence that it impacts the running system. At this time Zeebe-0 was restarted, but the log happened on Zeebe-1.

![general](https://user-images.githubusercontent.com/2758593/160583132-a11d8055-7788-42b6-a7c4-d017077d57d9.png)
![log](https://user-images.githubusercontent.com/2758593/160583135-4c3e4211-9f7b-4bd1-85ce-f956e5a8a5ac.png)

Error group:

https://console.cloud.google.com/errors/detail/CP6quOyVvdzu6AE;service=zeebe;time=P7D?project=camunda-cloud-240911

Related to 

 * https://github.com/spring-projects/spring-framework/issues/26434#issuecomment-1047599788
 * https://stackoverflow.com/questions/70937492/tomcat-ioexception-duplicate-accept-detected-this-is-a-known-os-bug-please-co
 * https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1924298

**To Reproduce**

Idk

**Expected behavior**

I just report this for visibility, I currently have no evidence that the system is impacted.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.io.IOException: Duplicate accept detected. This is a known OS bug. Please consider reporting that you are affected: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1924298
	at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:548) ~[tomcat-embed-core-9.0.58.jar:9.0.58]
	at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:78) ~[tomcat-embed-core-9.0.58.jar:9.0.58]
	at org.apache.tomcat.util.net.Acceptor.run(Acceptor.java:129) [tomcat-embed-core-9.0.58.jar:9.0.58]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

</p>
</details>

**Environment:**
- OS: k8/ubuntu
- Zeebe Version: 1.3.6
- Configuration: ClusterPlan: [G2-S](https://console.cloud.ultrawombat.com/admin/cluster-plan/plans/cca16c82-6156-4b17-a646-af9baf182cdf)

**Comment by npepinpe** [comment]
Assumption is this is fixed with the Spring dependency update in 1.3.7.
