### ISSUE TITLE
zeebe cannot downgrade

### ISSUE THREAD

**Issue by jerry123888** [camunda/zeebe#9160]
**Description:**

Environment:
PARTITIONSCOUNT=9
BROKER_CLUSTER_CLUSTERSIZE=3

Step1: set up zeebe for 1.2.4 and test a demo ---> work well
Step2: update zeebe-broker and zeebe-gateway  from 1.2.4 to 1.3.7,and then test a demo running --->  work well
Step3: downgrade from 1.3.7 to 1.2.4 --->broker startup failed, and can start successfully by upgrading  to 1.3.7.

The error message like this:
2022-04-18T03:01:42.225172955Z [2022-04-18 03:01:42.224]|Broker-2-SnapshotStore-9|Broker-2-zb-fs-workers-3|WARN|io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore|Expected snapshot /usr/local/zeebe/data/raft-partition/partitions/9/snapshots/735444-4-892363-892374 to have checksum 4260498054914973801, but the actual checksum is 3587756779; the snapshot is most likely corrupted. The startup will fail if there is no other valid snapshot and the log has been compacted.
2022-04-18T03:01:42.450060078Z [2022-04-18 03:01:42.441]||main|ERROR|io.camunda.zeebe.broker.system|Bootstrap Broker-2 [7/9]: zeebe partitions failed with unexpected exception.
2022-04-18T03:01:42.450082261Z java.lang.IllegalStateException: Expected to find a snapshot at index >= log's first index 685973, but found snapshot 0. A previous snapshot is most likely corrupted.
2022-04-18T03:01:42.450085216Z 	at io.atomix.raft.impl.RaftContext.verifySnapshotLogConsistent(RaftContext.java:222) ~[zeebe-atomix-cluster-1.2.4.jar:1.2.4]
2022-04-18T03:01:42.450087421Z 	at io.atomix.raft.impl.RaftContext.<init>(RaftContext.java:199) ~[zeebe-atomix-cluster-1.2.4.jar:1.2.4]
2022-04-18T03:01:42.450089725Z 	at io.atomix.raft.impl.DefaultRaftServer$Builder.build(DefaultRaftServer.java:258) ~[zeebe-atomix-cluster-1.2.4.jar:1.2.4]

![image](https://user-images.githubusercontent.com/92800459/163771938-0b3b6cb6-2ae8-4d18-8b69-4141ddb428d5.png)

**Comment by npepinpe** [comment]
Hi, in general you cannot downgrade Zeebe on major or minor versions. While it's sometimes possible, you should assume it's not. For major versions, it's simply that there are likely breaking changes upgrading already, so downgrading will have a similar effect. On minor versions, it's that newer versions may have new features (e.g. new BPMN symbol support) which an older broker would not know how to process or use.

Hope that makes sense!

**Comment by jerry123888** [comment]
> Hi, in general you cannot downgrade Zeebe on major or minor versions. While it's sometimes possible, you should assume it's not. For major versions, it's simply that there are likely breaking changes upgrading already, so downgrading will have a similar effect. On minor versions, it's that newer versions may have new features (e.g. new BPMN symbol support) which an older broker would not know how to process or use.
> 
> Hope that makes sense!

OK! I see. Thanks

**Comment by jerry123888** [comment]
> Hi, in general you cannot downgrade Zeebe on major or minor versions. While it's sometimes possible, you should assume it's not. For major versions, it's simply that there are likely breaking changes upgrading already, so downgrading will have a similar effect. On minor versions, it's that newer versions may have new features (e.g. new BPMN symbol support) which an older broker would not know how to process or use.
> 
> Hope that makes sense!

But... I update zeebe from 1.2.4 to 1.3.7 in local, in the process, someone is 1.2.4,and othes are 1.3.7 in the same zeebe cluster.
I see some pod looks like unhealthy, and will miss variable when using the "jobClient.newCompleteCommand(job.getKey()).variables(variables).send()".
