### ISSUE TITLE
ERROR       io.camunda.zeebe.broker.system - Bootstrap Broker-0 [6/14]: cluster services failed with unexpected exception.

### ISSUE THREAD

**Issue by bugbugmaker** [camunda/zeebe#9174]
```
2022-04-20 09:45:56.722 [] [main] INFO 
      io.camunda.zeebe.broker.system - Bootstrap Broker-0 [1/14]: actor scheduler
2022-04-20 09:45:56.726 [] [main] INFO 
      io.camunda.zeebe.broker.system - Bootstrap Broker-0 [2/14]: membership and replication protocol
2022-04-20 09:45:56.886 [] [main] INFO 
      io.camunda.zeebe.broker.system - Bootstrap Broker-0 [3/14]: command api transport
2022-04-20 09:45:57.044 [] [main] INFO 
      io.camunda.zeebe.broker.system - Bootstrap Broker-0 [4/14]: command api handler
2022-04-20 09:45:57.076 [] [main] INFO 
      io.camunda.zeebe.broker.system - Bootstrap Broker-0 [5/14]: subscription api
2022-04-20 09:45:57.104 [] [main] INFO 
      io.camunda.zeebe.broker.system - Bootstrap Broker-0 [6/14]: cluster services
2022-04-20 09:45:57.557 [] [main] ERROR
      io.camunda.zeebe.broker.system - Bootstrap Broker-0 [6/14]: cluster services failed with unexpected exception.
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Expected to find a snapshot at index >= log's first index 1702214, but found snapshot 0
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) ~[zeebe-atomix-utils-1.0.0.jar:1.0.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.IllegalStateException: Expected to find a snapshot at index >= log's first index 1702214, but found snapshot 0
	at io.atomix.raft.impl.RaftContext.verifySnapshotLogConsistent(RaftContext.java:190) ~[zeebe-atomix-cluster-1.0.0.jar:1.0.0]
	at io.atomix.raft.impl.RaftContext.<init>(RaftContext.java:166) ~[zeebe-atomix-cluster-1.0.0.jar:1.0.0]
	at io.atomix.raft.impl.DefaultRaftServer$Builder.build(DefaultRaftServer.java:257) ~[zeebe-atomix-cluster-1.0.0.jar:1.0.0]
	at io.atomix.raft.impl.DefaultRaftServer$Builder.build(DefaultRaftServer.java:231) ~[zeebe-atomix-cluster-1.0.0.jar:1.0.0]
	at io.atomix.raft.partition.impl.RaftPartitionServer.buildServer(RaftPartitionServer.java:175) ~[zeebe-atomix-cluster-1.0.0.jar:1.0.0]
	at io.atomix.raft.partition.impl.RaftPartitionServer.initServer(RaftPartitionServer.java:145) ~[zeebe-atomix-cluster-1.0.0.jar:1.0.0]
	at io.atomix.raft.partition.impl.RaftPartitionServer.start(RaftPartitionServer.java:103) ~[zeebe-atomix-cluster-1.0.0.jar:1.0.0]
	at io.atomix.raft.partition.RaftPartition.open(RaftPartition.java:113) ~[zeebe-atomix-cluster-1.0.0.jar:1.0.0]
	at io.atomix.raft.partition.RaftPartitionGroup.lambda$join$6(RaftPartitionGroup.java:201) ~[zeebe-atomix-cluster-1.0.0.jar:1.0.0]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at io.atomix.raft.partition.RaftPartitionGroup.join(RaftPartitionGroup.java:203) ~[zeebe-atomix-cluster-1.0.0.jar:1.0.0]
	at io.atomix.primitive.partition.impl.DefaultPartitionService.lambda$start$1(DefaultPartitionService.java:80) ~[zeebe-atomix-cluster-1.0.0.jar:1.0.0]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at io.atomix.primitive.partition.impl.DefaultPartitionService.start(DefaultPartitionService.java:81) ~[zeebe-atomix-cluster-1.0.0.jar:1.0.0]
	at io.atomix.core.Atomix.lambda$startServices$0(Atomix.java:178) ~[zeebe-atomix-1.0.0.jar:1.0.0]
	... 9 more
2022-04-20 09:45:57.568 [] [main] INFO 
      io.camunda.zeebe.broker.system - Closing Broker-0 [1/5]: subscription api
2022-04-20 09:45:57.570 [] [main] INFO 
      io.camunda.zeebe.broker.system - Closing Broker-0 [2/5]: command api handler
2022-04-20 09:45:57.570 [] [main] INFO 
      io.camunda.zeebe.broker.system - Closing Broker-0 [3/5]: command api transport
2022-04-20 09:45:59.624 [] [main] INFO 
      io.camunda.zeebe.broker.system - Closing Broker-0 [4/5]: membership and replication protocol
2022-04-20 09:45:59.626 [] [main] ERROR
      io.camunda.zeebe.broker.system - Closing Broker-0 [4/5]: membership and replication protocol failed to close.
java.lang.NullPointerException: null
	at io.atomix.raft.partition.impl.RaftPartitionServer.stop(RaftPartitionServer.java:141) ~[zeebe-atomix-cluster-1.0.0.jar:1.0.0]
	at io.atomix.raft.partition.RaftPartition.closeServer(RaftPartition.java:159) ~[zeebe-atomix-cluster-1.0.0.jar:1.0.0]
	at io.atomix.raft.partition.RaftPartition.close(RaftPartition.java:149) ~[zeebe-atomix-cluster-1.0.0.jar:1.0.0]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at io.atomix.raft.partition.RaftPartitionGroup.close(RaftPartitionGroup.java:221) ~[zeebe-atomix-cluster-1.0.0.jar:1.0.0]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at io.atomix.primitive.partition.impl.DefaultPartitionService.stop(DefaultPartitionService.java:102) ~[zeebe-atomix-cluster-1.0.0.jar:1.0.0]
	at io.atomix.core.Atomix.stopServices(Atomix.java:186) ~[zeebe-atomix-1.0.0.jar:1.0.0]
	at io.atomix.cluster.AtomixCluster.stop(AtomixCluster.java:240) ~[zeebe-atomix-cluster-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.broker.Broker.lambda$atomixCreateStep$13(Broker.java:263) ~[zeebe-broker-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.broker.bootstrap.CloseProcess.lambda$closingStepByStep$0(CloseProcess.java:59) ~[zeebe-broker-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:92) ~[zeebe-broker-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.broker.bootstrap.CloseProcess.closingStepByStep(CloseProcess.java:59) ~[zeebe-broker-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:92) ~[zeebe-broker-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.broker.bootstrap.CloseProcess.closeReverse(CloseProcess.java:40) ~[zeebe-broker-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.broker.bootstrap.StartProcess.startStepByStep(StartProcess.java:83) ~[zeebe-broker-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:92) ~[zeebe-broker-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.broker.bootstrap.StartProcess.start(StartProcess.java:46) ~[zeebe-broker-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.broker.Broker.internalStart(Broker.java:180) ~[zeebe-broker-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.LogUtil.doWithMDC(LogUtil.java:21) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.broker.Broker.start(Broker.java:160) [zeebe-broker-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:60) [camunda-cloud-zeebe-1.0.0.jar:1.0.0]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:819) [spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:803) [spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:346) [spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1340) [spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329) [spring-boot-2.4.5.jar:2.4.5]
	at io.camunda.zeebe.broker.StandaloneBroker.main(StandaloneBroker.java:47) [camunda-cloud-zeebe-1.0.0.jar:1.0.0]
2022-04-20 09:45:59.629 [] [main] INFO 
      io.camunda.zeebe.broker.system - Closing Broker-0 [5/5]: actor scheduler
2022-04-20 09:45:59.633 [] [main] INFO 
      io.camunda.zeebe.broker.system - Closing Broker-0 succeeded. Closed 5 steps in 2065 ms.
2022-04-20 09:45:59.633 [] [main] ERROR
```

Because of this error, the Zeebe service cannot be restarted.......

**Comment by npepinpe** [comment]
The error is because the log was compacted and starts at the given index > 0, but no snapshot for that index was found. Either the snapshot were corrupted or lost. Is there anything located under `data/raft-partitions/partitions/*/snapshots` ? Where the asterisk would be the partition ID.

That said, we don't support 1.0 anymore, so it's unlikely we will fix any bugs in these version. We still support 1.3.x and 8.x. Updating will most likely not solve your problem unfortunately, if you have lost the snapshots or they were corrupted. I'm afraid there's not much you can do, other than restore from your most recent backups.
