### ISSUE TITLE
RocksDBException: WriteBatch has wrong count

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#9187]
**Describe the bug**

```
Expected to process record 'TypedEventImpl{metadata=RecordMetadata{recordType=COMMAND, intentValue=255, intent=ACTIVATE, requestStreamId=3, requestId=113867, protocolVersion=3, valueType=JOB_BATCH, rejectionType=NULL_VAL, rejectionReason=, brokerVersion=8.0.1}, value={"type":"benchmark-task","worker":"default","timeout":300000,"maxJobsToActivate":116,"jobKeys":[],"jobs":[],"variables":[],"truncated":false}}' without errors, but exception occurred with message 'WriteBatch has wrong count'.

org.rocksdb.RocksDBException: WriteBatch has wrong count
	at org.rocksdb.Transaction.commit(Native Method) ~[rocksdbjni-6.28.2.jar:?]
	at org.rocksdb.Transaction.commit(Transaction.java:206) ~[rocksdbjni-6.28.2.jar:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.commitInternal(ZeebeTransaction.java:122) ~[zeebe-db-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.commit(ZeebeTransaction.java:97) ~[zeebe-db-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.lambda$updateState$9(ProcessingStateMachine.java:416) ~[zeebe-workflow-engine-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.util.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:36) ~[zeebe-util-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.util.retry.RecoverableRetryStrategy.run(RecoverableRetryStrategy.java:47) ~[zeebe-util-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:79) ~[zeebe-util-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:44) ~[zeebe-util-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) ~[zeebe-util-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97) ~[zeebe-util-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80) ~[zeebe-util-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189) ~[zeebe-util-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]

```

[Full log](https://drive.google.com/file/d/1Jh1OEAQigoeW2xVbbsywtIxj-PT5W-cc/view?usp=sharing)
[Link to log explorer](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-04-20T16:30:18.530198364Z;pinnedLogId=2022-04-20T16:30:18.530198364Z%2F7ygyxplx00985419;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.pod_name%3D%22zeebe-0%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.namespace_name%3D%22365c7c8f-61c7-4310-a25c-ae51c29095f9-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Atimestamp%3D%222022-04-20T16:30:18.530198364Z%22%0AinsertId%3D%227ygyxplx00985419%22;summaryFields=jsonPayload%252Fcontext%252FpartitionId:false:32:beginning:false;timeRange=2022-04-20T14:29:42.206Z%2F2022-04-20T16:30:18.550Z?project=camunda-cloud-240911)

**Environment:**
- Zeebe Version: "8.0.1-alpha0.12"

**Comment by deepthidevaki** [comment]
This was a test cluster `365c7c8f-61c7-4310-a25c-ae51c29095f9-zeebe` in ultrachaos. @romansmirnov Is this from your testing? Can you explain what you were testing and what process models you were using to help investigate the bug?

**Comment by Zelldon** [comment]
Now it becomes interesting :eyes:

**Comment by romansmirnov** [comment]
@deepthidevaki, please ignore this exception. I was running a benchmark with an un-merged code change, so to some degree, the exception is expected.
