### ISSUE TITLE
DueDateTimerChecher run outside of actor

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#9188]
**Describe the bug**

```
Expected to execute side effects for record 'LoggedEvent [type=0, version=16384, streamId=2, position=66, key=4503599627370523, timestamp=1650466645734, sourceEventPosition=57] RecordMetadata{recordType=COMMAND, intentValue=255, intent=ACTIVATE_ELEMENT, requestStreamId=-2147483648, requestId=-1, protocolVersion=3, valueType=PROCESS_INSTANCE, rejectionType=NULL_VAL, rejectionReason=, brokerVersion=8.0.1}' successfully, but exception was thrown.

java.lang.UnsupportedOperationException: Incorrect usage of actor.runDelayed(...): must only be called from within the actor itself.
	at io.camunda.zeebe.util.sched.ActorControl.ensureCalledFromWithinActor(ActorControl.java:407) ~[zeebe-util-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorControl.runDelayed(ActorControl.java:161) ~[zeebe-util-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.scheduled.DueDateChecker.schedule(DueDateChecker.java:51) ~[zeebe-workflow-engine-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.timer.DueDateTimerChecker.scheduleTimer(DueDateTimerChecker.java:52) ~[zeebe-workflow-engine-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.common.CatchEventBehavior.lambda$subscribeToTimerEvent$11(CatchEventBehavior.java:244) ~[zeebe-workflow-engine-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.streamprocessor.sideeffect.SideEffectQueue.flush(SideEffectQueue.java:35) ~[zeebe-workflow-engine-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.util.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:36) ~[zeebe-util-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.util.retry.AbortableRetryStrategy.run(AbortableRetryStrategy.java:44) ~[zeebe-util-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:79) ~[zeebe-util-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:44) ~[zeebe-util-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) ~[zeebe-util-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97) ~[zeebe-util-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80) ~[zeebe-util-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189) ~[zeebe-util-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
```

**Log/Stacktrace**

[Full log](https://drive.google.com/file/d/1lCZjFQgZsMx4rPkUYzqrIYXqdEqx5o4l/view?usp=sharing)
[Link to log explorer](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-04-20T14:57:25.819658138Z;pinnedLogId=2022-04-20T14:57:25.819658138Z%2Fflxla0jvhykmr1rm;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.pod_name%3D%22zeebe-1%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.namespace_name%3D%2262e78387-4acf-48d5-9894-f2d1dd60f13c-zeebe%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.container_name%3D%22zeebe%22%0Atimestamp%3D%222022-04-20T14:57:25.819658138Z%22%0AinsertId%3D%22flxla0jvhykmr1rm%22;summaryFields=jsonPayload%252Fcontext%252FpartitionId:false:32:beginning:false;timeRange=2022-04-20T13:57:13.572Z%2F2022-04-20T14:57:46.572Z?project=camunda-cloud-240911)

**Environment:**

- Zeebe Version: "8.0.1-alpha0.11"

**Comment by Zelldon** [comment]
@deepthidevaki what are these versions "8.0.1-alpha0.11" ?

**Comment by deepthidevaki** [comment]
That is the value from `jsonPayload.servicecontext.version`. I don't know where it is coming from.

**Comment by deepthidevaki** [comment]
https://github.com/camunda/zeebe/issues/9187#issuecomment-1105167276
