### ISSUE TITLE
NullPointerException:  "timer" is null

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#9189]
**Describe the bug**

```
Actor Broker-0-StreamProcessor-1 failed in phase STARTED.
java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.engine.state.instance.TimerInstance.getElementInstanceKey()" because "timer" is null
	at io.camunda.zeebe.engine.processing.streamprocessor.ReplayStateMachine.lambda$replayNextEvent$4(ReplayStateMachine.java:164) ~[zeebe-workflow-engine-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:33) ~[zeebe-util-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:82) ~[zeebe-util-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:44) ~[zeebe-util-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) ~[zeebe-util-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97) ~[zeebe-util-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80) ~[zeebe-util-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189) ~[zeebe-util-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
Caused by: java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.engine.state.instance.TimerInstance.getElementInstanceKey()" because "timer" is null
	at io.camunda.zeebe.engine.state.instance.DbTimerInstanceState.remove(DbTimerInstanceState.java:79) ~[zeebe-workflow-engine-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.engine.state.appliers.TimerCancelledApplier.applyState(TimerCancelledApplier.java:27) ~[zeebe-workflow-engine-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.engine.state.appliers.TimerCancelledApplier.applyState(TimerCancelledApplier.java:16) ~[zeebe-workflow-engine-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.engine.state.appliers.EventAppliers.applyState(EventAppliers.java:239) ~[zeebe-workflow-engine-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.streamprocessor.ReplayStateMachine.applyCurrentEvent(ReplayStateMachine.java:304) ~[zeebe-workflow-engine-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.streamprocessor.ReplayStateMachine.replayEvent(ReplayStateMachine.java:224) ~[zeebe-workflow-engine-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.streamprocessor.ReplayStateMachine.lambda$tryToReplayBatch$5(ReplayStateMachine.java:205) ~[zeebe-workflow-engine-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.streamprocessor.ReplayStateMachine.tryToReplayBatch(ReplayStateMachine.java:203) ~[zeebe-workflow-engine-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.streamprocessor.ReplayStateMachine.lambda$replayNextEvent$3(ReplayStateMachine.java:160) ~[zeebe-workflow-engine-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.util.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:36) ~[zeebe-util-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.util.retry.RecoverableRetryStrategy.run(RecoverableRetryStrategy.java:47) ~[zeebe-util-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:79) ~[zeebe-util-8.0.1-SNAPSHOT.jar:8.0.1-SNAPSHOT]
	... 5 more
```

**Log/Stacktrace**
[Full log](https://drive.google.com/file/d/1SroqU_pmkMZWykKSIWfzmpyWuxbSQAPF/view?usp=sharing)
[Link to log explorer](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-04-20T16:29:52.352611738Z;pinnedLogId=2022-04-20T16:29:52.352611738Z%2Fu2quhr2tamdidy0o;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.namespace_name%3D%22365c7c8f-61c7-4310-a25c-ae51c29095f9-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.pod_name%3D%22zeebe-0%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Atimestamp%3D%222022-04-20T16:29:52.352611738Z%22%0AinsertId%3D%22u2quhr2tamdidy0o%22;timeRange=2022-04-20T16:02:20.518Z%2F2022-04-20T16:30:17.518Z?project=camunda-cloud-240911)

**Environment:**
- Zeebe Version: "8.0.1-alpha0.12"

**Comment by deepthidevaki** [comment]
https://github.com/camunda/zeebe/issues/9187#issuecomment-1105167276
