### ISSUE TITLE
LogStorageAppenderTest.shouldFailActorWhenDetectingGapsInPositions

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#9336]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? 1
- Does it block your work? no
- Do we suspect that it is a real failure? no

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
org.opentest4j.AssertionFailedError: 
Expecting value to be true but was false
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at io.camunda.zeebe.logstreams.impl.log.LogStorageAppenderTest.shouldFailActorWhenDetectingGapsInPositions(LogStorageAppenderTest.java:199)
</pre>
</details>

**Hypotheses**

The test relies on two asynchronous components, the dispatcher and the actor scheduler, so it's most likely just something between the two.

**Comment by npepinpe** [comment]
So the issue is a race condition between failing due to the subscription failing, and when we add the failure listener. There's no controlled way of knowing _when_ the failure listener is added, so there's no controlled way of guaranteeing that now we can write with the wrong positions, because we never know when the listener is actually set up. :sweat_smile:
