### ISSUE TITLE
Flaky io.atomix.raft.zeebe.ZeebeTest:shouldNotifyCommitListeners 

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#9372]
**Summary**

- How often does the test fail? - once
- Does it block your work? - no
- Do we suspect that it is a real failure? - no

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at io.atomix.raft.zeebe.util.ZeebeTestHelper.await(ZeebeTestHelper.java:118)
	at io.atomix.raft.zeebe.ZeebeTest.shouldNotifyCommitListeners(ZeebeTest.java:254)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
</pre>
</details>

**Hypotheses**

Not sure if this check `listener.calledCount.get() == expectedCount` is determenistic. What if there are multiple entries committed together? Then the number of time listeners is invoked does not match the commit index.

**Logs**
[logs](https://drive.google.com/drive/folders/1o2_17dJNh812NdkGkwFWoTj93UErfoi6?usp=sharing)

**Comment by Zelldon** [comment]
Failed again https://github.com/camunda/zeebe/runs/6527368042?check_suite_focus=true
