### ISSUE TITLE
Zeebe basic auth to elasticsearch

### ISSUE THREAD

**Issue by kimabd** [camunda/zeebe#9451]
Hello, I have deployed Camunda helm chart with external Elasticsearch v7.17.0 with enabled security.
Operate and Tasklist configured to use ES with basic auth, Operates config(almost same for tasklist):
```
  application.yml: |
    camunda.operate:
      elasticsearch:
        clusterName: sapptest-elastic
        host: elasticsearch-master
        port: 9200
        username: camunda
        password: camundapassword
      zeebe:
        brokerContactPoint: "camunda-zeebe-gateway:26500"
      zeebeElasticsearch:
        clusterName: sapptest-elastic
        host: elasticsearch-master
        port: 9200
        prefix: zeebe-record
        username: camunda
        password: camundapassword
```
and application.yml for java application:
```
zeebe:
  client:
    security:
      plaintext: true
      cert-path:
      override-authority:
    broker:
      gateway-address: 172.17.10.11:30001 # this is NodePort for camunda-zeebe-gateway:26500
    cloud:
      base-url: operate.example.com
      auth-url: https://keycloak.example.com/auth/realms/camunda-platform/protocol/openid-connect/token
      client-id: operate-api
      client-secret: y11TuF9SulPk3nD05KyH2NEM1z9T0plX
    worker:
      max-jobs-active: 6
      threads: 200
      default-name: worker-test
spring:
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    io.camunda.zeebe.client.impl.ZeebeCallCredentials: ERROR
```
Below I have errors on Zeebe, how to make it work? I already tested with variable for Zeebe:
ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL: http://camunda:camundapassword@elasticsearch-master:9200
but it doesn't help
```
Caused by: org.elasticsearch.client.ResponseException: method [PUT], host [http://elasticsearch-master:9200], URI [/_component_template/zeebe-record], status line [HTTP/1.1 401 Unauthorized]
{"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/_component_template/zeebe-record]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/_component_template/zeebe-record]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}},"status":401}
        at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:342) ~[elasticsearch-rest-client-7.17.0.jar:7.17.0]
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:312) ~[elasticsearch-rest-client-7.17.0.jar:7.17.0]
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:287) ~[elasticsearch-rest-client-7.17.0.jar:7.17.0]
        at io.camunda.zeebe.exporter.ElasticsearchClient.putComponentTemplate(ElasticsearchClient.java:316) ~[zeebe-elasticsearch-exporter-8.0.0.jar:8.0.0]
        ... 17 more
2022-05-25 17:36:31.896 [Broker-2-Exporter-2] [Broker-2-zb-fs-workers-1] WARN
      io.camunda.zeebe.broker.exporter.elasticsearch - Error on exporting record with key 4503599627370538
io.camunda.zeebe.exporter.ElasticsearchExporterException: Failed to put component template
        at io.camunda.zeebe.exporter.ElasticsearchClient.putComponentTemplate(ElasticsearchClient.java:321) ~[zeebe-elasticsearch-exporter-8.0.0.jar:8.0.0]
        at io.camunda.zeebe.exporter.ElasticsearchClient.createComponentTemplate(ElasticsearchClient.java:275) ~[zeebe-elasticsearch-exporter-8.0.0.jar:8.0.0]
        at io.camunda.zeebe.exporter.ElasticsearchExporter.createComponentTemplate(ElasticsearchExporter.java:206) ~[zeebe-elasticsearch-exporter-8.0.0.jar:8.0.0]
        at io.camunda.zeebe.exporter.ElasticsearchExporter.createIndexTemplates(ElasticsearchExporter.java:148) ~[zeebe-elasticsearch-exporter-8.0.0.jar:8.0.0]
        at io.camunda.zeebe.exporter.ElasticsearchExporter.export(ElasticsearchExporter.java:81) ~[zeebe-elasticsearch-exporter-8.0.0.jar:8.0.0]
        at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.lambda$export$3(ExporterContainer.java:156) ~[zeebe-broker-8.0.0.jar:8.0.0]
        at io.camunda.zeebe.util.jar.ThreadContextUtil.runCheckedWithClassLoader(ThreadContextUtil.java:58) ~[zeebe-util-8.0.0.jar:8.0.0]
        at io.camunda.zeebe.util.jar.ThreadContextUtil.runWithClassLoader(ThreadContextUtil.java:34) ~[zeebe-util-8.0.0.jar:8.0.0]
        at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.export(ExporterContainer.java:155) ~[zeebe-broker-8.0.0.jar:8.0.0]
        at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.exportRecord(ExporterContainer.java:142) ~[zeebe-broker-8.0.0.jar:8.0.0]
        at io.camunda.zeebe.broker.exporter.stream.ExporterDirector$RecordExporter.export(ExporterDirector.java:510) ~[zeebe-broker-8.0.0.jar:8.0.0]
        at io.camunda.zeebe.util.retry.BackOffRetryStrategy.run(BackOffRetryStrategy.java:51) ~[zeebe-util-8.0.0.jar:8.0.0]
        at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:82) ~[zeebe-util-8.0.0.jar:8.0.0]
        at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:44) ~[zeebe-util-8.0.0.jar:8.0.0]
        at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) ~[zeebe-util-8.0.0.jar:8.0.0]
        at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97) ~[zeebe-util-8.0.0.jar:8.0.0]
        at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80) ~[zeebe-util-8.0.0.jar:8.0.0]
        at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189) ~[zeebe-util-8.0.0.jar:8.0.0]
```

**Comment by saig0** [comment]
The configuration of the ES exporter is listed here: https://github.com/camunda/zeebe/tree/main/exporters/elasticsearch-exporter#usage

You should set the following environment variables:

`ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL`
`ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_AUTHENTICATION_USERNAME`
`ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_AUTHENTICATION_PASSWORD`

@kimabd does this help you?

**Comment by kimabd** [comment]
> The configuration of the ES exporter is listed here: https://github.com/camunda/zeebe/tree/main/exporters/elasticsearch-exporter#usage
> 
> You should set the following environment variables:
> 
> `ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL` `ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_AUTHENTICATION_USERNAME` `ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_AUTHENTICATION_PASSWORD`
> 
> @kimabd does this help you?

Thanks, this solved my problem, I couldn't find those variables in the documentation.

**Comment by saig0** [comment]
@kimabd I agree. We should add this to the docs :+1: 

I found a related issue: https://github.com/camunda/camunda-platform-docs/issues/178 :heavy_check_mark:
