### ISSUE TITLE
ElasticsearchExporterException: Failed to connect to Elasticsearch 

### ISSUE THREAD

**Issue by pihme** [camunda/zeebe#9536]
**Describe the bug**
Observed in production logs

https://console.cloud.google.com/errors/detail/COaF45Lh37OyWg;service=zeebe;time=P7D?project=camunda-cloud-240911

Occurred only once (at the time this ticket was created) so most likely a benign connection error that should not be logged as an error.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>

 <p>

```
 io.camunda.zeebe.exporter.ElasticsearchExporterException: Failed to connect to Elasticsearch
	at io.camunda.zeebe.exporter.ElasticsearchClient.getIndicesWithRetries(ElasticsearchClient.java:461) ~[zeebe-elasticsearch-exporter-8.0.3-SNAPSHOT.jar:8.0.3-SNAPSHOT]
	at io.camunda.zeebe.exporter.ElasticsearchClient.getIndices(ElasticsearchClient.java:414) ~[zeebe-elasticsearch-exporter-8.0.3-SNAPSHOT.jar:8.0.3-SNAPSHOT]
	at io.camunda.zeebe.exporter.ElasticsearchClient.getLatestIndex(ElasticsearchClient.java:403) ~[zeebe-elasticsearch-exporter-8.0.3-SNAPSHOT.jar:8.0.3-SNAPSHOT]
	at io.camunda.zeebe.exporter.ElasticsearchClient.createIndicesBucket(ElasticsearchClient.java:385) ~[zeebe-elasticsearch-exporter-8.0.3-SNAPSHOT.jar:8.0.3-SNAPSHOT]
	at io.camunda.zeebe.exporter.ElasticsearchClient.<init>(ElasticsearchClient.java:91) ~[zeebe-elasticsearch-exporter-8.0.3-SNAPSHOT.jar:8.0.3-SNAPSHOT]
	at io.camunda.zeebe.exporter.ElasticsearchClient.<init>(ElasticsearchClient.java:83) ~[zeebe-elasticsearch-exporter-8.0.3-SNAPSHOT.jar:8.0.3-SNAPSHOT]
	at io.camunda.zeebe.exporter.ElasticsearchExporter.createClient(ElasticsearchExporter.java:122) ~[zeebe-elasticsearch-exporter-8.0.3-SNAPSHOT.jar:8.0.3-SNAPSHOT]
	at io.camunda.zeebe.exporter.ElasticsearchExporter.open(ElasticsearchExporter.java:54) ~[zeebe-elasticsearch-exporter-8.0.3-SNAPSHOT.jar:8.0.3-SNAPSHOT]
	at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.lambda$openExporter$0(ExporterContainer.java:67) ~[zeebe-broker-8.0.3-SNAPSHOT.jar:8.0.3-SNAPSHOT]
	at io.camunda.zeebe.util.jar.ThreadContextUtil.runCheckedWithClassLoader(ThreadContextUtil.java:58) ~[zeebe-util-8.0.3-SNAPSHOT.jar:8.0.3-SNAPSHOT]
	at io.camunda.zeebe.util.jar.ThreadContextUtil.runWithClassLoader(ThreadContextUtil.java:34) ~[zeebe-util-8.0.3-SNAPSHOT.jar:8.0.3-SNAPSHOT]
	at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.openExporter(ExporterContainer.java:66) ~[zeebe-broker-8.0.3-SNAPSHOT.jar:8.0.3-SNAPSHOT]
	at io.camunda.zeebe.broker.exporter.stream.ExporterDirector.startActiveExportingMode(ExporterDirector.java:312) ~[zeebe-broker-8.0.3-SNAPSHOT.jar:8.0.3-SNAPSHOT]
	at io.camunda.zeebe.broker.exporter.stream.ExporterDirector.onActorStarted(ExporterDirector.java:199) ~[zeebe-broker-8.0.3-SNAPSHOT.jar:8.0.3-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:79) ~[zeebe-util-8.0.3-SNAPSHOT.jar:8.0.3-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:44) ~[zeebe-util-8.0.3-SNAPSHOT.jar:8.0.3-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) ~[zeebe-util-8.0.3-SNAPSHOT.jar:8.0.3-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97) ~[zeebe-util-8.0.3-SNAPSHOT.jar:8.0.3-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80) ~[zeebe-util-8.0.3-SNAPSHOT.jar:8.0.3-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189) ~[zeebe-util-8.0.3-SNAPSHOT.jar:8.0.3-SNAPSHOT]
Caused by: java.net.ConnectException: Connection refused
	at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:914) ~[elasticsearch-rest-client-7.17.0.jar:7.17.0]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:299) ~[elasticsearch-rest-client-7.17.0.jar:7.17.0]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:287) ~[elasticsearch-rest-client-7.17.0.jar:7.17.0]
	at io.camunda.zeebe.exporter.ElasticsearchClient.getIndicesWithRetries(ElasticsearchClient.java:447) ~[zeebe-elasticsearch-exporter-8.0.3-SNAPSHOT.jar:8.0.3-SNAPSHOT]
	... 19 more
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
	at sun.nio.ch.Net.pollConnectNow(Unknown Source) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source) ~[?:?]
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:174) ~[httpcore-nio-4.4.15.jar:4.4.15]
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:148) ~[httpcore-nio-4.4.15.jar:4.4.15]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:351) ~[httpcore-nio-4.4.15.jar:4.4.15]
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:221) ~[httpasyncclient-4.1.5.jar:4.1.5]
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64) ~[httpasyncclient-4.1.5.jar:4.1.5]
	at java.lang.Thread.run(Unknown Source) ~[?:?] 
```

</p>
</details>

**Environment:**
- OS: Camunda Cloud 
- Zeebe Version: 8.0.3-rs.4

**Comment by pihme** [comment]
Severity and impact updated. This error lead to the exporter and the partition becoming unhealthy

**Comment by korthout** [comment]
The problem occurs during startup. Either because of a wrong config or due to network problems. We could retry a couple of times until a time out, otherwise the controller will restart the node because it's unhealthy.
