### ISSUE TITLE
`ReaderCloseTest#shouldDeleteCompactedSegmentsFiles` is flaky

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#9685]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? Once, as far as I can see
- Does it block your work? No
- Do we suspect that it is a real failure? No

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Error:  io.camunda.zeebe.it.clustering.ReaderCloseTest.shouldDeleteCompactedSegmentsFiles  Time elapsed: 24.919 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 
[The files in the segment directory should be either valid log segments or raft config and metadata. /tmp/junit4157082138733558581/2/data/raft-partition/partitions/1/raft-partition-partition-1-2.log_7-deleted] 
Expecting value to be true but was false
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at io.camunda.zeebe.it.clustering.ReaderCloseTest.lambda$assertThatFilesOfDeletedSegmentsDoesNotExist$2(ReaderCloseTest.java:103)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.camunda.zeebe.it.clustering.ReaderCloseTest.assertThatFilesOfDeletedSegmentsDoesNotExist(ReaderCloseTest.java:97)
	at io.camunda.zeebe.it.clustering.ReaderCloseTest.shouldDeleteCompactedSegmentsFiles(ReaderCloseTest.java:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
</pre>
</details>

**Hypotheses**

Log compaction is triggered asynchronously via `LogDeletionService#onNewSnapshot` so there seems to be no guarantee that segments are deleted after taking a snapshot.

**Comment by oleschoenburg** [comment]
This is happening pretty frequently now, we should try and fix it.

**Comment by Zelldon** [comment]
Agree, just searched for the test :+1:  happened here again https://github.com/camunda/zeebe/runs/7246700108?check_suite_focus=true

**Comment by npepinpe** [comment]
While I can't reproduce it, I think the hypothesis is pretty likely. The compaction is asynchronous after the snapshot is taken, so it's possible that checking immediately results in some files still being there. I couldn't really come up with a non-contrived way of emitting an event that compaction was done/finished, so we'll go with Awaitility.
