### ISSUE TITLE
Cannot reserve XY bytes of direct buffer memory

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#9713]
**Describe the bug**
We seeing errors `"Out of memory, exiting now because we can't recover from OOM. Consider adjusting memory limits."` on prod.

Error: https://console.cloud.google.com/errors/detail/CKSrwcbo6qihLg;service=zeebe;time=P7D?project=camunda-cloud-240911
[![error](https://user-images.githubusercontent.com/2758593/177546265-7a160437-dc76-47be-98b0-3acf9603c906.png)](https://grafana-ultrachaos.internal.ultrawombat.com/d/NzsO1mUnk/zeebe-overview?orgId=1&refresh=10s&var-DS_PROMETHEUS=Prometheus&var-namespace=24b7cc42-bdd2-4aad-9c20-c076c5e6c918-zeebe&var-pod=All&var-partition=All&from=now-3h&to=now)

The cluster seems to be completely borked. Impact as high since it looks like that cluster is unusable.

**To Reproduce**
I have no clue yet, it seems to be an election loop. You can see that in the metrics but also in the logs where the term is really high.

```
Transition to FOLLOWER on term 353 - transitioning StreamProcessor
```

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.OutOfMemoryError: Cannot reserve 75498884 bytes of direct buffer memory (allocated: 2003030408, limit: 2075918336)
	at java.nio.Bits.reserveMemory(Unknown Source) ~[?:?]
	at java.nio.DirectByteBuffer.<init>(Unknown Source) ~[?:?]
	at java.nio.ByteBuffer.allocateDirect(Unknown Source) ~[?:?]
	at io.camunda.zeebe.util.allocation.DirectBufferAllocator.allocate(DirectBufferAllocator.java:20) ~[zeebe-util-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.util.allocation.BufferAllocators.allocateDirect(BufferAllocators.java:16) ~[zeebe-util-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.dispatcher.DispatcherBuilder.initAllocatedBuffer(DispatcherBuilder.java:147) ~[zeebe-dispatcher-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.dispatcher.DispatcherBuilder.build(DispatcherBuilder.java:93) ~[zeebe-dispatcher-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.createAndScheduleWriteBuffer(LogStreamImpl.java:340) ~[zeebe-logstreams-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.lambda$openAppender$9(LogStreamImpl.java:297) ~[zeebe-logstreams-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:79) ~[zeebe-util-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:44) ~[zeebe-util-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) ~[zeebe-util-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97) ~[zeebe-util-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80) ~[zeebe-util-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189) ~[zeebe-util-8.0.2.jar:8.0.2]
```

</p>
</details>

**Environment:**
- OS: saas
- Zeebe Version: 8.0.2
- Configuration: [G3-Trial](https://console.cloud.ultrawombat.com/admin/cluster-plan/plans/451939f9-55f1-49a9-b5c3-3b9945606763)

**Comment by oleschoenburg** [comment]
This cluster ran into #9115 a while ago : [Logs](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-06-06T19:09:26.657316946Z;pinnedLogId=2022-06-06T17:44:57.943327929Z%2Ft3zat1xuts7j8fhj;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.namespace_name%3D%2224b7cc42-bdd2-4aad-9c20-c076c5e6c918-zeebe%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aseverity%3DERROR%0Atimestamp%3D%222022-06-06T17:44:57.943327929Z%22%0AinsertId%3D%22t3zat1xuts7j8fhj%22;timeRange=2022-05-25T12:19:48.190Z%2F2022-06-08T18:00:00.000000001Z?project=camunda-cloud-240911)

**Comment by menski** [comment]
Closing for now, the cluster is in an unhealthy state, and the error didn't happen in another cluster. We are fixing an issue related to memory leaks, which might be related.
