### ISSUE TITLE
Flaky CompleteProcessInstanceAfterLeaderChangeTest.shouldCompleteProcessInstanceAfterSeveralLeaderChanges

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#9813]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? 1
- Does it block your work? no
- Do we suspect that it is a real failure?

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
Error:  CompleteProcessInstanceAfterLeaderChangeTest.shouldCompleteProcessInstanceAfterSeveralLeaderChanges  Time elapsed: 31.408 s  <<< ERROR!
io.camunda.zeebe.client.api.command.ClientStatusException: Time out between gateway and broker: Request timed out after PT10S
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.transformExecutionException(ZeebeClientFutureImpl.java:93)
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:50)
	at io.camunda.zeebe.it.clustering.CompleteProcessInstanceAfterLeaderChangeTest.lambda$actions$4(CompleteProcessInstanceAfterLeaderChangeTest.java:97)
	at io.camunda.zeebe.it.clustering.CompleteProcessInstanceAfterLeaderChangeTest.shouldCompleteProcessInstanceAfterSeveralLeaderChanges(CompleteProcessInstanceAfterLeaderChangeTest.java:172)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: Time out between gateway and broker: Request timed out after PT10S
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:48)
	... 19 more
Caused by: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: Time out between gateway and broker: Request timed out after PT10S
	at io.grpc.Status.asRuntimeException(Status.java:535)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	... 1 more

</pre>
</details>

**Logs**

[logs ](https://drive.google.com/drive/folders/17m6DV_qwvWtuzMH6bIGLEgcF-HhAXfkA)

**Comment by deepthidevaki** [comment]
Still fails https://github.com/camunda/zeebe/pull/9886#issuecomment-1195476989

**Comment by deepthidevaki** [comment]
Found the following logs from the failed test
```
14:36:41.364 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] ERROR io.camunda.zeebe.processor - Expected to execute side effects for record 'LoggedEvent [type=0, version=0, streamId=1, position=1, key=-1, timestamp=1658846201352, sourceEventPosition=-1] RecordMetadata{recordType=COMMAND, intentValue=255, intent=PUBLISH, requestStreamId=1, requestId=0, protocolVersion=3, valueType=MESSAGE, rejectionType=NULL_VAL, rejectionReason=, brokerVersion=8.1.0}' successfully, but exception was thrown.
java.lang.RuntimeException: java.lang.NullPointerException
	at io.camunda.zeebe.streamprocessor.DirectProcessingResult.executePostCommitTasks(DirectProcessingResult.java:69) ~[zeebe-workflow-engine-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.lambda$executeSideEffects$11(ProcessingStateMachine.java:409) ~[zeebe-workflow-engine-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:36) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.retry.AbortableRetryStrategy.run(AbortableRetryStrategy.java:45) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
	at io.camunda.zeebe.broker.transport.commandapi.CommandResponseWriterImpl.tryWriteResponse(CommandResponseWriterImpl.java:99) ~[zeebe-broker-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.streamprocessor.writers.LegacyTypedResponseWriterImpl.flush(LegacyTypedResponseWriterImpl.java:142) ~[zeebe-workflow-engine-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.message.MessagePublishProcessor.sendCorrelateCommand(MessagePublishProcessor.java:193) ~[zeebe-workflow-engine-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.streamprocessor.DirectProcessingResult.executePostCommitTasks(DirectProcessingResult.java:67) ~[zeebe-workflow-engine-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	... 9 more
```

Not sure if this explains the failure. Related to https://github.com/camunda/zeebe/issues/9860

**Comment by deepthidevaki** [comment]
Found this log 
```
09:18:57.222 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] INFO  io.camunda.zeebe.broker.transport - Sending command MESSAGE_SUBSCRIPTION CREATE to partition 1, leader 1
```
where the command is sent to member 1. But at this time, the leader is 0 and member 1 (which was the previous leader) is already shutdown. It seems the topology is not updated when this command is send. I think that that topology will be eventually updated. But the retry delay is set to 10 seconds. The tests fails before the retry is attempted.

**Comment by deepthidevaki** [comment]
Also the NPE doesn't seems to affect this test because when this error happens, there are no subscription to correlate.

**Comment by korthout** [comment]
Happened again, see https://github.com/camunda/zeebe/pull/9935#issuecomment-1201175501

**Comment by deepthidevaki** [comment]
:sob: 
Will look into it. Probably then the topology is never updated :thinking:

**Comment by korthout** [comment]
Thanks @deepthidevaki Sorry to have to open this one again 🙇 But thanks for looking into it.

**Comment by remcowesterhoud** [comment]
Here is another example pipeline: https://github.com/camunda/zeebe/runs/7667370072?check_suite_focus=true

**Comment by deepthidevaki** [comment]
Was quite difficult to reproduce it. But reproduced it after several runs https://github.com/camunda/zeebe/actions/runs/2783045847 

From the logs it seems the topology is not updated correctly.
```
08:48:44.386 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] INFO  io.camunda.zeebe.broker.system - Transition to LEADER on term 3 completed
08:48:44.386 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Update leader of partition 1 to node 0
08:48:44.386 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Update leader of partition 1 to node 1
```
Broker 0 became the leader. The topology listener updates the leader to 0, but then it updates again to broker 1. Broker 1 was leader in the previous term. So the current leader is overwritten. No idea how it can happen.

**Comment by oleschoenburg** [comment]
When the partition leader is updated, we now schedule a timer:
https://github.com/camunda/zeebe/blob/b05271207aff00bffb372a0d9d7e35b881502624/broker/src/main/java/io/camunda/zeebe/broker/partitioning/topology/TopologyPartitionListenerImpl.java#L28

Before, we directly used `submit`.

Quoting from the documentation of `DeadlineTimerWheel`:

> Timers that expire in the same tick are not be ordered with one another. As ticks are fairly coarse resolution normally, this means that some timers may expire out of order.

**Comment by deepthidevaki** [comment]
Great point @oleschoenburg 

I suspected some thing like it, but the following test passed

```
@Test
  public void shouldExecuteInOrder() throws InterruptedException {
    // given
    final AtomicReference<ActorControl> actorControl = new AtomicReference<>();
    final CompletableFuture<Void> started = new CompletableFuture<>();
    final Actor temp =
        new Actor() {
          @Override
          protected void onActorStarted() {
            actorControl.set(actor);
            started.complete(null);
          }
        };

    actorSchedulerRule.submitActor(temp).join();
    started.join();

    // when
    final var actor = actorControl.get();

    final Runnable step1 = mock(Runnable.class);
    final Runnable step2 = mock(Runnable.class);
    actor.submit(() -> actor.runDelayed(Duration.ZERO, step1));
    actor.submit(() -> actor.runDelayed(Duration.ZERO, step2));
    ;
    final var inorder = inOrder(step1, step2);
    inorder.verify(step1, timeout(1000)).run();
    inorder.verify(step2, timeout(1000)).run();
  }
```
But as the documentation says, if it is not guaranteed, then that would explain why it fails non-deterministically.

**Comment by oleschoenburg** [comment]
IMO `TopologyPartitionListenerImpl` could use a small rewrite to just use a `ConcurrentHashMap` instead of relying on `Int2IntHashMap` plus the actor scheduler.

**Comment by deepthidevaki** [comment]
> IMO `TopologyPartitionListenerImpl` could use a small rewrite to just use a `ConcurrentHashMap` instead of relying on `Int2IntHashMap` plus the actor scheduler.

`TopologyPartitionListenerImpl` is only used by the `InterPartitionCommandSender`. I was thinking of merging them. And instead of sharing the actor with the `StreamProcessor,` it can run on its own actor. Then it doesn't have to use the `ProcessSchedulingService` to schedule the task, instead directly run on the actor. This way we can also build them outside of the engine. Right now they are constructed as part of `TypedRecordProcessorFactory`.

**Comment by oleschoenburg** [comment]
So `InterPartitionCommandSender` implements `TopologyPartitionListener` and we remove `TopologyPartitionListenerImpl`? That sounds even better :heart_eyes: :rocket:

**Comment by Zelldon** [comment]
Would reslove this https://github.com/camunda/zeebe/pull/9756#discussion_r937429996 as well

**Comment by npepinpe** [comment]
imo having the transport be its own actor kind of makes sense. you can pass the job of sending a command to another actor and keep processing :+1:
