### ISSUE TITLE
Deployment Distribution not idempotent

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#9877]
**Describe the bug**

A DMN resource was deployed which was distributed to another partition, and then this distribution was retried (for some reason). The retry results in the same command on the log. The second command is processed in the same way as the first and results in the same DMN_DECISION_REQUIREMENTS to be inserted into the state. The engine expects that this is an insert operation and thus triggers the consistency check. The consistency check then stops the second partition from making progress. The partition is marked as unhealthy.

In the meantime, the deployment partition keeps retrying the distribution, each time appending a new command to the other partition's log. This increases the disk usage continuously, as an additional symptom.

**To Reproduce**

06e517ab48 contains a test in `DeploymentClusteredTest.shouldRedeployDmn()` that reproduces the problem. Note that this test cannot be used directly in the fix, as it required some additional hard-coded changes to test the scenario.

**Expected behavior**

Retried sending of the Distribute command should be idempotent and not trigger the consistency checks.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
ERROR io.camunda.zeebe.logstreams - Actor Broker-2-StreamProcessor-3 failed in phase STARTED.
io.camunda.zeebe.db.ZeebeDbInconsistentException: Key DbLong{2251799813685249} in ColumnFamily DMN_DECISION_REQUIREMENTS already exists
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.assertKeyDoesNotExist(TransactionalColumnFamily.java:273) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$insert$0(TransactionalColumnFamily.java:81) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$ensureInOpenTransaction$17(TransactionalColumnFamily.java:301) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.DefaultTransactionContext.runInTransaction(DefaultTransactionContext.java:33) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.ensureInOpenTransaction(TransactionalColumnFamily.java:300) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.insert(TransactionalColumnFamily.java:76) ~[classes/:?]
	at io.camunda.zeebe.engine.state.deployment.DbDecisionState.storeDecisionRequirements(DbDecisionState.java:163) ~[classes/:?]
	at io.camunda.zeebe.engine.state.appliers.DeploymentDistributedApplier.lambda$putDmnResourcesInState$0(DeploymentDistributedApplier.java:53) ~[classes/:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at io.camunda.zeebe.engine.state.appliers.DeploymentDistributedApplier.putDmnResourcesInState(DeploymentDistributedApplier.java:48) ~[classes/:?]
	at io.camunda.zeebe.engine.state.appliers.DeploymentDistributedApplier.applyState(DeploymentDistributedApplier.java:42) ~[classes/:?]
	at io.camunda.zeebe.engine.state.appliers.DeploymentDistributedApplier.applyState(DeploymentDistributedApplier.java:26) ~[classes/:?]
	at io.camunda.zeebe.engine.state.appliers.EventAppliers.applyState(EventAppliers.java:239) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.streamprocessor.writers.EventApplyingStateWriter.appendFollowUpEvent(EventApplyingStateWriter.java:36) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.deployment.distribute.DeploymentDistributeProcessor.processRecord(DeploymentDistributeProcessor.java:58) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.lambda$processInTransaction$3(ProcessingStateMachine.java:300) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processInTransaction(ProcessingStateMachine.java:290) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:253) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:213) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:189) ~[classes/:?]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:79) ~[classes/:?]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:44) ~[classes/:?]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) ~[classes/:?]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97) ~[classes/:?]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80) ~[classes/:?]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189) ~[classes/:?]
```

</p>
</details>

**Environment:**
- Zeebe Version: 8.0.4

**Comment by korthout** [comment]
A workaround exists by disabling the [preconditions](https://github.com/camunda/zeebe/blob/8.0.4/dist/src/main/config/broker.standalone.yaml.template#L692-L695) consistency check.

**Comment by npepinpe** [comment]
I like solution no. 2 to be honest, especially since we can explain explicitly why it's being rejected (`ALREADY_EXISTS`). I think it's a flaw that we don't deal with rejections internally in general. For example, this incident highlighted that it's dangerous for our internal inter-partition communication not to go through the same command rate limiter, since it caused an incredible backlog as there was no flow control from the other partition. And flow control would necessarily be implemented with rejections (at least at the moment anyway).

Can you quickly summarize why no.2 is more complex? I think also with [this PR](https://github.com/camunda/zeebe/pull/9858), it might not be so complicated anymore, as that already simplifies the communication in the deployment distribution. Of course that only applies to main, so we might still want to go with no. 1 for a patch, but no. 2 for the main branch.

I guess we'll talk about that in the incident as well :)

**Comment by oleschoenburg** [comment]
> In the meantime, the deployment partition keeps retrying the distribution, each time appending a new command to the other partition's log. This increases the disk usage continuously, as an additional symptom.

The impact of this is somewhat mitigated by https://github.com/camunda/zeebe/pull/9858 where we now use an exponential backoff strategy. The log would still grow indefinitely, but slower.

**Comment by korthout** [comment]
>Can you quickly summarize why no.2 is more complex?

It needs logic to check that:
- none of the resources exist yet (expected, acceptable case)
- or all exist already (expected on retry from deployment leader that hasn't received an ack yet, rejected command but accepting the message to avoid further retry)
- or if some exists then we need to consider how to deal with this
- (potentially we could add) if all exist, but with differences, then we need to consider how to deal with this

It's not clear to me what should happen on the REAL failure cases. But it's also additional complexity that we could simply ignore if we just allow idempotent deployment distribution (storing the last received one).

TBH, I'm not strongly leaning either way, except for using the simple solution (i.e. just use upsert) to patch the broken version 8.0.x

**Comment by npepinpe** [comment]
100% on using it for the patch :+1: Just thinking we may do better for future versions, but that's something we can discuss in the review :rocket:
