### ISSUE TITLE
NPE in FeelToMessagePackTransformer

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#9925]
**Describe the bug**

```
Expected to successfully process record 'LoggedEvent [type=0, version=16384, streamId=2, position=1879241, key=4503599628309708, timestamp=1659040132806, sourceEventPosition=1879236] RecordMetadata{recordType=COMMAND, intentValue=255, intent=ACTIVATE_ELEMENT, requestStreamId=-2147483648, requestId=-1, protocolVersion=3, valueType=PROCESS_INSTANCE, rejectionType=NULL_VAL, rejectionReason=, brokerVersion=8.0.2}' with processor, but caught an exception. Skip this record.


"java.lang.NullPointerException: Cannot invoke "String.getBytes()" because "key" is null
	at io.camunda.zeebe.feel.impl.FeelToMessagePackTransformer.$anonfun$writeValue$2(FeelToMessagePackTransformer.scala:50) ~[zeebe-feel-integration-8.0.2.jar:8.0.2]
	at scala.collection.immutable.HashMap.foreach(HashMap.scala:1076) ~[scala-library-2.13.8.jar:?]
	at io.camunda.zeebe.feel.impl.FeelToMessagePackTransformer.writeValue(FeelToMessagePackTransformer.scala:49) ~[zeebe-feel-integration-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.feel.impl.FeelToMessagePackTransformer.toMessagePack(FeelToMessagePackTransformer.scala:27) ~[zeebe-feel-integration-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.dmn.impl.DmnScalaDecisionEngine.toMessagePack(DmnScalaDecisionEngine.java:170) ~[zeebe-dmn-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.dmn.impl.EvaluatedDmnScalaDecision.of(EvaluatedDmnScalaDecision.java:56) ~[zeebe-dmn-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.dmn.impl.DmnScalaDecisionEngine.lambda$getEvaluatedDecisions$1(DmnScalaDecisionEngine.java:162) ~[zeebe-dmn-8.0.2.jar:8.0.2]
	at scala.collection.immutable.List.foreach(List.scala:333) ~[scala-library-2.13.8.jar:?]
	at io.camunda.zeebe.dmn.impl.DmnScalaDecisionEngine.getEvaluatedDecisions(DmnScalaDecisionEngine.java:159) ~[zeebe-dmn-8.0.2.jar:8.0.2]
	at java.util.Optional.map(Unknown Source) ~[?:?]
	at io.camunda.zeebe.dmn.impl.DmnScalaDecisionEngine.evaluateDecisionById(DmnScalaDecisionEngine.java:105) ~[zeebe-dmn-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnDecisionBehavior.evaluateDecisionInDrg(BpmnDecisionBehavior.java:182) ~[zeebe-workflow-engine-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnDecisionBehavior.lambda$evaluateDecision$3(BpmnDecisionBehavior.java:111) ~[zeebe-workflow-engine-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.util.Either$Right.flatMap(Either.java:366) ~[zeebe-util-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnDecisionBehavior.evaluateDecision(BpmnDecisionBehavior.java:109) ~[zeebe-workflow-engine-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.engine.processing.bpmn.task.BusinessRuleTaskProcessor$CalledDecisionBehavior.lambda$onActivate$0(BusinessRuleTaskProcessor.java:89) ~[zeebe-workflow-engine-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.util.Either$Right.flatMap(Either.java:366) ~[zeebe-util-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.engine.processing.bpmn.task.BusinessRuleTaskProcessor$CalledDecisionBehavior.onActivate(BusinessRuleTaskProcessor.java:89) ~[zeebe-workflow-engine-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.engine.processing.bpmn.task.BusinessRuleTaskProcessor.onActivate(BusinessRuleTaskProcessor.java:40) ~[zeebe-workflow-engine-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.engine.processing.bpmn.task.BusinessRuleTaskProcessor.onActivate(BusinessRuleTaskProcessor.java:21) ~[zeebe-workflow-engine-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.lambda$processEvent$2(BpmnStreamProcessor.java:128) ~[zeebe-workflow-engine-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:381) ~[zeebe-util-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processEvent(BpmnStreamProcessor.java:127) ~[zeebe-workflow-engine-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.lambda$processRecord$0(BpmnStreamProcessor.java:110) ~[zeebe-workflow-engine-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:381) ~[zeebe-util-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processRecord(BpmnStreamProcessor.java:107) ~[zeebe-workflow-engine-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.engine.processing.streamprocessor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:54) ~[zeebe-workflow-engine-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.lambda$processInTransaction$3(ProcessingStateMachine.java:300) ~[zeebe-workflow-engine-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processInTransaction(ProcessingStateMachine.java:290) ~[zeebe-workflow-engine-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:253) ~[zeebe-workflow-engine-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:213) ~[zeebe-workflow-engine-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:189) ~[zeebe-workflow-engine-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:79) ~[zeebe-util-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:44) ~[zeebe-util-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) ~[zeebe-util-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97) ~[zeebe-util-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80) ~[zeebe-util-8.0.2.jar:8.0.2]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189) ~[zeebe-util-8.0.2.jar:8.0.2]
"

Expected to process record 'TypedEventImpl{metadata=RecordMetadata{recordType=COMMAND, intentValue=255, intent=ACTIVATE_ELEMENT, requestStreamId=-2147483648, requestId=-1, protocolVersion=3, valueType=PROCESS_INSTANCE, rejectionType=NULL_VAL, rejectionReason=, brokerVersion=8.0.2}, value={"bpmnProcessId":"Process_142fltf","version":38,"processDefinitionKey":2251799814624706,"processInstanceKey":4503599628309683,"elementId":"Activity_1jqxw00","flowScopeKey":4503599628309683,"bpmnElementType":"BUSINESS_RULE_TASK","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1}}' without errors, but exception occurred with message 'Cannot invoke "String.getBytes()" because "key" is null'.
```

The instances are blacklisted.
```
2022-07-28 22:28:52.845 CEST
Blacklist process instance 4503599628309683, due to previous errors.

2022-07-28 22:38:42.576 CEST
Blacklist process instance 4503599628309852, due to previous errors.

```

**To Reproduce**

**Log/Stacktrace**

[Link to data](https://drive.google.com/drive/folders/1Ni6pXrRAE-QoofsKLl2cqyXmMqdP6dEL)

**Comment by remcowesterhoud** [comment]
This is the same issue as occurred in https://github.com/camunda/zeebe/issues/9269. It seems I have forgotten to backport the fix back then.

**Comment by remcowesterhoud** [comment]
Fixed with https://github.com/camunda/zeebe/pull/9944
