### ISSUE TITLE
WARN        io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot - Failed to delete pending snapshot FileBasedTransientSnapshot

### ISSUE THREAD

**Issue by bugbugmaker** [camunda/zeebe#9953]
2022-08-02 17:30:44.303 [Broker-0-SnapshotStore-7] [Broker-0-zb-fs-workers-2] WARN 
      io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot - Failed to delete pending snapshot FileBasedTransientSnapshot{directory=D:\code\zeebe1.0\camunda-cloud-zeebe-1.0.0\data\raft-partition\partitions\7\pending\3207-1-6506-6507, checksum=828401809, snapshotStore=io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore@670fdaff, metadata=FileBasedSnapshotMetadata{index=3207, term=1, processedPosition=6506, exporterPosition=6507}}
java.nio.file.NoSuchFileException: D:\code\zeebe1.0\camunda-cloud-zeebe-1.0.0\data\raft-partition\partitions\7\pending\3207-1-6506-6507
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53) ~[?:?]
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:199) ~[?:?]
	at java.nio.file.Files.readAttributes(Files.java:1851) ~[?:?]
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:220) ~[?:?]
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277) ~[?:?]
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:323) ~[?:?]
	at java.nio.file.Files.walkFileTree(Files.java:2804) ~[?:?]
	at java.nio.file.Files.walkFileTree(Files.java:2882) ~[?:?]
	at io.camunda.zeebe.util.FileUtil.deleteFolderIfExists(FileUtil.java:58) ~[zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot.abortInternal(FileBasedTransientSnapshot.java:144) ~[zeebe-snapshots-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot.lambda$abort$2(FileBasedTransientSnapshot.java:92) ~[zeebe-snapshots-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.0.0.jar:1.0.0]
2022-08-02 17:30:44.305 [Broker-0-SnapshotDirector-7] [Broker-0-zb-fs-workers-2] INFO 
      io.camunda.zeebe.logstreams.snapshot - Current commit position 7145 >= 7145, snapshot 3832-1-7144-7145 is valid and has been persisted.
2022-08-02 17:30:59.125 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-3] INFO 
      io.camunda.zeebe.logstreams.snapshot - Finished taking snapshot, need to wait until last written event position 11465 is committed, current commit position is 11465. After that snapshot can be marked as valid.
2022-08-02 17:30:59.142 [Broker-0-SnapshotStore-1] [Broker-0-zb-fs-workers-3] WARN 
      io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot - Failed to delete pending snapshot FileBasedTransientSnapshot{directory=D:\code\zeebe1.0\camunda-cloud-zeebe-1.0.0\data\raft-partition\partitions\1\pending\4984-2-10843-10847, checksum=2786186738, snapshotStore=io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore@27b5f306, metadata=FileBasedSnapshotMetadata{index=4984, term=2, processedPosition=10843, exporterPosition=10847}}
java.nio.file.NoSuchFileException: D:\code\zeebe1.0\camunda-cloud-zeebe-1.0.0\data\raft-partition\partitions\1\pending\4984-2-10843-10847
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53) ~[?:?]
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:199) ~[?:?]
	at java.nio.file.Files.readAttributes(Files.java:1851) ~[?:?]
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:220) ~[?:?]
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277) ~[?:?]
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:323) ~[?:?]
	at java.nio.file.Files.walkFileTree(Files.java:2804) ~[?:?]
	at java.nio.file.Files.walkFileTree(Files.java:2882) ~[?:?]
	at io.camunda.zeebe.util.FileUtil.deleteFolderIfExists(FileUtil.java:58) ~[zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot.abortInternal(FileBasedTransientSnapshot.java:144) ~[zeebe-snapshots-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot.lambda$abort$2(FileBasedTransientSnapshot.java:92) ~[zeebe-snapshots-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.0.0.jar:1.0.0]
2022-08-02 17:30:59.143 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] INFO 
      io.camunda.zeebe.logstreams.snapshot - Current commit position 11465 >= 11465, snapshot 5593-2-11461-11465 is valid and has been persisted.
2022-08-02 17:31:44.761 [Broker-0-SnapshotDirector-6] [Broker-0-zb-fs-workers-0] INFO 
      io.camunda.zeebe.logstreams.snapshot - Finished taking snapshot, need to wait until last written event position 7044 is committed, current commit position is 7044. After that snapshot can be marked as valid.
2022-08-02 17:32:24.759 [Broker-0-SnapshotStore-6] [Broker-0-zb-fs-workers-0] WARN 
      io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot - Failed to delete pending snapshot FileBasedTransientSnapshot{directory=D:\code\zeebe1.0\camunda-cloud-zeebe-1.0.0\data\raft-partition\partitions\6\pending\3207-1-6465-6466, checksum=2600747085, snapshotStore=io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore@1cc7c268, metadata=FileBasedSnapshotMetadata{index=3207, term=1, processedPosition=6465, exporterPosition=6466}}
java.nio.file.NoSuchFileException: D:\code\zeebe1.0\camunda-cloud-zeebe-1.0.0\data\raft-partition\partitions\6\pending\3207-1-6465-6466
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53) ~[?:?]
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:199) ~[?:?]
	at java.nio.file.Files.readAttributes(Files.java:1851) ~[?:?]
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:220) ~[?:?]
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277) ~[?:?]
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:323) ~[?:?]
	at java.nio.file.Files.walkFileTree(Files.java:2804) ~[?:?]
	at java.nio.file.Files.walkFileTree(Files.java:2882) ~[?:?]
	at io.camunda.zeebe.util.FileUtil.deleteFolderIfExists(FileUtil.java:58) ~[zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot.abortInternal(FileBasedTransientSnapshot.java:144) ~[zeebe-snapshots-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot.lambda$abort$2(FileBasedTransientSnapshot.java:92) ~[zeebe-snapshots-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.0.0.jar:1.0.0]
2022-08-02 17:32:24.760 [Broker-0-SnapshotDirector-6] [Broker-0-zb-fs-workers-0] INFO 
      io.camunda.zeebe.logstreams.snapshot - Current commit position 7044 >= 7044, snapshot 3773-1-7043-7044 is valid and has been persisted.

What is the reason for this, the zeebe version is 1.0.0, the zeebe configuration file is as follows, and the partition configuration is 8。

`

# Zeebe Standalone Broker configuration file (with embedded gateway)

# This file is based on broker.standalone.yaml.template but stripped down to contain only a limited
# set of configuration options. These are a good starting point to get to know Zeebe.
# For advanced configuration options, have a look at the templates in this folder.

# !!! Note that this configuration is not suitable for running a standalone gateway. !!!
# If you want to run a standalone gateway node, please have a look at gateway.yaml.template

# ----------------------------------------------------
# Byte sizes
# For buffers and others must be specified as strings and follow the following
# format: "10U" where U (unit) must be replaced with KB = Kilobytes, MB = Megabytes or GB = Gigabytes.
# If unit is omitted then the default unit is simply bytes.
# Example:
# sendBufferSize = "16MB" (creates a buffer of 16 Megabytes)
#
# Time units
# Timeouts, intervals, and the likes, must be specified either in the standard ISO-8601 format used
# by java.time.Duration, or as strings with the following format: "VU", where:
#   - V is a numerical value (e.g. 1, 5, 10, etc.)
#   - U is the unit, one of: ms = Millis, s = Seconds, m = Minutes, or h = Hours
#
# Paths:
# Relative paths are resolved relative to the installation directory of the broker.
# ----------------------------------------------------

zeebe:
  broker:
    gateway:
      # Enable the embedded gateway to start on broker startup.
      # This setting can also be overridden using the environment variable ZEEBE_BROKER_GATEWAY_ENABLE.
      enable: true

      network:
        # Sets the port the embedded gateway binds to.
        # This setting can also be overridden using the environment variable ZEEBE_BROKER_GATEWAY_NETWORK_PORT.
        port: 26500

      security:
        # Enables TLS authentication between clients and the gateway
        # This setting can also be overridden using the environment variable ZEEBE_BROKER_GATEWAY_SECURITY_ENABLED.
        enabled: false

    network:
      # Controls the default host the broker should bind to. Can be overwritten on a
      # per binding basis for client, management and replication
      # This setting can also be overridden using the environment variable ZEEBE_BROKER_NETWORK_HOST.
      host: 0.0.0.0

    data:
      # Specify a directory in which data is stored.
      # This setting can also be overridden using the environment variable ZEEBE_BROKER_DATA_DIRECTORY.
      directory: data
      # The size of data log segment files.
      # This setting can also be overridden using the environment variable ZEEBE_BROKER_DATA_LOGSEGMENTSIZE.
      logSegmentSize: 128MB
      # How often we take snapshots of streams (time unit)
      # This setting can also be overridden using the environment variable ZEEBE_BROKER_DATA_SNAPSHOTPERIOD.
      snapshotPeriod: 15m

    cluster:
      # Specifies the Zeebe cluster size.
      # This can also be overridden using the environment variable ZEEBE_BROKER_CLUSTER_CLUSTERSIZE.
      clusterSize: 1
      # Controls the replication factor, which defines the count of replicas per partition.
      # This can also be overridden using the environment variable ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR.
      replicationFactor: 1
      # Controls the number of partitions, which should exist in the cluster.
      # This can also be overridden using the environment variable ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT.
      partitionsCount: 8

    threads:
      # Controls the number of non-blocking CPU threads to be used.
      # WARNING: You should never specify a value that is larger than the number of physical cores
      # available. Good practice is to leave 1-2 cores for ioThreads and the operating
      # system (it has to run somewhere). For example, when running Zeebe on a machine
      # which has 4 cores, a good value would be 2.
      # This setting can also be overridden using the environment variable ZEEBE_BROKER_THREADS_CPUTHREADCOUNT
      cpuThreadCount: 2
      # Controls the number of io threads to be used.
      # This setting can also be overridden using the environment variable ZEEBE_BROKER_THREADS_IOTHREADCOUNT
      ioThreadCount: 2

`

**Comment by Zelldon** [comment]
Please see https://github.com/camunda/zeebe/issues/4686 and other related issues. I suggest to update to a supported Zeebe version
